### ISSUE TITLE
1주차 1장 깨끗한 코드 ~ 4장 주석 

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#1]

**Comment by GitKangJi** [comment]
P47. Switch문 이해 안감.

P59. Finally에 뭐가 들어 가는지.

P78. 이런 주석은 괜찮은 것 같다. 나쁜 주석이라고 표현할 것 까지는 없을 것 같다.

P80. 어리석다....?

**Comment by hyesun03** [comment]
# 3장

## p.53 삼항함수
삼항짜리 assertEquals를 첨 봐서 좀 찾아봄. 이 책에 나온 `assertEquals(message, expected, actual)`은 부동소수점 비교에 대한 말이 나오는거 보면 문맥상 `assertEquals(java.lang.String message, double expected, double actual)`이걸 지칭하는듯 한데, 맞는지 모르겠음.

[junit4 문서](https://junit.org/junit4/javadoc/latest/index.html)에서 이건 Deprecated 되어있다고 하고,
[junit5 문서](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html)에서는 인자 순서가 바뀌었는데 message가 제일 마지막 인자로 밀려있고 expected가 첫번째 인자로 바뀜.

```
assertEquals(String message, double expected, double actual) 
          Deprecated. Use assertEquals(String message, double expected, double actual, double delta) instead
```
`assertEquals(message, expected, actual)`이랑 `assertEquals(1.0, amount, .001)`이거 두개가 다른 함수라고 말하는 거 같음. 뒤에껀 `assertEquals(double expected, double actual, double delta)`라고 이해했는데, 제대로 받아들인건지 모르겠음.


## p.55 목록 3-6 UserValidator.java
**checkPasswordAndInitializeSesion**이라는 이름으로 바꾸는게 좋다고 제안하는데 그냥 아래와 같이 쓰면 안되는지 궁금함. `Session.initialize();`이걸 checkPassword에서 지우고, password 확인 용도로만 쓰는게 더 나은거 같음. 아래와 같이 못바꾸는 경우는 어떤 경우가 있을지 생각을 좀 해봤는데 예상이 잘 안됨.. 

``` java
if(checkPassword(userName, pasword))
    Session.initialize();
```


# 4장

## p.74 TODO
예전에 코드 리뷰 받을때 TODO 주석자체를 쓰지 말라는 피드백을 받음. 기능 추가/변경/삭제 등에 대한건 이슈를 올리라고 배웠는데 실제로는 어떻게 쓰고 있는지 잘 모르겠음.

## p.84 위치를 표시하는 주석
극히 드물지만 유용한 경우가 어떤 경우인지 모르겠음

## p.86 주석으로 처리한 코드
이거 코드리뷰시 설득해본 경험있으면 공유 부탁드립니다........

**Comment by hyesun03** [comment]
## p.47
디자인 패턴 중에서 **팩토리 패턴**이 무엇이고 왜 쓰게 되는지 찾아보면 좀 이해가 될듯..?

## p.59
질문 이해가 안감 ㅠ

## p.77-79 같은 이야기를 중복하는 주석
변수명을 지을 때, 주석 없이도 충분히 저 변수명이 어떤역할을 하는지 설명을 해야만 하고 그렇게 해놨어. 변수 1줄마다 주석 3줄 달리게 되면 한 눈에 코드가 안들어와. 그게 꼭 필요한 정보면 모르겠는데, 불필요한 정보에 코드만 쓸데없이 길어져서 나쁜 코드라고 하는 듯.
