### ISSUE TITLE
[리팩터링] 22.01.29/1주차 -  챕터 1. 리팩터링:첫번째 예시 끝까지 ~ 77p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#100]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
77p
리팩터링을 효과적으로 하는 핵심은, 단계를 잘게 나눠야 더 빠르게 처리할 수 있고, 코드는 절대 깨지지 않으며, 이러한 작은 단계들이 모여서 상당히 큰 변화를 이룰 수 있다는 사실을 깨닫는 것이다.

이야기해보고 싶은것.
- 인라인 함수
- 임시 변수

**Comment by joi0104** [comment]
학생때 읽었을 때랑 현업때 읽었을때랑 느낌이 많이 다르네요. 일하다보면 리팩토링 부채가 엄청 쌓이는데, 그러다보니 더 와닿은거 같아요. n회독하기에 좋은 책이라는 걸 느낍니다.

> 리팩터링하기 전에 제대로 된 테스트부터 마련한다. 테스트는 반드시 자가진단하도록 만든다.

👍


> 임시 변수는 자신이 속한 루틴에서만 의미가 있어서 루틴이 길고 복잡해지기 쉽다.

여러곳에서 쓰일 여지가 있는 변수거나 계산방식이 복잡한 변수라면 질의함수로 추출하는게 좋지만. 해당 루틴에서만 명백하게 쓰일 변수라면 추출하는게 오히려 코드량만 늘어나게 하는건 아닐까?  

> 긴 함수를 작게 쪼개는 리팩터링은 이름을 잘 지어야만 효과가 있다. 이름이 좋으면 함수 본문을 읽지 않고도 무슨 일을 하는지 알 수 있다. 

👍

> 48p 이제 totalAmount 변수를 인라인한 다음(컴파일-테스트-커밋), 함수 이름을 더 의미 있게 고친다.

아무 이름을 먼저 붙여서 함수를 추출하게 되면, 이름을 짓기 어렵다는 code smell을 빨리 맡기 어렵지 않나? (이름 짓기 어렵다 -> 함수가 많은 역할을 하고 있다는 시그널일 수 있으니) 


> 50p 코드

인라인 함수가 전체 로직 뒤에 있는게 좋은 듯 하다. 전체적인 흐름을 먼저 읽고 세부사항을 읽을 수 있는 느낌.

>  좋은 코드를 가늠하는 확실한 방법은 얼마나 수정하기 쉬운가다.

👍

**Comment by wise1ight** [comment]
리팩터링을 할 때 테스트는 당연히 같이 따라가야 한다는 것을 많이 느꼈습니다.
겉보기 기능은 같아도 내가 코드를 수정하면서 실수할 수 있으니
테스트는 당연히 해야하는 작업인데 단순히 코드를 다시 짜면 되겠지 안일하게 생각하고 있었네요.

다만 코드가 많아서 책을 읽는 방법이 이전 객사오랑은 다르게
예제를 보고 어떻게 바꿀 수 있을지 생각을 해 보고
책에서 나오는 방법을 또 보면서 따라해보고 싶긴 했으나
최근에 거제에서 일을 하다가 다시 서울에 와서 정신없어서
다음주 부터는 열심히 참여하겠습니다 😢

**Comment by usageness** [comment]
진영이와 마찬가지로 처음 읽었을때와 지금 다시 볼때 느낌이 확 다르네요 😄

> 지역 변수를 제거해서 얻는 가장 큰 장점은 추출 작업이 훨씬 쉬워진다는 점이다.

변수의 유효 범위를 생각하다가, 그렇다면 함수는? 파일은? 하며 고민하던 때에 읽었던 아티클이 생각나서 공유해봅니다.

- [지역성의 원칙을 고려한 패키지 구조: 기능별로 나누기](https://ahnheejong.name/articles/package-structure-with-the-principal-of-locality-in-mind/)

> 그런데 이름이 마음에 걸린다.

제가 피어 리뷰를 할때 가장 많이 이야기 했던 점 중 하나가 바로 네이밍에 관한 것이었는데,
지금도 딱 맞는 이름을 정하는건 어려운 일인 것 같아요.
개인적으로 토스가 네이밍 하나는 기똥차게 정의한다고 생각하는데,

팀 프로젝트를 하며 Date 객체를 받아서 짧은 ISO 문자열(ex. 2023-01-29)을
반환하는 함수를 만들어야 하는 경우가 있었어요.

```js
function getISOString()
```

저는 처음엔 위처럼 만들어서 사용했었어요. 다만 팀원들이 `ISOString` 이라는 이름을
직관적으로 받아들이지 못해서 뭔가 아쉬운 기억이 있었습니다.
그러던 중 토스의 [slash](https://github.com/toss/slash) 라이브러리에선 이렇게 사용하는걸 발견했어요.

```js
function parseYYYYMMDD()
```

이런게.. 진짜 직관적이고 좋은 이름이구나 싶었습니다.

**Comment by hjsung809** [comment]
1.
자바 스크립트 문법을 이용해서
매개변수로 넘기지 않고 변수를 사용하는게
중쳡함수라고 하는게 맞는제 궁금합니다.

변수가 전역변수인지 로컬변수인지 구분하기 힘들고 사이드 이펙트를 만드는 실수를 할 가능성이 커보이는데 어떻게 생각하실지 궁금합니다.
자바의 멤버 변수를 대체하여 사용하는 느낌인데 명시적이지 못한것 같아서, 차라리 매개변수로 넘겨서 순수 함수화 처럼쓰는게 낫지
않나요?

2.
처음 제시된 코드에서 점진적으로 바꿔나가는게  인상 깊었습니다. 처음부터 클래스로 나누면 한번에 너무 많은 TC수정을 해야해서 힘들었던적이 있습니다. 점차적으로 변경하면서 테스트도 같이 수정해나가면 조금더 자연스럽게 변경 할수 있을것 같습니다

**Comment by wlsh44** [comment]
https://github.com/wlsh44/refactoring-java

책 예제를 자바로 진행을 해보다가 궁금한 점 몇가지가 생겼습니다!

사실 이번에 프런트 스터디를 하면서 js 리팩터링을 하다가 중첩함수에 파라미터를 넣지 않아도 바깥 함수의 변수에 접근할 수 있다는 사실을 처음 알았습니다. 그런데 그 때는 그냥 단순히 '아 이런게 되는구나' 정도만 생각하고, 사용할 파라미터를 지정하는게 더 좋은 것 같다는 생각에 파라미터를 하나하나 넣어줬는데 js에서는 책의 방식처럼 코드를 작성하나요?

그리고 자바로 리팩터링을 하다보니 중첩함수를 사용할 수가 없어, `playFor(aPerformance)` 메서드를 만들지 못해 책처럼 `play` 파라미터를 지울 수가 없어서 힘들었네요..

> 함수 추출이 끝났다면, 다음은 volumeCredits 변수를 인라인할 차례다.(47p)

책을 보다보니 가능하면 변수를 인라인을 통해 지우는 작업을 하는데 이 부분이 약간 궁금했습니다. 예를 들어 인라인 하는 메서드의 이름이 길어져 가독성이 떨어진다거나, 책의 예제 중 리팩터링의 중간 단계이긴 하지만 `usd(amountFor(perf))` 처럼 중첩으로 인라인을 하는 등 조금 과하지 않나? 라는 생각이 들었는데 다른 분들은 어떻게 생각하시는지 궁금합니다!

> 69p enrichPerformace 메서드 부분

이 부분도 자바로 리팩터링을 하는데 애를 많이 먹었습니다...
우선 js처럼 객체에 동적으로 필드를 추가하지 못하다보니 따로 `EnrichedPerformance` 라는 객체를 만들어서 진행을 했습니다. 그러다보니 책의 `enrichPerformance` 메서드 안에서 몇 가지 질문이 생겼습니다.

****

`PerformanceCalculator` 위치

`EnrichedPerformance` 를 만들기 전에 `calculator` 를 통해 값을 하나하나 바꾼 후에 넣어줬는데 파라미터가 너무 많아지게 되었습니다.

```java
private static EnrichedPerformance enrichPerformance(Performance performance, Plays plays) {
    Play play = plays.playFor(performance);
    PerformanceCalculator calculator = CalculatorFactoryFactory.createPerformanceCalculator(performance, play);
    return new EnrichedPerformance(performance, play, calculator.amount(), calculator.volumeCredits());
}
```
그래서 수정을 어떻게 할까 고민을 하다가 `calculator` 를 `EnrichedPerformance` 생성자에 넘기거나 생성자 뒤로 숨기는 방법을 생각을 했습니다.

```java
public EnrichedPerformance(Performance performance, Play play) {
    PerformanceCalculator calculator = CalculatorFactoryFactory.createPerformanceCalculator(performance, play);
    ...
}

public EnrichedPerformance(Performance performance, Play play, PerformanceCalculator calculator) {
    ...
}
```
다만 두 번째 방법은 `EnrichedPerformance` 가 `calculator`에 의존적이어야 하는지에 대한 의구심이 들었고, 첫 번째 방법은 단순 자료구조에서 계산된 값을 제공하는 역할을 가진 객체가 되는 듯한 느낌도 들고 이게 괜찮은지에 대한 판단이 잘 서질 않았습니다. 조금 사소한 부분일수도 있지만 혹시 이 부분에 대해 의견이나 다른 방법이 있으신지 궁금합니다!

****

`result.play = calculator.play;`

`calculator`를 추상화 하면서 `getPlay()` 메서드가 여기 있는게 맞나 라는 생각을 했습니다. 그래서 해당 메서드는 따로 만들지 않았는데 요 부분은 필드 접근에 대한 js와 자바의 코드 스타일의 차이일까요??

```java
public interface PerformanceCalculator {
    int amount();
    int volumeCredits();
    // Play getPlay(); <- ??
}
```

### 느낀 점

처음에는 그냥 책을 쭉 읽으면서 그렇구나 정도로 넘어가는 부분이 많았는데 직접 자바로 작성을 해보니까 생각보다 잘 되지 않아서 부족한 점을 많이 느꼈던 것 같습니다..ㅠ
그리고 리팩터링 할때마다 통합 테스트만 돌리고 새로운 클래스에 대한 테스트는 귀찮아서 만들지 않았는데 이 부분도 반성해야겠네요..

**Comment by eagleda** [comment]
> p.32 
한 번에 너무 많이 수정하려다 실수를 저지르면 디버깅하기 어려워서 결과적으로 작업 시간이 늘어난다.
조금씩 수정하여 피드백 주기를 짧게 가져가는 습관이 이러한 재앙을 피하는 길이다.

간단한 문제에서도 한번에 모든 파트를 작성/수정하고 보면 항상 문제가 생기고 고치는데 오랜 시간이 걸리더군요.
예제에서 반복적인 컴파일-테스트-커밋을 하는 것처럼 각 부분에 대해 그때그때 테스트를 할 수 있도록 하는 습관을 가져겠습니다.

> p.35
 컴퓨터가 이해하는 코드는 바보도 작성할 수 있다. 사람이 이해하도록 작성하는 프로그래머가 진정한 실력자다.  

그럴 실력인지 모르겠지만 최근 지인의 백준 공부를 도와주며 스스로가 짠 코드를 보여주며 가르쳐줘야 하는 경우가 종종 생기게 되었는데,  급조한 코드에 난잡한 구성 등 때문에 이해하기 어려워하더군요.. 위의 말과 같이 다른 사람이 이해할 수 있도록 코드를 짜는 것의 중요성을 통감할 수 있었습니다.

**Comment by siathus** [comment]
일단 기본적으로 이전 책과 달리 코드로 된 예제(비록 자바스크립트지만)가 있어서 더욱 직관적으로 리팩토링의 기본 단계를 알 수 있어서 좋았습니다.

### play 변수 제거하기
왜 `plays[perf.playID]`를 기어코 `playFor()` 함수로 추출해야 하는지 잘 와닿질 않네요. 또한, 저자는 임시 변수를 제거해야 할 대상으로 보는데 같은 함수가 두 번 이상 호출되어야 할 때에도 임시 변수를 제거하고 인라인시키는게 맞는지 궁금합니다.

## 중간 점검: 난무하는 중첩 함수
p. 50의 주석 "여기서부터 중첩 함수 시작"이 `totalAmount()`가 아닌 `totalVolumeCredits()`에 적혀 있는데, 그렇다면 `totalAmount()`는 중첩 함수가 아닌걸까요? 그냥 오류인 게 맞겠죠?

**Comment by KimDa99** [comment]
- 리팩토링은 변경의 위험 때문에 발생한다
- →! 변경하기 쉽게! *변경점을 예측하는 것도 중요하겠구나*

*나의 문제점 중에 하나 - 완벽하지 않을거면 아예 하지 말아야지*

*문제는 완벽한 설계는 불가능*

*완벽하게 하려다가 포기하고 세상에서 제일 더러운 코드를 씀*

*요구사항이 바뀌고 상황이 바뀌는 것은 둘째고, 애초에 설계를 할 수 있는 경험치가 부족하다.*

*설계를 하긴 해야겠지만 처음부터 완벽을 바라지 말아야지.*

*문제점/궁금점 - 리펙토링을 해야하는 시점?*

*리펙토링의 필요성을 느끼긴 하지만, 언제 해야할지 잘 모르겠다*

*리팩토링을 해야지 - 라고 마음 먹은 시점에 코드가 너무 복잡하고 긴 것 같다.*

*그렇다고 중간에 하기엔 리팩토링의 목적을 잡기 너무 이른 시점인 것 같다.* 

*그냥 복잡하고 어지럽더라도 그걸 극복해야하는 것 같기도하다*

## 1.3 리팩터링의 첫 단계: 테스트 코드 작성

리팩터링한 코드 영역을 꼼꼼하게 검사해줄 테스트 코드들부터 마련해야한다.

리팩터링하기 전에 제대로 된 테스트부터 마련한다.

테스트는 반드시 자가진단하도록 만든다.

- 일일이 눈으로 비교 x 틀리면 빨강불 ㅡ 이런 식으로

*게임 개발하면서 문제 - 경험치, 돈, 대사, 정책 등 이러한 로직의 부분에서는 이런 테스트 코드을 만드는 것이 쉽겠지만 비쥬얼과 관련된 요소들을 다룰 때에는 이를 마련하는 것이 어렵다. 컴파일하는데에도 시간이 오래 걸린다.*

*→ ~비쥬얼 로직이 바뀌면 (요구사항이 바뀌면 ) 비쥬얼도 바뀐다. 그럼, ~비쥬얼을 먼저 개발을 시작하면 좋을 것 같다?*

*→ 여러 테스트 맵을 만드는 것도 좋을 것 같다. (컴파일 시간도 줄이고 환경도 확실히 제약하고)*

*→ 하지만 전체 모든 요소가 있을때에도 테스트를 해야하는데 시간이 오래 걸릴 것 같다.* 

*→ 게임에선 별의 별 상황과 변경사항들이 생기는데 이런 구석구석들에 대한 테스트 코드를 마련하는 것이 현실적으로 가능한가?*

*→ 이래서 게임 테스터라는 직업이 있는 건가?
