### ISSUE TITLE
[리팩터링] 22.02.05/2주차 - 챕터 2. 리팩터링 원칙 끝까지 ~ 111p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#101]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
### 리팩터링시 고려할 문제
개발팀을 이끌고 있다면 코드베이스가 더 건강해지는 것을 추구한다는 사실을 팀원들에게 명확히 밝혀야 한다.

하지만 내가 볼 때 사람들이 빠지기 쉬운 가장 위험한 오류는 리팩터링을 ‘클린 코드’ 나 ‘바람직한 엔지니어링 습관’ 처럼 도덕적인 이유로 정당화하는 것이다. 리팩터링의 본질은 코드베이스를 예쁘게 꾸미는데 있지 않다. 오로지 경제적인 이유로 하는 것이다. 리팩터링은 개발 기간을 단축하고자 하는 것이다. 기능 추가 시간을 줄이고, 버그 수정 시간을 줄여준다. 스스로 그렇게 인식하는 데 그치지 말고 다른 사람과 대화할 때도 이 점을 명심해야 한다. 리팩터링하도록 이끄는 동력은 어디까지나 경제적인 효과에 있다. 이를 명확히 이해하는 개발자, 관리자, 고객이 많아질수록 앞에서 본 소프트웨어 개발 진행 그래프에서 ‘좋은 설계’ 곡선을 더 많이 볼 수 있다. (93p)

### 리팩터링, 아키텍처, 애그니 (YAGNI)
이런 식으로 설계하는 방식을 간결한 설계, 점진적 설계, 애그니등으로 부른다. YAGNI를 문자 그대로 해석해서 적용할 때도 있지만, 아키텍처를 전혀 고려하지 말라는 뜻은 아니다. 내가 바라보는 YAGNI는 아키텍처와 설계를 개발 프로세스에 녹이는 또 다른 방식이며, 리팩터링의 뒷받침 없이는 효과를 볼 수 없다.

YAGNI를 받아들인다고 해서 **선제적인 아키텍처에 완전히 소홀해도 된다는 뜻은 아니다.** 리팩터링으로는 변경하기 어려워서 미리 생각해두면 시간이 절약되는 경우도 얼마든지 있다. 다만 이제는 둘 사이의 균형점이 크게 달라졌다. 나는 나중에 문제를 더 깊이 이해하게 됐을 때 처리하는 쪽이 훨씬 낫다고 생각하는 편이다. 이러한 경향은 진화형 아키텍처 원칙이 발전하는 계기가 됐다 (진화형 아키텍처는 아키텍처 관련 결정을 시간을 두고 반복해 내릴 수 있다는 장점을 활용하는 패턴과 실천법을 추구한다.) (101p)

**Comment by KangJiJi** [comment]
전체적으로 어렵지 않게 읽을 수 있는 내용이였습니다.'

# 리팩터링 정의

리팩터링 과정에서 발견된 버그는 리팩터링 후에도 그대로 남아 있어야 한다(단, 아무도 발견하지 못한 숨은 버그는 수정해도 괜찮다). => 겸사겸사 그냥 고쳐버리자 ㅎㅎ

# 두 개의 모자

하나의 PR에 다 넣고, 커밋만 나눠서 하면 괜찮을 것 같다 ㅎㅎ

# 데이터베이스 리팩터링

엄청난 대공사...

**Comment by siathus** [comment]
# 리팩터링 정의
> 리팩터링 전과 후의 코드가 똑같이 동작해야 한다는 뜻이다. (중략) 리팩터링 과정에서 발견된 버그는 리팩터링 후에도 그대로 남아 있어야 한다. (p. 80)

(알려진) 버그마저 그대로 남아 있어야 한다는 문장이 코드가 똑같이 동작해야 한다는 리팩터링의 정의를 더욱 잘 나타내는 것 같네요.

> 리팩터링은 코드가 더 잘 읽히게 도와준다. (중략) 단지 다른 사람을 배려하기 위해서가 아니다. 사실 그 다른 사람이 바로 나 자신일 때가 많다. (p. 82)

> 리팩터링하면 안 되는 상황도 있다. (중략) 내부 동작을 이해해야 할 시점에 리팩터링해야 효과를 제대로 볼 수 있다. (p. 91)

# 리팩터링 시 고려할 문제
> 사람들이 빠지기 쉬운 가장 위험한 오류는 리팩터링을 '클린 코드'나 '바람직한 엔지니어링 습관'처럼 도덕적인 이유로 정당화하는 것이다. 리팩터링의 본질은 코드 베이스를 예쁘게 꾸미는 데 있지 않다. 오로지 경제적인 이유로 하는 것이다. (p. 93)

이 부분은 이해가 조금 어렵네요. "도덕적인 이유"라는게 리팩터링 하는 이유를 '클린 코드'나 '바람직한 엔지니어링 습관'처럼 '코드를 예쁘게 가꾸는 것은 개발자라면 모름지기 해야 할 덕목'으로 생각하지 말라는 뜻일까요?

# 리팩터링과 성능
> 하드 리얼타임 시스템을 제외한 소프트웨어를 빠르게 만드는 비결은, 먼저 튜닝하기 쉽게 만들고 나서 원하는 속도가 나게끔 튜닝하는 것이다. (p. 103)

> 성능에 대한 흥미로운 사실은, 대부분 프로그램은 전체 코드 중 극히 일부에서 대부분의 시간 을 소비한다는 것이다. 그래서 코드 전체를 고르게 최적화한다면 그중 90%는 효과가 거의 없기 때문에 시간 낭비인 셈이다. (p. 105)

**Comment by hjsung809** [comment]
p82
컴퓨터에게 시키려는 일과 이를 표현한 코드의
차이를 최대한 줄여야 한다.
코드의 목적이 더 잘 드러나게 내 의도를 명확하게 전달하도록 개선할 수 있어야 한다.

이 부분에 나타난 생각들이 참 좋았습니다. 


p85
3의 법칙에서 '일을 한다'의 기준이 뭘까요? 코드를 작성하는 일인지, 논리 구조가 잘 파악이 안되서 코드를 다시 읽어야 하는 것도 일인지 궁금합니다

p105
성능을 고려한답시고 가독성을 포기하는 개발자들에게 일침을 날릴 생각에 설랬습니다. 성능을 핑계로 코드를 관리할 의무를 저버린 사람들을 생각보다 많이 보는 것 같습니다.


전반적으로 말하는 내용인, 리팩토링을 과하게 하는것을 경계하면서 조금씩 꾸준히 하라는 전략이 참 좋은것 같습니다
그리고 테스트를 전부 작성하기 어려울때 테스트 없이 진행하는 리팩토링 부분도 흥미로웠습니다

**Comment by wise1ight** [comment]
80p
> 리팩터링하는 동안에는 코드가 항상 정상 작동하기 때문에 전체 작업이 끝나지 않았더라도 언제든 멈출 수 있다.

리팩터링 정의를 생각해보면 당연한 것이지만 유념해야 할 부분


숨은 버그 찾기는 리팩토링이 가져다 주는 부산물일까요 😂

82p
모자 바꿔쓰기는 내가 지금 뭘 하는지 정확히 알고 하나에만 집중하자는걸 의미하는 것 같네요.

89p
리팩터링 커밋 분리 yes/no 이신지?

93p
> 리팩터링은 개발 기간을 단축하고자 하는 것이다. 기능 추가 시간을 줄이고, 버그 수정 시간을 줄여준다.

리팩터링은 생산성과 관련된 일.

**Comment by joi0104** [comment]
> 83p 이 사실은 켄트 벡의 말을 떠올리게 해준다. “난 뛰어난 프로그래머가 아니에요. 단지 뛰어난 습관을 지닌 괜찮은 프로그래머일 뿐이에요.” 리팩터링은 견고한 코드를 작성하는 데 무척 효 과적이다.

프로그래머에게 좋은 습관이 얼마나 강력한 무기가 될 수 있는지 알 수 있는 문장. 리팩토링을 왜 해야하고 어떻게 해야하는지 알고 있는 것과 그것을 습관으로 녹이는 것의 차이는 큰 것 같다.

> 그렇더라도 상황에 맞게 조율해야 한다. 예컨대 (대대적인) 리팩터링이 필요해 보이지만, 추가하려는 새 기능이 아주 작아서 기능 추가부터 하고 싶은 상황에 마주칠 수 있다. 이럴 때는 프로 개발자로서 가진 경험을 잘 발휘해서 결정한다. 이럴 때 내가 균형점을 잡는 방법을 설명 하기는 쉽지 않고, 정량화하기는 더더욱 어렵다.
나는 준비를 위한 리팩터링을 하면 변경을 훨씬 쉽게 할 수 있다고 확신한다.그래서 새 기능을 구현해넣기 편해지겠다 싶은 리팩터링이라면 주저하지 않고 리팩터링부터 한다. 한번 본 문제 일 때도 리팩터링부터 하는 편이다. 반면 내가 직접 건드릴 일이 거의 없거나, 불편한 정도가 그리 심하지 않다고 판단되면 리팩터링하지 않는 편이다. 때로는 어떻게 개선해 야 할지 확실히 떠오르지 않아서 리팩터링을 미루기도 한다. 물론 개선점이 떠오르면 시험 삼 아 고쳐보고 더 나아지는지 살펴본다.


리팩터링도 결국 판단의 영역. 이 책에서는 안해야할 때를 몇개의 예시를 들어서 소개해줬지만 이것도 상황에 따라 다를 수 있을 것 같다. 결국 해야할지 안해야할지는 상황에 따라 다를 수 있는데 그걸 판단하는 것도 프로그래머의 역량인 것 같다.


> 89p 나는 이런 상황에 처하더라도 팀 전체가 리팩터링에 매달리는 데는 회의적이다. 그보다는 주어 진 문제를 몇 주에 걸쳐 조금씩 해결해가는 편이 효과적일 때가 많다. 누구든지 리팩터링해야 할 코드와 관련한 작업을 하게 될 때마다 원하는 방향으로 조금씩 개선하는 식이다. 리팩터링 이 코드를 깨트리지 않는다는 장점을 활용하는 것이다. 일부를 변경해도 모든 기능이 항상 올 바르게 동작한다. 예컨대 라이브러리를 교체할 때는 기존 것과 새 것 모두를 포용하는 추상 인터페이스부터 마련한다. 기존 코드가 이 추상 인터페이스를 호출하도록 만들고 나면 라이브러 리를 훨씬 쉽게 교체할 수 있다(이 전략을 추상화로 갈아타기 Branch By Abstraction*라 한다).

리팩터링하다 보면 기존 코드는 전부 레거시고 빨리 없애야 한다는 생각을 하게 된다. 이러다보니, 기존 코드를 일괄로 수정하는 경우가 많은데 이런 함정에 빠지면 안되겠다는 생각을 했다. 리팩터링은 조금씩 점진적으로. 추상 인터페이스를 시작으로 일부만 조금씩 변경하자.

**Comment by usageness** [comment]
> p.81 
> 나는 소프트웨어를 개발할 때 목적이 '기능 추가'냐, 아니면 '리팩터링'이냐를 명확히 구분해 작업한다.
> 새 기능을 추가하다 보면 코드 구조를 바꿔야 작업하기 훨씬 쉽겠다는 생각이 들기도 하는데, 그러면 잠시 모자를 바꿔 쓰고 리팩터링한다.

'새 기능을 추가할 때'
반대로 말하면 새 기능을 추가할게 아니라면 리팩터링은 굳이 안해도 되겠네요.

+개인 프로젝트를 하면서 "구조를 바꿔야 작업하기 훨씬 쉽겠다" 라는 생각이 들어서 먼저 변경을 마친 후 새 기능을 추가했는데, 제 경우는 UI에 관련한 부분이다보니 이것도 리팩터링이라고 볼 수 있을까? 하는 호기심이 문득 드네요.


> p.89
> 버전 관리 시스템에서 리팩터링 커밋과 기능 추가 커밋을 분리해야 한다는 조언을 들은 적이 있다. (중략) 나는 이 견해에 완전히 동의하지는 않는다.

저는 개인적으로 이 견해에는 동의하지 않습니다.

기능 추가와 리팩터링이 붙어있을 이유가 단순히 맥락 파악이라면 그럴 필요는 없다고 생각합니다.
바로 아래에 오래 걸리는 리팩토링과 같은 경우가 있는데, 그때까지 리팩터링에 영향을 받는 기능 구현을
미룰 수도 없을뿐더러 리팩터링과 기능 구현의 방향성은 명확히 달라서 구분지을 필요가 있다고 생각해요.

> p.98
> 이처럼 난감한 상황에서 빠져나오기 위한 더 쉬운 방법은 아쉽게도 없다.

현실적인 벽에 부딪히는 주변 개발자들을 보면 회의감이 많이 드네요 ㅎㅎ...

**Comment by KimDa99** [comment]
> 소프트웨어를 개발할 때 목적이 '기능 추가'냐, 아니면 '리펙터링'이냐를 명확히 구분해 작업한다. 81p
그동안 '리팩터링을 더 자주 해야하겠다!' 라고 마음을 먹었을 때, 이 둘을 명확히 구분해서 작업하지 않고 섞어가면서 동시에 했던 것 같다. 그래서 끝나고 보면 내가 뭘 했는지 헷갈리고 주어진 시간에 기능 추가도, 리팩토링도 제대로 하지 못했다. 의식적으로 구분하면서 작업을 해야겠다.

> ... 리펙터링하면 안되는 상황도 있다 91p
이를 구분하지 못해서 1) 모든 걸 정리하거나, 2) 아무것도 정리 안하거나 이 둘 중 하나였다.

그 이유 중 하나가 리팩터링의 정의를 제대로 잡지 않아서 그랬던 것 같다.
> 리팩토링은 재구성 중 특수한 한 형태로 본다. 80p
> 리팩터링은 성능 최적화와 ... 목적이 다를 뿐이다. 80p 
> 리팩토링을 '클린코드'나 '바람직한 엔지니어링 습관'처럼 도덕적인 이유로 정당화하는 것이다. 리팩터링의 본질은 코드 베이스를 예쁘게 꾸미는 데 있지 않다. 93p

**Comment by wlsh44** [comment]
> 내가 경험한 가장 좋은 방법은 작성자와 나란히 앉아서 코드를 흝어가면서 리팩터링하는 것이다. 이렇게 하면 자연스럽게 짝프로그래밍이 된다.(90p)

실제로 현업에서도 이런 식으로 페어프로그래밍이 자주 이뤄지는지 궁금합니다!

> 하지만 내가 볼 때 사람들이 빠지기 쉬운 가장 위험한 오류는 리팩터링을 '클린 코드'나 '바람직한 엔지니어링 습관'처럼 도덕적인 이유로 정당화하는 것이다. 리팩터링의 본질은 코드베이스를 예쁘게 꾸미는 데 있지 않다. 오로지 경제적인 이유로 하는 것이다. (p93)

이 문장을 보고 약간 의아함을 느꼈습니다. 결국에 클린 코드나 바람직한 개발자 습관도 경제적인 이유로 생긴 것이 아닌가요..? 여기서 저자가 말하는 `도덕적인 이유` 가 뭘 의미하는지 궁금하네요

> 머지의 복잡도를 줄일 수 있어서 CI를 선호하기도 하지만, 가장 큰 이유는 리팩터링과 궁합이 아주 좋기 때문이다.

단순히 독립적인 작업을 통합시키려는 목적으로의 CI만 생각을 했었는데 리팩터링의 관점에서 CI를 생각해보게 되어서 좋았습니다!
