### ISSUE TITLE
[리팩터링] 22.02.12/3주차 - 챕터 4. 테스트 구축하기 끝까지 ~ 151p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#102]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
# 3. 코드에서 나는 악취

3.3 긴 함수

함수 이름은 **동작방식**이 아닌 **의도**가 드러나게끔 짓는다.

핵심은 함수의 길이가 아닌, 함수의 목적 (의도) 과 ㄱ현 코드의 괴리가 얼마나 큰가다.

즉, ‘무엇을 하는지’를 코드가 잘 설명해주지 못할수록 함수로 만드는게 유리하다.

# 4. 테스트 구축하기

자주 테스트하라. 작성 중인 코드는 최소한 몇 분 간격으로 테스트하고, 적어도 하루에 한 번은 전체 테스트를 돌려보자.

테스트는 위험 요인을 중심으로 작성해야 한다. 테스트의 목적은 어디까지나 현재 혹은 향후에 발생하는 버그를 찾는 데 있다. 따라서 단순히 필드를 읽고 쓰기만 하는 접근자는 테스트할 필요가 없다.

문제가 생길 가능성이 있는 경계 조건을 생각해보고 그 부분을 집중적으로 테스트하자.

**버그 리포트를 받으면 가장 먼저 그 버그를 드러내는 단위 테스트부터 작성하자.**

**Comment by joi0104** [comment]
전반적으로 읽기가 힘든 장이네요 ㅠ 예시와 함께 작성어 있지도 않고 아직 소개하지 않은 리팩토링 기법도 언급되어 있어서 내가 이해한게 맞나? 라고 생각하면서 읽었던 장이었습니다 🙏


## 3. 코드에서 나는 악취

> API를 만들 때는 질의 함수와 변경 함수 분리하기를 활용해서 꼭 필요한 경우가 아니라면 부작용이 있는 코드를 호출할 수 없게 한다. 

put, post, delete api의 경우에 연산을 수행한 데이터의 id나 데이터를 반환하도록 설계하기도 하는데, 이때 위 api는 질의와 변경을 함께 수행하고 있다고 할 수 있을까요? 그렇다면 분리하는게 이상적일까요?


> 한편, 데이터 클래스는 필요한 동작이 엉뚱한 곳에 정의돼 있다는 신호일 수 있다. 이런 경우라 면 클라이언트 코드를 데이터 클래스로 옮기기만 해도 대폭 개선된다. 물론 예외도 있다. 특히 다른 함수를 호출해 얻은 결과 레코드 (데이터 객체)로는 동작 코드를 넣을 이유가 없다. 대표 적인 예로 단계 쪼개기 결과로 나온 중간 데이터 구조가 있다. 이런 데이터 구조는 (적어 도 현실에서 활용되는 모습상으로는) 불변muable 이다. 불변 필드는 굳이 캡슐화할 필요가 없고, 불변 데이터로부터 나오는 정보는 게터를 통하지 않고 그냥 필드 자체를 공개해도 된다.


이 부분 전체를 이해 못했는데 설명해주실 분 있을까요?

**Comment by hjsung809** [comment]
3장은 예시가 없어 어려웠지만 다양한 리팩토링 케이스를 확인할 수 있어 좋았습니다. 뒤 내용을 더 읽어보고 다시 읽으면 좋을것 같습니다.


3.7 3.8
공식에 대입하듯이 메서드나 클래스로 분리하기보다는 항상 고민하고 더 나은 방향으로 분리해야 되는 것 같습니다. 분리가 과하면 shootgun surgery가 될것같고 부족하면 divergent change가 될것 같습니다

3.17
굉장히 미묘하고 어려운 부분 같습니다.
어느 단계에 위임할지를 어떻게 정할까요? 복잡하지 않다면 최상위 객체에 위임하는게 일반적일것 같습니다


3.22
데이터 클래스는 객체보다는 자료구조로 보면 될까요? 클린 아키텍처 내용이 었던것 같습니다.

**Comment by lallaheeee** [comment]
## 03. 코드에서 나는 악취

```
냄새 나면 당장 갈아라. 
-켄트 벡 할머니의 육아 원칙 

'적용 방법’을 아는 것과 ‘제때 적용’할 줄 아는 것은 다르다. (p.113)

우리는 이 방식을 권하지 않는다. 
아니, 항상 이렇게 해야 한다는 입장은 아니다. 
일부 동작을 재활용하기 위한 목적으로 상속을 활용하기도 하는데, 실무 관점에서 아주 유용한 방식이다. 
솔직히 냄새를 풍기지만, 보통은 참을 만한 경우 가 많다. 
그래서 상속을 포기할 시 혼란과 문제가 생긴다면 앞에서 설명한 예전 방식을 따른다. 
단, 무조건 이래야 한다는 생각은 버리자. 
열에 아홉은 냄새가 미미해서 굳이 씻어내지 않아도 된다. (132p)
```
예술의 경지이라고 생각이 듭니다


```
현재 진행 상황뿐만 아니라 확실하지 않은 부분에 주석에 남긴다. 
코드를 지금처럼 작성한 이유를 설명하는 용도로 달 수도 있다. 
이런 정보는 나 중에 코드를 수정해야 할 프로그래머에게, 특히 건망증이 심한 프로그래머에게 도움될 것이다.
```
for..me..


## 04. 테스트 구축하기

```
 난 상당히 게을러서 일을 줄이는 작업이라 면 얼마든지 감수할 각오가 돼 있다.  (135p)
```
ㅎㅎ xdescribe.. 

```
테스트를 작성하 다 보면 원하는 기능을 추가하기 위해 무엇이 필요한지 고민하게 된다. 
구현보다 인터페이스에 집중하게 된다는 장점도 있다(무조건 좋은 일이다).

리팩터링에는 테스트가 필요하다. 그러니 리팩터링하고 싶다면 테스트를 반드시 작성해야 한다. (136p)
```
리팩토링으로 인터페이스가 "많이" 변경되면 
바로 테스트의 변경으로 이어질 텐데 이럴 경우엔 정확한 동작이 맞는지는 어떻게 확인할 수 있을까요.. 

```
-
실패해야 할 상황에서는 반드시 실패하게 만들자. 

-
이를 위해 내가 흔히 쓰는 방법은 일시적으로 코드에 오류를 주입하는 것이다. (142p)

```
좋은 테크닉 1

```
명심하자! 테스트는 위험 요인을 중심으로 작성해야 한다! 
테스트의 목적은 어디까지나 현재 혹은 향후에 발생하는 버그 를 찾는 데 있다. (143p)
```
맞는 말 1

```
사실 나는 먼저 기댓값 자리 에 임의의 값을 넣고 테스트를 수행한 다음, 프로그램이 내놓는 실제 값(230)으로 대체했다. 직접 손으로 계산해도 되지만, 코드가 제대로 동작할 거라 믿고 일단 이렇게 했다. 그런 다음 테스트가 제대로 작동한다고 확인되면, 총수익 계산 로직에 * 2를 덧붙여서 잘못된 값이 나오 도록 수정한다. 일부러 주입한 이 오류를 테스트가 걸러내는 게 확인되면, 만족해하며 원래 코 드로 되돌린다. 임시 값을 설정했다가 실제 값으로 대체하고, 오류를 심었다가 되돌리는 이 패 턴은실제로내가기존코드를검사하는테스트를추가할때흔히쓰는방식이다.
```
좋은 테크닉 2

```
그런데 이 범위를 벗어나는 경계 지점에서 문제가 생기면 어떤 일 이 벌어지는지 확인하는 테스트도 함께 작성하면 좋다. (148p)
```
맞는 말 2

```
버그를 고치기 전에 항상 이런 테스트부터 만든다. 그러면 해당 버그가 다시 나타나지 않는지 확인할 수 있다 (151p)
```
테스트가 왜 필요해요? 할 때 상대를 설득할 수 있는 좋은 말~!

**Comment by wlsh44** [comment]
이번 3, 4장은 성찰을 많이 하면서 읽었던 것 같아요

> 그래서 데이터 항목 서너개가 여러 곳에서 항상 함께 뭉쳐 다니는 모습을 흔히 목격할 수 있었다. 이렇게 몰려다니는 데이터 뭉치는 보금자리를 따로 마련해줘야 마땅하다. ... 데이터 뭉치인지 판별하려면 값 하나를 삭제해보자. 그랬을 때 나머지 데이터만으로는 의미가 없다면 객체로 환생하길 갈망하는 데이터 뭉치라는 뜻이다. (122p 데이터 뭉치)

데이터에 의미를 부여한다는 말이 참 좋았습니다. 확실히 언제부턴가 단순 list나 map과 같은 단순 데이터 저장 자료구조를 보면 이게 뭐지 라는 생각이 들면서 의미를 주고싶다는 생각이 들고 있었던 것 같아요.

> 솔직히 냄새를 풍기지만, 보통은 참을 만한 경우가 많다. 그래서 상속을 포기할 시 혼란과 문제가 생긴다면 앞으로 설명한 예전 방식을 따른다. 단, 무조건 이래야 한다는 생각은 버리자. 열에 아홉은 냄새가 미미해서 굳이 씻어내지 않아도 된다. (131p 상속 포기)

항상 사람들이 말하는 코드에 정답은 없는 것 같다는 말 같네요. 최근에 계속 상속보다는 인터페이스를 통한 구현이 좋다는 말을 들어서 죽어도 상속을 안하려고 했는데 반성하게 되네요..

사실 3장은 새로운 내용을 배운다기 보다는 이 내용을 잘 지키고 있는지에 대해 생각을 하며 읽었습니다. 항상 이런 내용들을 지키려고 해도 저도 모르는 사이에 이런 냄새가 나는 코드를 작성하는 것 같아요. 말 할때 필터링 거치고 말하듯이 코드도 좀 더 정신차리고 작성 해야겠다는 생각을 했습니다!

> 자주 테스트하라. 작성 중인 코든느 최소한 몇 분 간격으로 테스트하고, 적어도 하루에 한 번은 전체 테스트를 돌려보자.(141p)

사실 테스트 자주 안돌리고 기능 다 만든 후에 push 하기 전에 돌렸다가 테스트 깨져있는 경우가 많아서 많이 찔리는 부분이었습니다..😭

> 테스트를 너무 많이 작성하다 보면 오히려 의욕이 떨어져 나중에는 하나도 작성하지 않게 될 위험도 있다. (150p)

저는 의욕이 너무 쉽게 꺾이는데 혹시 다른 분들은 어떤 생각을 가지고 테스트를 작성하시는지 궁금합니다!

> 버그 리포트를 받으면 가장 먼저 그 버그를 드러내는 단위 테스트부터 작성하자. (151p)

명심하겠습니다..!

**Comment by usageness** [comment]
# 3. 코드에서 나는 악취

```
p.114
(리팩토링을 언제 멈출지에 대한 이야기 중) ...우리 경험에 다르면 숙련된 사람의 직관만큼 정확한 기준은 없다.
(중략) 각자 경험을 통해 감을 키워야 한다.
```

직관의 영역.. 정말 맞는 이야기 같습니다. 리팩토링 종료의 시점은 명확하게 언제라고 정의내릴 수가 없는 것 같아요.
빨리 취업을 하고 현업을 뛰다 보면 그 감이 생길텐데.. 취업하기 전에 Chat GPT한테 일자리 뺏길 것 같네요 ㅎㅎ


```
p.114
마땅한 이름이 떠오르지 않는다면 설계에 더 근본적인 문제가 숨어 있을 가능성이 높다.
```

피어 리뷰 중 제가 가장 많이 하는 리뷰가 네이밍에 관련한 리뷰인데,
사실 저는 설계에 문제가 있다는 느낌적인 느낌을 받고 있었는지도 모르겠어요 😂


```
p.115
함수가 길수록 이해하기 어렵다는 사실을 깨달았다.
```

긴 함수를 줄이다가도 아직 보기에 복잡하고 길어보이는 함수지만
더 이상 줄일곳이 보이지 않아서 "여기서 어떻게 더 줄이지?" 하고 고민할 때가 많았어요.
지금 생각해보니 이때는 추상화 수준을 맞춰주는 작업을 할 수 있었을 것 같네요.
길이는 여전하지만 복잡하지 않은 함수로 바꿀수는 있었을 것 같습니다.
단순히 길다고 문제가 아니라, 길어서 생기는 문제를 찾는게 중요했던 것 같습니다~

```
p.117
전역 데이터를 주의해야 한다는 말은 우리가 소프트웨어 개발을 시작한 초창기부터 귀가 따갑게 들었다.
```

`var` 쓰지 말기 운동

```
p.124
... 하지만 이제는 1970년대에 유행하던 나팔바지나 솜털 무늬 벽지보다도 못한 존재가 됐다.
```

제발 `for` 그만 쓰기 운동

# 4. 테스트 구축하기

```
p.134
모든 테스트를 완전히 자동화하고 그 결과까지 스스로 검사하게 만들자.
```

개인 플젝에서라도 테스트 커버리지 100% 찍어보는게 꿈이었는데, 다시 열정이 샘솟네요.

전체적으로 4장은 과정을 볼 수 있어서 좋았습니다!
