### ISSUE TITLE
[리팩터링] 22.02.19/4주차 - 챕터 6. 기본적인 리팩터링, 6.7 변수 이름 바꾸기 끝까지 ~ 195p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#103]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
저는 딱히 음슴

**Comment by hjsung809** [comment]
p 159
'목적과 구현을 분리'
내용이 매우 짧아도 구현을 감추고 목적을 드러내는 것만으로도 코드를 쪼갤 이유가 된다는 부분이   평상시 코드 분리 후에 코드 양이
적어서 위화감을 느끼고 있던 부분이 괜찮았던 것이라고 생각되서 좋았습니다.
예전에 말씀해주신 부분 같습니다

**Comment by joi0104** [comment]
254p

constructor(value) {
 if (value instanceof Priority) { reuturn value; } 
 this._value = value;
}

value가 Priority 인스턴스라면 그대로 반환하는 로직이 어떤 이점을 가져다 주는건지 잘 모르겠습니다.. 어색하다고 느껴졌어요.

**Comment by usageness** [comment]
> 언제 코드를 독립된 함수로 묶어야 할지에 관한 의견 (p.159)

1회독때는 잘 몰랐는데, 막상 리팩토링을 몇 번 해보고 난 지금은
저자가 말한 목적과 구현을 분리한다는게 어떤 의미인지 알 것 같네요.


> 성능이 느려질까 걱정하는 사람도 있다. (p.159)

이 책 끝날때까지 계속 보게 될 이야기
"성능은 신경쓰지 마라"


> 인라인 작업을 한 번에 처리할 필요는 없다. 인라인하기가 까다로운 부분이 있다면 일단 남겨두고 여유가 생길 때마다 틈틈히 처리한다. (p.170)

팀에서 점진적으로 리팩토링을 진행할때, "최종 결과물이 어땠으면 좋겠다~" 하는 청사진을 팀원들에게 공유하시나요?
개개인이 조금씩 리팩토링을 진행한다는걸 팀원들이 모르면 나중에 곤란해질것 같다는 느낌이 들어요.


> 자바스크립트에서는 게터와 세터의 이름을 똑같이 짓고 인수가 있냐 없냐에 따라 구분하는 방식을 많이 따른다. (p.191)

여담이지만 자바스크립트에도 정식으로 get / set 접근자가 생겼습니다.
사용 방식이 좀 괴상해보이실것 같지만...

```
const bookStudy = {
  members: []
  set member(name) {
    this.members.push(name);
  },
}

bookStudy .member= 'genie-youn';
// ['genie-youn']
```

**Comment by siathus** [comment]
기본적인 리팩토링 기법들을 전체적으로 소개하는 챕터들이라 큰 궁금증은 없었네요.

저자는 게터 메소드 앞에 get을 붙이는 걸 싫어한다고 하는데(p. 191), 주석에 쓰여진 링크에 따르면 "내가 선호하는 것은 모든 세터들은 눈에 띄어야 하는 것"이기 때문인 것 같습니다. 이에 대한 여러분들의 의견이 궁금하네요.

**Comment by KangJiJi** [comment]
7가지 리펙터링 기법을 소개해주는 내용이였고, 크게 어려움은 없었습니다.

**Comment by wise1ight** [comment]
좋은 이름 떠올리는 방법 : 주석 달아보기 (180p)
호출하는 곳에서 새로 추가한 매개변수를 실제로 사용하는지 확인 : 어서션 추가 (185p)

**Comment by eagleda** [comment]
변수 이름 바꾸기, 함수 추출하기 등 코드를 이해하기 쉽게 만들 리팩터링 기법들이 많네요.
함수 추출하기는 페어 프로그래밍에서 @wlsh44 진호님이 예시와 장점을 보여주신 만큼 
습관화할 수 있도록 자주 사용해봐야겠습니다.

**Comment by wlsh44** [comment]
> 호출문을 변경하기 전에 어서션을 추가하여 호출하는 곳에서 새로 추가한 매개변수를 실제로 사용하는지 확인한다 (185p)

이런 부분은 테스트 코드의 역할이고, 이런 코드가 계속 생기다보면 코드 스멜이 되지 않나 하는 생각이 드는데 어떻게 생각하시는지 궁금합니다!
또 예시로 나온 코드가 잘 이해가 안가는데
```javascript
assert(isPriority == true || isPriority == false);
```
이 코드가 `null`인지를 체크하는 코드가 맞나요..?

그리고 클린코드에서 플래그 인수는 추하다는 내용이 생각났네요..🙃🙃
