### ISSUE TITLE
[리팩터링] 22.03.05/5주차 - 챕터 6. 기본적인 리팩터링 끝까지 ~ 234p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#104]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by joi0104** [comment]
이번장은 좋은 내용들이 많았던 것 같은데 조금 어렵네요 ㅠ

>  변환 함수는 원본 데이터를 입력받아서 필요한 정보를 모두 도출한 뒤, 각각을 출력 데이터의 필드에 넣어 반환한다.

변환함수를 위 정의대로 이해했는데요. 227p의 parseCommandLine 함수도 변환 함수라고 볼 수 있을까요?

**Comment by hjsung809** [comment]
p 197
비슷한 데이터 항목을 매개 변수 객체로 만들고 외부에 흩어져있던 로직들을 한 곳으로 모으는게 추상화를 위한 시작점이 되어주는 것 같습니다. 그런식으로 추상화 할때마다 전체 코드 변경이 많이 일어나고 코드가 훨신 간결해졌던 경험이 있습니다

6.9 ,6.10
데이터가 불변적이지 않을 때에는 질의 함수로 원본 데이터를 활용하고, 불변적일때는 레코드
화를 시켜 놓으면 좋을것 같습니다. 이렇게 2개로 나눠 놓으니 명확하고 재밌는것 같습니다.

6.11
단계 쪼개기는 코드의 가독성을 높이고 역할과 책임으로 코드를 나눌 수 있는 가장 기본적이고 유용한 기법 같습니다. 단계적으로 코드를 바꿔나가는 과정이 인상깊고 배울만 한것 같습니다.
6.9 처럼 리팩토링 할것인지 6.10 처럼 할것 인지에 따라 리팩터링 과정이 다른것도 신기하고 재미있었습니다

p223
 테스트가 어려운 코드를 테스트 가능하도록 바꿔놓고 리팩토링 진행(험블 객체 패턴)하는게 인상 깊었습니다

**Comment by wise1ight** [comment]
6.8 매개변수 객체 만들기에서 몰려다니는 파라미터들 값 객체로 만들면 나중에 관련 동작을 해당 클래스로 옮길때 유용하겠구나 느꼈습니다.
자바에서 몰려다니긴 하지만 그 수가 두개밖에 안되는 파라미터들을 위해(간단한 경우라고 여겨질 경우) 클래스 따로 만드는것도 귀찮지 않나요 🥲
제 심리적인 장벽이 있어서 그런진 모르겠는데 JS할땐 만들기 쉬우니까 많이 그렇게 썼던것 같습니다.

6.9는 자바를 주로 써서 그런지 하나의 기법이라고 소개되어있는게 신기하네요.
당연하게 클래스 단위에서 메서드를 만들어 사용하니까 이 부분은 잘 와닿지가 않습니다.

그리고 읽어보면서 사용하는 언어에서 불변 데이터 구조를 지원하느냐에 따라 리팩토링 기법도 차이가 나는구나 하고 읽어봤습니다.

**Comment by siathus** [comment]
이번에도 저번 주와 마찬가지로 여러 리팩토링 기법들을 소개하고, 그 기법이 어떤 경우에 사용되는지 예시를 들어 설명하는지라 크게 궁금한 점은 없었습니다.

**Comment by lallaheeee** [comment]
ㅎㅎ..어려워요..

**Comment by genie-youn** [comment]
## 6.8 매개변수 객체 만들기

개개인적으로 클래스로 만드는 걸 선호한다. 나중에 동작까지 함께 묶기 좋기 때문이다. 나는 주로 데이터 구조를 값 객체로 만든다. → 👀 ?

값 객체, 즉 자료구조라고 하더라도 동작이 포함되지 말라는 이유는 없다. 컬렉션인 List 는 다양한 메소드를 제공하지 않는가? 여기에 비즈니스 로직이 담기느냐 담기지 않느냐로 이해하면 될까?

세시간동안 쓴 코드 git reset 한 썰
> 처음부터 올바르게 시스템을 만들 수 있다는 믿음은 미신이다. 대신에 우리는 오늘 주어진 사용자 스토리에 맞춰 시스템을 구현해야 한다. 내일은 새로운 스토리에 맞춰 시스템을 조정하고 확장하면 된다. 이것이 반복적이고 점진적인 애자일 방식의 핵심이다. 테스트 주도 개발, 리팩터링, 깨끗한 코드는 코드 수준에서 시스템을 조정하고 확장하기 쉽게 만든다. - 클린코드

**Comment by eagleda** [comment]
계속해서 사용되는 매개변수들을 묶어 매개변수 객체를 만들면 확실히 여러 함수에서 호출해야 할 때 더 편리해지겠군요..
알고리즘 문제 풀이에서 C++의 클래스 기능을 써볼까 생각 중인데 매개변수가 많아지면 사용을 고려해 봐야겠습니다.
다른 것도 유용한 게 많은데 아직 개인 프로젝트등의 진행 경험이 없어 어떻게 쓰면 좋겠구나 보다는 이런 게 있구나 하고 넘어가야 하는 게 상당히 아쉽습니다.

**Comment by lallaheeee** [comment]
>처음부터 올바르게 시스템을 만들 수 있다는 믿음은 미신이다. 대신에 우리는 오늘 주어진 사용자 스토리에 맞춰 시스템을 구현해야 한다. 내일은 새로운 스토리에 맞춰 시스템을 조정하고 확장하면 된다. 이것이 반복적이고 점진적인 애자일 방식의 핵심이다. 테스트 주도 개발, 리팩터링, 깨끗한 코드는 코드 수준에서 시스템을 조정하고 확장하기 쉽게 만든다. - 클린코드

오.. 좋은 글.. 새 프로젝트를 맡게 된 1인으로써.. 마음에 새기고 갑니다..

**Comment by wlsh44** [comment]
불변성에 대해 보다보니까 자바 16에 정식으로 생긴 `record`라는 키워드가 생각이 났네요. 필드랑 객체 자체도 `final`로 선언해줘서 dto와 같은 불변 데이터 구조에 사용하기에 좋은 것 같았습니다. 다만 아직도 자바 8이나 11을 쓰는 곳이 많아서 그런지, 쓰이는 곳을 한 번도 못 봐서 손길이 안가는...

6.9
뭔가 자바에서는 클래스를 만든다는 거 자체가 패키지 구조를 복잡하게 만들어서 비용이 생겨 항상 고민을 많이 하는 것 같아요.. 예를 들어 JPA 쿼리에서 entity가 아니라 특정 row만 뽑아오게 하는 방법으로 dto를 쓰거나 인터페이스를 사용하는 방법이 있는데 오히려 패키지 구조만 더 복잡해져서 처음 알게된 이후로는 사용한 적이 없게 되었습니다

**Comment by KimDa99** [comment]
함수 선언 바꾸기 = 함수의 정의/역할을 더 명확히 하기
라는 생각이 들었다. 또 처음부터 역할을 완벽하게 정하는 걸 기대하면 안된다는 것을 느꼈다.
---

자바스크립트를 잘 알지 못해서 정확한 이해가 안되는 부분들이 꽤 많았다.
물론 눈치껏 어떤 뜻을 전하고 싶은 건지 알 순 있었다.

사실 책걸이에 들어왔을 당시 이러한 부분 + 경험 부족이 큰 걸 잘 알고 있었기 때문에, 이런 책들이 당장 나에게 도움이 될 거라고 기대를 안했었다. 책 자체에서 무언갈 얻어가길 기대하기 보단, 이 스터디 자체를 하면서 동기 부여를 받거나 방향을 잡고 싶었다.

근데 생각보다 더 일찍 책의 도움을 받을 수 있었다.
이번 책도 그렇고, 저번의 '객체지향의 사실과 오해'을 읽는 그 순간은 '아... 좋은 말씀' 이런 느낌만 들고 구체적으로 와닿진 않아 역시 당장 도움이 되지 않겠구나 예상했다.
하지만 프로젝트를 진행하다보니, 객사오에서 읽은 내용에 도움을 받아 (내 기준) 꽤 괜찮은 결정을 내릴 수 있는 순간들이 꽤 있었다.
책 없이 나의 경험으로만 코드를 짰다면 그런 결정을 내릴 때까지 훨씬 더 오래 걸렸을 것 같다.

그래서 완벽히 이해를 못하더라도 조만간 도움이 될 것이고, 이해가 될 것이라고 믿고 읽고 있다!
