### ISSUE TITLE
[리팩터링] 22.03.12/6주차 - 챕터 7. 캡슐화 끝까지 ~ 275p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#105]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
모듈을 분리하는 가장 중요한 기준은 시스템에서 각 모듈이 자신을 제외한 다른 부분에 드러내지 않아야 할 비밀을 얼마나 잘 숨기느냐에 있을것이다.

리스트-해시 구조
<img width="838" alt="스크린샷 2023-03-12 오후 5 27 41" src="https://user-images.githubusercontent.com/16642635/224533251-2fb8bdf3-c48b-43b3-a3f0-4d57499f48bf.png">

에휴..
<img width="796" alt="스크린샷 2023-03-12 오후 5 31 04" src="https://user-images.githubusercontent.com/16642635/224533395-5a3ef621-37ab-4c20-8315-85e3a966f5da.png">

그냥 7.3 예제가 좋아서, 얼마전 매 커밋마다 코드베이스가 깨지지 않도록 유지하면서 작게 변경하는것의 효용을 몸소 깨닫고 난 이후에는 책의 절차를 유심히 살펴보게 되었습니다.

```javascript
class Order {
  constructor(data) {
    this.priority = data.priority
  }
}

highPriorityCount = orders.filter(o => 'high' === o.priority || 'rush' === o.priority).length
```

```javascript
class Order {
  constructor(data) {
    this._priority = data.priority
    this.priority = new Priority(data.priority);
  }

  get priority() {
      return this._priority; // TO-BE this.priority.toString()
   }
}

class Priority {
  constructor(value) {this._value = value;}
  toString() {return this._value;}
}
```

**Comment by wlsh44** [comment]
7.1
> 해시맵은 다양한 프로그래밍 작업에 유용하지만, 필드를 명확히 알려주지 않는다는 게 단점이 될 수 있다. (237p)

개발을 하다보니까 확실히 맵같이 불특정 필드를 가진 자료구조는 추상화를 하거나 생명주기를 짧게 하는게 좋았던 것 같습니다..!

7.2
> 예컨대 aCustomer.orders.size()처럼 접근하는 코드를 aCustomer.numberOfOrders()로 바꾸는 것이다. 나는 이 방식에 동의하지 않는다. (247p)

이 부분이 잘 이해가 안가는데, 이 예제가 캡슐화를 대표할 수 있는 예제 아닌가요..? 뒤에 나오는 예제에서 `addCource`도 리스트의 `push` 메서드를 캡슐화를 한 거처럼 보이는데 이해를 잘 못하고 있는지 궁금합니다!

그리고
 `컬렉션 연산들을 조합해 쓰기도 어려워진다`
이 말이 어떤 어려움을 뜻하는지 잘 모르겠습니다..

7.3
요 장은 1번 과정 없이 냅다 클래스 만들고 값 다 때려 넣은 다음 기차코드부터 작성하던 저를 반성하게 하는 것 같습니다..ㅎㅎ(자동으로 getter같은 단순 메서드를 만들어주는 lombok 라이브러리의 단점이 요런 부분에서 있는 것 같기도 하네요) 보면서 제일 인상 깊었던 부분이었습니다!

```javascript
constructor(value) {
    if (value instanceof Priority) return value;
    ...
}
```
js에서 생성자에 return value를 추가할 수 있다는걸 처음 알았네요. 잘 이해한건지는 모르겠는데 이렇게 해서 혹시라도 Priority 객체가 인자로 넘어오면 바로 리턴 시키고 생성된 객체를 바로 gc 대상이 되도록 하는 건가요? (근데 이런 코드가 쓰일 일이 있나요...?)

(더 가다듬기를 보면서 자바의 enum이 잘 만들어졌다 라는걸 느끼고 갑니다..)

****
최근에 책 읽으면서 개인 플젝도 시작 했는데 확실히 병행을 하니까 책 내용이 조금 더 와닿는 게 느껴져서 재밌게 읽고 있습니다!!
예시도 좀 더 쉽게 들어지고 책 내용도 조금씩 적용을 해보고 있는데 좋은 것 같습니다ㅏㅏ 🙂🙂

**Comment by wise1ight** [comment]
237p
> 해시맵은 다양한 프로그래밍 작업에 유용하지만, 필드를 명확히 알려주지 않는다는게 단점이 될 수 있다.

저두.. 인상 깊어서..

244p에서
```javascript
get rawData() {
  return _.cloneDeep(this._data);
}

function compareUsage (customerID, laterYear, month) {
  const later = getCustomerData().rawData[customerID].usages[laterYear][month];
  const earlier = getCustomerData().rawData[customerID]
                                   .usages[laterYear - 1][month];
  return {laterAmount: later, change: later - earlier};
}
```
계속 타고 타고 쓰는부분
내가 만들면 너무 별로인데 책에서는 왜 괜찮아보일까 생각을 해보면
좋은 작명 때문에 코드가 직관적으로 이해되어서 변수명이던 함수, 메서드명이던 잘 지어야겠다 반성하게 됩니다.

그리고 바로 밑에 눈으로 성능 문제가 보이는 것은
>  나라면 막연히 걱정만 하지 않고 얼마나 영향을 주는지 실제로 측정해본다.

실천의 중요성까지 알려주시네요..

**Comment by joi0104** [comment]
254p

```
constructor(value) {
    if (value instanceof Priority) return value;
    ...
}
```

이거 이전에 남겼던 것인데.. 이렇게 작성하는게 왜 좋다고 표현하는지 모르겠습니다. 타입스크립트가 아니라 자바스크립트여서 그런걸까요..?

247p

컬렉션을 읽기전용으로 제공하거나 복제본을 제공하는 방식으로 내부 컬렉션을 직접 수정하지 못하게 방지하는 부분들이 인상깊었습니다. 추상화에 집중하다보니 이런 부분에서 캡슐화가 깨진다는 것을 간과하게 되기도 하는 것 같아요.

272p

> 필요하면 언제든 균형점을 옮 길 수 있으니 말이다. 시스템이 바뀌면 ‘적절하다’의 기준도 바뀌기 마련이다. 6개월 전에는 바람직했던 캡슐화가 이제는 어색할 수 있다. 리팩터링은 결코 미안하다고 말하지 않는다. 즉시 고칠 뿐이다

좋은 내용이라 인용해봤습니당

**Comment by KangJiJi** [comment]
크게 어려움 없이 읽을 수 있는 장이였습니다.

요즘 프로젝트의 코드를 리팩터링 하는 작업을 계속 하고 있는데, 쉽지 않네요. 책내용을 보면 항상 클래스 추출하기 <-> 클래스 인라인하기, 위임 숨기기 <-> 중개자 제거하기 등등 반대되는 기법들을 알려주는데, 상황에 따라 어떤것을 적용해야할지 고르는게 어렵네요.

> ~~동작만 하면 장떙인가 ㅎㅎ~~

**Comment by siathus** [comment]
> 컬렉션에 대해서는 어느 정도 강박증을 갖고 불필요한 복제본을 만드는 편이, 예상치 못한 수정이 촉발한 오류를 디버깅하는 것보다 낫다. 컬렉션 관리를 책임지는 클래스라면 항상 복제본을 제공해야 한다. (p. 250)

> 나는 단순한 출력 이상의 기능이 필요해지는 순간 그 데이터를 표현하는 전용 클래스를 정의하는 편이다. (p. 251)

> 먼저 `basePrice`에 `const`를 붙여 읽기전용으로 만들고 테스트해본다. (p. 258)

불변으로 선언해서 변수에 새로 값을 대입하는 코드가 있는지 확인하는 이 방법 아주 간단하면서도 효과적인 것 같네요.

**Comment by eagleda** [comment]
> 7.2 _컬렉션(Collection): 자바에서 다수의 데이터를 쉽고 효과적으로 처리할 수 있는 표준화된 방법을 제공하는 클래스의 집합_

자바를 많이 사용해보지 않아서 일단 기본적인 용어부터 찾아보고자 했습니다.
주요 인터페이스로 List, Map, Set 인터페이스를 설명하고 있는데, 다른 언어에서의 각각의 자료구조와 비슷한 방식으로 구현되어 있는지 좀 더 알아봐야겠습니다.

> 클래스 추출하기 <-> 인라인하기, 위임 숨기기<-> 중개자 제거하기

코드를 보고 현재 필요한 리팩터링 기법이 어떠한 쪽인지 파악할 수 있는 눈을 기르는 것이 중요할 것 같습니다.

**Comment by usageness** [comment]
개념 자체는 평소에 리팩토링 하던 것과 비슷해서 끄덕거리면서 읽었던 장인 것 같네요.
다만 클래스 관련 부분은 살짝 애매하다는 느낌이 들어요. 클래스를 쓸 일이 거의 없어서 그런지.. ㅎ
타입스크립트랑 같이 쓰려니 헷갈리는 부분도 있고, 자바스크립트로 코드가 써있어서 그럴지는 몰라도
확 와닿는 코드들은 아니었다는 개인적인 느낌입니다!


p.243
> 데이터 구조의 읽기전용 프락시를 반환하는 방법도 있다. 클라이언트에서 내부 객체를 수정하려 하면 프락시가 예외를 던지도록 하는 것이다. 이 기능을 손쉽게 구현할 수 있는 언어도 있지만, 자바스크립트는 아니다.

proxy 기반으로 데이터 상태를 관리하는 라이브러리가 있긴 했던걸로 기억합니다. 아마 valtio였던거 같은데... 혹시 아시면 제보 바랍니다 ㅎㅎ
