### ISSUE TITLE
[리팩터링] 22.03.12/6주차 - 챕터 8. 기능 이동 끝까지 ~ 328p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#106]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by joi0104** [comment]
8.3 문장을 함수로 옮기기 

> 문장들을 함수로 옮기려면 그 문장들이 피호출 함수의 일부라는 확신이 있어야 한다. 피호출 함수와 한 몸은 아니지만 여전히 함께 호출돼야 하는 경우라면 단순히 해당 문장들과 피호출 함수를 통째로 또 하나의 함수로 추출한다.

위에서 말한 함수 분리를 하게 되면 네이밍 짓기가 어려웠던 것 같아요. ~And~ 와 같은 네이밍을 쓰곤 했는데 함수가 두가지 역할을 하는 것 같아서 이렇게 분리해도 괜찮을까? 라는 생각이 들었습니다. 

8.5 

> 기존 함수의 코드를 수정하더라도 인라인 코드의 동작은 바뀌지 않아야 할 때뿐이다. 이 경우인가를 판단하는 데는 함수 이름이 힌트가 된다. 이름을 잘 지었다면 인라인 코드 대신 함수 이름을 넣어도 말이 된다. 말이 되지 않는다면 함수 이름이 적절하지 않거나(함수 이름을 바꿔주자), 그 함수의 목적이 인라인 코드의 목적과 다르기 때문일 것이다

👍

**Comment by usageness** [comment]
p.290
> 필드 옮기기 리팩터링은 대체로 더 큰 변경의 일환으로 수행된다.

실제로 필요에 의해 다른 리팩토링을 진행하는 과정에서 필드 옮기기를 먼저 해주게 되는 경우가 많았던 것 같네요.

p.316
> 반복문을 두 번 실행해야 하므로 이 리팩터링을 불편해하는 프로그래머도 많다.

이 책을 처음 읽을때 "굳이 반복문을 두 번이나 돌려야 하나..?" 싶어서 불편함을 느꼈던 것 같은데
지금 보니까 두 번 돌릴 필요가 있긴 할 것 같네요... ㅋㅋㅋ
반복문을 나누면서 생각했던 내용이 `p.318 더 가다듬기` 에 그대로 나와서 신기했습니다.

p.320
> 논리를 파이프라인으로 표현하면 이해하기 훨씬 쉬워진다.

함수형 최고 👍

**Comment by wlsh44** [comment]
8.6

> 내부(그리고 그 안에서 호출하는 모든 함수의 내부도... 또 그 내부도...)를 살펴 아무 부수효과가 없음을 확인해야 한다. 하지만 나는 거의 명령-질의 분리 원칙을 지켜가며 코딩하므로, 내가 직접 작성한 코드라면 값을 반환하는 함수는 모두 부수효과가 없음을 알고 있던 것이다. (312p)

저도 꼭 지키겠습니다ㅏ👍👍

> 잘 모르는 코드베이스에서 작업한다면 더욱 주의해야 한다. (312p)

정말 이런 경우에는 특히 테스트 코드가 더 든든할 것 같아요..

8.8

그동안 리팩터링 하는 내용들도 신기했지만 이번 반복문에서 파이프라인으로 리팩터링하는 과정이 되게 인상깊어서 바로 해보러 갔는데 생각보다 쉽지는 않았네요.. 자바라서 그럴 수도 있지만 한 번 파이프라인 수정할 때마다 foreach 대상 리스트와 파이프라인 리턴 값 타입을 수정해야 할 가능성도 높고, 변수 명도 계속 바꿔줘야 해서 정말 큰 반복문이 아니라면 적용하기 힘들 것 같다는 생각을 했습니다

**Comment by wise1ight** [comment]
294p
> Account가 AccountType의 이자율을 가져오도록 수정하면 문제가 생길 수 있다.

리팩터링시 겉보기 동작이 달라지는지 확인! 내가 하고있는것이 정말 리팩터링인가? 생각하게 만드네요.
어서션을 추가해서 오류가 생기는지 확인해보는 과정이 인상깊었습니다.

**Comment by eagleda** [comment]
p.278

> 좋은 소프트웨어 설계의 핵심은 모듈화가 얼마나 잘 되어 있느냐를 뜻하는 모듈성(modularity)이다.


p.289
>... 프로그램의 진짜 힘은 데이터 구조에서 나온다. 주어진 문제에 적합한 데이터 구조를 활용하면 동작 코드는 자연스럽게 단순하고 직관적으로 짜여진다. 반면 데이터 구조를 잘못 선택하면 아귀가 맞지 않는 데이터를 다루기 위한 코드로 범벅이 된다...

**8.7 반복문 쪼개기**
간단한 PS에서도 반복문 하나로 대부분을 처리하려고 하다보면 높은 확률로 로직에 문제가 생기거나 나중에 이해하기 힘든 코드가 되고는 하니.. 반복문 개수가 늘어나더라도 코드가 복잡해지지 않게 나눌 필요가 있을 듯 합니다.

> _파이프라인_:  한 데이터 처리 단계의 출력이 다음 단계의 입력으로 이어지는 형태로 연결된 구조를... (출처: wikipedia)

용어가 긴가민가해서(학교에서 배웠던가..?) 해당 부분을 읽는 데 애로사항이. . 😓 이번 기회에 확실히 알아둬야겠네요.

**Comment by siathus** [comment]
# 8.7 반복문 쪼개기
> 반복문 쪼개기는 서로 다른 일들이 한 함수에서 이뤄지고 있다는 신호일 수 있고, 그래서 반복문 쪼개기와 함수 추출하기는 연이어 수행되는 일이 잦다. (p. 316)

이 챕터를 읽기 전까진 그다지 의식하지 않았던 부분인데 읽어보고 나니 어찌보면 당연한 건데도 소홀했다는 생각이 드네요.

# 8.8 반복문을 파이프라인으로 바꾸기
최대한 스트림을 사용해보려 노력하긴 하는데 아직 숙련도가 부족하다보니 로직이 조금만 복잡해져도 반복문이 훨씬 편한 걸 보면 저는 역시 Young하고 MZ하지 못하다는 생각이 듭니다.

여담이지만 <8.8 반복문을 파이프라인으로 바꾸기> 기법을 적용하면 <8.7 반복문 쪼개기> 기법도 자동으로 같이 적용이 될 것 같은 느낌이네요.

**Comment by hjsung809** [comment]
전체적으로 잘 안 와닿는 내용이었습니다
다른 기법을 참조해서 말할때 너무 읽기 어려웠습니다 ㅜㅜ

p294
이자율이 다른 계좌가 하나라도 있었다면 이건 더이상 리팩토링이 아니다.
모든 계좌의 이자율이 계좌 종류의 부합하게 설정되어 있는지 확인해야 한다.
 - 리팩토링을 위하여 배치로 모든 데이터를 확인하거나 로깅을 하는 일을 상당히 빈번하게 되는것 같습니다.

**Comment by lallaheeee** [comment]
```
2. Move Field

데이터 구조를 잘못 선택하면 아귀가 맞지 않는 데이터를 다루기 위한 코드로 범벅이 된다. (289p)
```
서버 리소스가 부족해서 원하는 데이터를 주지 않는 경우들이 있는데 이럴 때는 어떻게 하는 게 좋을까요? 
1. 화면에 필요하지 않은 데이터를 왕창 주거나 (over-fetching)
2. 하나의 컴포넌트에서 화면에서 그릴려면 여러개의 API 를 호출해야할 때 
4. 같은 형태의 UI 지만 특정 flag값에 따라 Request /  Response 인터페이스가 달라질 때 


```
2. Move Field

어서션을 추가하는 대신 문제 발생시 로깅하는 방법도 있다. (295p)
```
해당 예제에서 throw Error 해준다는 걸까요? 문제 발생을 어떻게 감지한다는건지 이해가 어렵습니다!


```
6. Slides Statements

관련된 코드들이 가까이 모여 있다면 이해하기가 더 쉽다.
예컨대 하나의 데이터 구조를 이용하는 statements들은 다른 데이터를 이용하는 코드 사이에 흩어져 있기보다는 한데 모여 있어야 좋다.
(310p)
```

여러 서비스를 함께 사용하는 모노레포 구조로 되어있다면, 폴더 구조 다들 어떻게 가져 가시는지? 기능별? 도메인별?

**Comment by KangJiJi** [comment]
![image](https://user-images.githubusercontent.com/22635168/226173377-ca41af63-96c8-4a0f-9364-a727a02bed4f.png)

훌륭합니다 :)

함수들을 이리저리 이동하고 삭제하는 리팩터링 기법에 관한 내용이였습니다. 테스트 코드가 참 중요하다고 느끼네요(빨리 테스트 코드 작성을 해야하는데...)
