### ISSUE TITLE
[리팩터링] 23.03.26/8주차 - 챕터 9. 데이터 조직화 끝까지 ~ 352p

### ISSUE THREAD

**Issue by lallaheeee** [TeamCrazyPerformance/http#107]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
(340p) assertion을 리팩터링 중간 과정을 검증하기 위한 용도로 사용하는 부분이 인상적이었음. 또 하나 배웠다.

**Comment by eagleda** [comment]
> 330p. 예외는 없다. 역할 하나당 변수 하나다.

> 334p. 데이터 구조가 중요한 만큼 반드시 깔끔하게 관리해야 한다. 다른 요소와 마찬가지로 개발을 진행할수록 데이터를 더 잘 이해하게 된다. 따라서 그 깊어진 이해를 프로그램에 반드시 반영해야 한다.

9.2 필드 이름 바꾸기의 예제에서 변경될 변수 이름(name)과 변경할 변수 이름을 동시에 사용할 수 있는 상태로 만들어 리팩터링 단계를 세분화하는 것이 인상 깊었습니다.

**Comment by wise1ight** [comment]
이번주차는 그냥 간단하게 책을 읽었습니다.
단계별로 리팩토링 하는 과정들이 인상깊었습니다.
지금까지 호스트 한 적이 없어서 다음주차는 제가 호스트하겠습니다

**Comment by usageness** [comment]
저도 이번 주차는 무난하게 읽었습니다.

**TMI**
> p.332 (해기스 안을 뭘로 채우는지 아는 사람?)

<details>
<summary>해기스(Haggis)란...</summary>
<div markdown="1">
스코틀랜드의 전통음식.

양이나 염소의 부속(심장, 허파, 간)을 잘게 다져 귀리/보리와 향신료를 섞은 다음 위장에 넣고 삶아낸 요리이다.

궁금해서 찾아봤습니다.
</div>
</details>

**Comment by wlsh44** [comment]
> (해기스 안을 뭘로 채우는지 아는 사람?)

갑자기 순대국밥이 먹고 싶네요

9.3 파생 변수를 질의 함수로 바꾸기

```javascript
get production() {
  return this._adjustments
      .reduce((sum, a) => sum + a.amount, 0)
}
```

이 부분도 for문 쪼개기처럼 사이드이펙트가 생길 것 같은데, 만약 reduce 작업이 느리고 getter의 쓰임이 많다면 다르게 처리하는 방법이 또 있을까요?
기존 코드로 되돌리자니 책에서 언급한대로 `applyAdjustment` 메서드 내에 부수효과가 생기는 것 같아 다른 방식이 있는지 궁금합니다!

**Comment by hjsung809** [comment]
p348
값을 참조로 바꿔서 하나가 수정되면 나머지도 수정되어야 하는 상황이 있더라도 저장소 객체처럼 사용하는 것보다는 데이터의 유효성을 짧게 가져가는 편이 사이드 이펙트 측면에서 유리할 것 같습니다. 예제의 레포지터리를 이용하는 방법이 유리할 상황이 잘 생각 나지 않는것 같습니다. 플라이 웨이트 패턴이 비슷한 것 같은데 맞는지 모르겠습니다

**Comment by lallaheeee** [comment]
```
특정 객체를 여러 객체에서 공유하고자 한다면, 그래서 공유 객체의 값을 변경했을 때 이를 관련 객체에게 모두 알려줘야 한다면 공유 객체를 참조로 다뤄야 한다. (343p~)
```
메모

**Comment by siathus** [comment]
# 9.2 필드 이름 바꾸기
> 모든 변경을 한 번에 수행하는 대신 작은 단계들로 나눠 독립적으로 수행할 수 있게 됐으니 말이다. 여기서 '작은 단계'라 함은 각 단계에서 잘못될 일이 적어졌고, 그래서 할 일도 줄었다는 뜻이다. 물론 실수를 저지르지 않는다면 줄어들 일도 없지만, '실수 없이'란 내가 아주 예전에 포기한 판타지일 뿐이다.

실수를 저지르지 않고도 모든 변경을 한 번에 수행할 수 있는 IDE의 Rename을 적극 이용합시다.

**Comment by joi0104** [comment]
이번 장은 딱히 어려운 부분없이 읽혔던 것 같습니다. 필드 이름 바꾸는 과정이 나왔었는데 꽤나 인상 깊었고 요렇게까지 해야하나? 싶기도 했었습니다 ㅎㅎ
