### ISSUE TITLE
[리팩터링] 23.04.02/9주차 - 챕터 10.4조건부 로직을 다형성으로 바꾸기 끝까지 ~ 387p

### ISSUE THREAD

**Issue by wise1ight** [TeamCrazyPerformance/http#108]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by wise1ight** [comment]
356p.
취향에 따라 전체 조건문을 3항 연산자로 바꿔줄 수도 있다고 되어있는데 취향의 문제를 떠나서
3항 연산자를 사용해서 어떤 장점을 가져갈 수 있을까요?

**Comment by genie-youn** [comment]
## 10.2 조건식 통합하기

함수 추출하기는 ‘무엇’을 하는지를 기술하던 코드를 ‘왜’ 하는지를 말해주는 코드로 바꿔주는 효과적인 도구임을 기억하자

## 10.4 조건부 로직을 다형성으로 바꾸기

나는 switch문을 단 한 번만 참아준다.

**Comment by siathus** [comment]
# 10.4 조건부 로직을 다형성으로 바꾸기
> 슈퍼클래스인 `Bird`는 없어도 괜찮아 보인다. 자바스크립트에서는 타입 계층 구조 없이도 다형성을 표현할 수 있다.

이 부분에서 `Bird`가 없어도 된다는 게 `Bird` 클래스를 정의하지 않고, 세 개의 서브클래스에 붙은 `extends Bird`가 없어도 `plumages()`, `speeds()`에서 매핑을 처리할 때 알아서 같은 타입으로 취급한다는 의미라고 생각되는데 혹시 제가 이해한 게 맞을까요?

**Comment by eagleda** [comment]
> 조건을 검사하고 그 결과에 따른 동작을 표현한 코드는 무슨 일이 일어나는지는 이야기해주지만 '왜' 일어나는지는 제대로 말해주지 않을 때가 많은 것이 문제다. (p.354)

> 함수 추출하기는 '무엇'을 하는지를 기술하던 코드를 '왜' 하는지를 말해주는 코드로 바꿔주는 효과적인 도구임을 기억하자.( p.358)

버그 수정, 개선 뿐만이 아니라 이해와 수정이 쉽도록 만든다는 리팩터링의 기본 정의를 계속해서 되새겨주는군요.

**Comment by hjsung809** [comment]
p361
함수의 진입점과 반환점이 하나여야 한다고 배운 프로그래머와 함께 일하다보면 이 래팩터링을 자주 사용하게 된다.
-> 이게 무슨의미일까요?

**Comment by joi0104** [comment]
361p 

> 이와 달리, 보호 구문은 “이건 이 함수의 핵심이 아니다. 이 일이 일어나면 무언가 조치를 취한 후 함수에서 빠져나온다”라고 이야기한다.

early return 이 가독성이 좋다고 느껴지는 이유가 요런 의도를 빠르게 전달 할 수 있어서 그런 것 같아요.

**Comment by usageness** [comment]
### 10.2 조건식 통합하기
개인적으로는 크게 공감되지 않는 리팩토링이었습니다.
곰곰히 생각해봐도 실제로 이 방법을 쓰는 경우가 어떤게 있을지 잘 와닿지 않네요.

### 10.3 중첩 조건문을 보호 구문으로 바꾸기
타입 가드가 생각나는 리팩토링이네요 ㅎㅎ
early return이라고 뭉뚱그려서 말하고 있었는데 이제 보호 구문이라고 확실하게 말할 수 있겠어요
