### ISSUE TITLE
[리팩터링] 23.04.09/10주차 - 챕터 11.5 매개변수를 질의 함수로 바꾸기 끝까지 ~ 435p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#109]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
# 10.6 어서션 추가하기
토스커뮤니티는 어서션을 꽤나 적극적으로 사용하는데, 이 어서션은 동작에 영향(예외를 던짐) 을 준다. 어서션이 실패하면 어차피 이후 로직이 정상적으로 동작하지 않을텐데, 예외를 던지는게 맞지 않나?

나머지는 코드리뷰할때 써먹으려고

# 11. API 리팩터링

모듈과 함수는 소프트웨어를 구성하는 빌딩 블록이며, API는 이 블록들을 끼워 맞추는 연결부다.

## 11.1 질의 함수와 변경 함수 분리학

우리는 외부에서 관찰할 수 있는 겉보기 부수효과가 전혀 없이 값을 반환해주는 함수를 추구해야 한다. 이런 함수는 어느 때건 원하는 만큼 호출해도 아무 문제가 없다. 호출하는 문자의 위치를 호출하는 함수 안 어디로든 옮겨도 되며 테스트하기도 쉽다. 한마디로, 이용할 때 신경 쓸 거리가 매우 적다.

겉보기 부수효과가 있는 함수와 없는 함수는 명확히 구분하는 것이 좋다. 이를 위한 한 가지 방법은 ‘질의 함수’는 모두 부수효과가 없어야 한다 는 규칙을 따르는 것이다, 이를 명령 - 질의 분리라 하는데, 이 규칙을 절대적으로 신봉하는 프로그래머도 있다. 나는 이 견해에 (혹은 다른 무엇이라도) 100% 동의하지는 않지만 되도록 따르려 노력하고 있으며, 그동안 효과도 톡톡히 봤다.

‘겉보기’ 부수효과라고 부른데에는, 캐시가 그 대표적인 예다. 사이드이펙트를 내긴 하지만, 객체 밖에서는 관찰할 수 없다. 즉 겉보기 부수효과 없이 어떤 순서로 호출하든 모든 호출에 항상 똑같은 값을 반환할 뿐이다.

## 11.2 함수 매개변수화하기

내가 플래그 인수를 싫어하는 이유가 있다. 호출할 수 있는 함수들이 무엇이고 어떻게 호출해야 하는지를 이해하기가 어려워지기 때문이다. 나는 API를 익힐 때 주로 함수 목록부터 살펴보는데, 플래그 인수가 있으면 함수들의 기능 차이가 잘 드러나지 않는다. 사용할 함수를 선택한 후에도 플래그 인수로 어떤 값을 넘겨야 하는지를 또 알아내야 한다. 불리언 플래그는 코드를 읽는 이에게 뜻을 온전히 전달하지 못하기 때문에 더욱 좋지 못하다. 함수에 전달한 ture의 의미가 대체 뭐란 말인가? 이보다는 다음처럼 특정한 기능 하나만 수행하는 명시적인 함수를 제공하는 편이 훨씬 깔끔하다.

**Comment by KangJiJi** [comment]
# 11. API 리팩터링

## 11.4 객체 통째로 넘기기

&nbsp; 최근에는 인자로 객체를 넘기면, 결국에는 의존성이 생기게 된다고 생각해서 모든것을 인자로 하나씩 넘기거나 전역적으로 접근할 수 있는 common type 객체를 만들어서 사용하고 있습니다. 다른분들은 이런경우 어떤 방식을 많이 사용하시나요?

# 후기

전부 의식의 흐름대로 읽을 수 있는 내용이였다고 생각합니다. 지난 리팩터링 읽을때도 같은 생각을 했었던 것 같은데, 모든 리팩터링 기법이 장단점이 존재하기 때문인듯 합니다. A라는 기법을 말하면, 반대되는 B라는 기법을 같이 알려주고 상황에 따라 적절한것을 사용하는 것이 잴 어렵게 느껴지네요.

**Comment by joi0104** [comment]
395p 특이 케이스 추가하기
> 특이 케이스로부터 다른 클라이언트와는 다른 무언가를 원하는 독특한 클라이언트가 있을 수 있다. 예컨대 미확인 고객의 이 름으로 "거주자"를 사용하는 클라이언트가 23개나 되더라도 튀는 클라이언트가 하나쯤은 있 을 수 있다. 이런 경우엔 원래의 특이 케이스 검사 코드를 유지해야 한다.
`const name = !isUnknown(aCustomer) ? aCustomer.name : "미확인 거주자";`

꽤나 중요하면서도 프론트에서는 빈번하게 일어나는 부분. 위와 같이 튀는 클라이언트 코드가 점점 많아진다면 또다른 도매인 객체 (또다른 Customer객체)가 나와야 하는 신호일까?

404p 어서션 추가하기
> 어서션을 오류 찾기에 활용하라고 추천하는 사람도 왕왕 본다. 물론 좋은 일이긴 하지만 어서 션의 쓰임은 여기서 끝나지 않는다. 어서션은 프로그램이 어떤 상태임을 가정한 채 실행되는지 를 다른 개발자에게 알려주는 훌륭한 소통 도구인 것이다. 디버깅하기도 편하고 이런 소통 수 단으로서의 가치도 있어서, 나는 추적하던 버그를 잡은 뒤에도 어서션을 코드에 남겨두곤 한 다. 한편, 테스트 코드가 있다면 어서션의 디버깅 용도로서의 효용은 줄어든다. 단위 테스트를 꾸준히 추가하여 사각을 좁히면 어서션보다 나을 때가 많다. 하지만 소통 측면에서는 어서션이 여전히 매력적이다.

어서션이 단순히 버그 추적이나 이후 로직 방지 와 같은 역할 뿐만 아니라 소통 도구의 역할도 한다는 점이 굉장히 좋았던 것 같다.

414 명령-질의 분리

회사에서 아래와 같은 코드를 정말 많이 쓰는데, 지금보니 명령과 질의 두가지의 책임을 가진 훅이 아니였나 라는 생각이 든다..

```tsx
function useUser() {
  const data = useQuery(...

  const update = useMutation(...
  
  return { data, update }
}
```

417p 함수 매개변수화 하기

```tsx
function format(date: Date, formatString: string) {
   ...
}

const settlementDateString = format(settlementDate, 'YYYY.MM.DD');
```
format(settlementDate, 'YYYY.MM.DD'); 이런 코드가 정말 많다면? 프로덕트 디자인 단에서 우리는 날짜를 YYYY.MM.DD 포맷으로 보여주자~ 라고 약속되어 있다면?
```tsx
function formatTosspaymentsDate(date:Date) {
  ....
}

const settlementDateString = formatTosspaymentsDate(settlementDate);
```

이런 함수가 오히려 더 쓰임새 있지 않을까?

422p 플래스 인수 제거하기

`bookConcert(aCustomer, true);` 는 true라는 리터럴이 어떤 역할을 하는지 알기 어렵다는 것에는 공감한다. 하지만 `bookConcert(aCustomer, CustomerType.PREMIUM);` `premiumBookConcert(aCustomer);` 이 두개는 무슨차이인지 모르겠다. 두개다 프리미엄 콘서트를 예약하는다는 의미가 잘 드러나지 않나?

**Comment by eagleda** [comment]
> 어서션을 컴파일타임에 켜고 끌 수 있는 스위치를 제공하는 프로그래밍 언어도 있다.(p.404)

최근에 쓰는 언어들은  대부분 이러한 기능을 제공하나요?

### 10.7 제어 플래그를 탈출문으로 바꾸기
이 것도 리팩터링의 한 종류 였군요. 고등학교 때부터 종종 쓰던 방법이었는데 리팩터링 기법이라고 하니 기분이 상당히 묘하네요.. 
 
`freeze()`
저자분은 클래스를 사용하는 쪽을 선호하신다지만 JS를 배워야 하는 입장에선 찾아볼 필요가 있을 것 같습니다.


명령-질의 분리

> _질의 함수(읽기 함수)는 모두 부수효과가 없어야 한다._

**Comment by hjsung809** [comment]
[10.5]
p394
특이 케이스 객체는 값객체다. 따라서 항상 불변이어야 한다. 대체하려는 값이 가변이라도 마찬가지다.
-> 같은 타입이어도 불변성 여부는 다를 수 있다는 생각을 못해봐서 신기했습니다.

[10.5 ]
p401
isUnknown 함수의 매개변수로 String(primitive) 타입과 객체 타입을 둘다 수용가능한 함수를 만들어서 사용하는데,
실제 자바스크립트(혹은 타입스크립트) 개발에서 사용하는 형태일까요? 너무 어려워 보여서 질문드립니다..

[10.6 ]
p 404
어서션이 실패했다는건 프로그래머가 잘 못했다는 뜻이다.
p406
나는 프로그래머가 일으킬만한 오류에만 어서션을 사용한다. 데이터를 외부에서 읽어 온다면 그 값을 검사하는 작업은 가정이 아니라 프로그램 로직의 일부로 다뤄야한다.

-> 어서션을 사용하지 않는 이유중 하나가 예외 핸들링의 복잡함 때문이었는데, 어서션은 발생하면 안되는(실제 프로덕션 환경의 런타임에 발생하지 않는) 케이스로 가정하고 예외처리 없이 사용해도 되겠다고 생각이 들었습니다.
프로덕션 환경에서 발생하기전에 테스트 환경에서 걸러져야하고, 프로덕션 환경에서 발생시 즉각 롤백을 해야하는 경우로가정 하고 사용하면 예외 처리에 대해 생각할 필요가 없을 것 같습니다.
어서션을 남발하지 않고 테스트 코드로 대부분 커버하고, 테스트 코드까진 애매한 부분만 어서션으로 사용하면 좋을것 같습니다.

**Comment by usageness** [comment]
### 10.6 어서션 추가하기
어서션이 소통의 도구로 사용된다는 점이 재밌네요. 발전된 형태의 주석같은 느낌이 들어요.

### 11.1 질의 함수와 변경 함수 분리하기
매우 동의하는 리팩토링입니다. 큰 고민없이 일단 해도 될만큼 유용한 기법인것 같아요~~

### 11.4 객체 통째로 넘기기
```js
const low = aRoom.daysTempRange.low;
const high = aRoom.daysTempRange.high;
if (!aPlan.xxNEWwithinRange(aRoom.daysTempRange))
  alerts.push("방 온도가 지정 범위를 벗어났습니다.");
```

이런 경우에 `aRoom.daysTempRange` 가 low와 high 만 갖고있는 객체가 아니라면
따로 패킹하는 작업이 필요할까요?
불필요한 데이터를 추가로 넘겨주는 경우가 생길 것 같네요.

**Comment by wlsh44** [comment]
> 나는 프로그래머가 일으킬만한 오류에만 어서션을 사용한다. 데이터를 외부에서 읽어 온다면 그 값을 검사하는 작업은 (어서션의 대싱인) 가정이 아니라 (예외 처리로 대응해야 하는) 프로그램 로직의 일부로 다뤄야 한다.
...
어서션은 버그 추적을 돕는 최후의 수단이다. (406p)

책을 읽으면서 계속 어서션과 예외 처리의 차이가 궁금했었는데 이 부분을 읽고 조금은 해소가 된 것 같네요..
또 전에 어서션을 추가하는 것에 대해 이건 단위 테스트의 역할이 아닌가 하는 생각을 했던 기억이 있는데, 이 부분을 읽으면서 어서션은 테스트 코드 처럼 리팩터링이 올바르게 이뤄지고 있는지를 검증하면서도 단위 테스트보다 더 로우 레벨의 디버깅을 할 수 있다는 점에서 차이가 있다는걸 알게 된 것 같습니다

> 다른 객체의 메서드를 호출하면서 호출하는 객체 자신이 가지고 있는 데이터 여러개를 건네는 경우다. 이런 상황이면 데이터 여러 개 대신 객체 자신의 참조만 건네도록 수정할 수 있다. (428p) + 피호출 함수가 스스로 '쉽게' 결정할 수 있는 값을 매개변수로 건네는 것도 일종의 중복이다. (433p)

조회하는 API를 만들 때 response dto의 생성자에 필드를 하나하나 넣다가 필요한 데이터를 많이 가진 클래스 자체를 넣는 방식으로 바꾸니까 확실히 변경이 생겨도 깨지는 부분이 거의 없어서 좋았던 경험이 있었습니다..!

**Comment by wise1ight** [comment]
395p.
> 앞의 예처럼 정말 단순한 값을 위해 클래스까지 동원하는 건 좀 과한 감이 있다.

저는 과한 감이 있는지 잘 모르겠는데 다른분은 어떻게 느끼셨나요?

**Comment by siathus** [comment]
## 11.1 질의 함수와 변경 함수 분리하기
> 흔히 쓰는 최적화 기법 중 요청된 값을 캐시해두고 다음번 호출 때 빠르게 응답하는 방법이 있는데, 이러한 캐싱도 객체의 상태를 변경하지만 객체 밖에서는 관찰할 수 없다. 즉, 겉보기 부수효과 없이 어떤 순서로 호출하든 모든 호출에 항상 똑같은 값을 반환할 뿐이다. (p. 414)

'겉보기' 부수효과가 정확히 뭔지 잘 이해가 가지 않네요. 캐싱의 예를 보면 캐싱되어 요청에 반환되는 객체가 응답값이 바뀜에 따라 변경되는 걸 의미하는 걸까요? 만약 그렇다고 한다면, 캐싱된 값을 바꾸는 코드가 존재할텐데 객체 밖에서는 관찰할 수 없다는 건 무엇을 의미하는건지 헷갈리네요.

**Comment by lallaheeee** [comment]
11.3 Remove Flag Argument..
---
- 결국 어디선가는 분기 쳐줘야하는 경우 이 레이어가 어디인가?가 참 어려운 것 같습니다ㅎㅎ
