### ISSUE TITLE
[GoF 디자인패턴] 3주차 ~ 4.7 프록시 (구조패턴 끝까지)

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#11]

**Comment by genie-youn** [comment]
https://github.com/spring-projects/spring-retry/blob/baba3fa6583df2d3030615cf92f36966c54ded29/src/main/java/org/springframework/retry/interceptor/RetryInterceptorBuilder.java#L29-L399

**Comment by hyesun03** [comment]
java의 real world example을 찾다가 이런 글을 찾았어요
https://stackoverflow.com/questions/1673841/examples-of-gof-design-patterns-in-javas-core-libraries

**Comment by hyesun03** [comment]
저번에 python에서 자주 쓰는 숫자들은 캐시해서 쓴다고 했었잖아요. Java도 그런게 있는지 찾아봤는데 `IntegerCache` 라는게 있네요. Flyweight 패턴이 적용된 real world example 입니다 ㅋㅋ

https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/lang/Integer.java#L780

**Comment by hyesun03** [comment]
또 다른 Flyweight의 사용 예로 Java의 String이 있다고 해서.. 이런걸 해봤어요. 물론 갓텔리제이를 사용했습니다.

``` java
String a = "asdf";
String b = "asdf";
String c = new String("asdf");

System.out.println(a.equals(b));    // 실제 값 비교, true
System.out.println(a == b);         // 주소 비교, true
System.out.println(a.equals(c));    // 실제 값 비교, true
System.out.println(a == c);         // 주소 비교, false
```

위와 같은 결과 때문에 그런지 `String c = new String("asdf");`에서 `new String`이 회색으로 변하더니 아래와 같은 경고문이 나오는 것을 확인했어요. 
> 'new String' is redundant less... (⌘F1) 
Inspection info: Reports a variety of redundant String-related operations like calling String.toString() or String.substring(0). Also, reports usage of redundant String constructors like new String() (equivalent to "") or new String(anotherString) (equivalent to anotherString). Such code, when fixed, may change the program semantics if String referential equality is important (which is commonly considered as a bad practice). In this case, consider suppressing the warning.

대강 요약하자면, 굳이 주소값 비교가 중요한 상황이 아니라면 문자열을 `new String`으로 선언해서 쓰는것을 권장하지 않는다는 내용입니다.

**Comment by genie-youn** [comment]
IntegerCache에 관하여 자세히 설명되어 있는 글은 다음을 참고

https://mrkarl.github.io/devstory/2019/03/05/Java-Integer-Cache/

**Comment by genie-youn** [comment]
Vuejs 에서의 Proxy 
https://github.com/genie-youn/TIL/blob/master/Vue/Vue_Reactive_Data.md#%EB%B0%98%EC%9D%91%ED%98%95%EC%9D%B4-%EC%A0%81%EC%9A%A9%EB%90%98%EB%8A%94-%EA%B3%BC%EC%A0%95

**Comment by genie-youn** [comment]
javascript 에서의 Proxy https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by KangJiJi** [comment]
JS Proxy
https://tc39.es/ecma262/#sec-proxycreate

**Comment by KangJiJi** [comment]
1.  Facade와 Object literal의 차이
>Facade encapsulates one or more objects and provides easier API for the client, hiding the obscurities and making it harder to make a mistake. In your example mobileEvent.stop() function encapsulates two JavaScript calls that have to go together in order to achieve some higher level behaviour.
>Object literal isn't really a pattern, it is just a way to define one-time object in JavaScript. As you can see it can be used to implement Facade pattern and many others.
Facade는 실수를 줄여준다?

2. Weakness of Flyweight
특정 인스턴스의 공유 컴포넌트를 다르게 행동하게 하는 것이 불가능하다.

**Comment by genie-youn** [comment]
컴파일/빌드가 한시간? https://muchtrans.com/trans…/software-disenchantment.ko.html

**Comment by hyesun03** [comment]
@KangJiJi 
1. Facade와 Object literal의 차이 스택오버플로 링크
https://stackoverflow.com/questions/8947175/javascript-patterns-difference-between-the-facade-and-object-literal-pattern

**Comment by genie-youn** [comment]
https://youtu.be/UV_JN8g36fQ

**Comment by genie-youn** [comment]
https://namu.wiki/w/%ED%8A%B8%EB%9D%BC%EC%9D%B4
