### ISSUE TITLE
[리팩터링] 23.04.23/11주차 - 챕터 11.13 예외를 사전확인으로 바꾸기 ~ 434p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#110]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by usageness** [comment]
### 11.6 질의 함수를 매개변수로 바꾸기
설계 초반일수록 "누가 책임을 가지고 있어야 할지" 가 자주 바뀌는것 같은데
그러면서 이 리팩토링을 많이 사용했던 것 기억이 나네요

> 자바스크립트의 클래스 모델에서는 객체 안의 데이터를 직접 얻어낼 방법이 항상 존재하기 때문에 불변 클래스임을 보장하는 수단이 없다는 문제가 있다. (p.441)

JS가 죄송합니다...

### 11.12 오류 코드를 예외로 바꾸기

```tsx
// app.tsx
// ...

return (
  <ErrorBoundary>
    <App />
  </ErrorBoundary>
)
```

`각 예외 별로 개별적으로 핸들링하기` vs `위처럼 에러 바운더리에서 한 번에 핸들링하기`
어떤 방법이 나을까요?

**Comment by genie-youn** [comment]
### 11.6 질의 함수를 매개변수로 바꾸기

모듈을 참조 투명하게 만들어 얻는 장점은 대체로 크다. 그래서 모듈을 개발할 때 순수 함수들을 따로 구분하고, 프로그램의 입출력과 기타 가변 원소들을 다루는 로직으로 순수 함수들의 겉을 감싸는 패턴을 많이 활용한다.

이 리팩터링에도 단점은 있다. 질의 함수를 매개변수로 바꾸면 어떤 값을 제공할지를 호출자가 알아내야 한다. 결국 호출자가 복잡해지는데, 이왕이면 고객의 삶이 단순해지도록 설계하자는 내 평소 지론과 배치된다. 이 문제는 결국 책임 소재를 프로그램의 어디에 배정하느냐의 문제로 귀결된다. 답을 찾기가 쉽지 않으며 항상 정답이 있는 것도 아니다. 프로젝트를 진행하면서 균형점이 이리저리 옮겨질 수 있으니 이 리팩터링과는 아주 친해져야 한다.

UI 컴포넌트를 구성할때도 이 철학을 따르려고 애쓰는것 같다. 도메인을 모르는 순수한 컴포넌트와 이를 감싸는 도메인을 담은 컴포넌트.

### 11.9 함수를 명령으로 바꾸기

명령은 평범한 함수 매커니즘보다 훨씬 유연하게 함수를 제어하고 표현할 수 있다. 명령은 되돌리기 같은 보조 연산을 제공할 수 있으며, 수명주기를 더 정밀하게 제어하는데 필요한 매개변수를 만들어주는 메서드도 제공할 수 있다. 상속과 훅을 이용해 사용자 맞춤형으로 만들 수도 있다. 객체는 지원하지만 일급 함수를 지원하지 않는 프로그래밍 언어를 사용할 때는 명령을 이용해 일급 함수의 기능 대부분을 흉내 낼 수 있다. 비슷하게, 중첩 함수를 지원하지 않는 언어에서도 메서드와 필드를 이용해 복잡한 함수를 잘게 쪼갤 수 있고, 이렇게 쪼갠 메서드들을 테스트와 디버깅에 직접 이용할 수 있따.

이처럼 명령을 사용해 얻는 이점이 많으므로 함수를 명령으로 리팩터링할 채비를 갖춰야 할 것이다. 하지만 유연성은 언제나 그렇든 복잡성을 키우고 얻는 대가임을 잊지 말아야 한다. 그래서 일급 함수와 명령 중 선택해야 한다면, 나라면 95%는 일급 함수의 손을 들어준다. 내가 명령을 선택할 때는 명령보다 더 간단한 방식으로는 얻을 수 없는 기능일 필요할 때 뿐이다.

**Comment by joi0104** [comment]
> 이 리팩터링에도 단점은 있다. 질의 함수를 매개변수로 바꾸면 어떤 값을 제공할지를 호출자가 알아내야 한다. 결국 호출자가 복잡해지는데, 이왕이면 고객(호출자)의 삶이 단순해지도록 설계하자는 내 평소 지론과 배치된다. 이 문제는 결국 책임 소재를 프로그램의 어디에 배정하느냐의 문제로 귀결된다. 답을 찾기가 쉽지 않으며 항상 정답이 있는 것도 아니다. 프로젝트를 진행하면서 균형점이 이리저리 옮겨질 수 있으니 이 리팩터링(과 그 반대 리팩터링)과는 아주 친해져야 한다.

호출자가 복잡해지고 중복이 늘어나는 경우, 의존성을 호출하는 부분 + 순수함수 호출하는 부분을 래핑한 함수를 또 하나 만들면 복잡도를 낮추고 중복을 해소할 수 있지 않을까 싶네요. (학습비용이 조금 들어가는건 단점일것 같지만..)

> 이제 명령을 중첩 함수처럼 다룰 수 있다. 사실 자바스크립트에서라면 중첩 함수는 명령 의 합리적인 대안이 될 수 있다. 그래도 나는 여전히 명령을 사용한다. 내가 명령에 더 익 숙하기도 하거니와, 명령을 사용하면 (execute 외의) 서브함수들을 테스트와 디버깅에 활용할 수 있기 때문이다.

계속 읽으면서 중첩함수랑 뭐가 다르지? 라고 생각했는데 저자가 잘 정리해준 것 같아서 가져와봤습니당. 저는 개인적으로 중첩함수보다 명령 객체가 좀 더 익숙한 방식인 것 같은데 다른분들 생각이 궁금하네요~

**Comment by wise1ight** [comment]
## 11.9 함수를 명령으로 바꾸기
hook과 first-class function에 대해 ChatGPT한테 물어보았습니다.

> - Hook: React의 기능으로, 함수 컴포넌트 안에서 state와 다른 React 기능을 사용할 수 있게 해줍니다. Hook은 React 16.8 버전부터 도입되었으며, useState, useEffect, useContext 등이 대표적인 Hook입니다.
> 
> - First-class function: 함수를 변수처럼 다룰 수 있는 프로그래밍 언어의 특징입니다. 즉, 함수를 변수에 할당할 수 있고, 함수를 매개변수로 전달할 수 있으며, 함수를 반환값으로 사용할 수 있습니다. JavaScript는 first-class function을 지원하는 언어입니다. 
> 
> 두 개념은 모두 함수를 중심으로 동작한다는 공통점이 있습니다. 하지만 Hook은 React에서만 사용되는 기능이고, first-class function은 다양한 언어에서 지원되는 개념입니다.

Hook에 대해서 좀 더 보편적인 내용을 물어봤습니다.

> 보편적으로 Hook은 프로그래밍에서 이벤트(event)에 반응하여 실행되는 코드 블럭이나 함수를 말합니다. 이벤트는 사용자의 액션(클릭, 키보드 입력 등) 또는 애플리케이션의 상태 변화 등으로 발생할 수 있습니다.
> 
> Hook은 이벤트에 반응하여 실행되는 코드 블럭을 구현할 수 있는데, 이를 사용하면 코드의 가독성과 재사용성이 좋아지고, 프로그램의 로직을 더욱 쉽게 이해할 수 있습니다.
> 
> 보편적으로 사용되는 Hook으로는 React에서 사용되는 Hook인 useState, useEffect 외에도, JavaScript에서 사용되는 Hook으로는 Array.prototype.map(), Array.prototype.filter() 등이 있습니다. 함수형 프로그래밍에서도 Hook의 개념이 프로그래밍의 기본 개념 중 하나로 자리잡고 있으며, 이를 통해 코드의 가독성과 재사용성을 높일 수 있습니다.

**Comment by wlsh44** [comment]
> 명령은 평범한 함수 메커니즘보다 훨씬 유연하게 함수를 제어하고 표현할 수 있다. (449p)

명령이라는 이름이 잘 와닿지 않았습니다. 명령도 결국에는 하나의 책임을 가진 객체고, 여기서 말하는 장점도 클래스 분리를 통해 얻는 장점과 같은게 아닌가 하는 생각도 들었습니다..
그래서 예시에서 만든 Score 명령 객체도 결국에는 score를 계산하는 책임이 있어 보였고, 그래서 execute가 아니라 calculateScore같이 좀 더 의미를 부여하고 그렇게 얻은 score를 호출하는 쪽에 넘겨주는게 더 낫지 않나 생각을 했는데 혹시 이 방식과 명령 객체를 만드는 방식에 어떤 차이가 있는지 궁금합니다!

> 이번 리팩터링으로 추가된 예외만을 처리하고자 한다면 다른 예외와 구별할 방법이 필요하다. (468p)

아..

**Comment by eagleda** [comment]
> 순수 함수: 부수 효과가 없는 함수.
> 참조 투명성: 프로그램 동작의 변경없이 관련 값을 대체할 수 있다면 표현식을 참조 상 투명하다고 할 수 있다...

자주 등장하는 질의 함수 역시 순수 함수라 볼 수 있겠군요?

### 11.9 함수를 명령으로 바꾸기
그간 함수를  객체를 통해 캡슐화하여 사용한다는 생각을 해본 적이 없어 흥미롭게 보았던 리팩터링 기법이었습니다.
책에서 일급함수와 같은 더 간단한 방식이 있다고 서술하고 있지만 명령을 통해 얻을 수 있는 이점이 있으니 기억해 두는 것이 좋을 것 같습니다.

**Comment by siathus** [comment]
## 11.9 함수를 명령으로 바꾸기
> 객체는 지원하지만 일급 함수를 지원하지 않는 프로그래밍 언어를 사용할 때는 명령을 이용해 일급 함수의 기능 대부분을 흉내낼 수 있다. (중략) 일급 함수와 명령 중 선택해야 한다면, 나라면 95%는 일급 함수의 손을 들어준다. (p. 449)

일급 함수가 뭔지 검색해보니 함수를 변수처럼 사용(인자 및 반환값으로 취급, 변수에 할당 가능)할 수 있는 기능인 것 같네요. 자바에서는 일급 함수와 고민할 필요 없이 명령만 쓰면 되니 오히려 좋아

## 11.11 수정된 값 반환하기
> 데이터가 수정된다면 그 사실을 명확히 알려주어서, 어느 함수가 무슨 일을 하는지 쉽게 알 수 있게 하는 일이 대단히 중요하다.

절차가 좀 많거나 복잡한 리팩토링보다는 언뜻 보면 사소해 보이는 이런 리팩토링이 오히려 좀 더 깊게 와닿는 것 같네요.

**Comment by hjsung809** [comment]
p 445
생성자가 자신의 타입만을 반환해야 하는게 이상한 제약조건이라고 볼수 있다니 참신했습니다.

**Comment by KangJiJi** [comment]
## 11.12  오류 코드를 예외로 바꾸기

아래 코드는 p470. 에 나오는 리팩터링이 끝났을 때 코드입니다.

```javascript
try {
 status = calculateShippingCosts(orderData);
} catch (e) {
 if (e instanceof OrderProcessingError)
  errorList.push({order: orderData, errorCode: e.code});
 else
  throw e;
}
```

그런데 마지막에 자신이 처리할 수 없어서 상위로 던지는 오류도 결국에 누군가가 catch 하지 않으면 프로그램이 뻗을텐데, 이런 경우는 어떻게 검증하고, 처리하시나요?

개인적인 생각으로는 자신이 처리할 수 없는 예외가 발생하는 것 자체가 잘못된 상황이 아닌가 싶습니다.
