### ISSUE TITLE
[리팩터링] 23.04.30/12주차 - 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#111]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by wise1ight** [comment]
## 12.8 슈퍼클래스 추출하기
> 상속은 프로그램이 성장하면서 깨우쳐가게 되며, 슈퍼클래스로 끌어올리고 싶은 공통 요소를 찾았을 때 수행하는 사례가 잦았다.

**Comment by wlsh44** [comment]
> 객체 지향을 설명할 때 상속 구조는 '현실 세계에서 활용하는 어떤 분류 체계에 기초하여 구현에 들어가기 앞서 부모, 자식 관계를 신중하게 설계해야 한다'라고 이야기 하는 사람이 많다. 현실 세계의 이런 분류 체계는 상속을 적용하는 데 힌트가 될 수 있다. 하지만 내 경험에 비춰보자면 상속은 프로그램이 성장하면서 깨우쳐가게 되며, 슈퍼클래스로 끌어올리고 싶은 공통 요소를 찾았을 때 수행하는 사례가 잦았다. (502p)

객사오 첫 장에 나왔던 이야기와 비슷한 맥락인 것 같네요!

> 이 리팩터링은 그 자체만으로는 코드를 개선한다고 느껴지지 않는다. 상속은 이 상황을 잘 다루고 있는 데 반해, 위임을 적용하면 분배 로직과 양방향 참조가 더해지는 등 복잡도가 높아지기 때문이다. (518p)

개인적으로는 이 리팩터링의 장점이 크게 느껴지지 않았던 것 같아요.. 예시도 오히려 인터페이스를 이용한 다형성을 적용시키는게 더 낫지 않을까 하는 느낌도 많이 들었습니다.
혹시 위임 클래스를 만드는 방식을 실제로 많이 사용하나요?

**Comment by usageness** [comment]
### 12.3 생성자 본문 올리기
예문만 보고 팩터리 메서드가 생각났었는데, 곧바로 고려해보라는 나오네요.
> 이번 리팩터링이 간단히 끝날 것 같지 않다면 생성자를 팩터리 함수로 바꾸기를 고려해본다.

### 12.10 서브클래스를 위임으로 바꾸기
상속보다 컴포지션이 더 익숙해서 그런지,
해본 기억이 없는 리팩토링이네요 ㅎㅎ

**Comment by eagleda** [comment]
### 12.1 메서드 올리기

> 무언가 중복되었다는 것은 한 쪽의 변경이 다른 쪽에는 반영되지 않을 수 있다는 위험을 항상 수반한다.

> 동적 언어: 자료형을 실행시 결정/정적 언어: 자료형을 컴파일시 결정

객프 과목 시간에 배웠던 것 같은데 기억이 잘나지 않아 내용 이해가 힘들었습니다. 용어를 다시 알아보고 코드 내용을 보니 그제야 이해가 가더군요..

### 12.10,11 슈퍼/서브클래스를 위임으로 바꾸기
자바를 배울 때 클래스와 상속을 중점적으로 배워서 가장 주요하게 사용하는 걸로 알고 있었는데,
디자인 패턴 인용문의 예도 그렇고 상속의 사용에 주의를 표하는 입장이 꽤 나오는군요.
실제 개발에서도 클래스 상속에 잘 쓰이지 않는 편인가요?

**Comment by siathus** [comment]
## 12.5 필드 내리기
```java
// 변경 전
class Employee {
  private String quota;
}

// 변경 후
class Salesperson extends Employee {
  protected String quota;
}
```
이 부분은 단순 오타겠죠? `private`와 `protected` 위치가 바뀐 것 같네요.

## 12.9 계층 합치기
언뜻 봤을 땐 12.7 서브클래스 제거하기와 뭐가 다른가 싶었습니다. 서브클래스 제거는 서브클래스가 쓰이지 않거나 기능이 매우 제한적이라 슈퍼클래스의 필드로 대체할 수 있을 때 사용하는 기법이고, 계층 합치기는 계층구조가 진화함에 따라 슈퍼클래스와 서브클래스가 유사해지면서 계층구조로 나눌 이유가 없어졌을 때 사용하는 기법인 것 같네요.

## 12.10 서브클래스를 위임으로 바꾸기, 12.11 슈퍼클래스를 위임으로 바꾸기
> 하지만 나는 상속을 자주 사용하는데, 이렇게 하는 배경에는 나중에라도 필요하면 언제든 서브클래스를 위임으로 바꿀 수 있음을 알고 있다는 점이 한 몫 한다. (p. 509)

> 이상의 이유로 "상속은 절대 사용하지 말라"고 조언하는 사람도 있다. 나는 동의하지 않는다. (중략) 이런 상황이 변하여 상속이 더는 최선의 방법이 아니게 되면 언제든 이번 리랙터링을 이용해 슈퍼클래스를 위임으로 바꿀 수 있다. 그래서 (왠만하면) 상속을 먼저 적용하고 (만일) 나중에 문제가 생기면 슈퍼클래스를 위임으로 바꾸라는 것이 나의 조언이다. (p. 530)

일단 적용해보고 언제든지 다른 기법으로 변경할 수 있는 이런 부분이 점진적 리팩토링의 큰 장점 중 하나가 아닐까 싶습니다.
그 와중에 2판인데도 '리랙터링'이나 '왠만하면'같은 오타가 두 문장 연속해서 나오는 건 좀...

**Comment by joi0104** [comment]
> 488p 대상 클래스를 직접 서브클래싱하는 게 간단하지만 업무유형을 다른 용도로도 쓰고 싶을 때 그럴 수 없다는 단점이 있다. 또한 유형이 불변일 때도 직접 서브클래싱 방식은 이용할 수 없다.

앞 문장은 이해를 했는데 뒷 문장은 이해를 못했습니다. 유형이 불변일때 왜 서브 클래싱 방식을 사용할 수 없나요?
