### ISSUE TITLE
[TDD] 23.05.28/1주차 - 챕터 5. 솔직히 말하자면 끝까지 ~ 73p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#112]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
# 역자의 글

흔히들 TDD를 하면 승부는 컴퓨터 화면 속에서만 벌어진다고 생각하기 쉽습니다. 하지만 컴퓨터 화면 속 이상으로 중요한 곳이 있습니다. 바로 우리의 머릿속입니다. 올바른 길이 있고 자신은 그 길을 따라가지 못한다고 느끼면 자책과 자기비하가 일어납니다. 나는 멍청하다. 내가 하는 것은 잘못되었다. 그러나 이런 생각을 하는 순간부터 화면 위에서의 승부는 더 곤두박질칩니다. TDD를 하면서 이런 경험을 하는 사람을 자주 보았습니다. 하지만, 나의 내면에서 벌어지는 일에 관심을 갖고 심리적 안정 상태를 유지하면 엄청난 차이를 경험하게 됩니다.

빨리 테스트를 통과시키려고, 혹은 프로그램을 빨리 작성하려고 너무 조바심 내지 마세요. 자신감을 가지세요, TDD를 쫓아가려고 하지 마시고 TDD가 자신을 따라오게 하세요.

이렇게 해서 심리적인 안정 속에서 프로그래밍을 할 수 있게 되면 놀라운 일들을 경험하게 됩니다. 전에는 보지 못하던 것들을 보게 되며, 내가 생각하지 못했던 것들을 생각해 내게 됩니다. 하지만 그런 것들이 하늘에서 떨어진 것은 아닙니다. 내 속에 이미 있던 능력입니다. 나는 못한다라고 생각하지 말고 나는 잘한다는 생각을 가지세요. 여러분에게는 아무런 문제가 없습니다. (4p)

# 저자의 글

- 두려움은 여러분을 망설이게 만든다.
- 두려움은 여러분이 커뮤니케이션을 덜 하게 만든다.
- 두려움은 여러분이 피드백 받는 것을 피하도록 만든다.
- 두려움은 여러분을 까다롭게 만든다.

이는 프로그래밍에 도움이 되질 않는다. 아래 행동을 취해야 한다.

- 불확실한 상태로 있는 대신, 가능하면 재빨리 구체적인 학습을 하기 시작한다.
- 침묵을 지키는 대신, 좀더 분명하게 커뮤니케이션 한다.
- 피드백을 회피하는 대신, 도움이 되고 구체적인 피드백을 찾는다.
- (자신의 나쁜 성깔을 직접 해결해야 한다.)

프로그래밍을 우물에서 한 두레박의 물을 길어 올리기 위해 크랭크를 돌리는 것으로 상상해보라. 작은 두레박일 때에는 자유롭게 돌아가는 크랭크로도 괜찮다. 큰 두레박에 물이 가득 담겨 있을 때에는 두레박이 다 올라오기도 전에 지쳐버릴 것이다. 몇 차례 크랭크를 돌리고 나면 쉴 수 있게 해주는 어떤 톱니바퀴 메커니즘이 필요하다. 두레박이 크면 클수록 톱니바퀴의 이빨이 더 촘촘해야 한다.

테스트 주도 개발의 테스트가 그 톱니바퀴의 이빨과 같다. 일단 테스트 하나를 작동하게 되면, 그게 지금 현재 그리고 앞으로 영원히 작동할 거라는 걸 알 수 있다. 테스트가 망가져 있을 때에 비해, 이제 모든 것이 작동하는 쪽으로 한걸음 더 가까이 있다. 이제 다음 테스트를 작동하게 되고, 그 다음, 또 다음.. 비유하자면 프로그래밍 문제가 어려울수록 각각의 테스트는 좀 더 작은 부분을 커버해야 한다. (25p)

**Comment by wise1ight** [comment]
14p.
> 정말로 테스트를 어떻게 작성할지 알 수 없는 문제는 아직 접하지 못했습니다.

22p.
* 오직 자동화된 테스트가 실패할 경우에만 새로운 코드를 작성한다.
* 중복을 제거한다.

23p.
1. 빨강  
실패하기
2. 초록
통과하게끔 만들기
3. 리팩토링
이전 책에서 사용했던 기법들을 적용하자

> 결함 밀도를 충분히 감소시킬 수 있다면, 품질보증(QA)을 수동적인 작업에서 능동적인 작업으로 전환할 수 있다.

라고 되어있는데 수동에서 능동으로 되는 이유가 무엇일지 이해가 잘 안됩니다.

**Comment by KangJiJi** [comment]
전체적으로 크게 무리없이 읽을 수 있는 내용이였습니다. 화폐 계산을 위한 프로그램의 초기 구조를 잡아가는 내용이였고, 저도 읽으면서 이렇게 진행했을 것 같다고 공감하는 부분이 많았습니다.

다만, 연습을 위해서라도 단계단계를 너무 작게 쪼개둬서 읽는데 이질감이 조금 느껴졌었습니다 ㅋㅋ

결론적으로 어떤것을 테스트할지 생각하고, 그것을 기반으로 인터페이스를 설계하고 전체적인 구조를 잡아가면서 개발을 하는것이 TDD의 기본적인 철학이라고 생각되네요.

~쉽지 않습니다 ㅠㅠ~

**Comment by wlsh44** [comment]
> 저자: 레인스버거는 모의 객체를 쓴다는 사실이 나쁜 냄새의 징후일 수도 있다고 말합니다.
> ...
> 켄트 백: 저는 모의 객체를 많이 사용하지는 않습니다. 왜 그런지는 아직 모르겠습니다 (16p)

테스트 관련해서 찾아보면 은근히 모의 객체를 사용하지 않는다는 분들이 많은 것 같은데 왜 모의 객체가 코드 스멜이 될 수 있는지 궁금합니다!
객체들이 협력을 하는 과정에서 단위 테스트를 하려면 모의 객체가 필요하지 않나요..?

> 고약한 예외 상황의 숫자를 충분히 낮출 수 있다면, 프로젝트 매니저가 정확히 추정할 수 있어 고객을 매일의 개발 과정에 참여시킬 수 있다. (23p)

개발 입장에서의 장점만을 생각했는데 이런 장점도 있었네요

> 이제 동일성 문제는 해결됐다. (63p)

값 객체를 비교하는 예제라면 동등성이 맞지 않나요?

**TDD 흐름**
1. 테스트 추가
2. 컴파일 되게 하기
3. 실패 확인을 위한 테스트 실행
4. 실행하게 만듦
5. 리팩터링으로 중복 제거

> 처음 네 단계는 빨리 진행해야 한다. (71p)

전에 TDD를 직접 보여주는 강의를 본 적이 있는데 정말 4단계까지 가는데 속도가 엄청 빠르더라구요..
호흡이 긴 만큼 Idea를 잘 쓰는 능력도 TDD를 원활하게 하는데 중요한 것 같다 라는 생각을 했습니다

**Comment by eagleda** [comment]
>두려움은 여러분을 망설이게 만든다.
두려움은 여러분이 커뮤니케이션을 덜 하게 만든다.
두려움은 여러분이 피드백 받는 것을 피하도록 만든다.
두려움은 여러분을 까다롭게 만든다.(p.24)

> 일단 '작동하는 깔끔한 코드'를 얻어야 한다는 전체 문제 중에서 '작동하는' 부분을 먼저 해결하라. 그러고 나서 깔끔한 코드 부분을 해결하는 것이다. (p.54)

Money 예제
테스트를 진행함에 따라 기존의 목표를 해결하고 또 이로 인해 발생한 문제점과 이후 목표를 위해 테스트를 추가 하고 다시 이행하면서 코드가 점점 작성되는 것을 보고 이런 작은 단위의 테스트를 통해 코드를 진행시키는 것이 TDD의 기본 개념인가 생각하였습니다.

테스트에 대한 개념이 아직 부족하다 보니 어떻게 작성하고 적용하는 지도 알지 못했는데
책에 나온 JUnit과 같은 테스트 프레임워크를 통해 할 수 있군요. 
지금 연습 중인 js에 쓸 수 있는 프레임워크가 뭐가 있는지 찾아보고 직접 사용해보면서 배워가야겠습니다.

**Comment by siathus** [comment]
여태껏 읽은 기술서 중에서 가장 이질적이고 적응하기 힘든 책 아니었나 싶습니다. TDD는 이런 거라고 말은 익히 들어왔지만 일부러 틀리는 테스트를 작성하고 그걸 아주 작은 단계로 쪼개서 고쳐나가는 방식에 적응하는 건 쉽지 않을 것 같다는 생각이 먼저 드네요.

## 5장. 솔직히 말하자면
> 1. 테스트 작성
> 2. 컴파일되게 하기
> 3. 실패하는지 확인하기 위해 실행
> 4. 실행하게 만듦
> 5. 중복 제거

> 각 단계에는 서로 다른 목적이 있다. 다른 스타일의 해법, 다른 미적 시각을 필요로 한다. **처음 네 단계는 빨리 진행해야 한다.** 그러면 새 기능이 포함되더라도 잘 알고 있는 상태에 이를 수 있다. 거기에 도달하기 위해서라면 어떤 죄든 저지를 수 있다. 그동안 만큼은 속도가 설계보다 더 높은 패이기 때문이다. (중략) **주기의 다섯 번째 없이는 앞의 네 단계도 제대로 되지 않는다.** 적절한 시기에 적절한 설계를. 돌아가게 만들고, 올바르게 만들어라. (p. 71)

결국 핵심은 "일단 돌아가게 만든 뒤, 올바르게 고친다."라고 본다면 TDD의 이 이질적인 방식의 윤곽이 어느 정도 보이는 것 같네요.

**Comment by 29pyg** [comment]
아직 앞부분이라서 그런건지 읽는데 크게 어려운 부분이나 이해가 가지 않는 부분은 없었습니다.

그리고 오히려 잘 모르는 초심자? 라고 표현해야할지 아주 세세하게 나누어 알려주는게 친절하지만 오히려 세세하게 설명해주다보니 같은 설명을 반복하는 것처럼 느껴졌습니다.

또 어느정도 배우신 분들은 이미 안될것이 예상되는 부분이나 불필요한 부분을 그저 참고 작성해서 일부러 다시 고치는 작업을 하게 될 것이 상상되었는데 맞게 읽은건지 잘 모르겠습니다.

**Comment by Astin01** [comment]
일단 테스트를 빠르게 만든 후에 고친다는 것이 핵심이라는 점은 이해 할 수 있었습니다.

다만 테스트를 만드는 법을 잘 모르는 상태에서  중간부터 읽다보니 예제 이해가 좀 힘들었습니다.

**Comment by pianoop** [comment]
>2. 실행 가능하게 만든다. 다른 무엇보다 중요한 것은 빨리 초록 막대를 보는 것이다. 깔끔하고 단순한 해법이 명백히 보인다면 그것을 입력하라. 만약 깔끔하고 단순한 해법이 있지만 구현하는 데 몇 분 정도 걸릴 것 같으면 일단 적어 놓은 뒤에 원래 문제(초록색 막대를 보는 것)로 돌아오자. (p.53)  
처음에는 무작정 초록 막대를 보기 위해 아무 상수나 넣고 말도 안 되는 코드를 짜는 것을 보고 뭔가 싶었지만 위의 글을 곰곰히 생각해보니 코드를 짜다가 가끔 뇌정지가 와서 무엇을 해야할지 모르겠을 때에 사용하면 멍 때리면서 시간낭비하는 것을 줄일 수 있다는 생각이 들었습니다.
