### ISSUE TITLE
[TDD] 23.06.04/2주차 - 10장 흥미로운 시간 끝까지 ~ 107p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#113]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by wlsh44** [comment]
> 내가 여러분에게 정말 이런 식으로 일해야 한다고 주장하는 건가? 아니다.
나는 여러분이 이런 식으로 일할 수도 있어야 한다고 말하는 것이다. (97p)

이 부분 따라 하면서 과하다 생각이 들었는데 '해야 한다'가 아니라 '할 수 있어야 한다' 라고 말하는 부분이 인상깊었네요.

****

여담으로 테스트 코드 작성하는 부분 보면서 든 생각인데 다른 분들은 테스트 코드 이름을 어떤 식으로 작성하시나요?

**Comment by genie-youn** [comment]
### 5. 솔직히 말한다면
> 각 단계에는 서로 다른 목적이 있다. 다른 스타일의 해법, 다른 미적 시각을 필요로 한다. 처음 네 단계는 빨리 진행해야 한다. 그러면 새 기능이 포함되더라도 잘 알고 있는 상태에 이를 수 있다. 거기에 도달하기 위해서라면 어떤 죄는 저지를 수 있다. 그동안 만큼은 속도가 설계보다 더 높은 패이기 때문이다. (71p)

그냥 인상깊어서 1

### 7. 사과와 오렌지
> 더 많은 동기가 있기 전에는 더 많은 설계를 도입하지 않기로 했다. (85p)

그냥 인상 깊어서 2

### 9. 우리가 사는 시간
> 방금 나는 더 큰 단계로 일하다가 중간쯤 멍청한 실수를 했다. 일분간의 수정치를 되돌렸고, 더 낮은 기어로 변속했으며, 더 작은 단계로 다시 해보았다. (중략) 지금과 같은 일은 TDD를 하는 동안 계속 해주어야 하는 일종의 조율이다. 종종걸음으로 진행하는 것이 답답한가? 그러면 보폭을 조금 넓혀라. 성큼성큼 걷는 것이 불안한가? 그럼 보폭을 줄여라. TDD 란 조종해 나가는 과정이다. 이쪽으로 조금, 저쪽으로 조금, 지금도 그리고 앞으로도 정해진 올바른 보폭이라는 것은 존재하지 않는다. (98p)

그냥 인상깊어서 3

### 10. 흥미로운 시간
> 시스템에 대해 아는 지식을 기반으로 조심스럽게 생각해 보아야 할 문제다. 하지만 우리에겐 깔끔한 코드와, 그 코드가 잘 동작할 거라는 믿음을 줄 수 있는 테스트 코드들이 있다. 몇 분 동안 고민하는 대신 그냥 수정하고 테스트를 돌려서 컴퓨터에게 직접 물어보자. 컴퓨터라면 10초에서 15초 사이에 대답할 수 있는 문제를 놓고 최고의 소프트웨어 엔지니어들이 5분에서 10분 동안 고민하곤 한다. 가끔은 그냥 컴퓨터에게 물어보는 것도 좋다.(103p)

항상 손이 먼저나가는걸 경계하고 머리로 생각하고 코드를 옮기려고 노력했는데, **가끔은 그냥 컴퓨터에게 물어보는 것도 좋다.** 에서 한 대 맞은 느낌. 역시 중도가 가장 어렵다.

--
항상 추상을 만들고 다형성으로 문제를 해결하려 했지 이후에 '이게 정말 필요한 구체클래스인지?' 를 고민해본적은 없었던것 같다. 조금씩 중복을 없애고 멍청한 구체클래스를 제거할수도 있군

**Comment by pawful-code** [comment]
8.객체 만들기
이제 전보다 조금 나은 상황이다. 어떤 클라이언트 코드도 Dollar라는 이름의 하위 클래스가 있다는 사실을 알지 못한다. 하위 클래스의 존재를 테스트에서 분리함으로써 어떤 모델 코드에도 영향을 주지 않고 상속 구조를 마음대로 변경할 수 있게 됐다.
90p
--
 테스트 코드를 작성하다 보면 종종 현재의 코드를 적당히 테스트 되게 끔 작성하곤 하는데.  이렇게 작성된 테스트 코드는 개발 과정에서 코드의 구조가 바뀌면 기존에 테스트 코드를 못 쓰게 되거나 하나하나 수정해줘야 하는 경우가 있다. 또한 이러한 문제가 발생했을 때 대상 코드의 문제인지 테스트 코드의 문제인지 고민하며 디버깅에 시간을 많이 소모한 경험이 있다. 이러한 문제를 피해가는 모습이 인상적이었다.

**Comment by Astin01** [comment]
이번 챕터는 앞에서 테스트를 짜면서 생긴 중복들을 제거해나가는 부분이었다고 생각이 들었습니다.
책에서는 하위 클래스들의 로직을 같게 만들어서 이를 상위클래스로 옮기고 하위 클래스 부분을 제거하는 방식으로 중복을 제거는데 위 방식 말고 다른 방식으로 중복을 제거하는 방법이 있는지 궁금합니다.
>빨간 막대인 상황에서는 테스트를 추가로 작성하고 싶지 않다. (중략) 그후에는 원래 하던 일을 다시 할 수 있다.(p105)
tdd에서 문제가 생겼을 때 어떻게 하면 좋을 지 알 수 있어서 좋았습니다
>단, 하던 일을 중단하고 다른 일을 하는 상태에서 그 일을 중단하지는 않는다.(p90)
이 방식이 효율적이라는 걸 느낄 수 있었고 이런 식으로 저도 코드를 짜는게 좋을 것 같다는 생각이 들었습니다. 
그리고 현업에서는 이러한 tdd 원칙을 그대로 활용하는지, 아니면 다르게 적용하는지 궁금합니다.

**Comment by wise1ight** [comment]
79p.
> 있으면 좋을 것 같은 테스트를 작성하라.

… 그게 뭔가요?

잠재적으로 있을법한 문제들을 찾아내는 역량을 갖추기 위해 뭘 해야할까요?

98p.
> TDD란 조종해 나가는 과정이다. 이쪽으로 조금, 저쪽으로 조금. 지금도, 그리고 앞으로도 정해진 올바른 보폭이라는 것은 존재하지 않는다.

인상깊어서 넣었습니다.

103p.
> 컴퓨터라면 10초에서 15초 사이에 대답할 수 있는 문제를 놓고 최고의 소프트웨어 엔지니어들이 5분에서 10분 동안 고민하곤 한다. 가끔은 그냥 컴퓨터에게 물어보는 것도 좋다.

테스트 코드를 작성하는 이유

**Comment by usageness** [comment]
### 6. 모두를 위한 평등
모두(모든 하위 클래스)를 위한 평등(`.equal()`)

`p. 79`
> 리팩토링을 더 적게하면, 설계의 질이 저하되고, 결국 여러분은 해고될 것이다. 여러분의 강아지도 여러분 곁을 떠날 것이고, 여러분은 자신의 영양 상태에 신경을 쓰지 못하게 될 것이다. 그러면 이도 나빠진다. 자, 이를 건강하게 유지하기 위해 리팩토링하기 전에 테스팅을 하자.

충격적인 개발자의 유머 감각... 코드만 볼땐 괜찮았는데 이런걸 볼때마다 마음 한 켠에서 안타까움이 밀려듭니다.

_아래에 스터디에 새롭게 참여하시는 자바스크립트 유저 분들 중 테스트를 어떻게 작성해야 하는지 잘 모르시는 분들도 있을것 같아서 책 따라치던 코드 가져와봤습니다. 저도 잘 짜는건 아니라서 참고만 해주세요 😥_

<details>
<summary> <strong> 예시 JS 코드 </strong> </summary>

> 목표 : Dollar와 Franc을 상위 클래스 Money로부터 상속하는 형태로 변경하기

### 초기 상황
```js
class Dollar {
  #amount;

  equals(object) {
    const dollar = new Dollar(object);
    return amount == dollar.amount;
  }
}

class Franc {
  #amount;

  equals(object) {
    const franc= new Franc(object);
    return amount == franc.amount;
  }
}
```

필요한 테스트 작성하기.

```js
describe('Equality Test', () => {
  it('같은 값이면 true, 다른 값이면 false를 반환해야 한다.', () => {
    expect(new Dollar(5).equals(new Dollar(5))).toBe(true);
    expect(new Dollar(5).equals(new Dollar(6))).toBe(false);
    expect(new Franc(5).equals(new Franc(5))).toBe(true);
    expect(new Franc(5).equals(new Franc(6))).toBe(false);
  });
});
```

리팩토링 결과물.

```js
class Money {
  amount; // protected가 없어서 public으로 전환. private이면 하위 클래스 접근 불가능

  equals(object) {
    const money = new Money(object);
    return amount == money.amount;
  }
}

class Dollar extends Money {
}

class Franc extends Money {
}
```
</details>

### 9. 우리가 사는 시간
`p. 97`
> 나는 보통 짧은 중단이 필요할 경우에 이를 흔쾌히 받아들이는 편이다. 단, 하던 일을 중단하고 다른 일을 하는 상태에서 그 일을 또 중단하지는 않는다.

원활한 진행에 문제가 되는 부분이 있으면 잠깐 멈추고 그것부터 해결하자.
다만 작업의 depth는 2를 넘지 않도록 하기.

### 10. 흥미로운 시간
`p. 107`
> 단지 디버깅을 위해 테스트 없이 toString()을 작성했다.

챕터 마지막에 와서 잘못한 일을 고해성사하는 뉘앙스로 적어두었는데,
저자의 의도는 테스트를 위한 테스트를 작성하지 말자. 이런 뜻인것 같네요.

딱히 질문이 있지는 않고 "그랬구나.." 하고 읽게 되는 내용들이었습니다.

**Comment by 29pyg** [comment]
오늘 중복을 고치는 내용이구나 하면서 멍하니 책만 2회독 했습니다.

진짜 코딩을 1도 모르면 배우는게 적은 느낌을 얻은게 위에 여러분들이 올려주신 내용을 참고하면서 다시 읽으니까 2회독때는 지나갔던게 흥미로운 부분으로 보이고 의문을 가질 수 있는 문장으로 되는게 좋았습니다.

저희 스터디에 멍청한 질문이 없는 이유 
'혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.'

정말 격하게 느꼈습니다.

**Comment by Lee-Hyeong-Jin** [comment]
10장의 times중복 제거 예제 부분에서 times의 반환값은 자식 클래스가 아니라 부모 클래스인 추상 클래스를 반환 형식으로 사용하고 있는데 이것으로 인해 벌어지는 문제가 존재할수 있나요?

**Comment by siathus** [comment]
## 9장. 우리가 사는 시간
> 자, 그렇다면 통화 개념을 어떻게 구현하길 원하는가? 아차, 실수. 다시 해보자. 회초리가 나오기 전에 말을 바꿔야겠다. 자, 그렇다면 통화 개념을 어떻게 테스트하길 원하는가? 됐다. 일단 매는 피했다. (p. 94)

구현보다 테스트를 먼저 작성하기. 지키지 않는다면 회초리로 직접 체벌하는 것도 불사해야 함.

---
처음 10장까지 읽어봤는데 도무지 무슨 소린지 머릿속에 정리가 잘 안되더군요. 그래서 1장으로 되돌아가 예제 코드를 따라 쳐가면서 다시 정주행해봤는데 그냥 책만 읽을때와는 완전히 다른 경험을 했습니다. 똑같은 책을 읽었는데 말이죠. 혹시 책만 읽고 계시는 분이 계시다면 꼭 한번 코드도 같이 작성해 보시기 바랍니다.

**Comment by eagleda** [comment]
> 때로는 전진하기 위해 물러서야 하는 일도 있는 법이다.(p.102)

팩토리 함수를 사용하게 하였다가 다시 인라인 하는 등의 사례와 같이 테스트를 실행하는 과정에서 이전의 작업을 되돌리거나 해야 하는 경우도 많을 것 같습니다. 지금이 되돌려야 하는 상황인지 생각하는 판단력과 어디를 되돌려야 하는 지에 대한 발상이 필요하겠군요.

8장부터 나오는 추상 클래스와 관련해서 헷갈리는 게 있어 일단 이를 다뤄본 예제 코드 글을 찾아보니 막힌 게 풀리는 느낌이 
강하게 들더군요. 확실히 예제 코드를 직접 해보고 안 해보고 차이는 명확한 것 같습니다. 코드에 의문점이 들면 가만히 앉아 골머리 썩히기 보다는 일단 한번 작성에 봐야겠습니다.

**Comment by pianoop** [comment]
>리펙토링 하면서 실수했는데도 불구하고 테스트가 여전히 통과할 수도 있는 것이다. 어떻게 할 텐가? 있으면 좋을 것 같은 테스트를 작성하라. ...(중략) 리팩토링하기 전에 테스팅을 하자.  
(6장, 78~79p)  

"있으면 좋을 것 같은 테스트"를 알아가는 데 시간이 참 많이 필요할 것 같다는 생각이 들었습니다.  

>하던 일을 중단하고 다른 일을 하는 상태에서 그 일을 또 중단하지는 않는다. ...(중략) 내가 이런 작은 단계를 밟아가는 것에 대해서 다시금 방어적으로 되는 것 같다. 내가 여러분에게 정말 이런 식으로 일해야 한다고 주장하는 건가? 아니다. 나는 여러분이 이런 식으로 일할 수도 있어야 한다고 말하는 것이다.  
(9장, 97p)  

코드를 짤 때 항상 무언가를 우선시하지 않고 고쳐야할 새로운 무언가가 보이면 몇 번이고 멈추고 작성하다 멘붕하고 시간을 많이 날렸던 경험들이 떠올랐습니다. 자잘한 단계들도 최대한 생략하고 성큼성큼 나아가다 놓친 것들을 고치느라 더 많은 시간을 썼던 경우도 있고, 이런 의미에서 "여러분이 이런 식으로 일할 수도 있어야 한다고 말하는 것이다."라는 부분이 저에게 크게 다가왔던 것 같습니다.

**Comment by az0t0** [comment]
> 하지만 우리에겐 깔끔한 코드와 그 코드가 잘 작동할 거라는 믿음을 줄 수 있는 테스트 코드들이 있다. 몇 분 동안 고민하는 대신 그냥 수정하고 테스트를 돌려서 컴퓨터에게 직접 물어보자.
> (103p)

책에 있는 코드를 작성하면서 앞으로 먼저 어떻게 코드를 바꿔 나가야하는지, 늘 하던대로 고민에 빠지기 시작한다. 그렇게 코드 작성하느라 시간이 늘어지면서 이번 주 분량을 거의 다 읽을 즈음, 이런 글을 읽으면서 내가 이 책을 읽던 방식 잘못 되었다는 것을 깨달았다. 이건 TDD가 아니지 않은가? 한 문단 넘기면 휙휙 바뀌는 예제가 코드가 연이어 등장하는 것은 정말 단순히 코드를 따라해보고, 테스트를 해보라는 것이지 앞으로 나올 코드에 대해 고민하라는 의미가 아니었다.

그리고 *Factory Method*라는 처음 들어보는 개념이 등장하였다. 우리의 친구 ChatGPT의 답을 요약하자면, 생성할 객체의 클래스를 명시적으로 지정하지 않고 인스턴스를 만들어주는 부모 Class의 Method라고 한다. 이 책과 ChatGPT만으로는 이것이 왜 필요한지 아직 이해를 못 하여서 이번 스터디 시간에 한 번 이에 대해 질문을 해보고, 추가적인 정보를 찾아보려고 한다.
