### ISSUE TITLE
[TDD] 23.06.11/3주차 - 17. Money 회고 끝까지 ~ 157p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#114]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by JHyeon0915** [comment]
바로 전주차에서 필요할 것 같은 테스트코드에 대한 내용이 헷갈렸는데, Sum의 예시가 조금 도움이 된 것 같습니다.

14장 133 페이지에서 0이 최악의 해시코드라고 해서 특별한 이유가 있나? 했는데 0 뿐만이 아니라 해시코드로서 모두 같은 값을 리턴하는 것이 최악이라는 문맥인거 같네요.

15장 139-140페이지에서 컴포지트 패턴을 Sum이 2개 이상의 인자를 받게 되면 바뀐다고 하는 구절이 있는데, 3개 이상의 인자를 말하고 싶었던 걸까요..? 잘 이해가 안갑니다.

이번주 내용은 그 전과 달리 살짝 빠른 감이 있었는데 스터디 이후 한 번 다시 정독하고 다시 이해하는 시간을 가지려합니다ㅠㅠ 살짝 어려웠어요

**Comment by KangJiJi** [comment]
## 111 페이지

dollar 와 franc 객체를 없애버리는 것이 인상적이네요. 처음 Money 시스템에 대해서 단순히 생각했을 때 상속을 이용하면 좋겠다고 생각했었지만, 코드의 중복을 제거하기 위한 목적으로 상속을 생각했었네요.

## 115 페이지

여기서 Expression 의 존재가 처음 나오고 조금 이해하기 어려웠습니다. Money 객체들의 연산 결과를 5 + 5 = 10 과 같이 단순 숫자로 결과를 보여줄 수 없으니(USD + CHF), 결과를 추상화 했다고 이해하면 될까요?

메타포(은유)를 실제로 사용한적은 없는데, 다른분들은 현업에서 사용해보신적이 있나요?

**Comment by pianoop** [comment]
122p에서 "두 Money의 합은 Sum이 되어야한다."라며 Sum class가 등장했는데 왜 등장한 것인지 모르겠습니다.  
Money.plus()내에서 끝내면 되는 기능이라고 생각했는데, 여러분은 어떻게 생각하시는지 궁금합니다.

**Comment by usageness** [comment]
마지막에 전체 과정에 대한 회고가 붙어있어서 다시 한 번 살펴보기 좋았네요. 
화폐라는 도메인 자체가 생각보다 많이 복잡하다보니 엄두를 내기 쉽지 않은 주제였는데
저자가 TDD를 통해 시작을 잘 풀어준것 같습니다. 
이런 방식들로 하나씩 해나가면 잘 해결할 수 있겠다는 생각이 들었어요.

p.156
> 테스트 커버리지를 향상시키는 또다른 방법은 테스트의 수는 그대로 두면서 프로그램의 로직을 단순화하는 것이다.

실제로 저자가 "이 둘은 사실상 같은 테스트니 제거해준다" 라면서 보여줬죠.
좋은 접근인것 같아서 적었습니다.

**Comment by pawful-code** [comment]
언젠가는 Bank가 매개 변수가 되어야 할 거라고 '확신'이 들지만 이건 정말 간단한 리팩토링이기 때문에 일단은 나중을 위해 남겨두기로 한다.
p125
코드를 짜다보면 리팩토링 해야할 점이 보이고 이를 실행하다가 코드가 누더기가 되어 다음에 다시 알아보는데 시간이 걸린 경험이 있는데 한번에 하나에만 집중하는 점이 인상깊었다.

**Comment by eagleda** [comment]
sum, reduce 등등 클래스나 함수가 계속 추가됨이 따라 코드와 테스트의 흐름을 책을 읽는 것 만으로는 알기 힘들어지는 게 보였습니다. 다음 예제 부분을 시작하기 전에 저번에 다짐했던 것대로 Money 예제 코드들을 한 번씩 해보면서 흐름을 읽어봐야겠습니다.

**Comment by Astin01** [comment]
이번 파트는 메서드들을 추상화하는 과정이었던 것 같습니다. 또한 마지막에 tdd에 대해 전체적인 흐름을 정리해 주었습니다. 덕분에 읽으면서 낯설었던 tdd에 조금 익숙해진 것 같습니다. 
다만 
|   money.times()의 가시성을 높여줘야 한다. p146
에서 가시성을 높인다는 게 무슨 의미인지 잘 이해가 안됩니다.
제가 아는 건 가시성이 접근권한과 관련된 개념이라는 점인데 그렇다면 접근 권한을 높인다는 뜻인지 아니면 다른 의미인 건지 궁금합니다.

**Comment by siathus** [comment]
## 13장. 진짜로 만들기
> `Expression`과 `Bank`에 이름은 동일하지만 매개 변수 형이 다른 메서드가 있다는 것이 만족스럽지는 않다. 난 자바에서 이런 종류의 문제에 대한 만족할 만한 일반적 해법을 찾지 못했다. 키워드 매개 변수를 지원하는 언어에서는 `Bank.reduce(Expression, String)`와 `Expression.reduce(String)`의 차이점에 대한 의도를 명백히 표현할 수 있도록 문법 차원에서 지원을 해준다. 위치 매개 변수(positional parameters)만으로는 두 메서드가 어떻게 다른지에 대해 코드에 명확히 담아내는 것이 쉽지 않다. (p. 127)

문법 차원에서는 지원하지 않더라도 IDE로 어느 정도 대체 가능하다고 생각합니다. 메서드명을 적는 것만으로 자동완성을 통해 해당 메서드의 매개변수 타입과 이름을 알 수 있으니까요.

**Comment by wise1ight** [comment]
116p 부터 설계에 대한 내용을 알 수 있어서 따라가는 데에는 문제가 없었습니다.
다만 직접 코드를 따라 치며 해보는 동안 여러가지 클래스들이 등장하게 되면서 복잡해지기 시작하고
130p같이 '다음 한 줌의 지저분한 코드면 초록 막대를 볼 수 있다.'라고 되어있지만 실제로는 빨간색 뜨는 부분도 있어서 당황스러웠습니다.
실제로 따라해보면서 각자 어려웠던 점 있으셨으면 공유하면 좋겠습니다.

**Comment by wlsh44** [comment]
따라 쳐보면서 그렇구나 하고 넘어가긴 했지만 개인적으로 설계에 대한 의문을 지우지는 못했던 것 같습니다.
구현하는 방법이야 책에서 말한대로 여러가지겠지만, Money가 reduce를 하는 책임을 갖는거에 대해 생각을 많이 헀던 것 같고, 그 부분이 잘 받아들여지지 않아서 설계를 따라가는데 힘들었던 것 같네요

**Comment by az0t0** [comment]
이번 주차로 예제를 통해 Money 클래스 구현, 자식 클래스에서 통화 변환, 환율 적용 등의 기능을 테스트와 수행을 번갈아가며 차근차근 구현한 것에 대해 끝을 내면서 책을 거의 절반 읽었다.
실제로는 조금 더 가야 절반이지만, TDD라는 단어를 처음 들었을 때, 막연하게 '무엇을 테스트 해야하는가', '테스트는 어떻게 구현해야하는가'와 지속적인 TDD를 위한 설계 구조 등, 큰 의문에 대한 해답은 어느 정도 느낌이 왔으니 절반 정도는 읽었다고 생각하기로 했다...
하지만, 어떤 코드가 좋고 어떤 코드가 나쁜지(저자는 빨강/초록 코드라고 설명했지만 초보인 내가 보기엔 거기서 거기인거 같다.), 내가 세운 테스트가 의미있고 옳았는지 판단하는건 아직 느낌이 제대로 오지 않는 부분이 있다. 이 책을 한 번 읽으면 이런 작은 질문에 대한 해답이 될 수 있을지 기대가 된다. 아니면 내가 잊었거나 빠뜨린 부분이 있었을지도...

**Comment by Lee-Hyeong-Jin** [comment]
126p에서 다형성을 사용해 클래스를 명시적으로 검사하는 코드를 제거하는 과정이 잘 이해 되지 않습니다.
