### ISSUE TITLE
[TDD] 23.06.18/4주차 - 24. xUnit 끝까지 ~ 200p

### ISSUE THREAD

**Issue by KangJiJi** [TeamCrazyPerformance/http#115]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by JHyeon0915** [comment]
### Pluggable Selector Pattern
168p

호출될 메소드의 이름을 클래스 내에 저장하고, 그 메소드를 리플렉션을 이용해 호출하는 패턴.
하나의 상위클래스를 여러개의 하위클래스가 상속받고 있고, 하위클래스들이 상속받지 않은 각각 다른 메소드들을 가지고 있을 때 사용될 수 있는 패턴입니다.
167페이지에 중간 코드를 보면 testRunning, testMethod와 같은 메소드들이 name을 통해 호출됩니다.


다만 사용해야하는 순간은 한정되어있습니다
* 테스트 대상 클래스가 어떤 명칭의 테스트 함수를 구현하게 될지 알 수 없을 때
* 서로 다른 메소드가 한 개씩만 존재할 때와 같은 직관적인 상황에서 코드를 정리하고 싶을 때

**Comment by wise1ight** [comment]
168p.
플러거블 셀렉터는 TestCase 클래스의
```python
    def run(self):
        method = getattr(self, self.name)
        method()
```
이 부분 말하는건가요?

**Comment by usageness** [comment]
p.168
```
일단 하드코딩을 한 다음에 상수를 변수로 대체하여 일반성을 이끌어내는 방식으로 기능을 구현했다.
```
낯선 구현을 할때 좋은 접근법이 되겠다는 생각이 드네요.

```
플러거블 셀렉터(Pluggable Selector)를 사용했다.
```
익숙하지 않은 용어였는데, 제 언어로 풀어보자면 런타임에 메서드를 받아서 실행해주는 패턴이었네요.
왜 정적 분석을 어렵게 만드는지 이해했습니다.

p.172
```
당신이 뭔가를 배우고 싶다면, 한 번에 메서드를 하나 이상 수정하지 않으면서 테스트가 통과하게 만들 수 있는 방법을 찾아내려고 노력해라.
```
더 좋은 방법을 찾고 적용해보자는 의미. 좋은 말이라서 가져왔습니다.

**Comment by KangJiJi** [comment]
# p.161

자기 참조 프로그래밍은 뭔지 의문이네요....

# p.162

부트스트랩 테스트는 뭔지....


# p.168

플러거블 셀렉터 -> [처음보는 내용이네요.](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=wnxodnr&logNo=10122449238) 실행시키고 싶은 메서드를 동적으로 바꿀 수 있게 하는것으로 이해했습니다. 이런 문제라면, js의 eval이나 다른 언어들의 reflection 을 이용하면 된다고 그러네요.

# p.189

12살한테 첫 프로그래밍을 TDD 스타일로 알려주는 조기교육.... 👍

**Comment by pawful-code** [comment]
P.189
학생이 코드를 짜다가 주의가 산만한 모습을 발견하였다. 뭔가 번뜩 생각이나면 현재 작성 하던 코딩을 그만두고 아이디어에 집중하느라 기존에 구현 과정 및 진척도 까먹고 아이디어도 잃어 버리는 모습이었다. 현재 진행 중이던 작업이나 아이디어의 세이브 포인트(?)의 역할을 TDD가 해줄 수 있을 것 같았고 학생이 적용할 수준으로 간략화 시켜서 가르쳐 보았다.
1. 당장 구현 해야 할 기능을 메모장에 적는다.
2. 각 기능이 어떤 동작을하면 통과했다고 할 것 인가를 정한다.
3. 코딩을 시작한다.
4. 코딩을 하다가 잘 안될 것 같거나 개선할 수 있을 것(리팩토링) 같은 아이디어가 생각나면 1.과2.의 과정을 반복 한다.
해당 방식을 통해 entry 블록 코딩을 가르치는데 사용하였다. 학생이 3시간에 걸려서 구현을 해보다가 실패 한 문제를 2시간 만에 해결하는 모습을 보며 인상 깊었다.

**Comment by pianoop** [comment]
- 18장
  [getattr](https://chancoding.tistory.com/188)라는 파이썬 내장 메서드를 처음 알게 됐습니다.  
string으로 해당하는 이름의 필드나 메서드를 가져와서 사용할 수 있다니 굉장히 흥미롭네요.  
- 19장
  테스트 커플링을 만들지 말 것 (170p): 자주 실수한 것 같아 적어봤습니다.

**Comment by genie-youn** [comment]
딱히 없습니당~

**Comment by wlsh44** [comment]
> 성능 - 우린 테스트가 될 수 있는 한 빨리 실행되길 원한다
격리 - 우린 한 테스트에서의 성공이나 실패가 다른 테스트에 영향을 주지 않기를 원한다 
테스트 사이의 커플링은 확실히 지저분한 결과를 야기한다.(170p)

책에서 말하는 내용과는 포인트가 조금 다르지만 이 부분을 읽으면서 first 원칙이 생각났습니다
그리고 두 경우 때문에 혼자 열심히 삽질한 기억들이 새록새록 떠올랐네요..

****

코드를 다 따라해보고 느낀 점은 예제 코드이지만 예외가 있을 때 예외를 삼켜버린다는 점에서 약간 아쉬웠습니다.
그래도 테스트 프레임워크는 어떤 식으로 구현되어 있을까 하면서 상상만 했던걸 직접 해보니까 재밌었습니다!

다만 tdd는 익숙해지려면 한참 걸릴 것 같네요..ㅠ

**Comment by siathus** [comment]
## 19장. 테이블 차리기
> 테스트 사이의 커플링은 확실히 지저분한 결과를 야기한다. 한 테스트가 깨지면, 다음 열 개의 테스트 코드가 올바르더라도 같이 깨지는 식이다. (중략) 테스트 커플링을 만들지 말 것. (p. 170)

---

> 이 테스트를 실행하면(마지막 줄에 TestCaseTest("TestSetUp").run()을 추가해야 한다) 파이썬이 공손하게 wasSetUp 속성이 없다고 알려준다. (p. 171)

"TestSetUp" -> "testSetUp"으로 변경해야 컴파일됩니다. 많이 아쉬운 오타

---

갑자기 예제가 파이썬이 돼서 좀 당황했는데 익숙하지 않아서 그런지 전체적인 흐름은 이해가 가지만 클래스나 메소드 호출하는 부분이 한 눈에 와닿진 않아서 조금 고생했습니다.

**Comment by Astin01** [comment]
테스트 프레임워크가 어떤 절차로 동작하는지 알 수 있었던 부분이었습니다.
다만 용어가 여전히 익숙치 않아 이해하는데 어려움이 좀 있었네요

**Comment by eagleda** [comment]
> 파이썬은 객체 지원이 추가된 스크립팅 언어다보니 전역 참조가 암묵적으로 이루어지고 self에 대한 참조를 명시적으로 적어야 한다.(p.197)

**Comment by az0t0** [comment]
1부는 다 만들어진 테스트 메서드와 함께 예제 코드를 이용해 TDD가 이뤄지는 과정을 배웠다면, 2부는 자신만의 테스트 프레임워크를 바닥부터 만들면서 assert로 테스트하는 과정을 배웠습니다. 직접 테스트 짜는 내용이 전부라 1부에 비해 분량이 상당히 적네요...
갑자기 코드가 Python으로 바뀌고 익숙하지 않은 문법에 참조 프로그래밍, Pluggable Selector 등 생소한 개념들이 많아 이해에 어려움이 있었습니다...
