### ISSUE TITLE
[TDD] 23.07.02/5주차 - 챕터 28. 초록막대패턴 끝까지 ~ 251p

### ISSUE THREAD

**Issue by JHyeon0915** [TeamCrazyPerformance/http#116]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by lallaheeee** [comment]
## 25장. 테스트 주도 개발 패턴

```
211p
- 시스템을 개발할 때 무슨 일부터 하는가?
  완료된 시스템이 어떨 거라고 알려주는 이야기부터 작성한다.
- 특정 기능을 개발할 때 무슨 일부터 하는가?
  기능이 완료되면 통과할 수 있는 테스트부터 작성한다.
- 테스트를 개발할 때 무슨 일부터 하는가?
  완료될 때 통과해야 할 단언부터 작성한다.
```

좋아서 기록

**Comment by wise1ight** [comment]
203p

- 테스트한다는 것은 무엇을 뜻하는가?
- 테스트를 언제 해야 하는가?
- 테스트할 로직을 어떻게 고를 것인가?
- 테스트할 데이터를 어떻게 고를 것인가?

TDD를 떠나서 테스트를 한다는 본질적인 것에 대해 생각해 볼 수 있었습니다.
최근엔 테스트코드를 작성하는 습관을 들이려고 하다보니 결과적으로 테스트코드가 나오는 것에 대해서만 집중을 했는데
테스트의 의미를 다시 생각해보는 계기가 되었네요.

**Comment by genie-youn** [comment]
# 25. 테스트 주도 개발 패턴

뭘 테스트해야 하나? 시작하기 전에 작성해야 할 테스트 목록을 모두 적어둘 것. 프로그래밍 스트레스를 줄이기 위한 우리 접근법의 첫 단계는 발 디딜 곳이 확실해지기 전엔 결코 발을 떼어 전진하지 말자는 것이다. 프로그래밍하기 위해 자리에 앉았을 때, 우리가 성취하고자 하는 것은 무엇인가?

나는 향후 몇 시간 내로 해치워야 하는 모든 할일 목록을 컴퓨터 옆에 있는 종이 조각에 적어놓는 습관을 갖게 됐다. 비슷하게, 주 혹은 월 단위 목록도 만들어서 벽에 붙여뒀다. 이걸 다 적기만 하면 앞으로는 할일을 놓치지 않게 될 것이다. 새로운 항목이 나타나면 나는 빠르고 의식적으로 이 항목이 ‘지금’ 할일에 속하는지 ‘나중에’ 할일에 속하는지. 또는 할 필요 없는 일인지를 결정한다.

### 단언 우선

테스트를 작성할 때 단언은 언제쯤 쓸까? 단언을 제일 먼저 쓰고 시작하라.

- 시스템을 개발할 때 무슨 일부터 하는가? 완료된 시스템이 어떨 거라고 알려주는 이야기부터 작성한다.
- 특정 기능을 개발할 때 무슨 일부터 하는가? 기능이 완료되면 통과할 수 있는 테스트부터 작성한다.
- 테스트를 개발할 때 무슨 일부터 하는가? 완료될 때 통과해야 할 단언부터 작성한다.

# 26. 빨간 막대 패턴

TDD는 옹가의 샤워 방법론을 정제한 것이다. 키보드로 뭘쳐야 할 지 알면, 명백한 구현을 한다. 잘 모르겠다면 가짜 구현을 한다. 올바른 설계가 명확하지 않다면 삼각측량 기법을 사용한다. 그래도 모르겠다면 샤워나 하러 가는 거다.

피로해지면 (판단력이 떨어지므로) 여러분이 피로해졌다는 것을 올바르게 인식하기가 힘들어진다. 그래서 계속 일하면 더 피곤해진다.

**Comment by 29pyg** [comment]
```
신중한 등반가들은 등반할 때 두 다리와 두 팔 중 셋은 항상 고정한다는 규칙을 따른다. (209p)
```
이 규칙을 책 심지어 TDD에서 보게 될줄은 몰랐네요. 초보자들과 등산갔을 때 몸으로 알려주던 내용인데 혹시 등산가셨을 때 사용하시면 좋습니다. 



```
키보드로 뭘 쳐야 할지 알면, 그걸 치면 된다. 
뭘 해야 할지 모르겠으면 샤워하러 가서 뭘 해야 할지 생각날 때까지 계속 샤워를 한다. (225p)
```
여태껏 술을 마셔서 막혔던 코딩이 풀린 경험은 사실 술이 해결 방법이 아니었을지도 모른다!


```
혼자서 프로그래밍할 때 프로그래밍 세션을 어떤 상태로 끝마치는게 좋을까? 
마지막 테스트가 깨진 상태로 끝마치는 것이 좋다. (p239)
```
항상 삽질하다가 화나서 집어던지는 기분으로 끝냈었는데 고치려고할 때 보면 다음에 뭘 해야할지 잘 보이는 이유를 찾았다.

**Comment by usageness** [comment]
p.207
```
... 이 문제를 해결하기 위해 각 테스트 사이에서 매번 시스템을 재가동하는 방법을 써봤지만 시간이 너무 오래 걸렸다.
... 테스트는 좀 더 작은 스케일로 하는게 좋다는 것이다.
```

전에 모 스타트업의 면접 중 "테스트 코드를 어느정도까지 작성하시는 편인가요?" 라는 질문을 받았었습니다.
그때 서비스의 주 기능이 정상적으로 동작하는지 유저 입장에서의 골든 패스를 e2e로 테스트 하고,
기타 자잘한 부분들은 유닛 테스트를 이용해서 작성한다고 대답한 기억이 납니다.

그리고 지금 위 문장을 다시 읽어보니 시간 또한 개발자가 고려해야 할 유한한 자원이라는 생각이 새삼 들었네요.
전체를 다시 테스트한다면 물론 좋겠지만, 그만한 코스트를 항상 감내하기엔 어려울테니
우선순위와 최소한의 조건을 잘 고려해서 테스트를 작성해야겠습니다.

**Comment by siathus** [comment]
28장은 그냥 글 자체가 그런건지 번역때문인지 이해가 힘든 부분이 몇 군데 있었습니다. 특히,
> 가짜로 구현하기를 사용하면, 아이들을 뒷자석에 태우고 오랫동안 자가용 여행을 하던 기억이 난다. 나는 첫 번째 테스트를 작성하고, 좀 지저분한 방식으로 일단 작동하게 만들고는, "자동차를 멈추고 또 다른 테스트를 작성하게 하지 마라. 차를 갓길에 세우게 됐다가는 너희들 정말 혼날 줄 알아." (p. 246)

대체 뭘 말하고 싶은건지 모르겠어서 세 번은 다시 본 것 같네요. 결국 하나의 테스트를 작성하고 리팩토링하기 전까지는 다른 테스트를 작성하지 말라는 것 같은데 개인적으로는 글이 너무 난잡하게 읽혀서 힘들었습니다.

**Comment by pawful-code** [comment]
238p

> 테스트 되지 않은 코드는 작동하는 것이 아니다.  이것이 안전한 가정이다. 그렇다면 수많은 에러 상황에 대해서는 어떻게 테스트 할 것인가? 이것들도 다 테스트 해야할까? 작동하길 원하는 부분에 대해서만 하면 된다.

 테스트 커버리지를 만족하는데 익숙해져 있어서 "작동하길 원하는 부분에 대해서만 하면된다." 는 문장을 쉽게 받아들이기 힘들었다. 하지만 테스트 엔지니어가 아닌 개발자가 커버리지를 만족시키는 코드를 작성하기 보다. 제시간에 sw를 전달 하고 피드백을 받아 다음 개발 주기를 시작하는 편이 어플리케이션 제작에는 더 좋은 결과를 낼 수 도 있겠다는 생각이 들었다.

**Comment by pianoop** [comment]
```
회귀 테스트란, 사실 여러분에게 완벽한 선견지명이 있다면, 처음 코딩할 때 작성했어야 하는 테스트다. 
회귀 테스트를 작성할 때는 이 테스트를 작성해야 한다는 사실을 어떻게 하면 애초에 알 수 있었을지 항상 생각해보라.
p.224  
```
같은 실수 반복하지 않기, 당연하지만 굉장히 중요하고, 또 의외로 어려운 것이라 생각되어 이곳에 남겨보았습니다.

**Comment by eagleda** [comment]
205p. 
garbage collection/collector:
요약하자면 참조나 사용이 되지 않게 된 객체 등을 메모리 누수 방지를 위해 주기적으로 청소를 해주는 컬렉션정도 일까요

 #### 한 단계 테스트 239-240p
>목록에서 다음 테스트를 고를 때 무엇을 기준으로 할 것인가? 여러분에게 새로운 무언가를 가르쳐 줄 수 있으며, 구현할 수 있다는 확신이 드는 테스트를 고를 것

 #### 깨진 테스트 239-240p
>혼자서 프로그래밍할 때 프로그래밍 세션을 어떤 상태로 끝마치는게 좋을까? 마지막 테스트가 깨진 상태로 끝마치는 것이 좋다.

>반 쪽자리 문장을 보변 전에 그 문장을 쓸 때 무슨 생각을 했는지 떠올리게 된다.

전날 작성하던 코드를 다음 날 다시 잡으면 뭐 하던 거였지? 하며 맥락 잡는데만 시간을 잡아먹곤 했는데 이게 해결법이 될지도 모르겠네요.

각 트릭/패턴의 주요 논점을 Q&A형식으로 초반에 알려주고 후에 설명을 하는 방식이 어떤 것을 중점으로 봐야하는지가 잘보여서 좋았던 것 같습니다.

**Comment by JHyeon0915** [comment]
221p
```
단순한 시작법은 테스트를 이용하여 묻고, 테스트를 이용하여 설명하는 것이다.
```
테스트는 프로그램이 제대로 동작하는지 확인하고, 문제점을 발견하는 것에 의의를 두었는데 이렇게 커뮤니케이션의 관점을 리마인드 해 주어서 기억에 남네요.
