### ISSUE TITLE
[TDD] 23.07.09/6주차 - 챕터 30. 디자인패턴 끝까지 ~ 289p

### ISSUE THREAD

**Issue by lallaheeee** [TeamCrazyPerformance/http#117]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by wise1ight** [comment]
258p.
> TestCase의 하위 클래스와 하위 클래스의 인스턴스 사이의 관계는 xUnit에서 가장 혼란스러운 부분 중 하나다. 새로운 종류의 픽스쳐는 각각 Test-Case의 새로운 하위 클래스여야 한다.

빈 사각형을 테스트 하는 경우와 비어 있지 않은 사각형을 테스트 하려고 하면
빈 사각형 테스트 케이스 클래스를 만들고 비어 있지 않은 사각형 테스트 케이스 클래스를 만들어
전자의 클래스에는 setUp()에서 빈 사각형을 만들고, 후자는 비어 있지 않은 사각형을 setUp() 해야하는
**서로 다른 테스트 조건이라면 각 조건의 테스트 케이스 클래스를 만들고 픽스쳐도 각 클래스별로 별도로 만들어라**
라고 할 수 있는건가요?

**Comment by lallaheeee** [comment]
~~ 작성중 ~~ 

```
원과 원이 아닌 것을 구분하기 위해 한 곳에서 명시적인 조건문을 사용하게 되면, 조건문은 조만간 퍼져나갈 것이다.
-278p
```

현업에서 겪었던 문제라 와닿네요. 해결법도 근사한듯

**Comment by usageness** [comment]
p.253
```
테스트가 잘 작동하는지 어떻게 검사할 것인가?
```

어제 토스 Next에 참여했는데 프론트쪽 테스트 관련 이슈가 꽤 있었습니다.
이런걸 보면 테스트가 잘 되는지 테스트 하는 것도 중요하구나 싶네요.

p.261
```
JUnit에는 'testAssertPosInfinityNotEqualsNegInfinity' 라는 테스트가 있다.
```

부동소수점 이슈...! jest에선 어떤지 모르겠네요.
`Same-Value` vs `Same-Value-zero`

p.289
```
전역 변수를 제공하지 않는 언어에서 전역 변수를 사용하려면 어떻게 해야 할까? 사용하지 마라.
```

단호하네요... 😅
다행인지 불행인지 전역 변수를 제공하는 언어를 쓰는 입장이지만
잠깐 정도는 사용해도 괜찮다고 생각합니다. 다만 빠른 시일내로 리팩토링 해야겠어요.

**Comment by siathus** [comment]
## 30장. 디자인 패턴
> 역자 주: 형태로 봐서 자바 문법인 것 같지만 case 문에 string 형이 있기 때문에 사실은 문법 오류다. (p. 281)

독자 주: 자바 1.7버전부터 switch case문에 문자열도 지원하기 때문에 사실은 문법 오류가 아니다.

**Comment by KangJiJi** [comment]
# p.277 - 플러거블 셀렉터

조건문을 다형성으로 리팩터링과 같다? 라는 느낌을 받았습니다. 만약 제가 해당 로직을 작성했다면, `SingleSelection`과 `MultipleSection` 객체를 생성하는 팩토리 주입을 통해 SelectionMode 의 mouseDown 메서드에서 적절한 값을 넣어주도록 작성하였을 것 같습니다. 다만.....이렇게 작성하는것도 너무 코드의 복잡성을 높히는 것 같긴 하지만, 개인적인 의견으로는 해당 selection에 관한 객체들은 변경과 확장에 대비해야하는 객체중 하나가 아닐까라는 추측을 합니다.

**Comment by eagleda** [comment]
>테스트 메서드는 의미가 그대로 드러나는 코드로, 읽기 쉬워야 한다.


>우리가 언제나 완전히 다른 문제들을 해결하는 것 같지만 우리가 푸는 문제 대다수는 사용하는 도구에 의해 생기는 것이지 직면한 외부의 문제 때문에 생기는 것이 아니라는 점이다.

이러한 도구에 의해 생기는 공통적인 문제들을 공통적으로 풀어내기 위해 사용하는 게 패턴이군요.

패턴 파트는 아직 접한 게 많이 없다보니 용어와 설명이 이해하기 어려운 게 많더군요. 시간이 들더라도 이것저것 찾아보면서 읽어야 겠습니다. 유난히 자바 애기가 많이 나오는데 자바 공부를 시작해야하나 하고 압박을 받는 느낌이..

**Comment by JHyeon0915** [comment]
### 258p
```
난 대부분 공통의 셋업 코드를 분리하는데, 항상 세부사항에 대해 정확히 기억한다. 
내 코드를 읽는 사람은 기억해야 할 것들이 너무 많다며 불평하기도 한다. 좀 덜 분리하는 것이 좋을지도 모르겠다.
```
팀의 규모, 예상되는 셋업 코드의 길이 등에 따라 컨벤션으로 정리하면 좋은 프로젝트가 될 것 같다는 생각이 들었습니다. 개인적으로는 tdd는 Unit테스트에 주로 적용되니 셋업 코드의 길이는 보통 짧을 것이라 전제를 깔자면, setUp()에 코드를 분리하는게 미관적으로 더 예쁠 것 같고, 분리를 하지 않는 쪽이 더 직관적으로 이해가 쉬운 코드가 될 것 같네요.
만약 setUP()으로 코드 분리 시 코드가 복잡해졌거나 팀의 규모가 크다면, 주석도 또 하나의 해결책이 될 수 있지 않을까? 라는 생각이 들었습니다.

### 감상
전체적으로 디자인패턴과 tdd를 엮은 설명과 예제들이 좋았습니다. 유익한 느낌이네요. 똑똑해진 것 같은 느낌이 들어 기분이 좋습니다 ㅎ

**Comment by az0t0** [comment]
30장 디자인 패턴에서 이전에 `팩토리 메서드`, `플러거블 셀렉터`, 그리고 `임포스터`와 같이 처음 봤던 단어들을 설명했습니다. 이 내용이 먼저 나왔더라면 이전 내용이 좀 더 이해가 잘 됐을지도 모르겠습니다...

> 플러거블 셀렉터 해법은 리플랙션을 이용하여 동적으로 메서드를 출력하는 것이다.
> _30장, 281페이지_
Reflection보다 switch문이 메서드 호출 조건을 보고 흐름을 파악하는데 더 직관적인 것 같은데, Reflection을 사용하는 경우가 많은지 궁금합니다.

또 Reflection을 설명허는 코드에 `Method runMethod = getClass.getMethod(...);`라고... 마치 함수형 프로그래밍처럼 표현해놓은게 조금 이해가 안되네요... 이건 runMethod라는 객체에 메서드가 담긴건가요??

**Comment by pawful-code** [comment]
P291

> 일반적으로 리팩토링은 어떤 상황에서도 프로그램의 의미론을 변경해서는 안된다. 하지만 TDD에서 우리가 신경쓰는 부분은 현재 이미 통과한 테스트들 뿐이다.

P292
> 이 '관측상의 동치성'이 성립되려면 충분한 테스트를 가지고 있어야한다. 여기에서 충분한 테스트란, 현재 가지고 있는 테스트들에 기반한 리팩토링이 추측 가능한 모든 테스트에 기반한 리팩토링과 동일한 것으로 여겨질 수 있는 상태를 말한다. 

클린코드 심플 디자인을 의미하는 리팩토링과 TDD에서 코드를 개선하는 단계의 리팩토링을 구분짓는 중요한 문구인 듯 하다.(p 291)
또한 이를 보장할 수 있는 '충분한 테스트'에 대한 정의를 내리는 중요한 문장이다. 작가가 유우머대신 뒷줄에 확실한 사례를 곁들여 설명하는 모습이 인상 깊었다. (P292)

계속해서 저자는 테스트의 중요성을 강조하는데
어떤 테스트가 올바른 테스트이고 그러한 테스트 종류엔 무엇이 있으며 개발자는 어느 정도의 테스트 까지를 작성하고 담당 해야 한다고 생각하는지 의견이 궁금합니다. 

===============================================

Cohesion 과 Coupling
저번 주에  제대로 답을 못 해드린게 마음에 걸려서 조사한 자료를 간략하게 업로드합니다.  학술적으로 엄밀한 정의를 전달 하기보다는 cohesion과 coupling에 대한 가벼운 설명을 위함이라 틀리거나 엄밀하게는 조금 달라서 집고 넘어갈 부분은 지적해주시면 감사할 것 같습니다.


 Coupling & Cohesion 이 등장한 배경인 modular programming에 대해 간략히 설명한 후 coupling 과 cohesion에 대해 설명하겠습니다.

모듈화란?
 모듈화란 전체 프로그램을 기능별로 나누어 서브 프로그램들의 집합으로 만드는 일입니다.

(예시) 아무 계획 없이 코딩을 하는 A와 천천히 설계를 한 후에 코딩을 하는 B가 
사용자가 마우스로 버튼을 클릭하는 방식의 계산기 프로그램을 만든다고 생각해 봅시다. 
 inputA (+-/*) inputB =answer


A는 하나의 main 함수에 바로 코딩을 시작하였고

B는 프로그램을 사용자로부터 입력 계산 출력으로 구분한 후  
입력에 해당하는 소스 코드를 입력에 넣는 방식으로 관리하며 개발을 하였다면

극단적인 성능을 필요로 하지 않는 이상 A의 코드 보다는 여러가지 면에서 B의 코드가 유리할 것 입니다. 

유지보수성 측면
1. 요구사항이 변경되어 계산기 프로그램을 수정할 때 (수정용이성)
2.  신입인 C가 기존 개발 상황을 이해해야 할 때 ( understandability )
....


Coupling과 Cohesion은 이러한 프로그램의 모듈화가 얼마나 잘 되어 있는가를 보이기 위한 분류라고 생각하면 될 것 같습니다.

이번엔 신입 C가 같은 요구사항을 가지고 본인 만이 프로그램을 작성했다고 가정해 봅시다.
inputA (+-/*) inputB =answer

C는 프로그램을 (더하기 빼기 곱하기 나누기) 구분을 하였다고 해봅시다.
또한 C씨는 사장님에게 본인이 프로그램을 4개로 모듈화 하였으니 B의 모듈화보다 뛰어나기에 연봉인상을 요구한다면 과연 이 주장은 정당한 주장일까요.

사장님이 결정을 내리기전에 고객사에서 전화가 와서 요구사항이 추가 되어
inputA (+-/*) inputB =answer 뿐만 아니라
inputA (+-/*) inputB (+-/*) inputC =answer 이 되었다면

C의 모듈화 보다는 B의 모듈화가 요구사항 추가에 따른 변경점 및 변경에 필요한 테스트하는 부분이 적을 것이라고 생각 할 수 있습니다.

![6273d45dd94c17e6dc28e178__W2oPvJA4KJxmMhFjFBKVpMuy_J9vf17Jhix40rTFluc73W9Buo6Q6DiBnZxhElVoJoo9J0XRSM7_1V7kXeKReKKNrbyGlUqYc57kn91RiTs4pVy1eUhNBZiQHaNN5xIxqxwmFnOJT3UPk7fpg](https://github.com/TeamCrazyPerformance/http/assets/16588701/fc1b1c51-b473-41fe-8882-59a90a4f0512)

비약해서 표현하자면
모듈과 모듈 사이에서 일어나는 일은 coupling
모듈 안에서 일어나는 일은 cohesion

coupling 이 high할 수록 좋지 않음-> 테스트에 어려움, 수정 변경에 어려움, ...
cohesion이 high 할 수록 좋음
high cohesion, loosly coupling 


reference
https://en.wikipedia.org/wiki/Modular_programming
https://en.wikipedia.org/wiki/Coupling_(computer_programming)
https://en.wikipedia.org/wiki/Cohesion_(computer_science)

https://www.engati.com/glossary/cohesion-and-coupling
https://programmerbay.com/difference-between-cohesion-and-coupling/
https://blog.devgenius.io/coupling-and-cohesion-c647a9101715
