### ISSUE TITLE
[TDD] 23.07.23/7주차 - 끝까지

### ISSUE THREAD

**Issue by wise1ight** [TeamCrazyPerformance/http#118]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
# 31장 리팩터링
> 두 번째 코드가 더 좋아 보일 수도 있고, 아닐 수도 있다. 여기서 중요한건 제어 흐름을 이리저리 바꿔가며 실험해보기 위해서 메서드를 인라인할 수 있다는 점이다. ... "이놈은 저놈에게 메시지를 보내고, 그럼 그놈은 다시.. 우와, 모르겠다. 도대체 무슨 일이 벌어지는거지?" 이렇게 되면 나는 여러 추상화 계층을 인라인시켜 놓고 뭐가 어떻게 돌아가는지 제대로 이해한 다음, 예상이 아닌 실제적인 필요성에 기반하여 다시 추상화를 수행한다. (299p)

요즘 TDD와 함께 최대한 보폭을 작게 만드는 훈련을 하면서 얻고있는 최대 수혜가 아닐까? 잘 모르겠을땐 할 수 있는 모든 옵션을 그냥 구현해본다. 아닌것 같다 싶으면 직전 테스트성공 커밋으로 리셋하면 되니까. 그런 뒤 실제 결과물을 보면서 생각해보면 생각보다 쉽게 결정이 되는 케이스가 많더라. 예전같았으면 하루종일 고민만 했을텐데.

> 현 사례는 단 한가지 밖에 존재하지 않기 때문이다. 이럴때면 신경을 끄고 인터페이스 이름을 IFile 이라고 하고 클래스 이름을 그냥 File로 남겨두고 싶어진다. 나는 이럴 경우 잠시 멈추고 무슨 일이 벌어지고 있는가에 대해 좀더 심오한 것을 이해하지 못한 건 아닌지 확인하도록 자신을 단련했다. 아마도 인터페이스 이름을 File로 하고 클래스 이름을 DiskFile로 하는것이 맞을지도 모르겠다. 왜냐하면 클래스는 비트가 디스크상에 있다는걸 가정하고 있기 때문이다. (301p)

최근에 실무하다 비슷한 논의를 한번 가졌던 적이 있는데, 공감되어서 갖고 와보았습니다

# 32장 TDD 마스터하기
> 당신이 작성하는 것들에 대해서만 테스트해라. 불신할 이유가 없다면 다른 사람이 만든 코드를 테스트하지 마라. (309p)

e2e 테스트를 작성할 때, 테스트 대상인 클라이언트의 관점에서만 테스트하기. 서버와의 협력은 경계밖이므로 (다른 사람이 만든 코드이므로) API 요청이 기대한대로 전달했는지 까지만 테스트한 뒤 drop 시키고 이에 대한 응답도 API 명세에 적힌대로 정상 응답으로 mocking 한다.

> TDD의 테스트에 대한 관점은 실용적이다. TDD에서 테스트는 어떤 목적을 위한 하나의 수단이다 (여기서 목적은 우리가 깊이 신뢰할 수 있는 코드가 되겠다.) 만약 어떤 구현에 대한 지식이 신뢰할 만 하다면 그에대한 테스트는 작성하지 않을 것이다. (313p)

너무 좋네요.

> 테스트를 지워야 할 때는 언제인가?
> - 첫째 기준은 자신감이다. 테스트를 삭제할 경우 자신감이 줄어들 것 같으면 절대 테스트를 지우지 말아야 한다.
> - 둘째 기준은 커뮤니케이션이다. 두 개의 테스트가 서로 다른 시나리오를 말한다면 그대로 남겨두어야 한다. (315p)

너무 좋네요 2

# 부록A: 영향도

> 그림 A.5 (332p)

내 일상 도촬당한 기분

# 마치는 글

> 우리가 가진 화려한 도구들에도 불구하고, 프로그래밍은 여전히 어렵다. 동시에 여러 개의 공을 공중에 띄어놓고 저글링할 때처럼, 프로그래밍 할 때도 잠시만 집중을 놓치면 모든 게 무너져 버릴것 같은 느낌을 받은 적이 많다. 테스트 주도 개발은 이런 느낌을 감소시키는 데 도움이 되고, 그 결과로 신속한 느긋함을 얻게 된다. (339p)

신속한 느긋함이라는 말이 참 와닿는 부분. TDD를 진행하면서 급격히 불어나는 할일 목록을 보면서 처음엔 조급함이 앞섰지만, 결국 이게 제일 빠른 길이고 하나씩 하면 되지~ 하는 느긋함을 가질 수 있게 되는게 중요한것 같다.

# 실전 TDD

> GUI 코드를 작성, 프로그램을 만들면 모델과 뷰가 뒤섞인 코드를 작성할 수 있기 때문에 모델 부분을 미리 작성하는것이 좋다.
> 모델 코드와 뷰의 코드가 완전히 분리되면 이 말은 바로 성립한다. 이는 테스트 가능성에서도 중요한데, TDD를 하면서 주기를 짧게 하기 위해 '할 수 있는 가장 단순한 일은 무엇인가?' 라고 질문하며 작성하다 보면 적절하게 유도된다. 이러한 방법으로 도메인 로직 코드를 확실하게 분리해 놓으면 재사용하기에도 훨씬 쉽고 테스트 가능성도 높아진다.

관련해서 [포스팅](https://genie-youn.github.io/journal/Vue_Application_Architecture_part3.html) 한적이 있는데~~
도메인 로직을 리액트와 상관없는 순수한 타입스크립트로 작성하면 읽기도 쉽고, 재 사용하기도 쉽고 단위 테스트하기도 쉽다는 것. 뷰에 비해 변경주기도 훨씬 길다.

# 감상
그 전까지는 책으로만 접하고, "하면 좋지~ 그래그래 좋지~"라는 생각으로 사이드프로젝트 할때나, 여유가 있을때 깔짝깔짝 하다가 이직 후 본격적으로 테스트와 TDD의 필요성이 피부로 체감되어 이제야 좀 이 리듬에 적응이 되는것 같은 시기에 이 책을 다시 읽으니 전에는 와닿지 않던 부분이 색다르게 보이는 경험이 역시 또 신기했던 스터디였습니다~ 이런 책들은 역시 사골 끓이듯이 푹 고아서 재탕 재재탕을 거쳐야 하나 봅니다.

**Comment by KangJiJi** [comment]
# 리팩터링

이전에 읽었던 책의 요약본 같은 내용이였습니다~

# TDD 마스터하기

TDD 하기 쉽지 않다고 느끼는 장 이였습니다. 최근 팀에서 테스트 코드의 필요성을 느끼지만 어떻게 적용해야할지도 고민이 많네요.

**Comment by wise1ight** [comment]
# 31장
리팩터링 시즌 2

**Comment by pawful-code** [comment]
> 이 '관측상의 동치성'이 성립되려면 충분한 테스트를 가지고 있어야 한다. 여기에서 충분한 테스트란, 현재 가지고 있는 테스트들에 기반한 리팩토링이 추측 가능한 모든 테스트에 기반한 리팩토링과 동일한 것으로 여겨질 수 있는 상태를 말한다. p292

위의 문장을 아래와 같이 받아 들였습니다.
 1. 충분한 테스트를 통과한 코드는 다른 방식의 테스트 조합을 사용해도 통과 할 수 있어야 한다.
 2. 충분한 테스트를 통과하면 테스트 대상 코드가 요구사항 혹은 설계를 만족함을 보인다.

2번을 충족 하기 위해서는 결국 고객과의 협의가 가장 중요하게 될 것이라고 생각됩니다.

이 생각은 아래와 같은 질문들이 생겼습니다.
1. 단위, 모듈 테스트와 같은 영역과 같이 고객이 잘 모르는 분야에서 어떻게 고객과 소통하고 협의가 이뤄지는지 궁금합니다.
2. 개발자들 간에도 자신이 작성한 테스트가 어떻게 상위 설계를 만족할 수 있는지 증명하는 과정 또한 있는 것인지 궁금합니다.
3. 테스트 엔지니어라는 직업과(단순히 테스트를 수행하는 사람이 아니라 테스트를 작성하고 설계하는 사람) 굉장히 공통된 부분이 많은 것 같은데 실제 개발자들은 어떻게 느끼고 대비하고 있는지
4. ci/cd를 위해 jenkins가 사용되는 것 처럼 tdd를 지원하는 툴 또는 플랫폼이 있는지 
5. v모델과 같은 고전적인 방법론에 (설계/ 구현/테스트) 문서화 작업과 TDD의 테스트 작성이 굉장히 유사하다고 느꼈습니다.  V모델에서 요구사항을 분석하는 단계 부터 테스트를 설계하는 경우도 있는데 이를 TDD(애자일)로 봐야하는지 헷갈립니다.

**Comment by pianoop** [comment]
# 31장
책을 읽다 '관측상의 동치성(292p)'이 부분을 읽고 바로 이해가 되지 않아 한참을 생각했습니다.  
테스트를 통과한 리펙토링된 코드가 리펙토링 이전의 코드와 질적으로 동일하다는 것을 의미하는 것이 맞을까요?

**Comment by usageness** [comment]
p.291
`리팩토링`의 기능/인터페이스 유지의 리팩토링에서 'TDD'의 테스트 결과 유지의 리팩토링으로 옮겨갔네요.
리팩토링을 시작할때 코드를 바라보는 관점이 살짝 다르지만 결국에는 같은 곳을 지향하고 있다는 생각이 들었습니다.

p.308
```
자동화된 리팩토링 툴은 리팩토링을 엄청나게 가속화시킨다.
```
이 분야 원탑 **InteliJ**

p.309
```
당신이 작성하는 것들에 대해서만 테스트하라.
```

다른 분들의 **불신했던 경험 or 믿었는데 배신당한 경험**이 있는지 궁금합니다.


## 감상

제가 비록 현업자는 아니지만, 프로젝트를 진행하며 TDD를 얕게나마 사용해보고, 테스트 코드를 작성하기 시작하니
이전에 읽었을때와는 전혀 다른 느낌을 받았습니다. 제가 느끼고있던 TDD나 테스트의 문제점들, 또는 좋았던 점들이
책의 저자가 "그래~ 나도 그런 시절을 다 겪어봤단다~" 하고 알려주는 느낌이었네요.

아직까지 접해본 경험이 부족해서 책의 모든 부분이 와닿지는 않았지만 다음에 또 재탕할때는 다르게 느껴질거라 믿습니다.
지수형 말씀처럼 이 쪽 책들이 사골 맛집이네요. 😎

**Comment by eagleda** [comment]
## 31장 리팩토링
### 매개변수 추가
일단 매개변수를 추가하고 컴파일 에러 확인을 통해 고칠 부분을 확인하라는 게 의아했는데 사람이 체크하는 것보다 프로그램을 실행하는 컴퓨터 입장에서 확실하게 알려줄 터이니 맞는 말인 것 같네요.
## 32장
>당신이 작성하는 것들에 대해서만 테스트하라. 불신한 이유가 없다면 다른 사람이 만든 코드를 테스트하지 마라.(p.309)

>만약 당신이 어느 정도는 작동하는 코드를 왕창 입력해 넣는 것에 행복해 하고, 그 결과를 두 번 다시 쳐다보지 않는 것에 행복해 한다면, TDD는 당신을 위한 것이 아니다. TDD는 더 나은 코드를 작성한다면 좀 더 성공할 것이라는, 매력적일 정도로 나이브하며 해커적인 가정에 근거한다.(p.319)
## 감상
일전에 공부하면서 만들었던 코드들을 어떻게 작성했는가 생각해보니,  위의 문단처럼 일단 작동되도록 코드를 작성하고, 성공하면 그냥 넘어가서 돌아보지 않고, 실패에 대하여 큰 생각을 하지 않고 이것저것 건드려보며 문제를 찾는 방식으로  만들고 있었다는 생각이 듭니다.  이번, 그리고 앞으로 TDD를 읽으면서 방식을 개선하고, 테스트를 통한 정확한 문제 탐색,해결을 할 수 있게 되면 좋겠습니다.

**Comment by az0t0** [comment]
> 여러분은 한 줄의 로직을 추가하고 약간의 리팩토링을 할 수 있을 정도 크기의 테스트를 만들 수 있는가 하면, 수백 줄의 로직과 수시간 분량의 리팩토링을 할 만큼의 크기를 갖는 테스트를 만들 수도 있다. 이중 어떤 것이 옳은가?
답변의 일부는 다음과 같다. 여러분은 둘 다 할 수 있어야 한다.
P. 308

결국 작은 크기의 테스트를 여러 개로 쪼개서, 마치 분할 정복하는 것과 같이 테스트를 작성하다보면 리팩토링이 되어있다는 말이었습니다. 책 내내 어떤 사소한 것이든 일단 걸고 넘어져라는 것을 가르쳐게 규모가 큰 리팩토링을 하는 과정이었기 때문이었죠...

>자동화된 리팩토링 툴은 리팩토링을 엄청나게 가속화시킨다. 20번의 단계를 통해 해야 할 일이 메뉴 아이템 하나로 간단히 해결된다.

IDE는 무적입니다... 하지만 무색하게도 단축키를 모르니 메뉴 하나씩 클릭해가며 써서 느린게 함정...

> **TDD는 누구를 위한 것인가?**
... 만약 당신이 어느 정도는 작동하는 코드를 왕창 입력해 넣는 것에 행복해 하고, 그 결과를 두 번 다시 쳐다보지 않는 것에 행복해 한다면, TDD는 당신을 위한 것이 아니다. TDD는 더 나은 코드를 작성한다면 좀 더 성공할 것이라는, 매력적일 정도로 나이브하며 해커적인(geekoid) 가정에 근거한다. 

TDD를 읽기 시작하면서 필요성을 느끼게 된건 예전에 만든 프로젝트 코드를 천천히 리팩토링할 때 였습니다. 다시는 안 만질거 같았던 프로젝트였는데, 기능을 더 추가하려고 하니 1년이 다 되어가는 코드에 주석도 거의 없던지라 기억도 안 나서 구조 분석부터가 쉽지 않았습니다. 하지만 _기능 추가_ 단 한 가지를 위해 코드를 뜯어서 하나씩 테스트하고 코드 분석하고, 테스트하고 구조 분석하고... 토이 프로젝트 하나 끝내면 기억에서 지워버리는 예전의 저를 좀 혼내고 싶었네요. 시간을 생각하면 처음부터 만드는게 빠르겠지만... 예전의 나와 지금의 나의 코드를 비교하면서 얼마나 더 나아졌는지 보고, TDD와 IDE에 달린 여러가지 도구를 써보게 되는 시간을 갖고자 합니다.
