### ISSUE TITLE
[오브젝트] 23.08.13/1주차 - 챕터 2. 객체지향 프로그래밍까지 ~ 73p

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#119]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by wise1ight** [comment]
# 1. 패러다임
> 한 시대의 사회 전체가 공유하는 이론이나 방법, 문제의식 등의 체계
# 2. 프로그래밍 패러다임
> 특정 시대의 어느 성숙한 개발자 공동체에 의해 수용된 프로그래밍 방법과 문제 해결 방법, 프로그래밍 스타일
- 프로그래밍 패러다임은 개발자 공동체가 동일한 프로그래밍 스타일과 모델을 공유할 수 있게 함으로써 불필요한 부분에 대한 의견 충돌을 방지한다.
- 프로그래밍 패러다임을 교육시킴으로써 동일한 규칙과 방법을 공윺하는 개발자로 성장할 수 있도록 준비

# 3.

**Comment by usageness** [comment]
## 객체, 설계
p.14
```
하지만 불행하게도 변경 용이성과 읽는 사람과의 의사소통이라는 목적은 만족시키지 못한다
```
- 변경에 용이하지 못한 이유
  - Theater가 Audience와 TicketSeller에 결합되어 있다. -> 한 쪽이 수정되면 다른 쪽도 수정해야 한다.
  - 자율성을 주는 것으로 해결

p.33
```
첫째, 어떤 기능을 설계하는 방법은 한 가지 이상일 수 있다.
둘째, 동일한 기능을 한 가지 이상의 방법으로 설계할 수 있기 때문에 결국 설계는 트레이드오프의 산물이다.
```
-> 이전 스터디에서도 계속해서 등장했던 **트레이드 오프.** 다시보니 반갑네요

## 객체지향 프로그래밍
p.41
```
이처럼 문제를 해결하기 위해 사용자가 프로그램을 사용하는 분야를 도메인이라고 부른다
```

객체를, 구조를 잘 짜는 것도 결국 도메인을 잘 이해하고 있어야 가능한 일인 것 같아요.
최근에 프로젝트를 바닥부터 설계할 일이 생겼었는데 도메인에 대한 이해가 정말 중요한 것 같습니다.

p.72
```
상속은 클래스를 통해 강하게 결합되는 데 비해 합성은 메시지를 통해 느슨하게 결합된다.
따라서 코드 재사용을 위해서는 상속보다는 합성을 선호하는 것이 더 좋은 방법이다
```

처음부터 상속같은게 존재하지 않는 근본없는 언어를 썼다면 😉


---

전체적으로 앞내용은 지금까지 읽었던 객체지향 시리즈들과 완전 동일했네요.
덕분에 술술 넘기면서 본 것 같습니다.

**Comment by genie-youn** [comment]
### 2장 객체지향 프로그래밍

> 앞으로의 설명을 위해 '영화'와 '상영'이라는 용어를 구분할 필요가 있을 것 같다. (38p)

요즘 많이 느끼는, 중요한 부분. 도메인을 파악하고 요구사항을 명확하게 식별해내는것. 그 과정에서 이해관계자들의 의사소통 과정에서 혼란이 생기지 않도록 유비쿼터스 랭귀지를 명확하게 정의하고 코드가 이를 말하게 하는것.

> “영화의 예매 요금은 금액 할인 정책과 두개의 순서 조건, 한 개의 기간 조건을 이용해서 계산할 수 있다” 라는 문장은 “영화 예매 요금은 최대 하나의 할인 정책과 다수의 할인 조건을 이용해 계산할 수 있다” 로 추상화 할 수 있다.
>
> 추상화를 사용하면 세부적인 내용을 무시한 채 상위 정책을 쉽고 간단하게 표현할 수 있다. 추상화의 이런 특징은 세부사항에 억눌리지 않고 상위 개념만으로도 도메인의 중요한 개념을 설명할 수 있게 한다. 금액 할인 정책과 비율 할인 정책을 사용한다는 사실이 중요할 때도 있겠지만 어떤 때는 할인 정책이 존재한다고 말하는 것만으로도 충분한 경우가 있다. 추상화를 이용한 설계는 필요에 따라 표현의 수준을 조정하는 것을 가능하게 해준다. (66p)


추상화를 가장 멋지게 표현한 문장 아닐까?

> 여기서 이야기하고 싶은 사실은 구현과 관련된 모든 것들이 트레이드오프의 대상이 될 수 있다는 사실이다. 여러분이 작성하는 모든 코드에는 합당한 이유가 있어야 한다. 비록 아주 사소한 결정이더라도 트레이드오프를 통해 얻어진 결론과 그렇지 않은 결론 사이의 차이는 크다. 고민하고 트레이드오프 하라. (69p)

감상: 가장 크게 와닿는 부분은 “직관” 이었다. 객체지향이 주는 매력은 현실세계를 사상하기에 “직관”적으로 이해할 수 있는 부분이지 않을까?

**Comment by pawful-code** [comment]
p.29

> 설계를 어렵게 만드는건 의존성이라는 것을 기억하라. 해결 방법은 불필요한 의존성을 제거함으로써 객체 사이의 결합도릏 낮추는 것이다.

p33
첫째 어떤 기능을 설계하는 방법은 한 가지 이상일 수 있다. 둘째 동일한 기능을 한 가지 이상의 방법으로 설계할 수ㅠ있기 때문에 결국 설계는 트레이드 오프의 산물이다 어떤 경우에도 모든 사람들을 만족 시킬 수 있는 설계를 만들 수는 없다.

트레이드 오프를 통해 얼만큼의(정량적인) 품질지표를 얻을 수 있는지 계산하거나 추산하는 방법이 있다면 공유 부탁드리겠습니다. 
ex) 복잡도 측정을 위한 cyclomatic complexitiy


page 36

> 변경 가능한 코드란 이해하기 쉬운 코드다.
understandable 한 코드라는걸 평가하는 지표에는 어떠한 것이 있습니까?
ex) 대체로 line of code 가 짧으면 readability 가 높다 판단합니다. 
하지만 재귀를 사용하는 코드는 그렇지 않은 코드에 비해서 그 흐름을 이해하기 어렵고 재귀를 사용하나 사용하지 않냐의 선택을 해야할 때 어떠한 객관적인 잣대로 평가가 이루어지는지 궁금합니다.

**Comment by hjsung809** [comment]
p51
calculateDiscountAmount의 매개변수가 Screening이여서 구현이 감춰지는것도 있는것 같습니다. 필요한 변수만 넘기는것과 어떤 차이가 있을까요?

**Comment by siathus** [comment]
# 1장 객체, 설계
> 비록 현실에서는 수동적인 존재라고 하더라도 일단 객체지향의 세계에 들어오면 모든 것이 능동적이고 자율적인 존재로 바뀐다. 이처럼 능동적이고 자율적인 존재로 소프트웨어 객체를 설계하는 원칙을 가리켜 의인화(anthropomorphism)라고 부른다. (p. 33)

> 따라서 이해하기 쉽고 변경하기 쉬운 코드를 작성하고 싶다면 차라리 한 편의 애니메이션을 만든다고 생각하라. 다른 사람의 코드를 읽고 이해하는 동안에는 애니메이션을 보고 있다고 여러분의 뇌를 속여라. 그렇게 하면 코드 안에서 웃고, 떠들고, 화내는 가방 객체를 만나더라도 당황하지 않을 것이다. (p. 34)

다른 책에서 흔히 객체를 설명하기 위해 예시로 들던 현실 대입법들을 보면 뭔가 설명이 부족하거나 안맞는 듯한 느낌이 있었는데 이 '의인화'라는 설명이 어느 정도 그 간극을 메꿔주는 느낌이 들어서 좋네요.

나머지 부분은 스터디에서 다뤘던 책들에서 나온 내용들이 많아서 편하게 읽었습니다.

**Comment by eagleda** [comment]
> 객체지향으로 향하는 첫걸음은 클래스가 아니라 객체를 바라보는 것에서부터 시작합니다....

객체지향의 사실과 오해에서도 저자가 했던 말을 다시 보게 되네요.



> 여러분이 판매원이라고 하더라도 동일한 문제가 발생한다. 소극장이 여러분의 허락도 없이 매표소에 
보관 중인 티켓과 현금에 마음대로 접근할 수 있기 때문이다. 더 큰 문제는 티켓을 꺼내 관람객의 가
방에 집어넣고 관람객에게서 받은 돈을 매표소에 적립하는 일은 여러분이 아닌 소극장이 수행한다는 
점이다. 여러분은 매표소 안에 가만히 앉아 티켓이 하나씩 사라지고 돈이 저절로 쌓이는 광경을 두 손 
놓고 쳐다볼 수밖에 없는 것이다.

결합도가 높은 프로그래밍이 어떤 문제 상황을 가지는지 쉽게 이해시켜주는 부분이었습니다.

> 동일한 메시지를 전송하지만 실제로 어떤 메서드가 실행될 것인지는 메시지를 수신하는 객체의 클래스가 무엇이냐에 따라 달라진다. 이를 다형성이라고 부른다.

이전의 읽었던 책들에서 나온 내용들이 속속 나와서 잘 기억하고 있는지 되짚어 볼 수 있는 좋은 기회가 될 것 같은 책입니다
예제들을 클래스 다이어그램으로 표현해 보여주니 생 코드로 볼 때보다 객체간 관계 등이 명확하게 보여서 한결 보기 편했던 것 같아요.

**Comment by hyesun03** [comment]
## 1장 객체, 설계

**p.42 TicketSeller 클래스**
좀 사소하긴한데 예전에 이 책을 처음 봤을때도 TicketOffice가 TicketSeller안에 있는게 쫌 부자연스럽다 느꼈습니다. 매표소안에 직원이 여러명 있을거라 생각을 해서 그런거같은데, 직원의 정보(근무지?)를 나타내려고 그런건가~하고 생각했어요.

**p.46 변경에 취약한 코드**
일을 하다보니 대부분의 개발자들은 변경에 취약하게 짜려고 그런게 아니라, 각자 마음속에 생각하고있는 미래에 일어날 변경에 대한 범위가 다르다고 느꼈습니다. 그 당시에는 '이만하면 나쁘지않겠다'고 생각했던게 시간이 지나고 스펙이 바뀌면서 아니게 되는 경우들이 많은듯합니다. 
리소스(시간, 인력)는 제한되어있는데 '미래에 생길 변경사항을 예상'하는것은 불가능하기 때문에, 미래에 어떤 변경이 일어날지 예측하는 것을 멈추고 현재에 최선인 것을 고민하는게 맞지않을까?라고 요즘 생각합니다. '변경에 취약한 코드'를 피하자고 한 설계가 진짜 괜찮았는지 아닌지는 내가 아닌 타인이 평가하는 것이며 정량적인 측정방법은 사실상 없기에......

## 2장 객체지향 프로그래밍
Java는 언어적으로 모호함 때문에 다중상속을 언어차원에서 지원하지 않는데, 문득 다중상속을 지원하는 언어는 여러 부모들에 동일한 메서드가 있을때 어떻게 구분하는지~ 다이아몬드 상속문제 등 다중상속 관련해서 찾아보았습니다.

Python은 상속 그래프를 특정순서(MRO)에 따라 조회하고 첫번째로 선언된것이 있으면 나머지 슈퍼클래스들을 덮어쓰는 방식이고,
C++은 가상 상속으로 아예 할머니(부모 윗세대)를 2개로 만듭니다 ㅋㅋ 
https://ansohxxn.github.io/cpp/chapter12-8/

하지만 Python 이든 C++이든 언어적으로 가능은 한데, 다중상속을 쓰는 것 자체를 '지양'한다고 하네요.



## 기타
* 개인적으로는 Audience에 대한 로직, Bag 에 대한 로직등이 객체 안에 있는게 계속 신경 쓰였습니다. Audience, Bag 내에 있는 로직은 별도의 서비스로 밖에 빼야할거같은데.. 책에서 말하고자 하는 바 정도 이해하고 넘겼습니다.

* 책 전반적으로 같은말을 비슷하게 여러번 서술을 하고 있는데, 예전에는 '왜 이렇게까지 비슷한 말을 여러번 하는거지?' 싶었지만 요즘은 일하다보면 생각이상으로 각자 이해하고 있는 개념이 달라서 오해가 생기는 경우가 꽤 있는것 같아요. 요즘은 어떤 개념이나 스펙을 잘 '정의'하는게 참 중요하다고 느낍니다 ㅎㅎ

**Comment by Y0ngjun** [comment]
### 이 책의 대상 독자

> 이 책은 객체, 클래스, 메서드와 같이 객체지향 프로그래밍에서 사용되는 다양한 용어에 익숙하고, 하나 이
상의 객체지향 프로그래밍 언어를 능숙하게 다룰 수 있으며, 실무 프로젝트에서 충분한 프로그래밍 경험을 
쌓은 분들을 대상으로 한다. 다시 한번 강조한다. 이 책은 객체지향 패러다임에 어느 정도 익숙하고, 프로그
래밍 언어를 능숙하게 다룰 수 있으며, 실무 경험이 풍부한 독자들이 읽을 것이라고 생각하고 쓰여졌다

처음에 쫄았던 부분입니다.  저는 셋 중 하나도 해당되는 사람이 아니었기에...


### 책의 목적

> 소프트웨어 유지보수의 경우에는 그 격차가 더 심하다. 실무에서는 다양한 규모의 소프트웨어를 성공
적으로 유지보수하고 있지만 소프트웨어 유지보수와 관련된 효과적인 이론이 발표된 적은 거의 없다.
심지어 이론은 소프트웨어 유지보수에 전혀 관심이 없는 것처럼 보이기까지 한다. 소프트웨어 생명주
기 동안 유지보수가 차지하는 비중을 감안해 볼 때 현재의 상황은 매우 실망스러운 수준이라고 할 수
있다. 결론적으로 소프트웨어 설계와 유지보수에 중점을 두려면 이론이 아닌 실무에 초점을 맞추는 것
이 효과적이다.
이 책은 훌륭한 객체지향 프로그램을 설계하고 유지보수하는 데 필요한 원칙과 기법을 설명하기 위해
쓰여진 책이다.

책의 목적을 가장 알 수 있는 부분입니다.

### 개념

>  패러다임은 ‘한 시대의 사회 전체가 공유하는 이론이나 방법, 문제의식 등의 체계'를 의미한다.
의존성(dependency)  어떤 객체가 변경될 때 그 객체에게 의존하는 다른 객체도 함께 변경될 수 있다
결합도(coupling) 객체 사이의 의존성의 정도
캡슐화(encapsulation) 개념적이나 물리적으로 객체 내부의 세부적인 사항을 감추는 것
의인화(anthropomorphism) 능동적이고 자율적인 존재로 소프트웨어 객체를 설계하는 원칙

의외로 간단한 개념 설명은 되어있어 감사하며 읽었던 부분입니다.

### 감상
객체지향에 대해서 두루뭉술하게만 알고 있었는데 객체지향에 대해서 잘 설명해주는 책인것 같아요

**Comment by az0t0** [comment]
## 1장
> 객체지향 설계에서는 독재자가 존재하지 않고 각 객체에 책임이 적절하게 분배된다. 따라서 각 객체는 자신을 스스로 책임진다. 객체지향 애플리케이션은 스스로 책임을 수행하는 자율적인 객체들의 공동체를 구성함으로써 완성된다.
(중략)
여러분의 코드에서 데이터와 데이터를 사용하는 프로세스가 별도의 객체에 위치하고 있다면 절차적 프로그래밍 방식을 따르고 있을 확률이 높다. 데이터와 데이터를 사용하는 프로세스가 동일한 객체 안에 위치한다면 객체지향 프로그래밍 방식을 따르고 있을 확률이 높다.
_P. 28_ 

절차지향 프로그래밍으로 작성된 코드를 객체지향 프로그래밍으로 바꾸는 과정을 설명하면서, 첫 코드도 나름 잘 짰다고 생각했는데 역시 제 실력이 모자랐던거였군요... ㅋㅋㅋ 앞으로 배울 점이 많을 것 같다고 느꼈습니다.

## 2장
> 1장에서는 금액을 구현하기 위해 Long 타입을 사용했던 것을 기억하라. Long 타입은 변수의 크기나 연산자의 종류와 관련된 구현 관점의 제약은 표현할 수 있지만 Money 타입처럼 저장하는 값이 금액과 관련돼 있다는 의미를 전달할 수는 없다. 또한 금액과 관련된 로직이 서로 다른 곳에 중복되어 구현되는 것을 막을 수 없다. 객체지향의 장점은 객체를 이용해 도메인의 의미를 풍부하게 표현할 수 있다는 것이다.
_P. 47_

실제로 단순히 기본적인 자료형으로 표현 가능한 변수도 이것이 돈과 관련 있다는 의미 부여를 위해 객체로 캡슐화하는 편인가요?? 정말 이렇게 까지 해야하나 싶어서 솔직하게 질문을 해봅니다.

주로 Java를 써왔기 때문에, 아는 단어들이 많아서 그나마 이해가 쉬웠던거 같습니다. 저자의 말대로 코드를 먼저 제시하고 이론을 설명하니 읽기 편한 것 같네요.

**Comment by wlsh44** [comment]
티켓 발매 예시를 보면서 `Theater`, `TicketSeller`, `TicketOffice`의 의존 관계가 왜
`Theater` -> `TicketOffice` -> `TicketSeller`이 아니라 `Theater` -> `TicketSeller` -> `TicketOffice` 로 구현을 했는지 궁금증이 생겼습니다.
예시가 납득이 안가거나 그런건 아니지만, 뭔가 제가 만약에 처음 보고 구현을 했다면 극장 안에 티켓 판매소가 있고, 티켓 판매소 안에 판매원이 있어서 첫 번째 방법을 먼저 떠올렸을 것 같다는 생각을 했을 것 같아서 두 번째 방식으로 구현을 한 이유가 궁금해졌습니다..!
