### ISSUE TITLE
[GoF 디자인패턴] 5주차 ~ 5.3 인터프리터

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#12]

**Comment by hyesun03** [comment]
# Chain of Responsibility
Java 실 예제 찾아보면 아래의 2개가 많이 나오네요.
* [java.util.logging.Logger#log()](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/util/logging/Logger.java)
* javax.servlet.Filter#doFilter()

그리고 java exception 핸들링이 생각나서 찾아봤는데 아래의 두 글을 찾았어요.
- [stackoverflow](https://stackoverflow.com/questions/15446351/is-javas-exception-handling-mechanism-an-example-of-the-chain-of-responsibility)
- [quora](https://www.quora.com/In-Java-7-exception-is-handling-done-by-chain-of-responsibility-patterns)

stackoverflow의 답변에 달린 댓글보면 '개념적으로는 약간 비슷하긴하나 실제 구현은 그렇지 않다'고 적혀져 있는데, 그냥 그렇구나 하고 넘어갔습니다.

**Comment by hyesun03** [comment]
# Command
## p.316 결과 2번
> Command는 일급 클래스입니다. 다른 객체와 같은 방식으로 조작되고 확장 할 수 있습니다.

여기서 `일급 클래스`는 '일급 객체(first-class object)'가 맞나요? 
## 기타
* [람다식과 함께 커맨드 패턴 사용하기](http://www.hanbit.co.kr/media/channel/view.html?cms_code=CMS9762130221&cate_cd=)

**Comment by genie-youn** [comment]
# Chain of Responsibility

Vue의 Event는 왜 DOM과 다른게 구현했을까.

<img width="976" alt="스크린샷 2019-08-18 오후 3 15 13" src="https://user-images.githubusercontent.com/16642635/63220903-98f18e00-c1cb-11e9-837d-78bcc8aa6486.png">

**Comment by hyesun03** [comment]
* stackoverflow: command 패턴에서 왜 receiver가 있는지
https://stackoverflow.com/questions/16561473/why-do-we-need-a-receiver-class-in-the-command-design-pattern

아래 링크는 위 질문 아래에 달린 답변이고 
https://stackoverflow.com/a/16576972

그 답변에 달린 댓글에서는 "JUnit에 커맨드 패턴 쓰는데, 거기에는 receiver가 존재하지 않음"라고 하네요
> The command pattern is used in JUnit, there is no receiver in this case. We always put our testing code in the concrete command class.
