### ISSUE TITLE
[오브젝트] 23.08.20/2주차 - 챕터 4. 설계 품질과 트레이드오프 ~ 132p

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#120]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by Y0ngjun** [comment]
> 객체지향 패러다임의 관점에서 핵심은 역할(role), 책임(responsibility), 협력(collaboration)이다.
> 객체들이 애플리케이션의 기능을 구현하기 위해 수행하는 상호작용을 협력이라고 한다. 
> 객체가 협력에 참여하기 위해 수행하는 로직은 책임이라고 부른다. 
> 객체들이 협력 안에서 수행하는 책임들이 모여 객체가 수행하는 역할을 구성한다. 

주요하게 다뤄지는 개념들입니다.

> Movie 객체는 어떤 행동을 수행할 수 있어야 할까? 영화라는 단어를 들었을 때 대부분의 사람들은 극장에서 영화를 상영하는 장면을 상상할 것이고 자연스럽게 Movie 객체가 play라는 행동을 수행할 것이라고 생각할 것이다. 그러나 영화 예매 시스템 안의 Movie에는 영화를 상영하기 위한 어떤 코드도 포함돼있지 않다. Movie에 포함된 대부분의 메서드는 요금을 계산하는 행동과 관련된 것이다. 이것은 Movie가영화를 예매하기 위한 협력에 참여하고 있고 그 안에서 요금을 계산하는 책임을 지고 있기 때문이다.
> 
> Movie의 행동을 결정하는 것은 영화 예매를 위한 협력이다. 협력이라는 문맥을 고려하지 않고 Movie의 행동을 결정하는 것은 아무런 의미가 없다. 협력이 존재하기 때문에 객체가 존재하는 것이다. 

이 부분을 읽으며 'Movie는 역시 play아닌가?' 하고 생각했습니다만 이내 문맥을 고려하여 책임을 부여해야 한다는것을 알았습니다.

> 분명히 캡슐화 관점에서 두 번째 설계가 첫 번째 설계보다 향상된 것은 사실이지만 그렇다고 해서 만족스러울 정도는 아니다. 사실 본질적으로는 두 번째 설계 역시 데이터 중심의 설계 방식에 속한다고 할 수 있다. 고통이 조금 경감되기는 했지만 첫 번째 설계에서 발생했던 대부분의 문제는 두 번째 설계에서도 여전히 발생한다. 그 이유를 살펴보자

'훌륭하게 고쳐졌구나'라고 생각했는데 만족스러울 정도가 아니라고 해서 저의 수준을 깨달았습니다.

### 궁금증

각 객체에 적당한 책임을 부여해야 비로소 적절한 응집도, 결합도, 캡슐화와 함께 이상적인 객체지향이 만들어질텐데 객체에 어느정도의 책임을 부여하는것이 적절한지 그것을 어떻게 판별해야 하는지는 아직 잘 모르겠습니다.

책을 보면 마치 책임중심적 설계가 데이터중심적 설계보다 모든면에서 우월하고 뛰어난 완벽한 상위호환인것처럼만 보입니다. 우리가 알지못하는 데이터 중심적 설계에는 어떤 상대적 장점이 있을지 궁금합니다.

**Comment by lallaheeee** [comment]
## 03. 역할, 책임, 협력

```
이처럼 협력 안에서 역할이라는 추상화를 이용하면 기존 코드를 수정하지 않고도 새로운 행동을 추가할 수 있다
(94p)
```
끊임없는 분기를..낳지 않으려면.. 



## 04. 설계 품질과 트레이드 오프
```
- 설계는 변경을 위해 존재하고 ~
(97p)

```
변경이 어려운 이유는 설계가 없었기 때문이었다..당연함..  


```
변경될 수 있는 어떤 것이라도 캡슐화해야 한다.
유지보수성이 목표다. 여기서 유지보수성이란 두려움 없이, 주저함 없이, 저항감 없이 코드를 변경할 수 있는 능력을 말한다.
(109p)
```
코드 변경이 두렵고 주저할 때가 많어서 공감이 가네요.

```
데이터 중심의 설계를 시작할 때 던졌던 첫 번째 질문은 "이 객체가 포함해야 하는 데이터가 무엇인가?"다.
```
여기서 객체를 API로 바꾸면 화면을 보고 API를 합의할 때 첫번째로 하는 질문인데요.
결국 그 API 데이터를 가지고 프론트에서 화면을 그리게 되는 건데, 이런 경우 늘 데이터 중심의 설계로 흘러갈 수 밖에 없지 않나싶어요


느낌점 
- 데이터 중심의 영화 예매 시스템에서 `ReservationAgency` 평소에 짜는 코드와 닮아있어 불편했어요 ㅎㅎ 이책 정말 명작이네요..

- 데이터 중심 설계에서 처음 보는 레포에서 문맥을 빨리 파악할 수 있는 방법이 있을까요?

- 일독했을 때보다 어느정도 실무를 하고 나서 보니까 더 유익한 거 같아요.

**Comment by hjsung809** [comment]
p118
내부를 노골적으로 드러낸 Rectangle은 객체가 아니라 자료구조의 성격을 가지는 갓 같습니다.
추상화된 메서드를 노출 시켜야 객체가 될 수 있다고 클린 아키텍처? 에서 본것 같습니다.
p 119
'자신의 크기를 Rectangle 스스로 증가시키도록 책임을 이동~'
책에서 말하는 책임이 추상화를 말하는 것 같은 느낌이 들었습니다

**Comment by genie-youn** [comment]
# 3장 역할, 책임, 협력

> 대부분의 경우에 어떤 것이 역할이고 어떤 것이 객체인지가 또렷하게 드러나지는 않을 것이다. 특히나 명확한 기준을 세우기 어렵고 정보가 부족한 설계 초반에는 결정을 내리기가 더욱 어려울 것이다. 도메인 모델 안에는 개념과 객체와 역할이 어지럽게 뒤섞여 있으며 이것은 사람들이 세계를 바라보는 일반적인 관점이다. 사람들은 세상을 이해할 때 무의식적으로 개념, 객체, 역할을 뒤섞는다. 도메인 모델은 불완전한 사람들이 세상을 바라보는 모델에 기반하기 때문에 그 역시 동일한 불완전성을 가질 수밖에 없다.
이에 대한 개인적인 견해는 설계 초반에는 적절한 책임과 협력의 큰 그림을 탐색하는 것이 가장 중요한 목표여야 하고 역할과 객체를 명확하게 구분하는 것은 그렇게 중요하지는 않는다는 것이다. 따라서 애매하다면 단순하게 객체로 시작하고 반복적으로 책임과 협력을 정제해가면서 필요한 순간에 객체로부터 역할을 분리해내는 것이 가장 좋은 방법이다. 
.. 중략
처음에 특정 시나리오에 대한 협력을 구상할 때는 아마도 도메인 모델에 있는 개념들을 후보로 선택해 직접 책임을 할당할 것이다. 다양한 시나리오를 설계에 옮기면서 협력을 지속적으로 정제하다 보면 두 협력이 거의 유사한 구조를 보인다는 것을 발견하게 될 것이다. 이 경우 두협력을 하나로 합치면서 두객체를 포괄할 수 있는 역할을 고려해서 객체를 역할로 대체할 수 있다,
(91p)
> 

코드를 계속 깎아야 하는 이유이다. 진척이 없으면 우선 코드를 작성해야하는 이유이기도 하다. 잘 모르겠으면 우선 작성한다. 서비스를 운영하고 도메인에 대한 이해도가 높아지기 시작하면 “도약”의 시점이 오더라. 그 때 잘 갖추어진 테스트코드를 기반으로 리팩터링 해나가면 된다.

감상: 이러한 행위들이.. (유스케이스로부터 첫번째 메세지를 식별해내고 (책에서 이야기하는 시스템이 사용자에게 제공해야 하는 기능인 시스템의 책임) 더 작은 책임으로 나누고 적절한 객체를 찾아 할당하고..) 아직은 너무 고통스럽고 어렵다. 답은 무의식적 지식에 이르기 위한 훈련뿐이겠지.

**Comment by hyesun03** [comment]
## 03. 역할, 책임, 협력

### 90쪽
다른 곳은 쭉쭉 읽어 나갔는데 파란색으로 표기된 문단은 쉽게 못읽었습니다(ㅜㅜ)
* `동일한 종류의 객체가 하나의 역할을 항상 수행한다면 둘(객체, 역할)은 동일한 것이다.`
    * 여기서 말하는 `동일한 종류`가 무엇을 말하는건지 잘 모르겠습니다..
* `하나 이상의 객체가 동일한 책임을 수행할 수 있다면 역할은 서로 다른 방법으로 실행할 수 있는 책임의 집합이 된다.`
    * 이 문장은 88쪽에 있는 그림을 말하는게 맞겠죠?  


## 04. 설계 품질과 트레이드 오프
### 99쪽
**데이터를 준비하자** 쯤 부터 데이터 중심의 설계에 대해 이야기를 하는데, 평소에 일할때 데이터 중심으로 일하는 듯 해서 쫌 찔립니다 ㅋㅋ... 객체지향과는 조금 맥락이 다른것 같기도하고 최근에 클린아키텍처 관련 책을 보다보니 `웹-도메인-영속성` 이렇게 구성되는 계층형 아키텍처 자체가 데이터베이스 주도로 설계를 하게끔 유도한다는 말이 생각났습니다. 웹은 도메인 계층에 의존하고, 도메인 계층은 영속성 계층에 의존하기 때문에 의존성의 방향에 따라 사고가 자연스럽게 따라 가서, 비즈니스 로직을 먼저 생각하는게 아니라 테이블 설계등을 먼저 고민을 하게 된다고... 사실 일할때 습관처럼 테이블 추가가 필요해보이는데 어떤것을 추가할지, 어디에 저장해야할지 등..을 생각한 뒤 로직을 생각하게 되더라구요. 의식적으로 노력해야겠다는 생각이 듭니다ㅜ 

## 108쪽
거의 클래스 수준에서의 설명만 있는듯 해서 추가하자면, 패키지 내부에서만 활용되는 클래스면 패키지 외부에서 접근을 막기위해 package-private(default) 접근 수준으로 경계를 짓고 불필요한 의존(접근)을 막는 식으로도 캡슐화를 지킬 수 있습니다. 책에 있는 대로 `캡슐화란 어떤 것을 숨긴다는 것을 의미(109쪽 파란색 문단)` 하니까요.

**Comment by pawful-code** [comment]
p128

>다시한번 강조하지만 캡슐화란 변할 수 있는 어떤 것이라도 감추는 것이다.

이를 통해 객체간에 전달 받을 메시지 규격만 정의해서 하나의 소프트웨어를 만드는데 작게는 여러 개발자들이 여러 회사가 참여할 수 있다는 생각이 들었다.

**Comment by siathus** [comment]
## 3. 역할, 책임, 협력
### 협력
> 어떤 객체도 섬이 아니다. 애플리케이션 안에 어떤 객체가 필요하다면 그 이유는 단 하나여야 한다. 그 객체가 어떤 협력에 참여하고 있기 때문이다.
### 책임
> 여기서 중요한 사실은 책임의 관점에서 '아는 것'과 '하는 것'이 밀접하게 연관돼 있다는 점이다. 객체는 자신이 맡은 책임을 수행하는 데 필요한 정보를 알고 있을 책임이 있다. 또한 객체는 자신이 할 수 없는 작업을 도와줄 객체를 알고 있을 책임이 있다. 어떤 책임을 수행하기 위해서는 그 책임을 수행하는 데 필요한 정보도 함께 알아야 할 책임이 있는 것이다. 책임은 객체지향 설계의 핵심이다. 사실 협력이 중요한 이유는 객체에게 할당할 책임을 결정할 수 있는 문맥을 제공하기 때문이다.

> 객체가 협력에 적합한지를 결정하는 것은 그 객체의 상태가 아닌 행동이다. (중략) 상태는 단지 객체가 행동을 정상적으로 수행하기 위해 필요한 재료일 뿐이다.

### 역할
> 설계 초반에는 적절한 책임과 협력의 큰 그림을 탐색하는 것이 가장 중요한 목표여야 하고, 역할과 객체를 명확하게 구분하는 것은 그렇게 중요하지 않다.

> 배우가 여러 배역을 연기할 수 있는 것처럼 객체 역시 여러 협력에 참여하며 다양한 역할을 수행할 수 있다. 객체는 여러 역할을 가질 수 있지만 특정 협력 안에서는 일시적으로 오직 하나의 역할만이 보여진다는 점에 주의하라.

## 4. 설계 품질과 트레이드오프
### 설계 트레이드오프
> 객체지향의 관점에서 응집도는 객체 또는 클래스에 얼마나 관련 높은 책임들을 할당했는지를 나타낸다. 객체지향의 관점에서 결합도는 객체 또는 클래스가 협력에 필요한 적절한 수준의 관계만을 유지하고 있는지를 나타낸다.

--- 

다음 장부터 어떻게 개선하는지 보여주겠지만, `isDiscountable()` 메소드의 예를 포함해 4장까지 읽고 나서는 '이 모든걸 고려할 수 있는 완벽한 캡슐화라는게 존재하기나 할까?'라는 생각이 들 정도로 기준이 엄격하네요. 그만큼 캡슐화가 중요하다는 뜻이면서 데이터 중심의 설계에 근본적인 문제가 있다는 것을 의미하는 것이라 생각합니다.

**Comment by wise1ight** [comment]
# 03 역할, 책임, 협력
- 역할
객체가 어떤 특정한 협력 안에서 수행하는 책임의 집합

- 책임
객체가 협력에 참여하기 위해 수행하는 로직(행동)
객체에 의해 정의되는 응집도 있는 행위의 집합으로, 객체가 유지해야 하는 정보와 수행할 수 있는 행동에 대해 개략적으로 서술한 문장(doing, knowing)
협력 안에서 객체에게 할당한 책임이 외부의 인터페이스와 내부의 속성을 결정한다.
객체는 자신이 맡은 책임을 수행하는 데 필요한 정보를 알고 있을 책임이 있다.
객체는 자신이 할 수 없는 작업을 도와줄 객체를 알고 있을 책임이 있다.

- 협력
객체들이 애플리케이션의 기능을 구현하기 위해 수행하는 상호작용
메시지 전송, 메서드 실행해 요청에 응답
객체의 행동을 결정하는 것은 객체가 참여하고 있는 협력.
객체가 참여하는 협력이 객체를 구성하는 행동과 상태 모두를 경정, 협력은 객체를 설계하는 데 필요한 일종의 문맥을 제공한다.

- 책임 주도 설계
책임을 찾고 책임을 수행할 적절한 객체를 찾아 책임을 할당하는 방식으로 협력을 설계하는 방법

메시지가 객체를 선택하게 해야 하는 두 가지 중요한 이유
1. 최소한의 인터페이스
2. 충분히 추상적인 인터페이스

# 04 설계 품질과 트레이드오프
1. 객체지향 설계의 핵심이 책임
2. 책임을 할당하는 작업이 응집도와 결합도 같은 설계 품질과 깊이 연관

# 질문
1. 객체들을 설계하기 위해서 협업에서 쓰는 방법 또는 과정들이 궁금합니다.
책에서는 예시로 CRC 카드가 소개되어 있는데 어떠한 다이어그램을 그린다거나, 도메인에 빠삭한 다른 누군가와 같이 일하는 그런 경우가 궁금해지네요.

3. 83p에서 "어떤 경우에는 응집도와 결합도의 관점에서 정보 전문가가 아닌 다른 객체에게 책임을 할당하는 것이 더 적절한 경우도 있다." 라고 되어있는데, 구체적으로 어떤 경우일지 궁금합니다.

4. 92p의 "다양한 시나리오를 탐색하고 유사한 협력들을 단순화하고 합치다 보면 자연스럽게 역할이 그 모습을 드러낼 것이다."라는데
시간에 쫓기거나 해당 도메인에 대한 지식이 뒷받침이 안되서 만족할만한 수준까지 안될경우에는 이 문제를 어떻게 해소하면 좋을까요? 

# 감상
캡슐화가 설계 품질을 많이 좌우하는 것을 느꼈고, 캡슐화를 해치는 경우들을 책을 통해 확인해봤는데
데이터 중심의 관점과 책임 중심의 관점 각각의 과정과 코드들을 따라해봐야 더 와닿을 내용 같아서 해보고싶었지만
이번주는 바빠서 못해본게 아쉬웠습니다.
그리고 88p의
> 이 대표자를 협력 안에서 두 종류의 객체를 교대로 바꿔 끼울 수 있는 일종의 슬롯으로 생각할 수 있다.
라는 표현이 동일한 책임을 수행할 수 있는, 해당 메시지에 응답할 수 있는 대표자라는 것을 와닿게 해주는 표현 같아서 인상깊었습니다.

**Comment by az0t0** [comment]
## 캡슐화 위반
> 만약 DiscountCondition의 속성을 변경해야 한다면 어떻게 될까? 아마도 두 isDiscountable 메서드의 파라미터를 수정하고 해당 메서드를 사용하는 모든 클라이언트도 함께 수정해야 할 것이다. 내부 구현의 변경이 외부로 퍼져나가는 파급 효과(ripple effect)는 캡슐화가 부족하다는 명백한 증거다.
 P. 126

> 캡슐화란 변할 수 있는 어떤 것이라도 감추는 것이다. 그것이 속성의 타입이건, 할인 정책의 종류건 상관 없이 내부 구현의 변경으로 인해 외부의 객체가 영향을 받는다면 캡슐화를 위반한 것이다.
P. 128

클라이언트 개발자가 클래스의 변수에 접근한다고 끝이 아니라, 클래스를 수정할 때 다른 곳까지 수정사항이 생기지 않도록 코드를 작성하는 것 또한 캡슐화의 일부였네요. 분명 제 눈에는 잘 캡슐화 되어있는 것 처럼 보였지만 클래스의 `public`한 메서드도 경우에 따라 감춰야한다고 설명하기도 하고... 정말 세세하게 하나씩 따져야하는 것 같습니다.

## 데이터 중심 설계
> 비록 데이터를 처리하는 작업과 데이터를 같은 객체 안에 두더라도 데이터에 초점이 맞춰져 있다면 만족스러운 캡슐화를 얻기 어렵다. 데이터를 먼저 결정하고 데이터를 처리하는 데 필요한 오퍼레이션을 나중에 결정하는 방식은 데이터에 관한 지식이 객체의 인터페이스에 고스란히 드러나게 된다.
P. 132

데이터를 처리해야할 때 그냥 데이터를 클래스로 묶고 적절히 데이터 필드와 데이터 처리 메서드를 만들어서, 객체를 사용하는 부분에 코드를 끼워맞췄는데 이걸 정확히 지적해서 많이 찔리네요... 지금 진행 중인 게임 프로젝트에서도 서버와 클라이언트가 주고받은 데이터를 처리하는 부분이 딱 이런 상태인데 큰일...

**Comment by usageness** [comment]
## 역할, 책임, 협력
p.91
> 대부분의 경우에 어떤 것이 역할이고 어떤 것이 객체인지가 또렷하게 드러나지는 않을 것이다. 특히나
> 명확한 기준을 세우기 어렵고 정보가 부족한 설계 초반에는 결정을 내리기가 더욱 어려울 것이다. 

첫 설계 후 구현을 진행하면 설계가 변경되어야 한다는 걸 깨닫는 순간이 늘상 오는 것 같아요. 특히 기획이 불명확하고 자고 일어나면 정책이 바뀌는 프로젝트를 진행하면서는 어느 순간 설계에 대한 고민을 포기하는 경우도 있었습니다.

작은 단위의 프로젝트에서도 이런 일이 비일비재한데, 복잡한 도메인이 얽히고 섥혀있는 서비스에서는 특히 더 어려울것 같네요 😥



## 설계 품질과 트레이드오프
p.132
> 객체가 내부에 어떤 상태를 가지고 그 상태를 어떻게 관리하는가는 부가적인 문제다. 중요한 것은 객체가 다른 객체와 협력하는 방법이다.

데이터 중심 설계는 결국 실제 세계를 기반으로 설계를 한다는 느낌이 들었습니다. 왜 객체지향이라는 패러다임이 실세계를 단순히 옮기는 것이라고 할 수 없는지 잘 보여준 섹션이었다고 생각해요.

그럼에도 개인적으로는 데이터 중심 설계 방식이 마냥 나쁘지는 않은 것 같습니다. 결국 설계라는 그림도 기획 단계 이후 실제 구현에 들어가면서 더 구체적으로 보이기 마련인데, 처음부터 완벽하게 그림을 그리고, 그 그림을 따라가는 경우가 그렇게 많지는 않을것 같아요. (어쩌면 불가능할수도...)

그런 면에서는 데이터 중심 설계가 최고의 구조를 만드는 방법은 아닐지라도, 책에서 말하는 '적절한' 범위로 향하는데에는 꽤 괜찮은 접근법 같습니다. 우선 데이터를 중심으로 뼈대를 잡아보고, 이걸 기반으로 계속해서 수정해가며 개선해나가면 되지 않을까요~ ㅎㅎ
