### ISSUE TITLE
[오브젝트] 23.08.27/3주차 - 챕터 5. 책임 할당하기 ~ 172p

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#121]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by lallaheeee** [comment]
```
함께 초기화되는 속성을 기준으로 코드를 분리해야한다. 
- 152p 
```

**Comment by hyesun03** [comment]
## 05. 책임 할당하기
### p.149
Movie 클래스 안에 돈 계산하는 로직이 있는것을 보고 약간 불편한 느낌을 받았는데요, 도메인 객체안에 (단순 validation 같은 간단한거 말고) 로직을 넣는게 권장되는 방법일까요? 할인과 관련된 별도의 유스케이스로 뽑고 그 유스케이스 서비스 클래스에 로직을 옮기는게 좀 더 좋지않을까.. 하는 생각이 들어서 좀 찾아봤습니다. 

객체지향을 설명(모든 객체는 자율적이어야 한다..)하기 위해 그런것인지 권장되지 않은 방법으로 일을 하고 있던건지 이 책을 다시 읽을수록 의문이 드네요 ㅜㅜ

빈약한 도메인 모델, 풍부한 도메인 모델은 취향의 차이 정도로 인식하고 있었는데, 좀 검색을 하다보니 제가 하는 이런 생각이 전형적인 안티패턴이래서 좀 놀랬습니다... ㅋㅋㅋㅋㅜㅜㅜㅜ 제가 DDD책을 잡고 제대로 본적이 없다보니 이제 진짜 잡고 읽어야 되는 시점인것 같네요.
https://m.blog.naver.com/muchine98/220304821784


### 기타
이 5장 읽으면서 팩토리 패턴이 떠올랐습니다. 그런 의미로 과거에 제가 정리했던 글 하나 공유합니다 홍홍..
https://hyesun03.github.io/2019/07/31/gof-design-pattern-02-factory/

**Comment by usageness** [comment]
### **책임 할당을 위한 설계 과정** 
- **도메인 개념에서 출발하기**
  - 단지 출발점이 필요할뿐, 지금 시점에서 완벽한 설계가 필요하지 않다
  - 너무 많은 시간을 들이지 말고 빠르게 설계와 구현을 진행하자
- **정보 전문가에게 책임을 할당하기**
  - 메시지를 결정하고, 적합한 객체를 선택하기
- **높은 응집도, 낮은 결합도**
  - 책임과 협력의 품질을 검토할때 사용할 수 있는 평가 기준
- **창조자에게 객체 생성 책임을 할당하기**
  - 생성될 객체를 잘 알고 있는 객체에게 책임을 부여하기

**Comment by pianoop** [comment]
### 책임 주도 설계
- 책임을 결정한 후에 책임을 수행할 객체를 결정  
- 객체들의 책임이 어느 정도 정리가 될 때까진 내부 상태에 관심을 가지지 말자.  
---

캡슐화, 결합도, 응집도 이 셋 중 응집도가 잘 안 와닿았었는데 이번 5챕터에서 보여준 메서드의 응집도 예시와 그 메서드들을 담은 클래스의 응집도 또한 생각해야 한다는 부분에서 이해가 되었습니다.

**Comment by hjsung809** [comment]
p139
객체가 정보를 알고 있다고 해서 그 정보를 저장하고 있을 필요는 없다. 정보를 제공할 수 있는 다른객체를 알고 있거나 필요한 정보를 계산해서 제공할 수도있다.
-> 데이터 중심개발과 객체지향의 큰 차이점인것 같네요. 자꾸만 데이터가 어디있고 어디에 저장해서 어떻게 가져다 쓸지만 생각하게 되는것 같습니다. 그런데 결국엔 어디선가 저장이 필요하고 객체로 로딩해서 써야할 텐데 그부분이 많이 헷갈리네요.

p158
타입분기인 if else가 한두번 있을때는 그냥 쓰고 그 이상이 있을때는 각 타입별 if else를  객체로 묶어 다형성으로 구성하면 좋을것 같습니다.
타입 분기가 많이 나타내는데 그대로 두면 코드가    굉장히 빠르게 복잡해지는 것 같습니다

**Comment by pawful-code** [comment]
p171
클래스는 오직 하나의 작업만 수행하고 하나의 변경 이유만 가지는 작고 명확하고 응집도가 높은 메서드들로 구성돼 있다.

리팩토링의 목표가 한줄에 잘 담겨있는거 같습니다.

**Comment by az0t0** [comment]
>> 응집도가 낮다는 것은 서 로 연관성이 없는 기능이나 데이터가 하나의 클래스 안에 뭉쳐져 있다는 것을 의미한다. 따라서 낮은 응집도가 초래하는 문제를 해결하기 위해서는 변경의 이유에 따라 클래스를 분리해야 한다. (중략) 
응집도가 높은 클래스는 인스턴스를 생성할 때 모든 속성을 함께 초기화한다. 반면 응집도 가 낮은 클래스는 객체의 속성 중 일부만 초기화하고 일부는 초기화되지 않은 상태로 남겨진다. (중략)
모든 메서드가 객체의 모든 속성을 사용한다면 클래스의 응집도는 높다고 볼 수 있다. 반면 메서드들이 사용하는 속성에 따라 그룹이 나뉜다면 클래스의 응집도가 낮다고 볼 수 있다.
_P.152_

클래스를 응집도 높게 적절히 구성하는 방법과, 이 내용의 뒤에서 응집도 낮은 클래스의 문제점을 제시했습니다… 클래스가 제 역할을 담당하게 만드려고 너무 많은 내용을 넣어서 수정이 곤란해지기 전에, 미리 싹을 잘라놓으라는 이야기였네요. 이렇게 응집도에 대해 판단할 수 있는 여러 가지 징후(?)를 똑바르게 제시해줘서 좋았습니다…
