### ISSUE TITLE
[오브젝트] 23.09.10/4주차 - 챕터 6. 메시지와 인터페이스 ~ 214p

### ISSUE THREAD

**Issue by KangJiJi** [TeamCrazyPerformance/http#122]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by Y0ngjun** [comment]
6-2장
개발 경험이 부족해서 항상 이름은 그냥 그때 적절해 보이는 것으로 대충 정하곤 했는데 정확한 이름을 짓는 것도 중요하다는 것을 알았습니다.
다른 분들은 이름을 정할 때 나름의 규칙이 있는지 궁금하네요.

**Comment by hyesun03** [comment]
p. 208 맨 마지막 문장 `버그를 찾기 어려웠던 이유는 isSatisfied 가 명령과 쿼리의 두 가지 역할을 동시에 수행하고 있었기 때문이다..`
이거는 명령-쿼리 분리가 안된것도 문제지만 메서드 명을 보고 무엇을 하는지 전혀 나타내지 않아서 그런것 같다는 생각도 들었습니다.

**Comment by genie-youn** [comment]
> 먼저 도메인의 중요한 두 가지 용어인 "이벤트"와 "반복 일정"에 관해 살펴보자.

항상 설계보다 분석이 먼저다. 유비쿼터스 랭귀지를 명확하게 하는것이 최우선이다.

**Comment by wlsh44** [comment]
> 그러므로 수행 방법에 관해서는 언급하지 말고 결과와 목적만을 포함하도록 클래스와 오퍼레이션의 이름을 부여하라. 이렇게 하면 클라이언트 개발자가 내부를 이해해야 할 필요성이 줄어든다.
...
하나의 구현을 가진 메시지의 이름을 일반화하도록 도와주는 간단한 훈련 방법을 소개하겠다. 매우 다른 두 번 째 구현을 상상하라. 그러고는 해당 메서드에 동일한 이름을 붙인다고 상상해보라. 그렇게 하면 아마도 그 순 간에 여러분이 할 수 있는 한 가장 추상적인 이름을 메서드에 붙일 것이다(190p)

이름 잘 짓고 싶어요..

> 디미터 법칙은 하나의 도트(.)를 강제하는 규칙이 아니다.
따라서 대부분의 사람들은 자바 8의 IntStream을 사용한 아래의 코드가 기차 충돌을 초래하기 때문에 디미터 법칙을 위반한다고 생각할 것이다.(198p)

클린코드 읽을 때 stream이 디미터 법칙을 위반한건지 궁금해서 찾아봤었는데 여기에도 나오네요

**Comment by pianoop** [comment]
> 객체의 상태를 변경하는 명령은 반환값을 가질 수 없다.
객체의 정보를 반환하는 쿼리는 상태를 변경할 수 없다. (203p)  

명령-쿼리 분리 원칙 부분을 읽으며 예전에 한 메서드에 상태도 변경하고 정보도 반환하는 코드를 마구 남발하다 책의 내용처럼 예외 케이스에서 에러가 나와서 고생했던 기억이 떠올랐습니다. 당시에는 해당 에러가 뜨는 케이스만 if문으로 예외처리 하고 넘겼었는데 이제보니 구조 자체가 잘못됐던 거였네요. :cry:

**Comment by wise1ight** [comment]
183p의 디미터 법칙 더 쉽게 말하면 타고 타고 하지 말란건가요?

**Comment by KangJiJi** [comment]
187p
```
내부의 상태를 묻는 오퍼레이션을 인터페이스에 포함시키고 있다면 더 나
은 방법은 없는지 고민해 보라. 내부의 상태를 이용해 어떤 결정을 내리는 로직이 객체 외부에 존재하
는가? 그렇다면 해당 객체가 책임져야 하는 어떤 행동이 객체 외부로 누수된 것이다. 
```
중요!

**Comment by hjsung809** [comment]
p 190
메시지 이름을 일반화 하도록 도와주는 간단한 훈련법이 두번째 구현을 상상하는 거라고 했는데, 이게 일종의 추측에 의한 개발이라고 할수도 있을것 같습니다. 변경을 예상하는 거라고 말하면 좋게 들리고 추측에 의한 오버 엔지니어링이라고 하면 안좋게 들리네요 ㅎㅎ

p. 202
디미터 법칙 위반 여부를 따질때 대상이 객체인지 자료구조인지 생각해보는게 좋은것 같습니다.
자료구조라면 위반이 아니고 객체라면 위반인게 흥미로운것 같습니다. 결국에 추상화, 캡슐화를 위반하지 않으면 되는것 같습니다.

p 206.
명령 쿼리 분리의 예시에서.. 저렇게 짜는 사람이 팀에 있으면 제가 나가던지 쫒아 내던지 할것 같습니다.
명령 API에서 조회 결과를 리턴하는 경우가 많고 네트워크 비용등을 이유를 많이 말하는것 같습니다.

**Comment by az0t0** [comment]
읽을 양이 적었지만 내용이 알차고 정보량이 많아 천천히 읽어야 했던 파트였습니다.

> 메시지(message)는 객체들이 협력하기 위해 사용할 수 있는 유일한 의사소통 수단이다. 한 객체가 다른 객체에게 도움을 요청하는 것을 메시지 전송(message sending) 또는 메시지 패싱(message passing)이라고 부른다. 이때 메시지를 전송하는 객체를메시지 전송자(message sender)라고 부르고 메시지를 수신하는 객체를 메시지 수신자(message receiver)라고 부른다. 클라이언트-서버 모델 관점에서는 메시지 전송자는 클라이언트, 메시지 수신자는 서버라고 부르기도 한다.
_(중략)_ 자바 문법을 표현한 예에서 오퍼레이션명과 인자를 조합한 isSatisfiedBy(screening)이 ‘메시지’이고, 여기에 메시지 수신자인 condition을 추가한 condition.isSatisfiedBy(screening)이 ‘메시지 전송’이다.
_P.177_

여기서 메세지에 대해 설명하기 전까지 `메서드 == 메세지`로 이해하고 있었는데, 메세지의 종류에 따라 호출되는 메서드가 달라질 수 있으니 틀린 생각이었네요. 메세지 전송이라는 행위가 다양한 메서드 호출을 포함한다고 봐도 될까요?

**Comment by lallaheeee** [comment]
지났지만 궁금한 거 
200~202 결합도와 응집도의 충돌의 예제에선
응집도를 높이고 결합도를 낮추는 게 전체적인 관점에서 더 좋은 케이스였는데,
반대로 결합도를 높이고 응집도를 낮추는 게 좋은 케이스가 있을까요? 

구체적인 예시가 생각나지 않으니,
결합도를 낮추는 게 항상 좋은걸까 라고 받아들이게 되는 것 같아서 
다른 예가 궁금해요.
