### ISSUE TITLE
[오브젝트] 23.09.17/5주차 - 챕터 7. 객체 분해 ~ 252p 

### ISSUE THREAD

**Issue by lallaheeee** [TeamCrazyPerformance/http#123]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by hyesun03** [comment]
p.218
객체지향이란 무엇인가? 에 대해서 깔끔하게 말하기 어려운데 이 페이지 마지막 문단이 맘에 들었습니다.
> 프로그래밍 언어의 관점에서 객체지향이란 데이터를 중심으로 데이터 추상화와 프로시저 추상화를 통합한 객체를 이용해 시스템을 분해하는 방법니다. 그리고 이런 객체를 ~~ 클래스를 이용해 시스템을 분해하는 것이다.

p.252 - 타입 계층과 다형성은 협력이라는 문맥 안에서 책임을 수행하는 방법에 관해 고민한 결과물이어야 하며 그 자체가 목적이 되어서는 안 된다.

**Comment by wise1ight** [comment]
240p.
> 모듈의 가장 큰 단점은 인스턴스의 개념을 제공하지 않는다는 점이다. Employees 모듈은 단지 회사에 속한 모든 직원 정보를 가지고 있는 모듈일 뿐이다.

메모리에 관점에서 본다면 모듈은 Static 영역(Data Segment)을 사용하고 인스턴스의 개념은 Heap을 사용한다로 이해할 수 있는걸까요?

**Comment by Y0ngjun** [comment]
> 여기서 강조하고 싶은 것은 하나의 타입처럼 보이는 Employee 내부에는 정규 직원과 아르바이트 직원이라는 두 개의 타입이 공존한다는 것이다. 설계의 관점에서 Employee 타입은 구체적인 직원 타입을 외부에 캡슐화하고 있는 것이다. 윌리엄 쿡은 이처럼 하나의 대표적인 타입이 다수의 세부적인 타입을 감추기 때문에 이를 타입 추상화라고 불렀다. 타입 추상화는 개별 오퍼레이션이 모든 개념적인 타입에 대한 구현을 포괄하도록 함으로써 하나의 물리적인 타입 안에 전체 타입을 감춘다. 따라서 타입 추상화는 오퍼레이션을 기준으로 타입을 통합하는 데이터 추상화 기법이다. (p.246)

좀 헷갈렸는데 이 설명 덕분에 추상화를 좀 더 이해할 수 있었습니다.

> Employee 클래스는 직원의 이름과 기본급을 저장할 인스턴스 변수인 @name과 @basePay를 포함하고, 자식 클래스가 재정의할 수 있도록 calculatePay와 monthlyBasePay 메서드의 시그니처를 정의한다. 자바나 C#에 익숙한 사람들은 Employee 클래스를 추상 클래스로, calculatePay와 monthlyBasePay 메서드를 추상 메서드로 생각해도 무방하다

읽으며 '그럼 추상클래스 같은건가?' 라고 생각했는데, 글쓴이가 그렇게 생각해도 된다고 하니 뭔가 기분이 좋았습니다. ㅋㅋ

**Comment by pianoop** [comment]
>객체가 참여할 협력을 결정하고 협력에 필요한 책임을 수행하기 위해 어떤 객체가 필요한지에 관해 고민...
(중략) ... 그 자체가 목적이 되어서는 안 된다. (252p)

협력, 책임, 역할에 대해 고민하며 책에서 배우는 내용들을 수단으로써 사용할 것을 상기시켜주네요. 앞선 내용들을 포함해서 총 정리해주는 느낌이라 이해가 더 잘 되었습니다.

**Comment by eagleda** [comment]
> 하향식 설계와 관련된 모든 문제의 원인은 결합도다. (p.203)

고등학교 때 아두이노 프로젝트에서 하향식으로 설계하다 센서 변수 하나 추가하려고 코드를 죄다 뒤엎었던 기억이 떠오르네요.

>모듈의 개념을 구현했지만 모듈은 키워드의 지원 여부와 상관없이 적용할 수 있는 논리적인 개념이다....
C++와 C#에서는 네임스페이스(namespace)를 이용해 구현할 수 있다.(p.237)

매일같이 `using namespace std`를 쓰고 문제를 풀었는데
정작 모듈을 구현하기 위해 네임스페이스를 사용하면 된다고 했을 때 "그럴 때 쓰는 거였어?"하고 반응을 했던 걸 보니
제대로 알아 본 적도 없이 사용해오지 않았나..하는 생각이 문득 들었습니다.

**Comment by pawful-code** [comment]
227P

> 버트란드 마이어의 말을 인용하자면 "실제 시스템에 정상 이란 존재하지 않는다" 

쿠버네티스 도커등을 통해 이미 동작하는 프로그램과 연결하는 일이 많은 오늘 날에 더 와 닿는 말인 것 같다

**Comment by lallaheeee** [comment]
- 프로시저라는 단어와 데이터 추상화라는 어휘가 익숙하지 않아서 잘 와닿지 않았는데, 프로시저 추상화를 `**what to do**`로, 데이터 추상화는 `**what to know**`로 바꿔서 읽었더니 조금 더 읽기 수월했던 거 같아요 


```
시스템이나 프로그램 개발자가 이미 완료한 결과에 대한 명확한 아이디어를 가지고 있다면
머릿속에 있는 것을 종이에 서술하기 위해 하향식을 사용할 수 있다. 
이것은 사람들이 하향식 설계나 개발을 할 수 있고, 그렇게 함으로써 성공할 수 있다고 믿게 만드는 이유다. (...)
**하향식 단계가 시작될 때 문제는 이미 해결됐고, 오직 해결돼야만 하는 세부사항만이 존재할 뿐이다** (234p)
```

- 대부분의 기능 개발이 하향식 접근법을 따라가지 않나? 생각했는데, 위의 글을 읽고 왜 그렇게 인지했는지 깨달았어요 ㅋㅋㅋ 어느정도 코드베이스를 파악한 이미 구현된 기능에 기능을 덧붙여서, 하향식 접근법으로 개발을 하고 있던 것뿐.. 더불어 구체적인 루비 코드로 예시를 들어주고, 순서를 고정시키는 등 어떤 문제점을 야기하는지 구체적으로 집어줘서 좋았어요.


```
- 어려운 설계 결정이나 변화할거 같은 설계 결정들의 목록을 사용해 설계를 시작할 것을 권장한다. (235p)
- 기능 분해 = 순차적 탐색, 모듈 분해 = 감춰야할 비밀 선택 (236p)
- 추상 데이터 타입 = 세부 타입을 캡슐화, 클래스 = 세부 타입을 명시적으로 표현
```
- 그냥 메모 


- 리스코프 소프트웨어 역사에 한획을 그었네요 ㅋㅋㅋ SOLID 원칙에서 아무 생각없이 받아들였는데, SW의 추상화 수준을 업그레이드 시켜준 귀인.. (하지만 실무엔 적용 못함) 
- 지난주에 빠져서 6장과 함께 읽었는데 개인적으로 6장보다 읽기 수월했던 거 같아요. 다들 스터디 준비하는데 어느정도 걸리는지 궁금해요.

**Comment by hjsung809** [comment]
p 217
객체 지향을 추구 해야하는 이유중 가장 중요한 이유같습니다. 코드의 재사용성을 높이는 것 보단 잘 이해하기 위해서 필요한것 같습니다.

p 218
프로시저 추상화가 객체지향일줄 알았는데 DB나 C의 프로시저 같은 상태를 가지지 않는 프로시저를 말하는 것 같고
데이터 중심에 프로시저를 추상화 한게 객체지향이라는 말이 정교한것 같아서 좋았습니다.

p 219
하향식 접근법은 한가지 기능을 마치 트리 형태로 프로그램을 구성하는거라면, 객체 지향은 그래프 형태로 나타내서 진입점을 다양화 할 수 있다는 식으로 이해할 수 있을것 같습니다.

p 225
하향식 설계 방식은 이상적이고 이미 완성된 프로그램에 적합하지만 현실에 그런 경우는 별로 없다는 말이 와닿았습니다.
객체 지향으로 구성하고 이해가 안될땐 현재 구현을 하향식 설계 방식처럼 구성해서 바라보면 이해 될때도 있었던것 같습니다.

p 226
'하향식 접근법은 하나의 알고리즘을 구현하거나 배치 처리를 구현하기에는 적합하지만~'
배치를 구성할때는 객체지향으로 구성하지 않고 절차적으로 구성하는게 더 적합하다고 느꼇던적 있었던것 같습니다.

p 230
'하향식 설계 방식은 함수간의 호출순서를 중심으로 구성되고, 객체 지향은 논리적인 관계를 중심으로 설계를 이끌어 나간다.'
하향식 설계방식은 당장에 문제 해결에만 집중하는 느낌이고 객체 지향은 프로그램을 좀더 유기적으로 만드는 느낌인것같습니다.

p 252 
새로운 타입을 빈번하게 추가해야할 때는 객체지향의 클래스 구조가 더 유용하고 새로운 오퍼레이션을 빈번하게 추가해야한다면 추상 데이터 타입이 현명한 판단이다.
->  새로운 타입을 빈번하게 추가해야 하지만, 기본 행위(default method)를 쉽게 정의할 수 있으면 클래스 구조가 좋을 수도 있을것 같습니다.

**Comment by genie-youn** [comment]
어우 이번장을 내용이 너무 어려워서 두번 읽었네요.

216p 인트로가 너무 좋았습니다~ 인지부하에 대한 이야기를 근거를 들어가며 설득력있게 와닿았던것 같아요. 그치만 그 뒤에 프로시저 추상화와 데이터 추상화, 데이터 추상화중에서도 데이터를 중심으로 프로시저를 추상화.. 이런 얘기가 나오면서 살짝 정신이 혼미해졌음

226p 하향식 기능 분해의 문제점 -> 메인 함수와 관련된 부분들이 사실 잘 와닿지 않았다. 이 부분은 대부분 프레임워크가 잘 처리해주고 있고, 결국 개별적인 API 가 하나하나의 정상이라고 볼 수 있는것 아닌가?

235p
> 지금까지 하향식 설계가 가지는 문제점을 살펴봤다. 하향식 분해 방식으로 설계된 소프트웨어는 하나의 함수에 제어가 집중되기 때문에 확장이 어렵다. 하향식 분해는 프로젝트 초기에 설계의 본질적인 측면을 무시하고 사용자 인터페이스 같은 비본질적인 측면에 집중하게 만든다. 과도하게 함수에 집중하게 함으로써 소프트웨어의 중요한 다른 측면인 데이터에 대한 영향도를 파악하기 어렵게 만든다. 또한 하향식 분해를 적용한 설계는 근본적으로 재사용하기 어렵다.

프론트엔드를 개발하면서 빠지기 쉬운 함정중에 하나이지 않을까? 각각의 UI 구성 요소는 y = f(x) 로 동작하는 순수한 함수처럼 보일지는 몰라도 이 UI 구성 요소들을 조율하는 애플리케이션에는 데이터가 존재하기 마련인데 프론트엔드 애플리케이션의 설계에선 부분이 너무 저평가되는것 같다., 이로인해 프론트엔드 애플리케이션의 설계가 도메인 영역과 순수한 UI 구성요소 그리고 이를 묶어주는 Controller 역할의 Container 가 필요해지는 모습이 되는것이 아닌가 싶다.

244p
> 추상 데이터 타입은 사람들이 세상을 바라보는 방식에 좀 더 근접해지도록 추상화 수준을 향상시킨다. 일상 생활에서 Employee라고 말할 때는 상태와 행위를 가지는 독립적인 객체라는 의미가 담겨 있다. 따라서 개별 직원의 인스턴스를 생성할 수 있는 Employee 추상 데이터 타입은 전체 직원을 캡슐화 하는 Employees 모듈보다는 좀 더 개념적으로 사람들의 사고방식에 가깝다.

코드가 도메인을 말하게 한다.

**Comment by wlsh44** [comment]
```ruby
def hourly?(name)
  ...
```
> 웃긴 메서드 이름
Ruby에서는, 메서드 이름이 물음표나 느낌표로 끝날 수 있습니다. 관례에 의하면, 질문에 답하는 메서드는 물음표로 끝납니다. (예를 들어 리시버가 비었을 때 true를 반환하는 Array#empty?) 관례에서 “위험할” 수 있는 메서드는 느낌표로 끝납니다. (예를 들어 exit! 같은 self나 인자를 변경하는 메서드) [출처](https://www.ruby-lang.org/ko/documentation/ruby-from-other-languages/#:~:text=14%3A00%3A00-,%EC%9B%83%EA%B8%B4%20%EB%A9%94%EC%84%9C%EB%93%9C%20%EC%9D%B4%EB%A6%84,-Ruby%EC%97%90%EC%84%9C%EB%8A%94%2C%20%EB%A9%94%EC%84%9C%EB%93%9C)

신기하네요

> 모듈은 서브 프로그램이라기보다는 책임의 할당이다.(235p)
...
모듈이 정보 은닉이라는 개념을 통해 데이터라는 존재를 설계의 중심 요소로 부각시켰다는 것이다. 모듈에 있어서 핵심은 데이터다.
모듈은 감춰야 할 데이터를 결정하고 이 데이터를 조작하는 데 필요한 함수를 결정한다.(239p)

이전에는 책임을 부여하고 그 과정에서 데이터가 결정된다고 했었던 것 같은데 제가 이 부분을 잘못 이해한걸까요?

그리고 srp도 객체보다는 모듈에 초점을 맞추고 있다는 글을 많이 봤는데 객체와 모듈의 책임에 어떤 차이가 있는지 궁금합니다.
