### ISSUE TITLE
[오브젝트] 23.09.24/6주차 - 챕터 8. 의존성 관리하기까지 ~ 281p

### ISSUE THREAD

**Issue by wise1ight** [TeamCrazyPerformance/http#124]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by Y0ngjun** [comment]
> **의존성과 결합도**
일반적으로 의존성과 결합도를 동의어로 사용하지만 사실 두 용어는 서로 다른 관점에서 관계의 특성을 설명하는 용어다. 의존성은 두 요소 사이의 관계 유무를 설명한다. 따라서 의존성의 관점에서는 “의존성이 존재한다” 또는 “의존성이 존재하지 않는다”라고 표현해야 한다. 그에 반해 결합도는 두 요소 사이에 존재하는 의존성의 정도를 상대적으로 표현한다. 따라서 결합도의 관점에서는 “결합도가 강하다” 또는 “결합도가 느슨하다”라고 표현한다.

 저도 책을 읽으며 의존성과 결합도를 그냥 같은 의미로 생각했는데, 두 용어의 차이를 알게되었습니다.

**Comment by lallaheeee** [comment]
```
## 컨텍스트 독립성
구체적인 클래스를 알면 알수록 그 클래스가 사용되는 특정한 문맥에 강하게 결합되기 때문이다.
(...)
컨텍스트에 대한 정보가 적으면 적을수록 더 다양한 컨텍스트에서 재사용될 수 있기 때문이다.
- 260~261p
```

- 결국 사용하는 곳이 많으면 그 친구를 의존하는 곳이 많아진다는 건데, 책에 나온 이야기처럼 특정 문맥에 결합되지 않고 재활용 가능하게 만들어도, 인터페이스 변경이 이루어질 때 변경의 영향도가 커진다고도 해석할 수 있을 것 같아요.

```
## 명시적인 의존성

- 의존성이 명시적이지 않으면 의존성을 파악하기 위해 내부 구현을 직접 살펴볼 수밖에 없다.

- 의존성은 명시적으로 표현돼야 한다. 의존성을 구현 내부에 숨겨두지 마라. 
유연하고 재사용 가능한 설계란 퍼블릭 인터페이스를 통해 의존성이 명시적으로 드러나는 설계다. 
명시적인 의존성을 사용해야만 퍼블릭 인터페이스를 통해 
컴파일타임 의존성을 적절한 런타임 의존성으로 교체할 수 있다.

- 경계해야 할 것은 의존성 자체가 아니라 의존성을 감추는 것이다.

-299p
```

- 이번 장에서 제일 인상 깊어서 메모

**Comment by wlsh44** [comment]
> 컨택스트에 대한 정보가 적으면 적을수록더 다양한 컨택스트에 재사용될 수 있다. (261p)
많이 알수록 더 많이 결합된다. 더 많이 알고 있다는 것은 더 적은 컨택스트에서 재활용이 가능하다는 것을 의미한다. (267p)

메모

> 반면 Movie의 내부에서 AmountDiscountPolicy의 인스턴스를 직접 생성하는 방식은 Movie가 DiscountPolicy에 의존한다는 사실을 감춘다. 다시 말해 의존성이 퍼블릭 인터페이스에 표현되지 않는다. 이를 숨겨진 의존성(hidden dependency)이라고 부른다.

구체 클래스에 의존하는 방식을 오히려 퍼블릭 인터페이스에 숨겨진 의존성을 가진다고 표현한 부분이 신기했습니다.

**Comment by eagleda** [comment]
> 객체지향 설계의 핵심은 협력을 위해 필요한 의존성은 유지하면서도 변경을 방해하는 의존성은 제거하는데 있다. (254p)

>  ...따라서 모든 의존성이 나쁜 것은 아니다.
 의존성은 객체들의 협력을 가능하게 만드는 매개체라는 관점에서는 바람직한 것이다.
 하지만 의존성이 과하면 문제가 될 수 있다.(264p)

무조건 의존성을 없애라! 이런 정도는 아니라는 거네요. 불필요한 의존성들만 제거하는 선까지만..
```
public class PeriodCondition implements DiscountCondition { 
private DayOfWeek dayOfWeek;
 private LocalTime startTime;
 private LocalTime endTime;
 
 ...
 public boolean isSatisfiedBy(Screening screening) {
 return screening.getStartTime().getDayOfWeek().equals(dayOfWeek) &&
 startTime.compareTo(screening.getStartTime().toLocalTime()) <= 0 &&
 endTime.compareTo(screening.getStartTime().toLocalTime()) >= 0;
 }
}
```

> DayOfWeek의 인스턴스에게 compareTo 메시지를 전송하고...

DayOfWeek가 compareTo를 보낸 부분을 못 찾겠습니다...

>어떤 클래스의 인스턴스가 다양한 클래스의 인스턴스와 협력하기 위해서는 협력할 인스턴스의 구체적
인 클래스를 알아서는 안 된다. 실제로 협력할 객체가 어떤 것인지는 런타임에 해결해야 한다. (260p)

>**지식이 결합을 낳는다**
더 많이 알수록 더 많이 결합된다. 더 많이 알고 있다는 것은 더 적은 컨텍스트에서 재사용 가능하다는 
것을 의미한다. (...) 결합도를 느슨하게 유지하려면 협력하는 대상에 대해 더 적게 알아야 한다.
결합도를 느슨하게 만들기 위해서는 협력하는 대상에 대해 필요한 정보 외에는 최대한 감추는 것이 중요하다. (267p)

뭔가 '모르는 게 약이다' 라는 말이 생각나는 부분이네요.. 적절한 비유는 아니려나요.

**Comment by genie-youn** [comment]
> 협력을 위해서는 의존성이 필요하지만 과도한 의존성은 애플리케이션을 수정하기 어렵게 만든다. 객체지향 설계의 핵심은 협력을 위해 필요한 의존성은 유지하면서도 변경을 방해하는 의존성은 제거하는 데 있다. 이런 관점에서 객체지향 설계란 의존성을 관리하는 것이고 객체가 변화를 받아들일 수 있게 의존성을 정리하는 기술이라고 할 수 있다. (253p)
> 

요즘 문제라고 생각하는 부분. 함께 변경되어야 하는 의존하는 부분이 의존성으로 잘 드러나지 않는 경우. 예를 들면 api client. 현실세계에 존재하는 api 라는 실제 개념에 변경이 생겼는데 의존성이 애플리케이션 내부에서 잘 드러나지 않는 경우 변경을 어렵게 만든다. 추상하지 말하야 할 부분을 추상해서 만드는 문제들.
현실세계에 변경이 생겼을 때 그 변경의 시작점에 명확하게 접근할 수 있어야 한다. 해당 개념을 나타내는 도메인 모델이라던지 위에서 얘기한 api client 라던지.

**Comment by pawful-code** [comment]
P256

> 이번 장에서 다루고 있는 '의존성'은 uml의 '의존관계'와 다르다. UML은 두 요소 사이에 존재할 수 있는 다양한 관계의 하나로 '의존 관계'를 정의 한다. '의존성은 두 요소 사이에 변경에 의해 영향을 주고받는 힘의 역학관계가 존재한다는 사실에 초점을 맞춘다.  따라서 UML에 정의된 모든 관계는 의존성이라는 개념을 포함한다.


책에서 설명하려는 의존성이란 한 클래스의 코드의 변경이 다른 클래스에 영향을 끼치는 것을 의미하는 것 같습니다. 또한 이러한 하나의 클래스에 변경에 따른 영향(의존성)을 최소화 하는 것이 객체 지향 언어에서 중요한 토픽인 거 같습니다.

그렇다면 이러한 의존성 관계를 보다 줄일 수 있는 장점을 지닌 함수형 언어가 존재함에도 불구하고 객체 지향 언어를 사용하는 이유가 있을까요?

**Comment by az0t0** [comment]
> 어떤 클래스의 인스턴스가 다양한 클래스의 인스턴스와 협력하기 위해서는 협력할 인스턴스의 구체적인 클래스를 알아서는 안 된다. 실제로 협력할 객체가 어떤 것인지는 런타임에 해결해야 한다. 클래스가 협력할 객체의 클래스를 명시적으로 드러내고 있다면 다른 클래스의 인스턴스와 협력할 가능성 자체가 없어진다. 따라서 컴파일타임 구조와 런타임 구조 사이의 거리가 멀면 멀수록 설계가 유연해지고 재사용 가능해진다.
...
객체지향 프로그램의 실행 구조는 소스코드 구조와 일치하지 않는 경우가 종종 있다. 코드 구조는 컴파일 시점에 확정되는 것이고 이 구조에는 고정된 상속 클래스 관계들이 포함된다.
_P. 260_

메세지를 전달 받을 타입으로 구체적인 오브젝트 타입을 지정하지 말고, 그 오브젝트의 클래스가 상속하는 부모 클래스를 지정해서 유연하게 대처할 수 있도록 만들어야 한다는 내용입니다. 런타임에서 메서드에 객체를 넘길 때, 해당 객체가 어떤 구체적인 타입인지 판단하고 그 타입에 따른 역할을 수행해서 그 구체적인 타입에 있는 상세한 내용을 숨긴다는게 핵심인 것 같습니다.
이 부분 앞 뒤로 상속 받은 클래스의 자세한 코드를 알 필요 없게(?) 만들어야 유연성이 늘어난다는 내용이 반복되고 추상화를 강조하네요.

**Comment by usageness** [comment]
p.266
> 어떤 의존성이 다양한 환경에서 클래스를 재사용할 수 없도록 제한한다면 그 의존성은 바람직하지 못한 것이다.
> 어떤 의존성이 다양한 환경에서 재사용할 수 있다면 그 의존성은 바람직한 것이다.
> 다시 말해 컨텍스트에 독립적인 의존성은 바람직한 의존성이고
> 특정한 컨텍스트에 강하게 결합된 의존성은 바람직하지 않은 의존성이다.

컨텍스트의 유연성을 결정하는건 결국 도메인이고,
설계자는 이 도메인에 대한 깊은 이해가 있어야 **바람직한 의존성** 을 만들 수 있다. 라고 해석해도 되겠네요.

이 시점에서 Movie의 할인 정책은 `AmountDiscountPolicy`와 `PercentDiscountPolicy`가 상속받는
추상 클래스 `DiscountPolicy` 가 되겠지만, 여러 할인 정책을 동시에 적용할 수 있어야 한다면? (배민의 더하기 쿠폰)
-> `DiscountPolicies` 로 바꿔서 적용할 줄 알아야 한다.

라고 이해했습니다. 좋은 내용이네요.
