### ISSUE TITLE
[오브젝트] 23.10.08/7주차 - 챕터 10. 상속과 코드 재사용 ~ 347p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#125]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by pawful-code** [comment]
- p283
> 그림 9.1에서 알 수 있는 것처럼 Movie의 관점에서 DiscountPolicy에 대한 컴파일타임 의존성과 런타임 의존성은 동일하지 않다.

컴파일/런 타임 의존성을 같이 고려하는 점이 매우 인상 깊었습니다. 정적 분석등에 몰입해서 코드 구조만 생각하는 버릇이 들어있지는 않나 돌이켜보는 기회가 되었습니다.

-p329

> 설계는 트레이드오프 활동이라는 사실을 기억하라. 상속은 코드 재사용을 위해 캡슐화를 희생한다. 완벽한 캡슐화를 원한다면 코드 재사용을 포기하거나 상속 이외의 다른 방법을 사용해야한다.


설계 수준에서 생기는 장단점을 보여주는게 좋았습니다.

상위클래스에 수정사항이 하위클래스에 영향을 끼치어 유지보수에 어려움을 겪고


상위/하위클래스 결합도가 높아지면 조합 수 만큼 구현을 해야하는 문제가 트레이드 오프라는 것을 알 수 있었습니다.

상속을 대신하여 코드 중복을 줄여 재사용성을 높이기 위해 합성 또는 인터페이스를 사용할 수 있을 것 같은데 아래와 같은 예제에서 다들 어떻게 생각할 지 궁금합니다.

ex)클래스(새) 메서드(날기) 로 구현된 코드가 요구사항 변경으로 펭귄을 서브 클래스로 구현되게끔 하였다면
펭귄이 현실세계 행동(헤엄) 치기 위해서 Fly 메서드를 구현하는게 맞는가?
새들 중에도 타조는 달리기가 가능한데 (추후 추가 될 것이라 예상되는 부분). 펭귄이  fly 메서드를 유지하며 헤엄치게 하듯 달리게 해야하는가?

리팩토링을 어떻게 해볼지 각자의 의견이 궁금합니다.

클래스(새)에 이동을 위한 신체기관을 가진다고(has-a) 선언하여 신체기관에 이동(날기,달리기,헤엄....)을 위한 메서드를 추가할 지
-> 예상되는 문제: 수정사항이 발생하여 소스코드를 손봐야할 때 새 클래스와, 하위클래스만 열어서는 수정을 못하는 경우가 발생할 수 있음

**Comment by hyesun03** [comment]
**p.324 불필요한 인터페이스 상속 문제**
Stack이 Vector를 상속함으로써 생기는 문제는 초기 설계 문제인지라 여전하고, 이런 이유로 stack 자료구조가 필요하면 ArrayDeque 을 쓰는걸 권장합니다. (Stack, ArrayDeque 설명보면 관련 내용이 있어요 ㅋㅋ)

![image](https://github.com/TeamCrazyPerformance/http/assets/13658468/6a760fff-810f-4c8c-b7ec-b120cfbbba40)
![image](https://github.com/TeamCrazyPerformance/http/assets/13658468/d7ab6cac-23c1-4ebe-a2de-8f6ffb89d7fc)

**Comment by usageness** [comment]
p286.
> 비록 이런 기법들이 중요하지만 핵심은 추상화라는 것을 기억하라.
> -> 변하는 것과 변하지 않는 것이 무엇인지를 이해하고 이를 추상화의 목적으로 삼아야 한다.
> -> -> 그러니 무조건적인 추상화보다는 도메인에 대한 이해를 바탕으로 올바른 추상화를 해야


p.305
>유연한 설계는 유연성이 필요할 때만 옳다

유연성은 항상 복잡성을 수반한다. 유연하지 않은 설계는 단순하고 명확하다.
복잡성에 대한 걱정보다 유연하고 재사용 가능한 설계의 필요성이 더 크다면 코드의 구조와 실행 구조를 다르게 만들어라.

저번에 공유해주셨던 토비님의 글과도 일맥상통하네요

**Comment by KangJiJi** [comment]
p.291

순수한 가공물이라는 개념이 이해되지 않았습니다. 혹시 관련해서 예시나 실제 사용해본 경험이 있을까요?(14장에 나온다는 써져있는데, 와닿지 않네요)

**Comment by joi0104** [comment]
299p

> 이야기의 핵심은 의존성 주입이 ServiceLocator 패턴보다 좋다가 아니라 명시적인 의존성이 숨겨진 의존성보다 좋다는 것이다. 가급적 의존성을 객체의 퍼블릭 인터페이스에 노출하라. 의존성을 구현 내부에 숨기면 숨길수록 코드를 이해하기도 수정하기도 어려워진다.

이번주에 짠 코드중에 은행 프로모션 정보를 가져오는 훅을 만든적이 있다.

```
export function useBankPromotion() {
  const apiClient = useApiClient();
  const log = useLogger();
  
  return useQuery(['getBankPromotion'], () => {
    return apiClient.get('/bank/promotion');
  }, {
    onSuccess: () => {
       log({ message: 'call getBankPromotion'});
     }
  });
}
```

여기서 useBankPromotion의 입장에서 apiClient, logger는 하나의 의존성. 저자의 말대로 퍼블릭 인터페이스에 노출하게 되면 다음과 같다.

```
export Page() {
  const apiClient = useApiClient();
  const log = useLogger();
  const bankProtmotions = useBankPromotions(apiClient, log);
  
   ...
}
```

뭔가 이상하지 않나? api를 호출 한다 라는 구현이 사용하는 쪽에 드러나버리게 되었고, log를 매번 생성해서 주입해줘야해서 재사용성도 떨어졌다.

 > 하지만 직접 객체를 넘기를 방식이 불필요하거나 도리어 코드를 읽기 어렵게 하기도 한다. 로그나 메모리 관리 같은 정보가 모듈의 공개 API에 포함돼 있어서는 안된다. 랜더링 함수 매개변수에는 랜더링에 관련된 것만 있어야 하며 로그같은 것이 섞여 있어서는 곤란하다.
 
 아하 이미 저자가 뒤에서 말했다 ;; 그렇다면 의존성을 외부 인터페이스로 가급적이면 노출하되, 인터페이스가 어색해지는 경우에는 노출하지 않는다? 정도로 결론지으면 될까? 결국 이것도 trade off?

**Comment by genie-youn** [comment]
p 292
순수한 가공물에게 책임 할당하기
- DDD에서는 Factory도 도메인 모델로 다루지 않았나? 해서 찾아봤다.
- 비록 REPOSITORY와 FACTORY가 도메인에서 나오는 것은 아니지만 그것들은 도메인 설계에서 중요한 역할을 담당한다. 이러한 구성물은 모델 객체에 쉽게 접근하는 수단을 제공해 MODEL-DRIVEN DESIGN을 완성한다. (128p)
- 도메인에서 나오지는 않지만 도메인 모델에 쉽게 접근하기 위한 순수한 가공물이고, 마찬가지로 도메인 모델에 포함시킨다.

p 293 
생성-사용 분리 & 의존성 주입
- 소프트웨어 시스템은 응용 프로그램 객체를 제작하고 의존성을 서로 “연결”하는 시작 단계와 시작 단계 이후에 이어지는 실행 단계를 분리해야 한다.
- 사용으로부터 생성을 분리하는 데 사용되는 가장 보편적인 방법은 객체를 생성할 책임을 클라이언트로 옮기는 것이다.
- React 애플리케이션에서 의존성을 해결하는 Best Practice는?

**Comment by eagleda** [comment]
>정확하게 말하면 부모 클래스와 자식 클래스 모두 추상화에 의존하도록 수정해야 한다 (332p. 추상화에 의존하자)

>상위 수준의 모듈은 하위 수준의 모듈에 의존해서는 안 된다. 둘 모두 추상화에 의존해야 한다.(302p.)

의존성 관리 / 결합도 감소로 명시가 다르게 나왔지만
추상화를 통한 의존성 역전을 통해 모듈/클래스 각각의 재사용성을 높인다는 점에서 일맥상통함이 보였습니다.

>초보자가 자주 저지르는 실수 중 하나는 객체의 역할과 책임이 자리 잡기 전에 너무 객체 생성에 집중하는 것이다... 객체를 생성할 책임을 담당할 객체나 객체 생성 메커니즘을 결정하는 시점은 책임 할당의 마지막 단계로 미뤄야만 한다...

>역할, 책임, 협력에 먼저 집중하라... 역할, 책임, 협력의 모습이 선명하게 그려지지 않는다면 의존성을 관리하는 데 들이는 모든 노력이 물거품이 될 수도 있다는 사실을 명심하라.
