### ISSUE TITLE
[오브젝트] 23.11.19/9주차 - 챕터 12. 다형성 ~ 434p

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#127]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by hyesun03** [comment]
**p.390 그림 12.1 다형성의 분류**
예전 학교다닐 때 이런 분류를 배웠던거같은데 문득 왜 크게 universial과 ad hoc로 지칭하는지 궁금해서 찾아보았습니다. 정리해둔 글을 보면 universial은 더 일반적이고 광범위한 형태 ad hoc은 더 구체적이고 제한적인 경우 라고 하는데 잘 와닿지 않더라구요. 
찾아보니 특정 조건에서 '임시적'으로 동작할때랑 아닐때로 분류하는것

* 매개변수 다형성(Parametric Polymorphism): 
제네릭 함수나 클래스는 특정 타입에 국한되지 않고 다양한 타입의 데이터를 처리할 수 있는데, 이게 코드의 일반성과 재사용성을 증가시키니까 '유니버셜'이라는 용어를 씀

* 포함 다형성(Inclusion Polymorphism): 
하위 클래스의 인스턴스가 상위 클래스의 인스턴스로 취급될 수 있어서 다른 타입의 객체들이 동일한 방식으로 처리되는 특징 때문에 이것도 '유니버셜' 다형성이라고 지칭하는듯

* 오버로딩(Overloading):
함수가 특정한 시그니처나 구조에 따라 '임시적'으로 동작을 달리하는걸로 간주해서 ad hoc 이라고 하는듯

* 강제(Coercion): 
특정 연산 or 함수 호출에서 자동으로 타입 변환을 수행하는 경우. (정수를 부동 소수점 수로 변환하거나, 작은 정수 타입(int)을 더 큰 정수 타입(long)으로 변환하는 것들..) 이것도 특정 연산이나 상황에서 '임시적'으로 발생하는 것으로 봐서 ad hoc 이라고 하는듯

**p.397 GradeLecture 예제**
GradeLecture가 Lecture를 extend 하는게 썩 자연스러운 느낌은 아닌거같다고 느꼈습니다. 개인적으로는 GradeLecture 라는 클래스명도 썩 명확하지는 않은듯해서 계속 헷갈렸습니다... GradeStatistics 이런식으로 통계지표를 나타낸다는 의미가 있으면 좋을것 같다고 생각했어요.

**p.406 다운캐스팅**
보통은 위험해서 쓰는데 유의해야하고, 꼭 필요하다면 `instanceof` 키워드를 사용해서 체크한 다음에 다운캐스팅을 써야합니다. 이 내용이 빠져있어서 추가합니다 ㅎㅎ

**p.406**

**Comment by hjsung809** [comment]
다형성이 자동화된 위임이라는 개념을 알게되서 좋았습니다.
코드를 재사용하기 위해서가 아니라 타입 계층을 이용해서 위임을 자동화 하기 위해 사용하면 될것 같습니다.
코드만 보고 실제 실행되는 코드가 뭔지 알기어려워지는 복잡함이 단점인것 같다고 생각했습니다.

p421
'동적 타입 언어는 이해할 수 없는 메시지를 처리할수 있는 능력을 가짐으로써 메시지가 선언된 인터페이스와 메서드가 정의된 구현을 분리할 수 있다.'  
동적 타입언어에서는 이해할 수 없는 메시지도 전송할 수 있다는걸 말하는것 같은데, 이게 가능해서 좋은 상황이 있을까요?
정적 언어에서는 메시지를 처리하지 못하는 경우를 컴파일러에서 잡아주는데, 전송할 수 없는 메시지를 아예 막아주는게 무조건 좋은게 아닌가.. 합니다

**Comment by joi0104** [comment]
이번장은 기존에 알고 있던 다형성을 좀 더 자세하게 알아가는 챕터여서 막힘없이 술술 읽혔던거 같습니다.

> 390p 간단히 말해서 다형성은 여러 타입을 대상으로 동작할 수 있는 능력으로 정의한다. ... 유니버셜 다형성은 다시 매개변수 다형성과 포함 다형성으로 분류할 수 있고, 임시 다형성은 오버로딩 다형성과 강제 다형성으로 분류할 수 있다.

오버로딩 또한 다형성의 한 종류라고 본다는걸 처음 알았습니다 ㅎㅎ. 다형성을 `동일한 인터페이스를 다른 구현으로 연결하는 패러다임`으로 이해를 해서 오버로딩은 인터페이스가 각자 다르니 다형성이 아니라고 생각했는데, 책을 자세히 읽어보니 다형성은 좀 더 추상적인 범주였던거 같네요. 말 그대로 여러 타입을 대상으로 동작할 수 있는 코드를 작성하는 방법...!

> 392p 상속의 진정한 목적은 코드 재사용이 아니라 다형성을 위한 서브타입 계층을 구축하는 것이다.

책에서 한 4번은 나온건 같아서 인용해봤습니다 ㅋㅋ. 코드를 중복으로 작성하다가 코드 스멜을 맡고 상속으로 풀지 고민하는 경우가 많은데, 이럴때 함정에 빠지기 쉬운 것 같아요. 상속을 사용하게 되면 위 저자의 말을 곱씹어보면서 단순 코드 재사용을 위한게 아닌지 생각해 볼 수 있을 것 같습니당.

> super 참조의 정확한 의도는 지금 이 클래스의 부모 클래스부터 매서드 탐색을 시작하세요 다. ... 메서드를 호출하는 것과 메서드를 탐색하는 것은의미가 매우 다르다. 탐색한다는 것은 그 클래스 조상 어딘가에 메서드가 정의돼있기만 하면 실행할 수 있다는 걸 의미한다.

super의 동작은 알고 있었지만, 메서드 호출이 아닌 메서드 탐색을 한다는 표현이 좋았던거 같아요. super 전송의 경우에는 컴파일 시점에 미리 결정해 놓을 수 있다는 것도 미쳐 생각 못해봤던 부분이라 이 부분도 좋았던거 같습니다.

**Comment by wlsh44** [comment]
기존에는 객체지향의 철학적인 내용이 많이 있었는데 이번에는 다형성이 어떤 식으로 실행되는지 같은 이론적인 내용이 많아서 갑자기 왜 이 내용들이 지금 나오지 하는 의문점이 생겼는데 딱히 답을 내기 힘들었습니다..
이번 장에서 저자가 하고 싶은 말이 뭔지 설명해주실 분 계신가요?

> 이처럼 실행될 메서드를 런타임에 결정하는 방식을 동적 바인딩 또는 지연 바인딩(late binding)이라고 부른다. p407

지연 바인딩이 당연히 lazy binding인 줄 알았는데 late binding이였네요.

그래서 lazy binding이 뭔지 찾아봤는데 주로 리눅스에서 다이나믹 링킹 방식을 사용할 때 함수의 첫 호출 시점에 함수의 주소만 알아오는 방식의 용어로 많이 쓰이는 것 같았습니다.

> 이처럼 자신이 수신한 메시지를 다른 객체에게 동일하게 전달해서 처리를 요청 하는 것을 위임(delegation)이라고 부른다.
...
처리를 요청할 때 self 참조를 전달하지 않는 경우를 포워딩이라고 부른다. 이와 달리 self 참조를 전달하는 경우에는 위임이라고 부른다. 위임의 정확한 용도는 클래스를 이용한 상속 관계를 객체 사이의 합성 관계로 대체해서 다형성을 구현하는 것이다. p429

위임은 첫 번째 정의처럼 단순히 다른 객체에게 메시지를 넘기는거라고 알고 있었는데 self를 넘기는 것과 상관이 있는지 찾아봤습니다.

> In casual use, forwarding is often referred to as "delegation", or considered a form of delegation, but in careful usage they are clearly distinguished by what self refers to. 
While delegation is analogous to inheritance, allowing behavioral reuse (and concretely code reuse) without changing evaluation context, forwarding is analogous to composition, as execution depends only on the receiving (member) object, not the (original) sending object. [wekipedia](https://en.wikipedia.org/wiki/Forwarding_(object-oriented_programming))

여기에서도 포워딩과 위임은 self를 참조하는지에 따라 차이가 있고, 위임은 상속과 유사하며 포워딩은 합성과 유사하다고 나와있네요.
그럼 제가 기존에 생각했던 위임은 포워딩을 뜻하는 거였을까요?

**Comment by pawful-code** [comment]
이번 장은 어떻게 오버라이딩과 오버로드한 메서드를 컴퓨터 메모리에서 탐색하여 호출하는지를 알수있던 점이 무척 좋았습니다. 전통적인 프로그래밍에서는 함수를 호출한다고 하지만 객체 지향에서는 왜 메시지를 전달한다로 표현하게 되었는지와 관련되어 추가로 공부를 시작할 만한 지점이 있는지 궁금합니다.

**Comment by genie-youn** [comment]
> 407p 컴파일 타임에 호출할 함수를 결정하는 방식을 정적 바인딩, 초기 바인딩, 또는 컴파일타임 바인딩이라고 부른다. 객체지향 언어에서는 메시지를 수신했을 때 실행될 메서드가 런타임에 결정된다. foo.bar()라는 코드를 읽는 것만으로는 실행되는 bar가 어떤 클래스의 어떤 메서드인지 판단하기 어렵다. foo가 가리키는 객체가 실제로 어떤 클래스의 어떤 인스턴스인지 알아야 하고  bar 메서드가 해당 클래스의 상속 계층의 어디에 위치해야하는지를 알아야 한다. 이처럼 실행될 메서드를 런타임에 결정하는 방식을 동적 바인딩 또는 지연 바인딩 이라고 부른다.

자꾸 9장의 내용이 아른거려서 개발생산성 -30%인 상태

>유연성은 항상 복잡성을 수반한다. 유연하지 않은 설계는 단순하고 명확하다. 유연한 설계는 복잡하고 암시적이다.

>설계가 유연할수록 클래스 구조와 객체 구조 사이의 거리는 점점 멀어진다. 따라서 유연함은 단순성과 명확성의 희생 위에서 자라난다. 유연한 설계를 단순하고 명확하게 만드는 유일한 바법은 사람들 간의 긴밀한 커뮤니케이션 뿐이다

>불필요한 유연성은 불필요한 복잡성을 낳는다. 단순하고 명확한 해법이 만족스럽다면 유연성을 제거하라.

>내 두 번째 주장은 우리의 지적 능력은 정적인 관계에 더 잘 들어맞고, 시간에 따른 진행과정을 시각화하는 능력은 상대적으로 덜 발달했다는 점이다. 이러한 이유로 우리는 (자신의 한계를 알고 있는 현명한 프로그래머로서) 정적인 프로그램과 동적인 프로세스 사이의 간극을 줄이기 위해 최선을 다해야 하며, 이를 통해 프로그램(텍스트 공간에 흩뿌려진)과 (시간에 흩뿌려진)진행 과정 사이를 가능한 한 일치시켜야 한다(다익스트라 - Go To Statement Considered Harmful)"

이 모든게 위의 동적 바인딩에 해당하는 이야기인데, 생각해보면 도메인 모델을 구성할 때 기본적으로 모든 의존성을 동적 바인딩으로 연결해왔던것 같다. (생성자로 필요한 의존성을 전부 주입받게 만드니) 이게 잘못된건가. 꼭 필요한 경계만을 찾아내고 이 경계에 해당하는 객체들만 생성자로 주입받아야 하나? 대표적인 Repository 같은 아이들? 생각이 많아지는데 여러분들의 생각도 궁금하네요~

프로토타입 관련된 내용은 이제야 조금 이해한것 같네요. You don't know javascript 읽으면서 암기했던 this의 동작방식도 이 섹션이 이해가 가기 시작하면서 조금 이해가 되는것 같아요.

다형성과 관련된 코드 챙겨온건, 요즘 열심히 보고 있는 클린아키텍처 관련.

**Comment by eagleda** [comment]
>객체지향 프로그래밍에서 사용되는 다형성은 유니버설(Universal) 다형성과 임시(Ad Hoc) 다형성으로 분류할 수 있다.

각각의 다형성이 왜 이러한 명칭을 가지게 되었는지 궁금합니다.

>실제로 객체를 메모리에 생성하는 방식이나 구조는 언어나 실행 환경에 따라 다르다는 사실에 주의하라.(p.400)

1학년 입문과목 들을 때 C++ 객체 메모리 구조에 관련된 내용이 있던 것으로 기억하는데 이번 기회에 다시 한번 자료를 살펴봐야 겠네요.. 

학교 과목에서 한 차례 배웠던 오버로딩 같은 다형성 관련 내용들을 좀 더 심도있게 다루니 반가운 느낌이 들면서도 낯선용어랑 구조 해석에 어려움을 겪는 걸 보니 배울 게 산더미만 하다는 게 체감이 되었습니다.

**Comment by usageness** [comment]
p.389
> 상속의 목적은 코드 재사용이 아니다.
> 상속은 타입 계층을 구조화하기 위해 사용해야 한다

프론트에서도 컴포넌트를 분리하는 기준에 대해 생각해보면 위와 크게 다르지 않은 것 같습니다.
단순히 재사용성을 기준으로 분리하려고 했었을때는 설명하기 어려운 코드 스멜이 느껴졌었는데
이제는 계층 구조화를 이유로 들어 말할 수 있을것 같아요.

---

ad hoc 이라는 용어가 나와서 생각났던건데,
알고리즘 문제 분류 중에도 애드혹(ad hoc)이라는 카테고리가 따로 있었습니다.
특정 알고리즘을 기반으로 푸는 문제가 아니라, 복잡한 구현이나 시스템을 만들어서 풀어야 하는 등
그 문제에서만 통하는 로직을 짜서 푸는 문제들이었던걸로 기억해요.
universial과 ad hoc의 분류가 있길래, 그런 느낌으로 이해했습니다.

---

p.421
> 이해할 수 없는 메시지를 처리할 수 있는 동적 타입 언어는 좀 더 순수한 관점에서 객체지향 패러다임을 구현한다고 볼 수 있다

"상대가 이해할 수 있는 메시지"만 던진다는 것은 결국 (인터페이스에 한정한) 내부 구현을 안다는 의미...
자바스크립트처럼 로직이 런타임에 처리되는 동적 언어의 경우 꼭 필요한 능력이라고 생각됩니다.

**Comment by genie-youn** [comment]
누가 정리해주겠지.

In casual use, forwarding is often referred to as "delegation", or considered a form of delegation, but in careful usage they are clearly distinguished by what self refers to.
While delegation is analogous to inheritance, allowing behavioral reuse (and concretely code reuse) without changing evaluation context, forwarding is analogous to composition, as execution depends only on the receiving (member) object, not the (original) sending object. [wekipedia](https://en.wikipedia.org/wiki/Forwarding_(object-oriented_programming))

여기에서도 포워딩과 위임은 self를 참조하는지에 따라 차이가 있고, 위임은 상속과 유사하며 포워딩은 합성과 유사하다고 나와있네요.
그럼 제가 기존에 생각했던 위임은 포워딩을 뜻하는 거였을까요?
