### ISSUE TITLE
[오브젝트] 23.11.26/10주차 - 챕터 13. 서브클래싱, 서브타이핑 ~ 469p 

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#128]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by hyesun03** [comment]
#### p.438 가운데 쯔음 `동일한 퍼블릭 인터페이스를 가지는 객체들은 동일한 타입으로 분류할 수 있다.`
이 문장보고 'Java에서 다른 interface로 만들었지만 내부에서 제공되는 메서드가 아주 똑같으면 그건 동일한 타입으로 분류될까?' 라는 의문이 생겼습니다 ㅋㅋ
해당 페이지 맨 마지막에 `~~동일한 퍼블릭 인터페이스를 공유한다면 이들은 동일한 타입으로 분류된다.`라고 적혀져있다보니 `공유` 가 핵심인듯하고, 직접 확인해보는게 좋을거 같아서 확인해보니 역시 ClassCastException이 발생하네요.

테스트 할 때는 아래처럼 간단한 class, interface를 만들어서 테스트 했었고,
``` java
public interface HelloInterface {
	void sayhi();
}
public interface HelloInterface2 {
	void sayhi();
}
public class Hello implements HelloInterface {
	@Override
	public void sayhi() {
		System.out.println("Hello - hi");
	}
}
public class Hello2 implements HelloInterface2 {
	@Override
	public void sayhi() {
		System.out.println("Hello2 - hi");
	}
}
```

사실 뭔가 재미있는걸 발견할 줄 알고 기대했는데 약간 아쉬웠습니다...
``` java
@Test
public void asdf() {
	HelloInterface helloObj = new Hello();
	helloObj.sayhi(); // Hello - hi

	HelloInterface2 helloObj2 = new Hello2();
	helloObj2.sayhi(); // Hello2 - hi

	HelloInterface interfaceObj = new Hello();
	HelloInterface2 interfaceObj2 = new Hello2();

	interfaceObj = (HelloInterface)helloObj2; // java.lang.ClassCastException 발생
	interfaceObj2.sayhi();

	interfaceObj2 = (HelloInterface2)helloObj; // java.lang.ClassCastException 발생
	interfaceObj2.sayhi();
}
```

혹시나 위에 있는 테스트 코드처럼 명시적으로 ClassCast를 수행할 때, exception 발생안하고 적당히 대충 동작해서 동일한 타입으로 간주되는 언어가 있나 싶어서 좀 찾아보았는데요, typescript도 그렇고 위처럼 테스트 해보니까 다 다른 타입으로 인지해서 딱히 없는듯하네요. (python 같이 덕 타이핑 지원하는 언어 제외) 
**결론: 클래스의 계층 구조에 기반하여 타입 변환을 수행을 하다보니 그럴 수 밖에 없는거 같고 이렇게 exception 던지는게 맞겠다고 생각 정리했습니다.** 

----------
#### p.458에 `클라이언트와 격리한 채로 본 모델은 의미 있게 검증하는 것이 불가능하다.`

요즘 객체지향에 대해 고민을 하는 작업을 하질않아서 그런가 이번장은 읽고나서 공유할만한 내용이 떠오르지가 않았습니다.

**Comment by genie-youn** [comment]
처음 읽을때는 그냥저냥 넘겼던 것 같은데, 이번회차때는 is-a 내용이 많이 와닿았다.

## 03. 서브클래싱과 서브타이핑
### is-a 관계
이 예는 is-a라는 말을 너무 단편적으로 받아들일 경우에 어떤 혼란이 벌어질 수 있는지를 잘 보여준다. 스콧 마이어스의 말을 인용하자면 지금 우리는 명확하지 않는 자연어, 즉 사람의 말에 소위 ‘낚인’ 것이다. 따라서 어떤 두 대상을 언어적으로 is-a 라고 표현할 수 있더라도 일단은 상속을 사용할 예비 후보 정도로만 생각하라. 너무 성급하게 상속을 적용하려고 서두르지 마라. 여러분의 애플리케이션 안에서 두 가지 후보 개념이 어떤 방식으로 사용되고 협력하는지 살펴본 후에 상속의 적용 여부를 결정해도 늦지 않다. (445p)

### 클라이언트의 기대에 따라 계층 분리하기
요점은 자연어에 현혹되지 말고 요구사항 속에서 클라이언트가 기대하는 행동에 집중하라는 것이다. 클래스의 이름 사이에 어떤 연관성이 있다는 사실은 아무런 의미도 없다. 두 클래스 사이에 행동이 호환되지 않는다면 올바른 타입 계층이 아니기 때문에 상속을 사용해서는 안 된다. (451p)

왜 저자가 한 챕터를 통으로 할당했는지도 이제는 좀 알것 같은게, 보통 설계를 함에 있어 현실세계에 존재하는 업무규칙, 서비스정책을 모델링하고 이를 기반에 깔고 설계를 해 나가다 보니 자연스럽게 자연어와 현실의 개념들간의 관계에 현혹되게 된다.

최근 후회했던 설계중 하나는 '인증대행사'. 자세한 내용은 스터디에서.

결국 중요한건 테스트다.

**Comment by pawful-code** [comment]
is-a 관계를 맹목적으로 따라갈게 아니라 인터페이스를 이용하여 구분하는 예시가 나왔던 점이 좋았습니다. 이전에 합성과 상속 사이의 trade off 를 비교하며 생긴 의문점을 잘 해결해준 장이었습니다.

상속을 통한 구현 : 펭귄은 fly 행위를 할 수 없는 새 -> 상속으로 인해 fly를 penguin에 구현하면 어색해짐  

<img width="350" alt="image" src="https://github.com/TeamCrazyPerformance/http/assets/16588701/f6e32a5d-1ab0-492d-99ea-f1ef784e4d69">

인터페이스로 Fly행위를 bird클래스로 부터 분리한 예
<img width="400" alt="image" src="https://github.com/TeamCrazyPerformance/http/assets/16588701/10bd839c-5fca-4a18-b533-48157409b30f">

합성을 통해 개선시킨 예
<img width="401" alt="image" src="https://github.com/TeamCrazyPerformance/http/assets/16588701/87625cc1-b736-40e5-a6a7-9488a9bbf2db">
해당 예시를 보면서 클래스 계층에 따라 여러 인터페이스가 존재할 수 있게 된다는 점을 알게 되었습니다.

Question.
 상속 대신 합성을 이용함으로 써 다중 구현, 다중 상속을 가능하게 하여 상속에 한계를 벗어 날 수 있는 모습을 보았습니다.  정리하면 class들 간에 field를 통합하는 데에는 상속을 이용하고, 동일한 기능을 보장하되 상속을 이용하면 문제가 생길경우 합성을 사용한다로 정의해도 문제가 없을지 궁금합니다.

**Comment by usageness** [comment]
p.443
> 서브타입의 인스턴스는 슈퍼타입의 인스턴스로 간주될 수 있다. 이 사실이 이번
장의 핵심이다. 그리고 상속과 다형성의 관계를 이해하기 위한 출발점이다. 

p.445
> 상속 관계가 is-a 관계를 모델링하는가? 
> 클라이언트 입장에서 부모 클래스의 타입으로 자식 클래스를 사용해도 무방한가?

이전까지 생각하던 상속의 개념과 충돌해서 계속 위화감이 들고 있었는데,
"펭귄은 새인가?" 예시가 제 혼란을 명쾌하게 해결해 준 것 같습니다.

A라는 슈퍼클래스를 상속받아 B라는 서브클래스를 구현했을때,
A에 존재하지 않는 메서드를 추가로 만들어 사용하던 경험이 종종 있었습니다.
제가 지금까지 잘못된 상속을 사용하고 있었던 것이었네요.

**Comment by wlsh44** [comment]
> 리스코프 치환 원칙에 따르면 자식 클래스가 부모 클래스와 행동 호환성을 유지함으로써 부모 클래스를 대체할 수 있도록 구현된 상속 관계만을 서브타이핑이라고 불러야 한다. p454

사실 그동안 리스코프 치환 원칙을 약간 언어의 문법적으로 생각을 했었는데 이번 장을 읽고 정리를 좀 하게 된 것 같습니다.
결국엔 올바른 서브타이핑인가 -> 올바른 상속인가 -> 상속을 사용하기 위한 두 질문을 만족하는가 가 성립이 될 때 리스코프 치환 원칙을 만족하는구나 라는 생각을 했습니다.

> 클라이언트 관점에서 자식 클래스의 행동이 부모 클래스의 행동과 호환되지 않고 그로 인해 대체가 불가능하다면 어휘적으로 is-a라고 말할 수 있다고 하더 라도 그 관계를 is-a 관계라고 할 수 없다.
...
클라이언트를 배제한 is-a 관계는 여러분을 혼란으로 몰아갈 가능성이 높다. p458

is-a 를 그동안 너무 간단하게 생각하고 있었다는걸 이번 장을 읽으면서 많이 깨닫고 반성하는 계기가 되었습니다..

> 서브타입에 슈퍼타입과 같거나 더 약한 사전조건을 정의할 수 있다. p467

```java
public class Movie {
  public Money calculateMovieFee(Screening screening) {
    checkPrecondition(screening);
    return fee.minus(discountPolicy.calculateDiscountAmount(screening)); 
  }
}

public class BrokenDiscountPolicy extends DiscountPolicy { \
  ...
  @Override
  public Money calculateDiscountAmount(Screening screening) {
  // checkPrecondition(screening);    기존의 사전조건 제거
  Money amount = screening.getMovieFee(); 
  ...
}
... }
```

이 부분이 개인적으로 항상 맞다고 생각하면서도 진짜 맞는지에 대한 의구심이 드는 부분이었습니다! 
결국에 이 말은 클라이언트는 서버에게 올바른 값을 넘겨줘야 하는 책임이 있기 때문에 저 말이 맞다고 생각을 했는데, 실제 개발에서 현실적으로 가능한 일인지 궁금했습니다.
예전에 어떤 시니어 개발자분께서도 저런 곳에서 null 처리같은 걸 꼼꼼히 해주는 편이 좋다고도 말씀을 하신 적이 있어서 많이 헷갈리네요..

또 여기서 screening을 넘겨주는 클라이언트인 Movie도 누군가에겐 서버이고 screening에 대한 사전 조건 계약이 있었을텐데 이 경우에는 어떻게 해야 할까 라는 생각도 많이 들었습니다.

```java
class A {
  private B b;

  public void someFunc1(Screening screening) {
      ...
      checkPrecondition(screening);
      b.someFunc2(screening);
  }
}

class B {
  private Movie movie;

  public void someFunc2(Screening screening) {
      ...
      checkPrecondition(screening);
      movie.calculateMovieFee(screening);
  }
}
```
좀 과하게 예시를 들면 이런 느낌으로..?

**Comment by kye8524** [comment]
2년의 휴학동안 이론?개념?적인 공부를 놔버려서 읽는데 시간이 좀 걸렸습니다
너무 열심히 놀았던 그동안을 반성하는 시간이 되었습니다...

이번장은 그동안 제가 상속을 코드 재사용에 중점을 두고 있었다는걸 깨닫게 해주고 이를 바로 잡는데 도움이 되었습니다.

> 상속 계층을 사용하는 클라이언트의 입장에서 부모클래스와 자식 클래스의 차이를 몰라야한다. p443

처음 이 문구를 봤을때는 이게 어떻게 가능한건지 이해가 잘 안되었는데 펭귄예제가 도움이 되었습니다.

**Comment by joi0104** [comment]
"클라이언트 관점에서 is-a 관계인지 살펴봐라. 클라이언트 입장에서 동일한 행동을 하는 행동 호환성을 가진 관계인지 대체 가능성이 있는 관계인지를 염두에 두고 이에 따라 타입계층을 정의하라" 라는 말이 좋았던거 같습니다 ㅎㅎ 결국 클라이언트 입장에서 동일한 행동을 하는 객체인가 라는 말 같은데 그런 의미에서는 is a 관계 라기보다는 can 관계 라고 정의 하는게 더 좋지 않나? 라는 생각이 드네요.
is a 관계라고 하면 뭔가 명사로 그 객체를 정의하게 되는 거 같습니다. 그러다보니 행동을 기준으로 책임을 할당하기 보다는 사람의 말에 의해 본능적으로 책임을 할당하게 되는 것 같구요. 처음부터 "날다" 라는 행위에 집중했다면 Flyer라는 객체가 먼저 나오지 않았을까 싶네요.


현업에서 상속구조를 썼던 부분을 고민해보니, 일반적인 자료구조를 좀 더 확장해서 사용하려고 상속을 많이 썼던거 같아요. 왜 자료구조에 상속을 많이 적용했을까? 를 생각해보면 코드 중복을 해소하려고 많이 사용했던 것 같습니다. 자바도 이런구조 인걸로 알고 있는데, (List , ArrayList, LinkedList) 클라이언트 관점에서 is a 관계라고 두는게 합당한가? 에 대해서 이야기해보고 싶습니다 ㅎㅎ
