### ISSUE TITLE
[GoF 디자인패턴] 5주차 ~ 5.6 메멘토

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#13]

**Comment by hyesun03** [comment]
# Iterator
그냥 내부구현 몰라도 순회 가능하다는 것만 알고있었는데 책 읽으면서 걸리는게 꽤 많아서ㅜㅜ 도대체 뭘 읽었는지 모르겠습니다...

## p.342 두 번째 문단
여기 문단 전체가 이해가 안감
> 이 CreateIterator()의 구현에는 팩토리 메서드 패턴을 사용할 수 있습니다. 팩토리 메서드를 사용하여~~

## p.344 2번
aggregate 인터페이스를 단순화 한다는게, aggregate내에 여러 메소드들이 있는데 거기에 있는 메소드들 중에 순회목적으로 쓰는 메소드들을 iterator로 빼서 그렇다는건가요?
> 2. Iterator는 Aggregate 클래스의 인터페이스를 단순화합니다.

## p.344 마지막 문단
예전부터 제가 인식하던 "그 반복자"는 외부 반복자 였던것 같아요. [Java Stream API 소개](https://cornswrold.tistory.com/293) 이 글 보고 좀 감을 잡았습니다,,
> 외부 반복자가 내부 반복자보다는 유연한 방법입니다. 외부 반복자를 이용하면 두 집합 객체가 동일한 집합인지 비교할 수 있지만, 내부 반복자를 이용할 때는 불가능합니다~~

## p.346 5번
여기서 첫 번째 문단에 언급되는 `확장된 반복자`가 프록시 패턴을 써서 메모리 해제 하는걸 의미하나요?
그냥 메모리 해제 잘못하면 메모리 누수때문에 문제가 될 수 있다~ 그래서 프록시패턴 쓰면 문제 해결 가능~~ 이 정도로만 이해하고 넘겼습니다...

## p.346 6번
`반복자를 그 집합 구조의 friend로 정의한다~`이 부분이 이해가 안가서 계속 보고 있었는데, c++에 있는 `friend`라는 키워드가 있었어요. (friend로 지정되면 내부 private, protected로 선언된것 까지 다 접근 가능)
c++에 왜 이런 키워드가 있지..하면서 찾아봤는데 아래와 같은 내용을 찾았습니다. https://stackoverflow.com/a/182370 
> Java언어 설계할 때 C++에 있는 friend 개념을 명시적으로 거절했다. 제임스 고슬링이 friend는 OOP를 명백히 위반하며 package 개념은 꽤 합리적인 방법이다. 누군가가 Java의 reflection 문제를 지적했지만, Security Manager를 쓰지 않을 경우에만 동작하지 Java의 표준 보안 정책을 키면 리플렉션으로 치팅 할 수 없다~~ 대략 이런 내용

## p.347 8번
`널 반복자`는 그냥 널 객체 쓴다는거 맞죠? 리턴할 객체는 없는데 null 처리 따로 하기 번거로우니까 쓰는 그런 맥락이랑 비슷한듯..

## p.352
믹스인 클래스 개념 찾아보려고 위키 글 열었는데....,,,, 지훈아 어서 위키 글쓰자..,,,
> 다른 방법은 Traversavle이라는 일반적인 믹스인 클래스를 만드는 것입니다.~~~

## 잘 알려진 예
- C++ STL의 iterator
- [java.util.collection](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/util/Collection.java) (Java의 collection framework는 모두 [iterable interface](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/lang/Iterable.java) 상속 받음)

**Comment by hyesun03** [comment]
# Mediator
## 잘 알려진 예

저번에 공유했던 [Java core library에서 볼 수 있는 gof 패턴들](https://stackoverflow.com/questions/1673841/examples-of-gof-design-patterns-in-javas-core-libraries)에서 Java 코드만 링크합니다.

* [java.util.Timer](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/util/Timer.java) 에 있는 `scheduleXXX()` 메소드들
`scheduleXXX()`함수가 TimerTask와 새로운 쓰레드를 중재(연결?)

* [java.lang.reflect.Method.invoke()](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/lang/reflect/Method.java#L484)
`invoke()`함수가 현재 쓰레드와 임의의 객체를 중재(연결?)

**Comment by hyesun03** [comment]
# Memento

## p.372 첫번째줄
"제약 해결(constraint-solving) 시스템"이 뭔지 모르겠어요. 검색하면 [CSP 문제](https://redcarrot.tistory.com/48) 이거 밖에 안보이는데, 이 책에서 말하는게 뭔지 감도 안옵니다..

## p.372 아래서 2번째줄
뭔가 문장이 이상해서 한참 봤는데.. 아래 문장은 "`원조본` 내부 구현을 메멘토 객체가 아닌 다른 객체에게 공개하지 않는다"는 말 맞죠? 
> 즉, 메멘토 이외의 다른 객체에게는 보이지 않습니다.

## p.375 5번
아래 두 가지는 이해를 했는데, `적지 않은 저장비용을 유발`이 무슨 뜻인지 이해가 안가요. 

Caretaker(보관자 객체)는 메멘토에 얼만큼 저장했는지 알 수 없음(ㅇㅇ 이해함)
-> Caretaker가 메멘토를 삭제할 책임이 있다는 것(ㅇㅇ 이해함)
-> 적지 않은 저장 비용 유발(???)

## p.376 1번
여기서 말하려는거는 "제한 범위 인터페이스와 광범위 인터페이스를 잘 나눠서 설계해야한다~" 인거 같아요. 특정 언어에서는 지원이 안된다는게, "C++에서는 `friend`키워드가 있어서 이상적으로 구현 할 수 있는데, `friend` 키워드와 같은 컨셉이 없는 타 언어에서는 이상적인 구현이 어렵다~"는 말인가요??

## 기타
[Git: 델타와 스냅샷](http://dogfeet.github.io/articles/2012/git-delta.html)
이 패턴 읽으면서 버전관리시스템이 생각났는데, git이나 svn같은 VCS가 메멘토 패턴의 한 예라고 볼 수 있을까요?
암만 찾아봐도 원하는 답이 안나와서..ㅜ

## 잘 알려진 예
https://blog.naver.com/2feelus/220665171889
* [java.io.Serializable](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/io/Serializable.java)

**Comment by KangJiJi** [comment]
헤헤...

**Comment by lallaheeee** [comment]
# Iterator

### 공부하기 전 들었던 의문

#####  1) for loop를 도는 것과 iterator의 차이 

1. for-loop vs iterator

   [iterator vs for](https://stackoverflow.com/questions/22267919/iterator-vs-for)

   [iterator vs for loop and why iterator was introduced as we had for loop?](https://stackoverflow.com/questions/5504570/iterator-vs-for-loop-and-why-iterator-was-introduced-as-we-had-for-loop)

   1. for 문과 for-each는 다름. for문은 배열에 인덱스로 접근한 것이고, for-each는 iterator를 사용한 것 
   2. 배열을 사용한다면 인덱스를  통해 접근하면 더 빠르다. (ex. arr[i]) 하지만 tree나 list처럼 다른 자료구조에서 인덱스를 사용한다면 처음 element부터 시작하여 target까지 접근하기 때문에 O(n)의 시간이 걸리므로 느리다. (= linkedList.get(i) 는 O(n)이다)
   3. iterator를 사용하면 컴파일러는 current position을 알고 있고, current position부터 시작하기 때문에 O(1)이 걸린다. 그렇기 때문에 배열이 아닌 다른 자료구조를 이용한다면 iterator를 사용하는 것이 효율 적이다. 
   4. 컬렉션의 타입과 구현(+크기)에 신경쓰지 않고 코드를 분리하여 프로그래밍이 가능해지기 때문에 변경에 보다 유연하게 대처 가능하다. 

### 공부하면서 들었던 의문

##### 1) iterator 도 패턴인가? 해결하고자 하는 문제는?

> *How can the elements of an aggregate object be accessed and traversed without exposing its underlying representation?* 

컬렉션 구현 방법(혹은 데이터 구조)을 노출시키지 않으면서, 순차적으로 그 집합체 안에 들어있는 모든 항목에 접근할 수 있게 할 수 있을까?


##### 2) 다형성을 지닌 반복(polymorphic iteration)이란?

list의 복합구조를 변경하더라도 사용자 코드는 변경하지 않도록 만들기 위해.. 그니까 aggregate가 변경되어도 영향받지 않고 반복할 수 있어야 한다는 의미로 이해


##### 3) Factory method 패턴을 사용하여 어떻게 `createIterator()` 를 구현?

iterator가 특정 객체를 순회하니까, 특정 객체의 자료구조의 인터페이스와, iterator를 상속받아서 factory를 정의하고,  이제 aggregate Object의 iterator를 만들려면 팩토리한테 이 aggregate의  iterator를 줘! 하면 팩토리 메서드가 그 객체의 iterator를 반환한다고 일단 이해



##### 4) Aggregate Object의 뜻 

> An aggregate object is one which contains other objects. For example, an Airplane class would contain Engine, Wing, Tail, Crew objects. Sometimes the class aggregation corresponds to physical containment in the model (like the airplane). But sometimes it is more abstract (e.g. Club and Members).
>
> [Lecture Notes on Object-Oriented Programming](https://atomicobject.com/resources/oo-programming/object-oriented-aggregation)

간단히 array나 tree, linked list같이 데이터 집합이라고 이해


##### 5) 결과 

1. *순회를 동적으로 변경 가능. 예를 들어서 트리 순회를 전위 순회할지 후위 순회할 지 런타임에 결정 가능*

   >  Allows changing the traversal dynamically at run-time.
   > – "Iterators make it easy to change the traversal algorithm: just replace the iterator instance with a different one."

   

2. *Iterator는 Aggregate 클래스의 인터페이스를 단순화합니다.* 

   > 원문
   >
   > Iterators simplify the Aggregate interface.Iterator's traversal interface obviates the need for a similarinterface in Aggregate, thereby simplifying the aggregate's interface. 

   Iterator의 traversal 인터페이스는 Aggregate에서 유사한 인터페이스가 필요하지 않으므로 Aggregate 인터페이스를 단순화한다. 순회의 책임은 iterator에게 넘긴다고 이해.

   

3. *집합 객체에 따라 하나 이상의 순회 방법이 제공될 수 있습니다. (번역이 이상해서 찾아봄)*

   >  More than one traversal can be pending on an aggregate.An iterator keeps track of its own traversal state. Therefore you canhave more than one traversal in progress at once. 

   각 iterator는 자신의 순회 상태가 있기 때문에, 하나의 aggregate를 동시에 순회할 수 있다

   

##### 6) 구현 1- 내부 반복자에서 iterator는 어떻게 자신의 반복을 제어할까

`구현 2- 순회 알고리즘을 어디에서 정의할 것인가`와 짬뽕 믹스가 되어 헷갈립니다. 둘이 다른 이야기를 하고 있는 것 같은데, iterator 내에서 자신의 순회 처리 방법을 정의하고 제어하면 그게 내부 반복자일까요..

- [연속 어구(continuation)](https://en.wikipedia.org/wiki/Continuation) 란?

  *a continuation is an abstract representation of the control state of a computer program.*

> 원문
>
> Internal iterators are especially weak in a language like C++ that does not provide anonymous functions, closures, or continuations like Smalltalk and CLOS. But on the other hand, internal iterators are easier to use, because they define the iterationlogic for you. 



##### 7) 구현 5- 다형성을 지닌 반복자와 확장된 반복자의 차이?

위에서 다형성을 지닌 반복자를 `aggregate의 데이터 구조가 조금 변경되어도 영향받지 않고 반복할 수 있어야 한다 ` 로 의미했는데 그럼 확장된 iterator는 aggregate의 데이터 구조가 변경된 확장된 클래스를 상속받아(확장하여) 구현한 iterator 일까요?  

- 왜 다형성을 지닌 iterator는 객체에 할당된 힙메모리를 삭제할 수 없나요.. 

- 스택에 저장한 프록시를 iterator처럼 사용하는 방법?

  c++에 국한된 내용이길 바래봅니다.



##### 8) 또 하나의 의문 

외부 반복자는 클라이언트가 반복을 제어하고, 내부 반복자는 iterator가 반복을 제어한다면

외부 반복자는 iterator를이용해 클라이언트가 원하는 방식으로 제어를 하는 것이고, 내부 반복자는 어떤 시스템 내에서 aggregate를 제어해야할 때 사용하는 걸까요?!

**Comment by genie-youn** [comment]
# Memento

https://github.com/spring-projects/spring-webflow/blob/master/spring-binding/src/main/java/org/springframework/binding/message/StateManageableMessageContext.java
