### ISSUE TITLE
[오브젝트] 23.12.17/12주차 - 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#130]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by hyesun03** [comment]
이번은 코멘트 남길 내용이 떠오르지 않습니다.
패턴을 맹목적으로 사용하면 안된다에 매우 공감하지만 한편으로는 과하게 해본 경험이 있기에 정도를 스스로 깨닫게 되는거 같기도합니다 ㅎㅎ

**Comment by usageness** [comment]
> 망치를 들면 모든 것이 못으로 보인다는 격언처럼 패턴을 익힌 후에는 모든 설계 문제를 패턴으로 해결하려고 시도하기 쉽다.
> 조슈아 케리에브스키는 이를 ‘패턴 만능주의’라고 부른다[Kerievsky04]. (p.522)

무작정 어떤 패턴을 넣을까 고민하던걸 들킨 느낌이라 뜨끔하네요 😂

> 실무자들은 학습의 마지막 단계인 ‘거침없는 수준’에 이른 상태이기 때문에 심지어 실무자들의 옆에 앉아 설계가 진행되는 과정을 지켜보더라도 설계자가 따르는 절차와 찰나의 순간에 머릿속에 떠올랐던 트레이드오프 과정을 완벽하게 이해할 수 없다. 실무자들은 정해진 절차를 따르지 않는다. (p.532)

왠지 그 날 학교에서 느꼈던 것만 같은 기분이...

---

TS를 처음할때 공변성/반공변성/이변성 이런걸 보면서 엄청 헷갈리는 개념들이라고 생각했는데,
본편과 부록에서 타입 구조부터 설명해주니까 흐름이 눈에 들어오는 것도 같아요 :)
이외에 별다른 코멘트는 없습니다!

**Comment by pawful-code** [comment]
행동 호환성

page 573 ~574
 타입 계층은 동일한 메시지에 대한 행동 호환성을 전제로 하기 때문에 여기서 언급하는 모든 방법은 타입 계층을 구현하는  방법인 동시에 다형성을 구현하는 방법이기도 하다. 이번 장에서 설명하는 방법을 자세히 살펴보면 공통적으로 슈퍼타입에 대해 전송한 메시지를 서브타입별로 다르게 처리할 수 있는 방법을 제공한다는 사실을 알 수 있다. 이 방법들은 12장에서 설명한 동적 메서드 탐색과 유사한 방식을 이용해 적절한 메서드를 검색한다.

여기서 제시하는 방법을 이용해 타입과 타입 계층을 구현한다고 해서 서브타이핑 관계가 보장되는 것은 아니다. 13장에서 설명한 것처럼 올바른 타입 계층이 되기 위해서는 서브타입이 슈퍼타입을 대체할 수 있도록 리스코프 치환 원칙을 준수해야 한다. 리스코프 치환 원칙은 특정한 구현 방법에 의해 보장될 수 없기 때문에 클라이언트 관점에서 타입을 동일하게 다룰 수 있도록 의미적으로 행동 호환성을 보장하는 것은 전적으로 우리의 책임이다. 뒤에서 다루는 다양한 구현 방법을 이용할 때 타입 사이에 리스코프 치환 원칙을 준수하도록 만드는 책임은 우리 자신에게 있다는 사실을 기억하라.



Question) 리스코프 치환 원칙을 어기더라도 컴파일 타임에 잡히지 않는 코드들이 있을 것이라고 판단되는데 이러한 일을 예방하고 리스코프 치환 원칙을 준수하기 위해서 현업에서는 어떠한 활동을 하는지가 궁금합니다.

이러한 일을 예방하기 위해 코드 리뷰 등이 제일 좋겠지만 테스트 코드등을 통한 자동화 사례가 있다면 더욱 좋을것 같습니다.
 
page 581

클래스와 타입 간의 차이를 이해하는 것은 중요한 일이다. 객체의 클래스는 객체의 구현을 정의한다. 클래스는 객체의 내부 상태와 오퍼레이션 구현 방법을 정의하는 것이
고 객체의 타입은 인터페이스만을 정의하는 것으로 객체가 반응할 수 있는 오퍼레이션의 집합을 정의한다. 하나의 객체가 여러 타입을 가질 수 있고 서로 다른 클래스의 객체들이 동일한 타입을 가질 수 있다. 즉, 객체의 구현은 다를지라도 인터페이스는 같을 수 있다는 의미다. 클래스와 타입 간에는 밀접한 관련이 있다. 클래스도 객체가 만족할 수 있는 오퍼레이션을 정의하고 있으므로 타입을 정의하는 것이기도 하다. 그래서 객체가 클래스의 인터페이스라고 말할 때 객체는 클래스가 정의하고 있는 인터페이스를 지원한다는 뜻을 내포한다[GOF94].

요약하면 아래와 같다고 생각하는데 정정할 점이 있거나 다른 의견이 궁금합니다.
1. 타입은 객체가 행할 수 있는 동작의 집합이다.
2. 객체의 내부 상태 및 동작을 클래스에서 정의 하기 때문에 클래스를 작성하면 한 객체의 타입을 정의한 것으로 볼 수 있다.
3.  인터페이스를 통해 타입의 일부분 혹은 전체를 정의할 수 있다.

question 요구되는 동작이 많은 객체의 경우 코드를 보았을 때 상속 받는 부분이 길어져서 가독성이 떨어질 것 같고 디버깅에 긴 시간이 필요할 것 같은데 이 시간을 줄이는 노하우가 있을까요?

**Comment by genie-youn** [comment]
https://www.notion.so/23-12-17-12-2bb231dbb0654b0e9806a4fd657939dc?pvs=4

**Comment by hjsung809** [comment]
p 522
'정당한 이유 없이 사용된 모든 패턴은 설계를 복잡하게 만드는 장애물이다.'
공감되는 말이지만, 정당한 이유를 넓은 의미로 생각할줄 알아야할것 같습니다.
 협력의 일관성을 지키기 위해서 적용할 수 도 있는데, 단순히 그 부분의 코드만 보고 설계만 복잡해졌다고 생각하기 쉬운것 같습니다.


p529
'만약 요구사항이 빠르게 진화하는 코드에서 의존성 역전 원리가 적절하게 지켜지지 않고 있다면 그곳에는 변경을 적절하게 수용할 수 없는 하향식의 절차적인 코드가 존재할수 밖에 없다' 
-> 의존성이 역전되어있다고 객체지향은 아니지만, 객체지향이면 의존성역전이 되어있다. 라고 이해할수 있을것 같습니다. 같은 생각인지 궁금합니다.

p530
'우리는 프레임 워크가 적절한 시점에 실행할것으로 예상되는 코드를 작성하는것이다.'
-> 이 부분이 객체지향에 익숙하지 않은 개발자들이 어려움을 느끼는 부분인것 같습니다. 정확히 어떻게 실행되는지 모르면 불안해서 그냥 전부 절차적으로 구성한다는 이야기를 많이 들은것 같습니다.

계약에 의한 설계.
->리스코프 치환원칙에 대해 깊게 이해할 수 있어서 좋았습니다.

p 540
불변식에 대해 헷갈리기 시작했습니다.
사전 조건과 사후 조건이 만족했는데 불변식을 만족하지않는 경우가 있을 수 있을까요?
불변식을 사전 조건과 사후 조건으로 나눌수 있는 느낌이네요

**Comment by wlsh44** [comment]
> 프레임워크가 제공하는 메인 프로그램을 재사용하고 이 메인 프로그램이 호출하는 코드를 애플리케이션 개발자가 작성해야 한다. 따라서 자신이 작성한 코드가 호출될 것인지를 스스로 제어할 수 없다. 제어 주체는 자신이 아닌 프레임워크로 넘어간 것이다. 530p

코드와 설계의 재사용을 위해 제어의 역전이 반드시 필요하긴 하지만 종종 프레임워크에 대한 학습의 진입 장벽을 높이는 원인이기도 한 것 같아요..
오늘도 새로 시작한 사이드 프로젝트에 안 써본 기능을 적용하고 테스트를 해보려다, 원하는 대로 동작하지 않아 1시간 동안 스프링 디버깅만 한 기억이..
