### ISSUE TITLE
[클린 아키텍처] 24.01.28/1주차 - 4장 구조적 프로그래밍 ~ p.36

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#131]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by hjsung809** [comment]
갑자기 드는 질문인데 우리 스터디에서 질문의 형태로 남겨야 하는건가요? 감상평으로 남기는걸 경계하시는것 같던데 이유가 있을까요?



p3
"나는 천국에 가 보았다. ... 당신의 경험을 보자. 전혀 반대의 상황을 ..."

너무 패기로워서 홀리게 되는 말인것 같습니다. 아무리 설계가 뜻대로 되서 변경의 비용이 적고 결함률이 낮은 소프트웨어를 만들어도 현실 행복과 트레이드 오프한거라면 천국이 아닐것 같다는 생각을 했습니다
소프트웨어와 별개로 직장에서 인간 관계도 좋아야하고 급여도 만족스러워야하고 건강해야 할것 같은데 저자가 말한 천국에 그런것들도 다 포함될지 궁금합니다 ㅋㅋㅋ
제대로 만들려다가 정치적으로 다퉈서 인간관계 틀어지고 야근으로 인해 건강을 잃게 된건 아닐까 하는 우려가 들기도 하네요 ㅋㅋ

**Comment by pawful-code** [comment]
3장 요약
세가지 프로그래밍 패러다임을 소개하고 각 패러다임이 프로그래밍을 하는데 있어서 제약을 두는 점을 설명한다.
프로그래밍 패러다임의 포함관계


명령형(Imperative)
-절차적(procedual)
-객체 지향적(Object-oriented)

선언형(Declrative)
-함수형(functional)

제어 흐름 [1](https://en.wikipedia.org/wiki/Control_flow) - (순차, 분기, 반복)

> 구조적 프로그래밍(structured) - 제어 흐름의 직접적인 전환에 대해 규칙을 부여한다
제어 흐름 - 분기문 - go to, jump 와 같은 "비/무조건 분기문 제약(Unconditional Branch)"

> 객체 지향 프로그래밍 - 제어 흐름의 간접적인 전환에 대해 규칙을 부여한다


> 함수형 프로그래밍 - 할당문에 규칙을 부여한다.

패러다임과 프로그래밍 언어(java, c, ...)의 관계가 자주 헷갈렸는데 위의 패러다임을 지원하는 범위와 그 방식이 프로그래밍 언어마다 다른 것으로 정리하면 될까요?

중간저장

**Comment by usageness** [comment]
지수 선배가 강조하신 **모든 책은 서문부터 읽기**
"아키텍쳐 규칙은 동일하다" 라는 말을 보니 
결국 백엔드는 json 상하차, 프론트는 json 뷰어라는 말이 생각나네요 ㅋㅋ

이번 분량에는 특별히 들어가는 내용이 없어서 술술 읽었습니다.
문장들을 보고 있으면 지수 선배가 스터디에서 하셨던 말들이 오버랩되네요...

**Comment by wlsh44** [comment]
> 내가 이들 세 가지 프로그래밍 패러다임을 소개하면서 신중하게 설정한 패턴이 보일 것이다. 각 패러다임은 프로그래머에게서 권한을 박탈한다. 어느 패러다임도 새로운 권한을 부여하지 않는다. 각 패러다임은 부정적인 의도를 가지는 일종의 추가적인 규칙을 부과한다. 즉, 패러다임은 무엇을 해야 할지를 말하기보다는 무엇을 해서는 안 되는지를 말해준다. 세 가지 패러다임 각각은 우리에게서 goto문, 함수 포인터, 할당문을 앗아간다.(27p)

인상깊은 부분이어서 적어봤습니다. 근데 객체지향이 함수 포인터를 사용하지 못하게 하는건 어떤 이유라고 설명해야 정확할까요?
