### ISSUE TITLE
[클린 아키텍처] 24.02.04/2주차 - 9장 LSP: 리스코프 치환 원칙 ~ p.86

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#132]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by pawful-code** [comment]
46P

> 이 말이 완전히 옳은 말이 아니긴 하다. OO 언어는 다형성을 제공하지는  못했지만, 다형성을 좀 더 안전하고 더욱 편리하게 사용할 수 있게 해준다.  함수에 대한 포인터를 직접 사용하여 다형적 행위를 만드는 이 방식에는  문제가 있는데, 함수 포인터는 위험하다는 사실이다. 이러한 기법은 프로그래머가 특정 관례를 수동으로 따르는 방식이다. 즉, 이들 포인터를 초기화하는 관례를 준수해야 한다는 사실을 기억해야 한다. 그리고 이들 포인터를 통해 모든 함수를 호출하는 관례를 지켜야 한다는 점도 기억해야 한다. 만약 **프로그래머**가 **관례**를 지켜야 한다는 사실을 **망각**하게 되면 **버그가 발생**하고, 이러한 버그는 **찾아내고 없애기가 지독히도 힘들다.**

과거 비슷한 내용으로 많이 헷갈려서 제 이해가 맞는지 확인 겸 고민해 보고자  적어둡니다.
1. 특정 패러다임을 따르는 **언어는** 반드시 특정한 방법에 제약을 거는 것인가?
&emsp;(객체 지향은 포인터를 못쓰는 것인가?)  패러다임과 무관하게  언어 &emsp;차원에서 개발자에게 제약을 가하는 사례로 볼 수 있을 것 같습니다. &emsp;다른 사례가 있는지 궁금합니다.
2. 특정 패러다임을 따르는 언어가 패러다임에서는 존재하지만 지원하지 않는 기능이  있는가?
&emsp;JAVA의 경우 **다중 상속**을 지원하지 않고 인터페이스를 통해서 적용하는

48P~49P
> 실제로 모든 호출 함수는 피호출 함수가 포함된 모듈의 이름을 명시적으로 지정해야 한다. 이러한 제약 조건으로 인해 소프트웨어 아키텍트에게 남은 선택지는 별로 없었다. 즉, **제어흐름은 시스템의 행위에 따라 결정되며, 소스 코드 의존성은 제어흐름에 따라 결정된다.**

>이러한 접근법을 사용한다면, OO 언어로 개발된 시스템을 다루는 소프트웨어 아키텍트는 시스템의 소스 코드 의존성 전부에 대해 방향을 결정할 수 있는 절대적인 권한을 갖는다. 즉, 소스 코드 의존성이 제어흐름의 방향과 일치되도록 제한되지 않는다. 호출하는 모듈이든 아니면 호출 받는 모듈이든 관계없이 소프트웨어 아키텍트는 **소스 코드 의존성을 원하는 방향으로 설정** 할 수 있다.

제어 흐름 역전(Inversion of Control :IoC)과/ 의존성 역전(Dependency inversion:DI) 이 헷갈려서 요약하면 다음과 같은 걸까요?

결론: 제어 흐름 역전을 구현 하기 위해  의존성 역전을 이용할 수 있다.

제어흐름 역전
: 하위 함수들이 필요 시 상위 함수를  호출하는데 이용할 수 있다.  
&emsp;일반적인 제어흐름 : (상대적으로) 상위 모듈 -> (상대적으로) 하위 모듈
&emsp;제어흐름 역전 : (상대적으로) 하위 모듈 -> (상대적으로) 상위 모듈

의존성 역전
(중간저장)

**Comment by usageness** [comment]
![image](https://github.com/TeamCrazyPerformance/http/assets/28296575/bdb49c1c-fd18-49e4-b74f-617a4f843d88)

슬픈 사연으로... 일단 여기에 저장해두겠습니다 ㅠㅠ 

p. 41
> 하지만 OO를 제공한다고 주창한 언어들이 실제로는 C 언어에서 누렸던 완벽한 캡슐화를 약화시켜 온 것은 틀림없다.

캡슐화의 관점에서 바라보고 이후에 등장한 언어들이 오히려 캡슐화를 약화시켰다는 관점은 새롭네요.
다만, 약화된 캡슐화는 개발자의 관점에서 나쁘다고만 볼 수는 없을것 같습니다.
책에서 말했듯 public, private 등으로 최악의 상황은 막으면서 오히려 생산성을 증대시키는 역할을 했다고 생각해요.
이후에 **"OO언어는 이러한 관례를 없애주며, 실수할 위험을 없애주었다"** 라는 문장이 위의 말들과 비슷하게 들리네요.

p. 71
> 모든 클래스는 반드시 단 하나의 메서드를 가져야 한다는 주장에 근거하여
> 앞의 해결책에 반대할 수도 있다. 하지만 이 주장은 현실과는 전혀 다르다.

어디서 저런 주장이 나왔는지 궁금해서 chat GPT에게 물어봤는데... 찾을수가 없네요.

```
Q. "모든 클래스는 단 하나의 메서드만을 가져야 한다" 라는 주장의 출처를 알려줘
A.
"모든 클래스는 단 하나의 메서드만을 가져야 한다"는 주장의 출처를 정확하게 찾기는 어려운 것으로 알려져 있습니다.
이 주장은 일반적으로 "단일 책임 원칙(Single Responsibility Principle)"에 대한 잘못된 해석으로 인해 나온 것으로 생각되며,
여러 원칙 중 하나인데도 특히 이런 형태로 언급된 적은 적습니다.

단일 책임 원칙은 클래스나 모듈은 단 하나의 변경 이유만을 가져야 한다는 원칙으로,
클래스가 하나의 책임을 수행하고 이를 변경할 이유가 하나여야 한다는 것을 강조합니다.
그러나 이것이 반드시 "단 하나의 메서드만 가져야 한다"로 해석되어서는 안 됩니다.
```

**Comment by eagleda** [comment]
8장 함수형 프로그래밍
> 클로저에서는 x와 같은 변수가 한 번 초기화되면 절대로 변하지 않는다. ..함수형 언어에서 **변수는 변경되지 않는다**

함수형 프로그래밍을 모르는 입장에서 변경되지 않은 변수란 말은 기이하게 느껴지네요.
모든 변수가 const같은 상수 선언이 되어있다 생각하면 될까요.

2부 결론
>지난 반세기 동안 우리가 배운 것은 해서는 안 되는 것에 대해서다.
이 사실을 깨닫는다면 우리는 환영받지 못할 사실, 즉 소프트웨어는 급격
히 발전하는 기술이 아니라는 진실과 마주하게 된다. 1946년 앨런 튜링이 전
자식 컴퓨터에서 실행할 거의 최초의 코드를 작성할 때 사용한 소프트웨어 
규칙과 지금의 소프트웨어 규칙은 조금도 다르지 않다.

**Comment by wlsh44** [comment]
1988년 바바라 리스코프Barbara Liskov는 하위 타입subtype을 아래와 같이 정의했다.
> 여기에서 필요한 것은 다음과 같은 치환substitution 원칙이다. S 타입의 객체 o1 각각에 대응하는 T 타입 객체 o2가 있고, T 타입을 이용해서 정의한 모든 프로그램 P에서 o2의 자리에 o1을 치환하더라도 P의 행위가 변하지 않는다면, S는 T의 하위 타입이다.

이 정의는 볼 때마다 어렵다고 느껴지는 것 같네요.. 그러면서도 오브젝트에서 클라이언트 관점으로 봐야 한다는 부분이 설명을 정말 잘 한 것 같다는 생각이 계속 들었습니다.
