### ISSUE TITLE
[클린 아키텍처] 24.02.18/3주차 - 14장 컴포넌트 원칙 ~ p.138

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#133]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by pawful-code** [comment]
P92

> 이러한 이유로 DIP를 논할 때 운영체제나 플랫폼 같이 안정성이 보장된 
> 환경에 대해서는 무시하는 편이다. 우리는 이들 환경에 대한 의존성은 용납
> 하는데, 변경되지 않는다면 의존할 수 있다는 사실을 이미 알고 있기 때문
> 이다. 
> 우리가 의존하지 않도록 피하고자 하는 것은 바로 변동성이 큰volatile 구체
> 적인 요소다. 그리고 이 구체적인 요소는 우리가 열심히 개발하는 중이라 자
> 주 변경될 수밖에 없는 모듈들이다. 
> 

상속 대신 interface를 통한 메소드 구현이 유연한 설계를 갖는데 이전 회의에 동의하였다 하지만 '그렇다면 왜 상속은 아직도 남아서 쓰이는가'를 고민하고 있었다. 문득 개발 초기에는 interface를 사용하였지만 후에  SW가 안정된 단계에 이르렀을 때 변경점이 없다고 판단되거나 누락 및 변경 되서는 안되는 기능들을 상속을 통해 강제하면 가독성을 높이고(interface 선언부가 줄어들기 때문에) 뒤에 들어와 개발되는 과정에 히스토리와 도메인 지식이 부족한 개발자의 휴먼 에러를 줄일 수 있지 않나 생각하였다. 

독자가 가질 수 있는 이러한 생각을 서문에 간략하고 확실하게 (개발 초기 단계, 변경점이 많은 모듈) 제한하고 주장을 펼치는게 인상깊었다. 해당 챕터를 다 읽어갈 무렵 든 생각이었는데 앞 부분에 이미 그러한 생각을 할 줄 알고 있었다는 듯 적혀있는 문장에 본인의 경솔함을 깨달을 수 있었다.

**Comment by usageness** [comment]
p.114
>일반적으로 프로젝트는 삼각형의 오른쪽에서 시작하는 편이며, 이때는 오직 재사용성만 희생하면 된다. 프로젝트가 성숙하고, 그 프로젝트로부터 파생된 또 다른 프로젝트가 시작되면, 프로젝트는 삼각형에서 점차 왼쪽으로 이동해 간다. 즉, 프로젝트의 컴포넌트 구조는 시간과 성숙도에 따라 변한다는 뜻이다. 

어느정도 성숙한 팀이더라도, 삼각형의 오른쪽(재사용성)에서 시작하는건 어쩔 수 없다고 느껴지네요.
프로젝트는 단순히 내부 구성원의 역량 뿐 아니라 개발 외적인 요소들도 무시할 수 없이 큰 영향을 미치고 있더라구요.
언제 삼각형의 모양을 바꾸어야 하는지, 어떻게 지금의 개발 속도를 유지해나가며 모양을 바꿔나갈지도
신중하게 고려해야 할 부분인것 같습니다.

**Comment by eagleda** [comment]
## 4부 컴포넌트 원칙
CCP 설명에서 컴포넌트 수준의 SRP라고 나온 것,  클래스 간의 의존성을 관리하듯 컴포넌트 간에서의 의존성을 관리해야한다는 부분 등 전반적으로 이전까지의 내용을 컴포넌트 단위로 올려서 적용한다는 느낌이 들었습니다.
