### ISSUE TITLE
[클린 아키텍처] 24.02.25/4주차 - 17장 경계: 선 긋기 ~ p.183

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#134]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by pawful-code** [comment]
p.143

> 아키텍처의 주된 목적은 시스템의 생명주기를 지원하는 것이다. 좋은 아키텍처는 시스템을 쉽게 이해하고, 쉽게 개발하며, 쉽게 유지보수하고, 또 쉽게 배포하게 해준다. 아키텍처의 궁극적인 목표는 시스템의 수명과 관련된 비용은 최소화하고, 프로그래머의 생산성은 최대화하는 데 있다.

임베디드 업종 회사에 SW 디자이너로 요구사항 분석을 주 업무로 하다 보면 V모델을 제법 잘 준수하는 편으로 변경이 가해질 수 있는 부분 마다 구현에 주의할점이 적힌 아키텍처 관련 문서를 읽을 때면  매번 감탄하곤 한다. 다만 매번 읽었고 유의했다는 느낌만 가지고 다들 개발에 착수하여 항상 테스트 시점에서 문제가 발생하고 종종 인수 테스트 직전에 버그가 발생하여 다들 얼굴을 붉히는 일이 만들어지는데 아직 어떻게 해결할 수 있을지 고민이 많다.


> 요컨대, 우리가 도달하려는 목표는 뚜렷하지 않을 뿐만 아니라 시시각각 변한다. 현실 세계에 온 것을 환영한다.

현실세계에 온 것을 환영한다.는 문구에 문득 이해관계자 (고객과 엔지니어)간의 입장 차이가 떠오르는 일화가 있어서 공유해보고자 한다.  현재 업무에 대부분은 고객의 요구사항을 인건비가 싼 나라에 위치한 기술팀에게 전달하는 역할을 하며 개발일정을 조율하고 있다. 고객은 요구 사항을 표출하지 못하고 개발자는 요구 사항에 의도를 못 읽는 경우를 주로 본다.
 
고객 : (A를 하고 싶기에) SW의 B를 변경하고 싶다고 함. (B는 A를 해결하기 위한 결정적인 부분이 아님)
기술 담당자: SW의 B는 고객님이 원하는 대로 변경이 가능하다
나: 해당 변경은 가능할지 모르나 결국 A를 이룰 수 없다.

신입인 관계로 의견은 묵살 되었고 이후 대화는 실질적으로 고객과 기술 담당자 간에 오고 가며 말을 전달하는 역할만 하였다.
 변경이 결정된 이후 변경된 SW가 적용되기 전에 시스템 테스트를 할 것을 자원했고 A를 할 수 없음을 측정 결과를 통해 밝혀 내었다. 결국 측정 데이터를 기준으로 고객의 요구사항을 만족시키기 위한 회의를 다시 진행한 경험이 있다. 결국 B의 변경 계획은 취소 되었다.

**Comment by hjsung809** [comment]
p 143
"아키텍처의 역할은  수동적이며 피상적인 것이지 능동적이거나 본질적인 것은 아니다"
-> 중요한 역할이지만 능동적이거나 본질적이지 않다는 말이 인상 깊었습니다. 어디선가 소프트 웨어가 하는 일을 그대로 사람이 해도 가치가 창출된다라는 글을 본적 있는 것 같은데, 실제로 하는 일이 본질적인것이고 아키텍처는 그 시스템을 보조하는 것이라는 통찰이 좋았습니다.


p 146
"유지보수의 가장 큰 비용은 탐사와 이로 인한 위험부담에 있다."
소프트웨어의 핵심 로직이 추상적이여야 하는 이유라고 생각합니다. 변경해야할 부분과 관련있는 추상적인 핵심 로직에서 시작해서 타고 들어갔을때 자연스럽게 변경해야 하는 부분이 보인다면 좋은 설계라고 생각합니다.

p146
선택 사항 열어 두기
"소프트 웨어는 두 종류의 가치, 즉 행위적 가치와 구조적 가치를 지닌다. 이 중에서 두번째 가치가 더 중요한데, 소프트웨어를 부드럽게 만드는 것은 바로 이 구조적 가치이기 때문이다."
-> 본질적인 행위적 가치보다 보조적인 구조적 가치가 더 중요하다고 말하는게 신기한것 같습니다. 소프트웨어의 측면에서 그러한게 아닐까 합니다.


p 156
"앞서 서술한 바와 같이 좋은 아키텍처는 다음을 지원해야 한다."
"아키텍처가 ~를 지원해야 한다." 라는 말이 "~ 측면의 아키텍처가 존재해야한다." 라는 말로 받아드려도 될까요?
예를 들면 "유스 케이스 측면의 아키텍처가 존재해야한다." 처럼요.

그리고 아키텍처가 시스템 수준의 추상화 같다는 생각을 했습니다. "유즈 케이스에 대한 추상화가 있어야한다" 그래서 시스템의 의도를 알기 쉽고, 한눈에서 볼 수 있으며 변경하기 쉽다. 이런식으로요.

p 161
"계층을 가로지르는, 얇은 수직적인 유즈케이스로 시스템을 분할할 수 있다"
수평과 수직으로 자르고 나면 나뉜 각 부분들이 매우 간단해지는 것 같습니다. 유즈 케이스를 잘게 나누는 것과 풍부한 도메인 모델을 만드는 것이 같이 될 수 있을까요? 매우 간단한 부분하게 만든 시점에 모델이 풍부한 의미가 적어지는게 아닌가 하는 느낌이 들다가도.. 별개인가 싶기도 하네요.

p 166.
아키텍처의 경계를 나눌때, 소스코드 -> 배포 -> 서비스 순으로 해서 서비스로 갈 수 있는 선택권을 열어두라는 점이 좋았습니다.
