### ISSUE TITLE
[클린 아키텍처] 24.03.24/6주차 - 27장 클린 아키텍처 ~ p.259

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#136]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by pawful-code** [comment]
p227
> 각 아키텍처 경계마다 경계 가까이 숨어 있는 험블 객체 패턴을 발견할 수 있을 것이다. 경계를 넘나드는 통신은 거의 모두 간단한 데이터 구조를 수반할 때가 많고, 대개 그 경계는 테스트하기 어려운 무언가와 테스트하기 쉬운 무언가로 분리될 것이다. 그리고 이러한 아키텍처 경계에서 험블 객체 패턴을 사용하면 전체 시스템의 테스트 용이성을 크게 높일 수 있다.

험블 객체 패턴을 몰라서 조사하게 된 것을 남깁니다.[1]

적용 대상 : '테스트가 어렵거나 불가능한' 'program element'를 그대로 두면 bug의 발생이 쉽거나 변경이 어렵기 때문에 원본 object를 2개의 object로 쪼갠다.
- 테스트 가능한 logic과 요소를 분리한 object
- 쪼개지고 남은 object (Humble object) 

주 사용처: UI

[ref]
[1] https://martinfowler.com/bliki/HumbleObject.html (humble obj pattern )
[2] https://martinfowler.com/articles/humble-dialog-box.html (humble이라고 불리게된 이유)
