### ISSUE TITLE
[클린 아키텍처] 24.03.31/7주차 - 30장 데이터베이스는 세부사항이다 ~ p.296

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#137]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by pawful-code** [comment]
> 소프트웨어는 닳지 않지만, 펌웨어와 하드웨어에 대한 의존성을 관리하지 않으면 안으로부터 파괴될 수 있다.


268page

현재 유지보수 중인 장비 특정 HW 플랫폼에서 소규모 변경이 가능한 정도의 firmware와 (driver rtos scheduling 포함) 어플리케인션이 섞여있다. 아키텍처상으로 분리되어있지만 여전히 이를 수정하는 팀은 프로그래밍 지식 보다는 HW지식이 뛰어난 경우가 많아 '동작하게끔'만 작성하여 

> 임베디드 엔지니어가 아닌 엔지니어들 또한 펌웨어를 작성한다! 임베디드 엔지니어가 아닌 당신도 코드에 SQL을 심어 놓거나 "개발하는 코드 전반에 플랫폼 의존성을 퍼뜨려 놓는다면, 본질적으로 펌웨어를 작성하는 셈이다. " 안드로이드 앱 개발자 역시 업무 로직을 안드로이드 API로부터 분리하지 않는다면 펌웨어를 작성하는 셈이다.

269page

펌웨어의 모호한 정의를 명쾌하게 설명한 문장 같다.
Q1) OS가 되지 못한 , 드라이버와 같은 , .... 기타 여러 모호한 정의 보다 플랫폼(system, hw, os, sw, ...)의 경계에서 다른 계층에 의존하는 소스코드를 펌웨어로 본다면 옳게 이해한 것인지 의견이 궁금하다.


> 전체 제품은 가장 윗단부터 밑바닥까지 모두 하드웨어/기술 의존적이었고, 엉킨 것을 풀 수 없었다. 전체 제품이 본질적으로 펌웨어가 되어버린 것이다.

270page

RTOS 와 펌웨어 HW(저장장치 및 주변장치)와 SW (드라이버 등)에 의존성이 강한 코드들을 통해 가공할 data를 수집하는 이상 필연적인 일인 듯 하다. 데이터를 가공하는 단계에서 비슷한 값이 비슷한 변수가 여러개 생성되는데 고객의 요구사항에 따라 중간에 변수를 가져가는 경우가 있어서 히스토리를 모르는 이상 접근하기도 어려운 코드들이 많다.

> 하지만 이런 것들은 상관이 없었다. 단지 고객은 전적으로 RDBMS를 원했다. 

295page
공학 외적인 이유로 기술 도입을 원하고 적용을 요청하지만 적용이후 발생하는 문제를 하청업체에 돌리는 경우가 있다. 이에 대해 예민한 근 1년을 보냈는데 결국 모두가 겪을 수 밖에 없는 일이라는것에 위로를 받는다.

**Comment by hjsung809** [comment]
p264
테스트 API는 없는게 낫지않나 싶습니다.
유지보수 비용도 클 것 같고..
테스트 API가 잘 이해가 안됩니다. 테스트 구조를 애플리케이션 구조로부터 결합을 분리하는 게 목표라는데 뭘까요..? 
예를들면 어떤 API를 호출하기 위해서는 인증 토큰이 필요하고 이 인증 토큰을 얻기 어려울때, 인증 토큰을 목킹해주는 API 같은걸 말하는 걸까요?

**Comment by eagleda** [comment]
> 소프트웨어는 닳지 않지만. 펌웨어와 하드웨어에 대한 의존성을 관리하지 않으면 안으로부터 파괴될 수 있다.

변경될 수 있는 부분에 대해 의존성을 가지게 하지 말라는 조언의 연장선처럼 보입니다..

> "그리고 빠르게 만들어라." 코드를 리팩터링해서 '요구되는' 성능을 만족시켜라 271p.
