### ISSUE TITLE
[GoF 디자인패턴] 6주차 ~ 5.9 전략

### ISSUE THREAD

**Issue by lallaheeee** [TeamCrazyPerformance/http#14]

**Comment by hyesun03** [comment]
# Observer
## p.387 3번
여기서 (a)가 **push 모델**을, (b)가 **pull 모델**을 말하는게 맞나요??

## p.388 6번
6번 항목 이름인 **감시자별 갱신 프로토콜을 피합니다**라는 말 자체가 이해가 안가요.

## p.389 첫 번째 문단
이 두 줄이 이해가 안가요.
```
푸시 모델을 사용하면 감시자 클래스의 재사용성이 떨어지게 됩니다. Subject 클래스는 Observer 클래스에 대한 어떤 거정을 하게 되는데, 이런 가정이 늘 맞는 것은 아닙니다.
```

## 기타
SNS에 있는 following, follower 기능이 생각났는데, 이것도 Observer 패턴으로 구현할까요?

**Comment by hyesun03** [comment]
# State
## p.400 구현4 동적 상속을 이용하는 방법
결국은 어지간한 객체지향 언어에서는 할 수 없다는 게 결론 같아요. 이거 관련된 내용을 좀 더 알고싶은데, 검색해도 마땅찮은게 안나와서.. 혹시 이 부분에 대해서 찾아본게 있으면 공유 부탁드립니다ㅜㅜ

**위임 기반 언어**라는 용어를 한국어로 검색하면 아무것도 안나오고, **delegation-based programming languages**라고 검색을 해봤더니 [학술자료](https://www.researchgate.net/profile/Jacques_Malenfant/publication/221321991_On_the_Semantic_Diversity_of_Delegation-Based_Programming_Languages/links/0912f50b86a390066a000000/On-the-Semantic-Diversity-of-Delegation-Based-Programming-Languages.pdf) 같은것만 나옵니다. 저걸 다 읽긴 귀찮고, 좀 이해하고 싶은데 어렵네요.. 

## 기타
이 패턴과는 상관없는 내용이지만... 여러가지 찾아보면서 [Delegation vs Inheritance](https://www.geeksforgeeks.org/delegation-vs-inheritance-java/)의 좋은 예를 찾았어요.

**Comment by hyesun03** [comment]
# Strategy 
## p.408 활용성 2번
여기서 말하려는 거는 **'상황에 맞게 알고리즘을 골라야(바꿔야)할 때 쓰면 좋다'**로 이해했는데 맞겠죠?

## p.412 구현 2번
컴파일 타임에 Strategy 객체를 확정하고, 런타임에 바꿀일이 없으면 굳이 이 패턴을 써야할 이유가 있나요?

## p.413 구현 3번
Context에 default로 수행할 알고리즘(기본 행동)들을 정의 해 놓는다는 말이죠?
이 기본 행동을 수행해도 상관없으면 그대로 수행하고, 그게 아니라면 적절한 Strategy 구상 클래스 가져다 쓴다는걸로 이해했는데 맞을까요?

**Comment by lallaheeee** [comment]
> # Observer
> ## p.387 3번
> 여기서 (a)가 **push 모델**을, (b)가 **pull 모델**을 말하는게 맞나요??

저는 그렇게 이해했습니다! 


> 
> ## p.388 6번
> 6번 항목 이름인 **감시자별 갱신 프로토콜을 피합니다**라는 말 자체가 이해가 안가요.

> ## p.389 첫 번째 문단
> 이 두 줄이 이해가 안가요.
> 
> ```
> 푸시 모델을 사용하면 감시자 클래스의 재사용성이 떨어지게 됩니다.
> Subject 클래스는 Observer 클래스에 대한 어떤 거정을 하게 되는데, 이런 가정이 늘 맞는 것은 아닙니다.
> ```

제가 원문을 찾아왔습니다. ! 
> 원문을 찾아보면 다음과 같이 나와요!

```
> Avoiding observer-specific update protocols.
> Implementations of the Observer pattern often havethe subject broadcast additional information about the change. Thesubject passes this information as an argument to Update. The amountof information may vary widely.
> At one extreme, which we call the push model, the subjectsends observers detailed information about the change, whether theywant it or not. At the other extreme is the pull model;the subject sends nothing but the most minimal notification, andobservers ask for details explicitly thereafter.
> The pull model emphasizes the subject's ignorance of its observers, whereas the push model assumes subjects know something about theirobservers' needs. The push model might make observers less reusable,because Subject classes make assumptions about Observer classes thatmight not always be true. On the other hand, the pull model may beinefficient, because Observer classes must ascertain what changedwithout help from the Subject. 
```

* 도와줘 구글 ! *
```
관찰자 특정 업데이트 프로토콜을 피하십시오.

관찰자 패턴의 구현은 종종 주제가 변경에 대한 추가 정보를 브로드 캐스트합니다. 대상은이 정보를 Update의 인수로 전달합니다. 정보의 양은 크게 다를 수 있습니다.

우리가 푸시 모델이라고 부르는 극단적 인 한 가지 경우, 대상은 관찰자에게 변경 여부에 관계없이 변경에 대한 자세한 정보를 보냅니다. 또 다른 극단에는 풀 모델이 있습니다. 피험자는 가장 작은 알림 만 보내지 않으며 관찰자는 그 이후에 세부 사항을 명시 적으로 요청합니다.

풀 모델은 관찰자에 대한 피험자의 무지를 강조하지만, 푸시 모델은 피험자가 관찰자의 요구에 대해 무언가를 알고 있다고 가정합니다. 푸시 모델은 주제 클래스가 항상 참일 수는없는 관찰자 클래스에 대해 가정하기 때문에 관찰자를 재사용 할 수 없게 만들 수 있습니다. 반면, 관찰자 클래스는 주제의 도움없이 변경된 내용을 확인해야하기 때문에 풀 모델이 비효율적 일 수 있습니다.
```


> ## 기타
> SNS에 있는 following, follower 기능이 생각났는데, 이것도 Observer 패턴으로 구현할까요?

제가 했던 졸업작품에서 관심있는 태그를 follow 할수 있는 기능이 있었는데요 !
`Firebase Cloud messaging`의 Pub/Sub 이용해 이 기능을 구현했습니다! 

SNS의 팔로잉, 팔로워도 이 패턴을 이용해 구현하지 않았을까요?!
