### ISSUE TITLE
[GoF 디자인패턴] 7주차 ~ 5.11 Visitor 끝

### ISSUE THREAD

**Issue by lallaheeee** [TeamCrazyPerformance/http#15]

**Comment by hyesun03** [comment]
# Template Method
이 부분은 책 분량이 적기도 했고 쉬운 내용이었습니다.

## 기타 예제
- [java.util.Collections#sort()](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/util/Collections.java#L140)

Collections에 있는 sort()를 보면 [java.util.List#sort()](https://github.com/JetBrains/jdk8u_jdk/blob/8db9d62a1cfe07fd4260b83ae86e39f80c0a9ff2/src/share/classes/java/util/List.java#L476) 를 호출함을 볼 수 있습니다.

 List 인터페이스에 있는 sort()를 보면, abstract class안에 템플릿 메소드를 구현한 것이 아닌, `default` 키워드를 사용해서 템플릿 메소드를 구현할 것을 볼 수 있습니다.

Collections.sort()는 List.sort()를 호출하고,  List.sort()안에 구현된 디폴트 메소드는 구현클래스인 ArrayList의 listIterator 메소드를 호출함.

https://blog.naver.com/2feelus/220669520535

**Comment by genie-youn** [comment]
# Visitor

#### 클래스 계층 구조에 걸쳐서 방문한다. (p.432 1문단)
이터레이터는 동일한 타입에 대해서만 순회가 가능한데, 비지터는 동일한 부모 클래스가 없는 객체들도 방문할 수 있다. 비지터의 방문 대상은 관련될 필요가 전혀 없다.
> 근데 결국 누군가는 Composite가 됐든 컬렉션이 됐든 각 원소를 이터레이션 해주면서 `accept`를 호출해주어야 하는거 아닌가?

**Comment by KangJiJi** [comment]
# VIsitor

#### ObjectStructure(p.430 참여자)
존재 이유
> 모르겠음

#### 협력 방법
각 원소를 방문하며 순회해야 합니다.
> 순회를 왜 해야 하는가요?

#### 알고리즘에 특화된 자료 구조는 어떤 것이든지 방문자 속에 숨겨집니다.(431 결과 2번)
연산들을 분리했기 때문에 간단한 자료구조들이 방문자 속으로 이동한다는 뜻인가요?
> 잘 모르겠습니돠.

#### void CompositeElement:: Accept (Visitor& v) {...} (p.434 코드 부분 마지막)
이것이 ObjectStructure인가요?

#### 누가 책체 구조를 순회할 책임을 지는가? (p.435)
???....

**Comment by Kwoo4357** [comment]
# Visitor

## 활용성

> 다른 인터페이스를 가진 클래스가 객체 구조에 포함되어 있으며, 구체 클래스에 따라 달라진 연산을 이들 클래스의 객체에 대해 수행하고자 할 때

p.429 구조의 클래스 다이어그램을 보면 요소들이 Element 인터페이스를 따르고 있는데, 이 경우엔 이미 
객체들이 한 가지 인터페이스를 따르고 있는 것 아닌가요? 다른 인터페이스를 가진 객체들을 구조화시킨 객체 구조에 Visitor가 어떻게 사용되는지 궁금합니다.

## ObjectStructure
책을 읽어보면 ObjectStructure가 인터페이스가 서로 다른 객체들을 구조화(조직화?)시킬 수 있는 것 같은데, 이런 경우를 몰라서 어떻게 구조화 시키는지 모르겠습니다.

**Comment by hyesun03** [comment]
# Visitor
## 결과 4. 클래스 계층 구조에 걸쳐서 방문한다. (p.432 1문단)
저도 여기서 이해가 잘 안가긴 했는데.. Element 클래스 계통이랑 Visitor 클래스 계통이 있고, Visitor에게 접근을 열어주려면 Element 클래스 쪽 객체들도 자기 상태를 외부에 노출하는 꼴이잖아요.

Element 클래스쪽에서 내부 구현을 노출 하니까 MyType이든, YourType이든 `accept()`만 가지고 있다면, 구체적인 타입이랑 상관없다~~ 이런것 같기도하고... 쓰고나서 보니까 이것도 좀 말이 이상한것 같아요. '어떻게 인터페이스가 다른데 동일한 연산을 수행시킬 수 있는거지??' 이런 의문이 드네요.
