### ISSUE TITLE
2주차 5장 형식맞추기 ~ 8장 경계

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#2]

**Comment by GitKangJi** [comment]
p.119
	1. 왜 6-4가 6-3보다 좋은가요?
	2. 6-4가 6-3도 포함하고 있으면 더 좋지 않은가요? (상황에 맞는 값을 제공)

...지속적으로 추가중

**Comment by hyesun03** [comment]
# 5장
## p. 101 수직거리
`타당한 근거가 없다면 서로 밀접한 개념은 한 파일에 속해야 마땅하다. 이게 바로 protected 변수를 피해야 하는 이유 중 하나다.`는 이해가는데 부적절하게 protected 사용하고 어떻게 개선하는지, 개선하는 예제를 찾고 싶습니다..

## p. 105 수직거리
`[G35] getPageNameOrDefault 함수 안에서 "FrontPage" 상수를 사용하는 방법도 있다.` 이 말이 이해가 안갑니다...


# 7장
## p. 133 미확인 예외를 사용하라
미확인 예외라는것이 너무 세분화해서 예외 나누지 말고`catch(Exception e) {}`이런거 쓰라는건가요?

## p. 137 호출자를 고려해 예외 클래스를 정의하라
`한 예외는 잡아내고 다른 예외는 무시해도 괜찮은 경우라면 여러 예외 클래스를 사용한다.` 이 말이 이해가 안갑니다...     

## p. 140 null을 전달하지 마라
`정상적인 인수로 null을 기대하는 API가 아니라면 메서드로 null을 전달하는 코드는 최대한 피한다.` 에서 정상인수로 null을 기대하고 쓰는 경우가 있나요??

## p. 142 null을 전달하지 마라
`대다수 프로그래밍 언어는 호출자가 실수로 넘기는 null을 적절히 처리하는 방법이 없다. 그렇다면 애초에 null을 넘기지 못하도록 금지하는 정책이 합리적이다.` 에서 실수로 넘어오는 null을 적절히 처리하는 프로그래밍 언어가 있는지 궁금해졌습니다...
