### ISSUE TITLE
[리팩터링] 1주차 ~ 01 리팩터링: 첫 번째 예시

### ISSUE THREAD

**Issue by hyesun03** [TeamCrazyPerformance/http#37]
9월 12일 오전 10시 첫 스터디 (온라인)
@TeamCrazyPerformance/packet 

issue에는 assignees에 팀을 못넣는건지 안되네요ㅜㅜ

**Comment by hyesun03** [comment]
1장이라 그런가 가볍게 읽었습니다 ㅋㅋ

코드를 쪼개는 과정이나, 테스트 돌리는 과정 등 전반적으로는 동의를 하는데 변수명은 참을 수가 없네요...
33쪽에 변수 이름을 명확하게(??)한다고 리턴값으로 주는 변수명을 result로 짓는것...
34쪽에 접두어로 타입 이름을 붙이는데 명확하지 않다고 a를 붙이는것.....

제 개인적으로는 result라는 변수명은 테스트 작성할 때나, 알고리즘 문제 풀때나 쓰는 변수명인데 명확하지 않다고 생각합니다ㅋㅋ

사실 메서드명도 좀 맘에 안들어요 ㅜㅜ

**Comment by KangJiJi** [comment]
저도 result와 접두어 그리고 함수를 동사로 시작하지 않는 것? 이 신경쓰이는 부분이였습니다.

**Comment by kyr9389** [comment]
저는 성능 개선을 굉장히 중요하게 생각했었는데.. 저자는 **일단 리팩토링을 하고 개선은 나중에 하면 된다!** 라고 해서 좀 신기했습니다.

반복문을 바깥으로 빼내거나 해서 반복횟수가 많아지면 속도가 느려질 수 밖에 없다고 알고 있었는데,
백준 알고리즘 문제에 과몰입해서 그런건지...ㅎㅎ 크게 봤을때는 그렇게 큰 차이가 없다고 하니 그러려니 해야겠어요

**Comment by KangJiJi** [comment]
> 저도 result와 접두어 그리고 함수를 동사로 시작하지 않는 것? 이 신경쓰이는 부분이였습니다.

질의함수는 명사로 시작
