### ISSUE TITLE
[리팩터링] 3주차 ~ 05 리팩터링 카탈로그 보는 법

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#39]
@TeamCrazyPerformance/packet 

숙제 - 디자인패턴을 학습하지 않은 친구들은 전략패턴을 학습해오세요.

**Comment by seungg-0** [comment]
**1)전략 패턴이란?** 
객체가 할 수 있는 행위들 각각을 전략 클래스로 만들어 놓고,유사한 행위들을 캡슐화 하여 인터페이스를 정의
동적으로 행위의 수정이 필요한 경우 **행위를 직접 수정하지 않고 전략을 바꿔주는 방법으로 행위의 수정이 가능하도록** 만든 패턴

**2)전략패턴을 사용하는 이유** 
Ex) Train, Bus 클래스가 있고, 두 클래스는 Movable이라는 인터페이스를 구현했다고 가정한다.
그리고 Train과 Bus 객체를 사용하는 Client도 있다.

//구현
public interface Movable {
    public void move();
}

public class Train implements Movable{
    public void move(){
        System.out.println('선로를 통해 이동'); //기차는 선로를 통해 이동
    }
}
 
public class Bus implements Movable{
    public void move(){
        System.out.println('도로를 통해 이동'); //버스는 도로를 통해 이동
    }
}

public class Client {
    public static void main(String args[]){
        Movable train = new Train();
        Movable bus = new Bus();
       
        train.move();
        bus.move();
    }
}

도로를 통해 이동하던 버스가 시간이 지나 선로를 통해 이동할 수 있도록 개발되었을 때

public void move(){
    System.out.println('선로를 따라 이동');
}

Bus의 move()메서드를 바꿔주면 되는데, 이런 수정방식은 SOLID의 원칙 중 OCP에 위배된다.

그리고 이와같은 방식은 시스템이 확장되었을 때 **유지보수를어렵게 한다. ** 
또한 위의 선로를 통해 이동할 수 있는 교통수단이 여러개 추가되었을 때 move()메서드를 일일이 수정해야하며 **중복문제가 발생한다.** 

**3)전략 패턴 구현**
3.1)전략을 생성하는 방법

현재
-선로를 통해 움직이는 방식
-도로를 통해 움직이는 방식
두 가지가 존재한다.

움직이는 두 방식에 대해 전략 클래스를 생성해준다. (RailLoadStrategy, LoadStrategy)
두 클래스는 move()메서드를 구현하고 어떤 경로를 통해 움직이는지에 대해 구현한다.

RailLoadStrategy와 LoadStrategy 두 전략 클래스를 캡슐화하기 위한 MovableStrategy 인터페이스를 생성한다.

//구현
public interface MovableStrategy { //두 전략 클래스를 캡슐화하는 인터페이스
    public void move();
}
public class RailLoadStrategy implements MovableStrategy{
    public void move(){
        System.out.println("선로를 통해 이동");
    }
}
public class LoadStrategy implements MovableStrategy{
    public void move() {
        System.out.println("도로를 통해 이동");
    }
}

3.2)운송 수단에 대한 클래스를 정의
기차와 버스의 이동 방식을 move()메서드로 구현하지 않고, 전략의 움직임 방식을 사용하여 움직이도록 한다.
전략을 설정하는 메서드 'setMovableStrategy()'

//구현
public class Moving{
    private MovableStrategy movableStrategy;

    public void move();{
        movableStrategy.move();
    }

    public void setMovavleStrategy(MovableStrategy movableStrategy){
        this.movableStrategy = movableStrategy;
    }
}

public class Bus extends Moving{

}

public class Train extends Movint{

}

3.3)Train과 Bus객체를 사용하는 Client를 구현
public class Client {
    public static vlid main(String args[]){
        Moving train = new Train(); 
        Moving bus = new Bus();
     
        train.setMovableStrategy(new RailLoadStrategy()); //선로를 통해 움직이는 기차
        bus.setMovableStrategy(new LoadStrategy()); //도로를 통해 움직이는 버스

        train.move();
        bus.move();

        bus.setMovableStrategy(new RailLoadStrategy()); //선로를 통해 움직이는 버스 개발 (전략을 바꾸는 방법으로 행위 수정)
        bus.move();
    }
}

참고한 블로그 포스팅 : https://victorydntmd.tistory.com/292
