### ISSUE TITLE
[리팩터링] 5주차 ~ 8.2 필드옮기기

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#43]
@TeamCrazyPerformance/packet  

결혼기념일인 관계로 한주쉬고 11월 15일에 합니다.

axios 개발환경 설정하고 코드도 읽어오세여

**Comment by hyesun03** [comment]
결혼기념일 축하드려요~~!!!!! 🎉

**Comment by joi0104** [comment]
🎉🎉🎉
