### ISSUE TITLE
[리팩터링] 6주차 ~ 9.4 참조를 값으로 바꾸기

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#44]

**Comment by genie-youn** [comment]
320p

논리를 파이프라인으로 표현하면 이해하기 훨씬 쉬워진다.

**Comment by kyr9389** [comment]
313p
명령 - 질의 분리 원칙
- get~ 으로 시작하는 함수처럼 요청한 값을 반환하는 질의 함수 명령형 함수처럼 사용할 수 없음. 의도하지 않은 동작을 일으킬 수 있는 위험성을 내포
https://webactually.com/2018/02/06/%EB%AA%85%ED%99%95%ED%95%9C-%EC%BD%94%EB%93%9C-%EC%9E%91%EC%84%B1%EB%B2%95/
리팩토링시 위 원칙을 잘 지키면서 코드를 짠 경우 이 함수를 수정했을때 고려해야 할 부수적인 효과의 양이 줄어든다.

323p
파이프라인 사용할때 별도 줄에 세미콜론(;)을 많이 쓰는지..? ( javascript 에서 )

346p
js의 경우 참조 기반 동치성을 값 기반 동치성으로 대체하는 일에 관련하여 라이브러리 차원에서 지원하지 않는다.
