### ISSUE TITLE
[리팩터링] 9주차 ~ 12.5 필드내리기

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#47]
@TeamCrazyPerformance/packet

**Comment by usageness** [comment]
p.449 **일급 객체, 일급 함수**
- 일반적으로 다른 객체에 적용 가능한 연산을 지원하는 객체, 또는 함수.
- c언어를 포함한 구형 언어는 일급함수를 지원하지 않는 반면, **js**는 일급 함수를 지원한다.
