### ISSUE TITLE
5주차 14장 점진적인 개선 ~ 15장 JUnit

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#5]

**Comment by hyesun03** [comment]
# 14장 점진적 개선
p.286에서 `갑자기 ClassCastException을 왜 사용했느냐고? 이유는 내가 인수 테스트 케이스를 FitNess에서 구현했기 때문이다.` 이게 무슨말인지...

# 15장 JUnit 들여다보기
이 책에서 말하는 개선방향을 쭉 읽으면 설득이 충분히 되는데 왜 junit4에서는 그 안좋다는? 상태로 남아있는걸까요?
어찌되었건 ComparisonCompactor는 잘 동작하고있고, 굳이 고칠필요가 없어서 냅둔걸까요?

junit5에는 ComparisonCompactor가 안보이고 어딘가에 비슷한 구현이 있을 것같아서 찾아보는 중인데, 혹시 찾다가 발견하면 알려주세영,,
