### ISSUE TITLE
6주차 16장 SerialDate 리팩터링 17장 냄새와 휴리스틱

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#6]

**Comment by hyesun03** [comment]
# 16장 SerialDate 리팩터링
p.346에 있는 코드에서 `result = -1;`을 왜 457번 라인에 추가해준건지 모르겠어요.


# 17장 냄새와 휴리스틱
## p.368 주석 - C1: 부적절한 정보
> 일반적으로 작성자, 최종 수정일,  SPR 번호 등과 같은 메타 정보만 주석으로 넣는다.

이것도 깃같은데서 다 관리 해주지 않나요?

## p.376 G10: 수직분리
> 비공개 함수는 처음으로 호출한 직후에 정의한다.

비공개 함수라는게 private 함수 말하는건가요? 호출한 직후에 정의한다는게 무슨말인지 이해가 안가요.

**Comment by KangJiJi** [comment]
끝!
