### ISSUE TITLE
[1주차] ~5장 객체 지향 프로그래밍 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#78]

**Comment by lallaheeee** [comment]
분명 speed가 중요한, 시장 선점이 중요한 case가 있는데 내가 너무 엔지니어 관점을 배제하고 있는걸까? 생각하면서 읽고 있었는데 ㅋㅋㅋ 뼈때리네요.. 😢 
> 개발자는 "코드는 나중에 정리하면 돼. 당장은 시장에 출시하는 게 먼저야!"라는 흔해 바진 거짓말에 속는다. 이렇게 속아 넘어간 개발자라면 나중에 코드를 정리하는 경우는 한 번도 없는데, 시장의 압박은 절대로 수그러들지 않기 때문이다. '시장 출시가 먼저' 라는 생각을 하는 이유는 바로 뒤에 여러 무리의 경쟁자가 뒤쫓고 있고, 경쟁자보다 앞서 가려면 가능한 한 빠르게 달려야 하기 때문이다 -p.11
