### ISSUE TITLE
[2주차] ~11장 DIP: 의존성 역전 원칙 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#79]
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
람다 계산법?
그럼 프론트엔드에서 불변이란? (56p)
프론트엔드에서 가변성의 분리란.. (56p)

**Comment by GyujinCh0** [comment]
OCP 에서 방향성 제어와 정보은닉의 방식 (78p)
인터페이스 말고 다른 것은 없나?

**Comment by joi0104** [comment]
95쪽에서 최소한의 구체 컴포넌트인 main 함수에 대해서 이야기를 하는데.. 어떤 이점이 있는건지?

**Comment by KangJiJi** [comment]
많은 문제가 가변 변수로인해 발생한다(멀티스레드 한정인가?) => 점점 객체들이 상태를 안가지도록 코딩하고 있었다.
모든 클래스는 반드시 단 하나의 메서드를 가져아 한다 => 어디서 나온 주장이지?

**Comment by hjsung809** [comment]
p84. LSP 위배 사례에서 rest api uri를 인터페이스로 보고있는데 인터페이스를 정의해보면 어떻게 될까요?

**Comment by duckbok** [comment]
- 추이 종속성을 가지면 `FinancialReportController`가 엔티티에 의존하게 돼서 "자신이 직접 사용하지 않는 요소가 절대로 의존해서는 안 된다" 가 맞는 표현이라 생각이 드는데 맞는가? (79p)

> “파견 URI를 key로 사용하는 설정용 데이터베이스를 이용하는 파견 명령 생성 모듈을 만들어야 할 수도 있다.” (86p)
- 범용적인 택시회사와 각 택시회사에 대한 파견 URI를 key로 갖고, 파견 명령 URI 포맷을 가지고 있는 데이터베이스를 이용한다? 가 무슨 말인지 이해가 안된다..
- URI를 통해 관리하는 방식은 85p 코드의 if문과 다른 점은 무엇인가?
- REST 서비스들의 인터페이스가 서로 치환 가능하지 않다는 사실을 처리하는 중요하고 복잡한 매커니즘은 무엇일까?

- `ConcreteImpl`에 대한 소스 코드 의존성을 만들지 않으면서 인스턴스 생성을 하기 위해서 추상팩토리를 사용했다고 하는데, `Application`이 'ServiceFactoryImpl`의 생성은 직접하면 소스코드 의존성이 생기는 것이라고 이해를 하는데 이건 괜찮은 부분인지? 이걸 해결하는 구체 컴포넌트? (94~95p)
- 그렇다면 그냥 애초에 팩토리 안만들고 Service를 이렇게 만들면 되는 거 아닐까? 차이는 뭘까..
<img width="495" alt="스크린샷 2022-05-13 오후 9 48 32" src="https://user-images.githubusercontent.com/63839917/168475136-6a2736bd-ffdd-4ba4-9a95-ec72813e8c74.png">

**Comment by genie-youn** [comment]
9시까지 모두 올리고. 스터디 전에 읽어 오는걸로 하자. 안 올린 사람들 중에서 사다리 돌리기
