### ISSUE TITLE
[3주차] ~14장 컴포넌트 결합 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#80]
.
9시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올린 사람들을 대상으로 호스트 정하기 사다리~

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
람다 계산식

**Comment by lallaheeee** [comment]
REP ( Reuse/Release Equivalence Principle) 재사용/릴리즈 등가 원칙

- 재사용 단위는 릴리즈 단위와 같다 (이해 감)
- 이 원칙은 소프트웨어 설계와 아키텍처 관점에서 보면 단일 컴포넌트는 응집성 높은 클래스와 모듈들로 구성되어야 함을 뜻한다 (이해 안감.. 메이저 릴리즈일 때 의미하는건지? )
    - REP 원칙에서 단일 컴포넌트는 어떤 범위의 컴포넌트인지? (프론트엔드에서의 컴포넌트와 빠른 릴리즈에 익숙해져서 그런지)
    - 하나의 컴포넌트로 묶인 클래스와 모듈은 버전 번호가 같아야 하며, (이부분은 업데이트 마다 달라질 수 있지 않는지)

**Comment by GyujinCh0** [comment]
책에 나온 안정성 지표(p127), 추상화 지표 (p133), 주계열 거리 (p136)의 계산법을 실제로 사용하나?
사용한다면 이를 도와주는 라이브러리 같은게 있나?

**Comment by KangJiJi** [comment]
121) "순환을 끊는다" 라는 표현은 추상화에 의존시켜서 의존성을 역전시키는 것. 이해는 가지만 추상(인터페이스, 추상클래스 등등)이 변경되는 일도 자주 있다고 생각된다. => 안정적인 추상화하기가 잴 어려운 것 같다.

133) 이런 지표를 사용하기에는 현실성이 없어보인다(다른 업무도 많고 바쁜데 언제 계산하고 있나...하지만 지향해야하는건 맞다고 생각). 정말 중요한 설계 부분에서만 도저히 모르겠을 때 의사결정의 도움을 주는 용도로만 쓰면 좋을 것 같다는 생각이 든다(물론 안쓸 것 같지만 ㅎㅎㅎ).

여담) 데이터엔지니어링 도메인에서 자주 사용하는 도구로 [Airflow](https://airflow.apache.org/)라는 것이 있는데 여기서도 모든 batch성 작업을 DAG로 표현. 이 책에서 DAG를 보니 반갑네요.

**Comment by hyesun03** [comment]
### 111쪽 CRP: 공통재사용 원칙
맨 첫 번째 문장인 `컴포넌트 사용자들을 필요하지 않는 것에 의존하게 강요하지 말라`는 말은 이해갔습니다. 111쪽 아래에서 4번째 문장인 `이 처럼 CRP는 각 컴포넌트에 어떤 클래스들을 포함시켜야 하는지를 ~~`에서 112쪽 `많은 컴포넌트를 재배포하느라 우리의 소중한 노력을 허비하게 된다.` 여기까지 다 맞는말인건 알겠는데 왜 들어가있는 설명인지 모르겠습니다... 

`CRP는 동일한 컴포넌트로 묶어서는 안되는 클래스가 무엇인지도 말해준다.`를 설명하기 위해 넣은 문장들인거 같은데.. 정작 그 문장 뒤에 붙은 내용을 읽고 느낀건 '강한 의존이 있고, 쓸데없는 재배포를 많이 하지 않으려면 걍 하나의 컴포넌트로 묶어라'로 읽혀서, 몇 번을 읽어도 잘 와닿지 않았습니다 ㅜㅜ 

### 기타
- 책에 나온 안정성 지표(p127), 추상화 지표 (p133), 주계열 거리 (p136) 이거 보면서 저런 지표를 굳이 왜 계산하는거지..? 싶었습니다. 적어도 제가 보고 들은것에선 개발할때 저런 지표를 뽑는건 못봤고, 책을 쓸 때 본인이 설명을 하기 위해서 만든 지표라는 느낌을 많이 받았습니다. 직접 개발하는 사람이 아니라 관리자의 입장에서 어떻게든 수치화해서 보고하거나 설명할 때 필요할진 모르겠지만.. 그래서 그런지 **138쪽 결론** 항목에서는 `지표는 신이 아니다.` 라고 언급하신듯 하네요.

**Comment by siathus** [comment]
p. 113 균형 다이어그램
p. 114 "일반적으로 프로젝트는 삼각형의 오른쪽에서 시작하는 편이며, 이때는 오직 재사용성만 희생하면 된다."

결국 REP는 "하나의 컴포넌트로 묶인 클래스와 모듈은 반드시 함께 릴리스할 수 있어야 한다."인데, 굳이 프로젝트 시작부터 이 REP를 '희생'할 필요까지 있을까 싶습니다. 프로젝트 시작부터 REP까지 함께 고려해볼 수 있는 것 아닌지?

**Comment by duckbok** [comment]
### 109p
> 동일한 이유로 동일한 시점에 변경되는 클래스를 같은 컴포넌트로 묶어라.
서로 다른 시점에 다른 이유로 변경되는 클래스는 다른 컴포넌트로 분리하라.

동일한 이유로 다른 시점에, 동일한 시점에 다른 이유로 변경되는 클래스 관계는 있을까요? 시점 얘기가 나와서 막 비동기 처리에 따른 것밖에 생각이 안나는데.. 아마 없으니까 쟤네 둘만 책에서 얘기한거겠죠?

### 114p, 124p
> 프로젝트 초기에는 개발 가능성이 재사용성보다 더욱 중요하기 때문이다.
즉, 프로젝트의 컴포넌트 구조는 시간과 성숙도에 따라 변한다는 뜻이다.

> 컴포넌트 의존성 구조는 시스템의 논리적 설계에 발맞춰 성장하며 또 진화해야 한다.

현재 토이?프로젝트를 설계를 하고 진행중에 있는데, 요새 계속 고민하고 머리 아팠던 문제에 대한 해답을 찾은 느낌이었습니다. 의존성이나 재사용성을 계속 고려하고 지키려다 보니까 진행이 되지 않고 제대로 알지 못하는 부분이 있어서 확실히 떨어지지 않는 결정이 발목을 잡았었는데 일단 개발가능성이 중요하고, 의존성 구조도 고정된 것이 아니라는 것!!

### 121p 단위 테스트
그 동안 단위 테스트를 하려 할 때마다, 코드의 답답함이 항상 느껴지면서 막 이리저리 몸을 비틀면서 해야해서 굉장히 고통스러웠는데, 그 이유 중에 한가지에 대해서 확실히 안 느낌이네요. 의존성 네 이놈..
