### ISSUE TITLE
[4주차] ~17장 경계: 선 긋기 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#81]
.
9시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올린 사람들을 대상으로 호스트 정하기 사다리~

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
143p
소프트웨어 시스템의 아키텍처란 시스템을 구축했던 사람들이 만들어낸 시스템의 형태다.
그 모양은 시스템을 컴포넌트로 분할하는 방법, 분할된 컴포넌트를 배치하는 방법, 컴포넌트가 서로 의사소통하는 방식에 따라 정해진다.

아키텍처의 주된 목적은 시스템의 생명주기를 지원하는 것이다. 좋은 아키텍처는 시스템을 쉽게 이해하고, 쉽게 개발하며, 쉽게 유지보수하고, 또 쉽게 배포하게 해준다.
아키텍처의 궁극적인 목표는 시스템의 수명과 관련된 비용은 최소화하고, 프로그래머의 생산성은 최대화하는데 있다.

163p
우발적 중복
서로 다른 속도와 서로 다른 원인으로 변경된다면 이 두 코드는 진짜 중복이 아니다.

178p
화살표의 방향에 주의해라. 
Database는 BusinessRule에 대해서 알고 있지만 BusinessRule은 Database에 대해 알지 못한다.
이는 DataBaseInterface는 BusinessRule에 속하지만 DatabaseAccess는 Database에 속한다는 것을 의미한다.

어색하게 느껴지는가? BusinessRule이 메시지를 전달하면 Database는 이에 맞는 쿼리를 생성해 실행한다.
번역의 책임을 갖는다.

이러한 의존관계는 어느 데이터베이스를 사용하던지 개념치 않는다는 것을 의미한다.
다시말해 MySQL이든 오라클이든 카우치베이스든 심지어 플랫파일시스템이든 데이터베이스에 대한 결정을 연기한채 업무 규칙을 작성하고 테스트할 수 있도록 한다.

**Comment by duckbok** [comment]
### 선택사항 열어두기 (146p)
> 이러한 일을 용이하게 만들기 위해서는 가능한 한 많은 선택지를, 가능한 한 오래 남겨두는 전략을 따라야 한다. (142p)

아.. 그러네? 하면서 벙쪘다. 뭐 프로젝트를 몇 개 해보지는 않았지만, 설계할 때 항상 어떤 DB를 쓰고, 서버를 쓸지 다 정해둔 다음에 이걸 쓸 거를 코드에 박아두고 이에 의존하지 말자! 하면서 그다음에 추상화를 하였는데, 순서가 뒤바뀌어서 항상 반쪽짜리 추상화를 하고 있었다는 생각이 들어서다. 물론 책과 같이 진행하려면 정말 어려울 거 같긴 한대.. 구조에 익숙해지면 한번 진행해보고 싶다.

### 유스케이스란? (156p)
계속 읽으면서 유스케이스라는 개념이 모호하게 자리 잡았는데, 기존에 알고 있던 거(Use-Case diagram)와 같은 사용자의 행위가 맞을까요?

### 중복 (164p)
지금까지 코드가 중복되면 무조건 통합을 했는데, 이 글을 읽고 보니 확실히 그 중복이 진짜 중복이 아닌 일시적으로 일어난 가짜 중복일 수도 있다는 것을 깨달았다.

### 결합 분리 모드 (165p)
소스 수준이 아마 내가 계속 만들고 있던 아키텍처라고 생각이 든다. 그러면 여기서 컴포넌트 별로 다른 프로젝트로 두어 빌드를 따로 한 뒤에 이를 통합해서 같이 실행한다면 배포 수준 분리 모드이고, 아예 이를 따로 실행까지 하면 서비스 수준 분리 모드이다..라고 이해를 했는데 맞을까요 ㅎㅎ

그리고 이를 왔다 갔다 할 수 있어야 좋은 아키텍처라고 하는데, 실제로 이게 대부분 가능한지 궁금합니다.

### 테스트 관련 (176p)
> 또한 테스트를 느리게 만드는 데이터베이스가 없으니 테스트를 더 빨리 돌릴 수 있다는 뜻이기도 하다.

이게 단위 테스트에 대한 얘기가 아니라서 그런가? 내가 알기로는 상관없이 동작하도록 mock이나 stub을 두면 되니 여기서는 데이터베이스의 유무가 중요하지 않은 것 같다는 생각이 들었다.

**Comment by siathus** [comment]
### 유스케이스 결합 분리 (p. 161)
![image](https://user-images.githubusercontent.com/23095970/172040880-d5d1d725-d6d6-41c6-93a5-aed4ca8d960b.png)
> 유스케이스의 업무 규칙과 데이터베이스 부분도 마찬가지다. (중략) 유스케이스들이 각 계층에서 서로 겹치지 않게 한다.

`주문 추가용 데이터베이스`와 `주문 삭제용 데이터베이스`를 겹치지 않게 분리해야 한다는 게 이해가 잘 안가네요. 주문 추가와 주문 삭제 두 행위 모두 같은 데이터베이스 테이블을 참조해야 할텐데...

**Comment by KangJiJi** [comment]
## 144

MSA때문에 배포하기 어려워질 수 있다. => 잘 와닿지는 않았는데 웹 서비스만 겪어봐서 그런가? 다른분은 이런 경험이 있으신가요?

## 158

좋은 아키텍처는

- 수십개의 작은 설정 스크립트나 속성 파일을 수정하는 방식을 사용하지 않는다.
- 꼭 필요한 디렉터리나 파일을 수작업으로 생성하게 내버려두지 않는다.

위 내용이 이해가지 않음.

## 163

배포 독립성은 새로운 jar 파일이나 서비스를 몇개 추가하는 정도로 단순한일 => 너무 과하다는 생각이 든다. 그리고 이게 진짜 단순한 일인가..?
저자도 그렇게 생각하는지 166쪽에서는 서비스화될 가능성이 있다면 컴포넌트 결합을 분리하되 서비스가 되기 직전에 멈추는 방식을 선호 한다고 하긴 함.

**Comment by hyesun03** [comment]
### p.146 선택사항 열어두기
저자가 말하려는 의도에 공감하지만.. 개발팀이 좀 커지면 많은것을 미정으로 열어두고 개발을 하는것도 혼란 대잔치일것 같습니다 ㅋㅋ 책에서도 쉽지 않다는걸 말하기도했듯이 적당히 열어두면 되겠죠..?ㅋㅋ 저희는 보통 스프링부트를 쓰고, 무슨 DB를 쓰는지는 정하고 코드레벨에서 사용하는 프레임워크/라이브러리 정도는 여러개로 써보다가 하나로 흡수시키는거 같긴합니다. (예를 들면 저희는 스프링부트로 이전을 하면서 feign client, web client를 초기에 혼용해서 쓰다가 feign client만 쓰는것 처럼)
특히 DB는 리얼환경에 배포가 된 상태에서 바꾸는게 많이 어려운데, DB 전환이 쉬운 경우는 없으니 보통 처음 고를때 신경쓰고 바꿀 생각을 잘 안하는듯 합니다. 갠적으로 뒤쪽 17장의 FitNesse 서비스에서 DB를 뭘 써야할지 정하지 않을 수 있었던건 그냥 그 서비스의 특성이 그랬던게 아니었을까 싶습니다.

### p.162
첫 번째 문단의 마지막 문장 `높은 대역폭을 요구하는 유스케이스는 여러 서버로 복제~~` 이 문장이 딱 와닿진 않은데, 여기서 말하는 '높은 대역폭'은 '뭔가 커버하는게 많고 큰 유스케이스'로 생각했는데 적절하게 이해했겠죠..?

### p.164
중복이 진짜 중복인지 확인하라. 일하면서 한번씩 찾아오는 고민인데, 코드리뷰 할 때도 한번씩 이 주제로 이야기가 나올 정도로 이게 진짜 중복이었는지 아니었는지를 그 당시에 결정할 수 없는 경우도 있어서 어려운듯합니다ㅜㅜ

**Comment by GyujinCh0** [comment]
p.142
"이러한 일을 용이하게 만들기 위해서는 가능한 한 많은 선택지를, 가능한 한 오래 남겨두는 전략을 따라야 한다."
=> 아키텍처에 관한 관점을 바꿔주는 좋은 문장이다
=> 그런데  결국 비용을 낮추는게 중요하다면 어떤 '세부사항'들은 미리 정해놓고 개발할 때 더 효율적일 수도 있지 않을까?
=> 실제로 이러한 방식으로 현업에서 개발하시나요?

p.164
"중복이 진짜 중복인지 확인하라"
=> 사실 그 전에는 이런 생각을 별로 안 해봤는데 관점을 바꿔주는 좋은 단락이다.
=> 그러면 이를 확인하는 좋은 방법이 있을까? 리팩터링 책에서는 세 번 반복되면 그 때 통합하라고 했던 것 같은 데 이러한 지침이 도움이 될까?

**Comment by genie-youn** [comment]
=== 정리
규진 p.142
"이러한 일을 용이하게 만들기 위해서는 가능한 한 많은 선택지를, 가능한 한 오래 남겨두는 전략을 따라야 한다."
=> 아키텍처에 관한 관점을 바꿔주는 좋은 문장이다
=> 그런데 결국 비용을 낮추는게 중요하다면 어떤 '세부사항'들은 미리 정해놓고 개발할 때 더 효율적일 수도 있지 않을까?
=> 실제로 이러한 방식으로 현업에서 개발하시나요?

지수 143p
소프트웨어 시스템의 아키텍처란 시스템을 구축했던 사람들이 만들어낸 시스템의 형태다.
그 모양은 시스템을 컴포넌트로 분할하는 방법, 분할된 컴포넌트를 배치하는 방법, 컴포넌트가 서로 의사소통하는 방식에 따라 정해진다.

아키텍처의 주된 목적은 시스템의 생명주기를 지원하는 것이다. 좋은 아키텍처는 시스템을 쉽게 이해하고, 쉽게 개발하며, 쉽게 유지보수하고, 또 쉽게 배포하게 해준다.
아키텍처의 궁극적인 목표는 시스템의 수명과 관련된 비용은 최소화하고, 프로그래머의 생산성은 최대화하는데 있다.

지훈 144p
MSA때문에 배포하기 어려워질 수 있다. => 잘 와닿지는 않았는데 웹 서비스만 겪어봐서 그런가? 다른분은 이런 경험이 있으신가요?

송열 146p

선택사항 열어두기 (146p)
> 이러한 일을 용이하게 만들기 위해서는 가능한 한 많은 선택지를, 가능한 한 오래 남겨두는 전략을 따라야 한다. (142p)

아.. 그러네? 하면서 벙쪘다. 뭐 프로젝트를 몇 개 해보지는 않았지만, 설계할 때 항상 어떤 DB를 쓰고, 서버를 쓸지 다 정해둔 다음에 이걸 쓸 거를 코드에 박아두고 이에 의존하지 말자! 하면서 그다음에 추상화를 하였는데, 순서가 뒤바뀌어서 항상 반쪽짜리 추상화를 하고 있었다는 생각이 들어서다. 물론 책과 같이 진행하려면 정말 어려울 거 같긴 한대.. 구조에 익숙해지면 한번 진행해보고 싶다.

혜선 p.146 선택사항 열어두기
저자가 말하려는 의도에 공감하지만.. 개발팀이 좀 커지면 많은것을 미정으로 열어두고 개발을 하는것도 혼란 대잔치일것 같습니다 ㅋㅋ 책에서도 쉽지 않다는걸 말하기도했듯이 적당히 열어두면 되겠죠..?ㅋㅋ 저희는 보통 스프링부트를 쓰고, 무슨 DB를 쓰는지는 정하고 코드레벨에서 사용하는 프레임워크/라이브러리 정도는 여러개로 써보다가 하나로 흡수시키는거 같긴합니다. (예를 들면 저희는 스프링부트로 이전을 하면서 feign client, web client를 초기에 혼용해서 쓰다가 feign client만 쓰는것 처럼)
특히 DB는 리얼환경에 배포가 된 상태에서 바꾸는게 많이 어려운데, DB 전환이 쉬운 경우는 없으니 보통 처음 고를때 신경쓰고 바꿀 생각을 잘 안하는듯 합니다. 갠적으로 뒤쪽 17장의 FitNesse 서비스에서 DB를 뭘 써야할지 정하지 않을 수 있었던건 그냥 그 서비스의 특성이 그랬던게 아니었을까 싶습니다.

송열 156p
계속 읽으면서 유스케이스라는 개념이 모호하게 자리 잡았는데, 기존에 알고 있던 거(Use-Case diagram)와 같은 사용자의 행위가 맞을까요?

지훈 158p

좋은 아키텍처는

- 수십개의 작은 설정 스크립트나 속성 파일을 수정하는 방식을 사용하지 않는다.
- 꼭 필요한 디렉터리나 파일을 수작업으로 생성하게 내버려두지 않는다.

위 내용이 이해가지 않음.

성국 유스케이스 결합 분리 (p. 161)
![image](https://user-images.githubusercontent.com/23095970/172040880-d5d1d725-d6d6-41c6-93a5-aed4ca8d960b.png)
> 유스케이스의 업무 규칙과 데이터베이스 부분도 마찬가지다. (중략) 유스케이스들이 각 계층에서 서로 겹치지 않게 한다.

`주문 추가용 데이터베이스`와 `주문 삭제용 데이터베이스`를 겹치지 않게 분리해야 한다는 게 이해가 잘 안가네요. 주문 추가와 주문 삭제 두 행위 모두 같은 데이터베이스 테이블을 참조해야 할텐데...

혜선 p.162
첫 번째 문단의 마지막 문장 높은 대역폭을 요구하는 유스케이스는 여러 서버로 복제~~ 이 문장이 딱 와닿진 않은데, 여기서 말하는 '높은 대역폭'은 '뭔가 커버하는게 많고 큰 유스케이스'로 생각했는데 적절하게 이해했겠죠..?

지훈 p163

배포 독립성은 새로운 jar 파일이나 서비스를 몇개 추가하는 정도로 단순한일 => 너무 과하다는 생각이 든다. 그리고 이게 진짜 단순한 일인가..?
저자도 그렇게 생각하는지 166쪽에서는 서비스화될 가능성이 있다면 컴포넌트 결합을 분리하되 서비스가 되기 직전에 멈추는 방식을 선호 한다고 하긴 함.

지수 163p
우발적 중복
서로 다른 속도와 서로 다른 원인으로 변경된다면 이 두 코드는 진짜 중복이 아니다.
