### ISSUE TITLE
[5주차] 18장 경계 해부학 ~ 21장 소리치는 아키텍처 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#82]
.
9시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올린 사람들을 대상으로 호스트 정하기 사다리~

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

--- 안건
- 스터디 이대로 괜찮은가.
- 개인이 남긴 코멘트 어떻게 잘 취합할 수 있을까.
  - 최첨단 수동..
  - 템플릿을 만들고 스크립트를 만들어볼까? 
- 호준

```
지수 178p
화살표의 방향에 주의해라.
Database는 BusinessRule에 대해서 알고 있지만 BusinessRule은 Database에 대해 알지 못한다.
이는 DataBaseInterface는 BusinessRule에 속하지만 DatabaseAccess는 Database에 속한다는 것을 의미한다.

어색하게 느껴지는가? BusinessRule이 메시지를 전달하면 Database는 이에 맞는 쿼리를 생성해 실행한다.
번역의 책임을 갖는다.

이러한 의존관계는 어느 데이터베이스를 사용하던지 개념치 않는다는 것을 의미한다.
다시말해 MySQL이든 오라클이든 카우치베이스든 심지어 플랫파일시스템이든 데이터베이스에 대한 결정을 연기한채 업무 규칙을 작성하고 테스트할 수 있도록 한다.
```

**Comment by joi0104** [comment]
1. ddd에서 도메인 계층에 존재하였지만 엔티티의 성격을 띄지 않았던 서비스 객체들 유즈케이스의 일종이라고 볼 수 있을까?
2. 프레임 워크 말고도 웹 또한 전달 매커니즘으로, 세부사항이라고 했지만 거부감이 조금 든다. 웹, 브라우저의 제약사항으로 인해 정책이 변경된 적도 있었는데 과연 추후에 고려해야 할 세부 사항일까?


아 그리고 프로젝트의 구조를 보고 어플리케이션의 유즈케이스에 대해 소리쳐야 한다는 부분 정말 좋았습니다.. 프레임워크 문서가 권장하는 방식으로 기본 폴더구조를 가져 갔는데 반성하게 되네요

**Comment by KangJiJi** [comment]
190
로컬 프로세스에서는 고수준의 프로세스의 소스 코드가 저수준 프로세스의 이름, 물리 주소, 레지스트리 조회 키를 절대로 포함해서는 안 된다. -> 이해가 가지 않는다. 추상 프로세스와 구체 프로세스를 모두 분리해서 별도의 서비스(MSA?)로 만들어야 한다는건가? 아니면 단순히 라이브러리화 시키라는건가?(라이브러리로 빼내도 고수준 프로세스와 저수준 프로세스간 결합은 생기지 않나...?)

209
좋은 소프트웨어 아키텍처는 프레임워크, DB, 웹 서버, 그리고 여타 개발 환경 문제나 도구에 대해서는 결정을 미룰 수 있도록 만든다. -> 만약 java라는 언어를 사용한다 할 때 스프링외에 다른 프레임워크를 사용하는 결정을 미룰 수 있나? 도메인 영역에서도 어노테이션을 통해 bean에 등록하기만해도 스프링에 의존성이 생기는거 아닌가?

**Comment by GyujinCh0** [comment]
p.208
"이제 도서관의 아키텍처를 보고 있다고 가정해 보자... (중략) ... 이 아키텍처는 '도서관이야'라고 소리칠 것이다."
=> 도메인마다 그 특성을 잘 나타내는 아키텍처의 형태가 있다면 비교적 정형화된 도메인(은행, 해운 등)은 업계에 널리 통용되는 공통의 아키텍처가 있나?

**Comment by hyesun03** [comment]
p.195 
여기 `encrypt()` 예제를 먼저 보고 글을 읽었는데요, 코드를 봤을땐 별 나쁜 냄새를 못느꼈는데, 글 읽으면서 **그림 19.2** 를 보니 진짜 대단하구나싶었습니다. 이렇게 생각을 하고 코드를 짜야하는데...

p.210
프레임워크가 없어도 유스케이스 전체에 대해 단위테스트를 할 수 있다는게 잘 이해가 안됩니다.

p.211
**결론** 쪽에 있는 제일 마지막에 나오는 대화 내용은 잘 이해가 안갔습니다. (저 대화에서 말하는 뷰, 컨트롤러가 뭔지 이해를 못한거 같은데, 우리가 보는 웹 FE, 안드로이드, ios 화면을 의미하는거면 이해가갑니다.)

**Comment by hjsung809** [comment]
프론트엔드에서 유스케이스 이외의 업무규칙을 다루는 케이스가 있다면 어떤게 있을지 궁금합니다

**Comment by genie-youn** [comment]
## 18장 경계 해부학
배포 수준 결합 분리이다. 경계를 나누어 컴파일하고 이를 동적으로 링크하여 배포한다.
> FE에서 사내 NPM에 배포하고 이를 사용하는 경우 이 케이스라 할 수 있을까?

가장 강한 물리적 경계, 경계의 횡단은 네트워크 통신을 통해 이루어진다.
> FE 컴포넌트와 API 컴포넌트는 서비스 차원의 경계를 갖는 것이었다.

## 19장 정책과 수준
`수준 (level)` 은 엄밀하게 정의하면 "입력과 출력까지의 거리"이다.

## 20장 업무 규칙
핵심 업무 데이터를 기반으로 동작하는 일련의 자그마한 핵심 업무 규칙을 구체화한다. 엔티티를 만드는데 꼭 객체 지향 언어를 사용할 필요는 없다. 유일한 요구사항은 핵심 업무 데이터와 핵심 업무 규칙을 묶어 별도의 소프트웨어 모듈로 만들어야 한다는 것이다.
> 백엔드를 js로 구성을한다면 이 모듈을 함께 사용할 수 있을까? 코틀린의 KMM이 그런 의미에서 강점이 있을 수 있지 않을까?

## 21장 소리치는 아키텍처
과도한 문제나 근본적인 아키텍처를 뜯어고치지 않더라도 시스템을 콘솔 앱, 웹 앱, 리치클라이언트 앱, 심지어 웹서비스 앱으로도 전달할 수 있어야 한다.
> 웹 앱과 웹서비스 앱은 무슨 차이지? 리치클라이언트는 또 뭘까

아키텍처가 유스케이스를 최우선으로 한다면, 그리고 프레임워크와는 적당한 거리를 둔다면 프레임워크를 전혀 준비하지 않더라도 필요한 유스케이스 전부에 대해서 단위테스를 할 수 있어야 한다.
> 공감 백배였다.

**Comment by genie-youn** [comment]
도메인 영역에서도 어노테이션을 통해 bean에 등록하기만해도 스프링에 의존성이 생기는거 아닌가?
프레임워크와는 적당한 거리를 둔다면 프레임워크를 전혀 준비하지 않더라도 필요한 유스케이스 전부에 대해서 단위테스를 할 수 있어야 한다.

유스케이스란?
