### ISSUE TITLE
[6주차] 22장 클린 아키텍처 ~ 25장 계층과 경계 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#83]
.
9시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올린 사람들을 대상으로 호스트 정하기 사다리~

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

--- 안건
- 스터디 이대로 괜찮은가.
- 도메인 영역에서도 어노테이션을 통해 bean에 등록하기만해도 스프링에 의존성이 생기는거 아닌가?
- 프레임워크와는 적당한 거리를 둔다면 프레임워크를 전혀 준비하지 않더라도 필요한 유스케이스 전부에 대해서 단위테스를 할 수 있어야 한다.
- 유스케이스란?

**Comment by KangJiJi** [comment]
22장
220 경계를 가로질러 데이터 전달할 때, 데이터는 항상 내부의 원에서 사용하기에 가장 편리한 형태를 가져야만 한다.

- DTO이야기를 하는 것이겠죠??
- 혹시 개발중에 DTO의 변경이 많이 발생하시나요? 저는 개인적으로 DTO에 데이터를 계속 넣었다가 뺐다가 반복하고, 도메인 객체 혹은 메서드마다  DTO를 계속 추가하다보니 코드의 중복도 많아지는 상황을 자주 겪는 것 같습니다.

25장
243 오버 엔지니어링이 언더 엔지니어링보다 나쁠 때가 훨씬 많다.

- 좋은 이야기!!!(같습니다 ㅎ)

**Comment by GyujinCh0** [comment]
23장 
p.227
"경계를 넘나드는 통신은 모두 간단한 데이터 구조를 수반할 때가 많고, 대개 그 경계는 테스트하기 어려운 무언가와 테스트하기 쉬운 무언가로 분리될 것이다."
=> 잘 생각해보지 못했던 좋은 문장이다. 테스트와 아키텍처를 연결지어서 생각하는게 좋았다.

24장
p.230
"마지막 단계를 건너뛰기" 부분 첫번째 문단
=> 무슨 소리인지 잘 모르겠다. 일단 하나에 몰아 넣고 나중에 경계를 짓는다는 이야기인가?

**Comment by genie-youn** [comment]
# 22장
214p

UI 독립성. 시스템의 나머지 부분을 변경하지 않고도 UI를 손쉽게 변경할 수 있어야 한다. 예를 들어 업무규칙을 변경하지 않고서도 웹 UI를 콘솔 UI로 대체할 수 있어야 한다.

# 23장
225p

예를들어 GUI의 경우 화면에 각 요소가 필요한 위치에 적절히 표시되었는지 검사하는 테스트는 어렵지만, GUI에서 수행하는 행위들은 테스트하기 쉽다. 이때 전자를 뷰로 후자를 프레젠터로 구성하고 이때 뷰가 험블객체가 된다.

> 현대의 프론트 애플리케이션에서는 이 뷰를 테스트하기 위해 애쓰지 않나? 맞나 이게?

# 24장 
231p

> 이게 왜 일차원 경계이지..? Boundary와는 무슨 차이인지 모르겠다. 위험천만한 점선 화살표..?

# 25장
242p

> 결론이 너무 아름다워서 적어두었다.

**Comment by joi0104** [comment]
## 23장

### 험블 객체 패턴

q) front 시점에서는 뷰 모델 정도가 험블 객체가 될 것 같은데, back 시점에서는 dto 정도가 험블 객체라고 생각해도 되겠죠?

### 프레젠터와 뷰

> 뷰는 뷰 모델의 데이터를 화면으로 로드할 뿐이며, 이 외에 뷰가 맡은 역할은 전혀 없다. 따라서 뷰는 보잘 것 없다.

좋은 문장이라고 생각합니다. 항상 보잘 것 없던 뷰에만 집중해서 테스트 코드를 작성했었던 것 같아요.


## 24장

### 일차원 경계

> 쌍방향 인터페이스가 없고 개발자와 아키텍트가 근면 성실하고 제대로 훈련되오 있지 않다면, 이 점선과 같은 비밀통로가 생기는 일을 막을 방법이 없다.

비밀통로를 숨겨진 의존성이라고 대충 이해했는데.. 와닿지 않습니다 ㅠ 저자가 말하는 비밀통로는 어떤 의미인가요?

**Comment by hjsung809** [comment]
p 215 프레젠터에서 유스케이스 출력 포트를 사용할때는 필요하지 않는이상 인터페이스를 굳이 둘 필요가 없지 않을까요? 의견이 궁금합니다

**Comment by hyesun03** [comment]
## 23장
### p.224
https://martinfowler.com/bliki/HumbleObject.html
`험블 객체 패턴`을 이 책을 읽으면서 첨 봤는데, 완전히 이해한 느낌이 들진 않네요.. 사실 아래 말 자체가 잘 와닿지 않았습니다. 뭔가 적절한 예를 찾으려고 했는데 어렵네요 ㅜㅜ `실제 비즈니스 로직을 수행하는 코드와 아닌걸 구분하라` 정도로 받아들였습니다. 
```
행위들을 두 개의 모듈 또는 클래스로 나눈다.
테스트하기 어려운 것들은 험블 객체, 나머지는 다른 객체에 옮긴다.
```
