### ISSUE TITLE
[6주차] 26장 메인 컴포넌트~ 29장 클린 임베디드 아키텍처 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#84]
.
9시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올린 사람들을 대상으로 호스트 정하기 사다리~
호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

--- 안건
- 스터디 이대로 괜찮은가.
- 도메인 영역에서도 어노테이션을 통해 bean에 등록하기만해도 스프링에 의존성이 생기는거 아닌가?
- 프레임워크와는 적당한 거리를 둔다면 프레임워크를 전혀 준비하지 않더라도 필요한 유스케이스 전부에 대해서 단위테스를 할 수 있어야 한다.
- 유스케이스란?

**Comment by genie-youn** [comment]
# 26장 메인 컴포넌트
246p

모든 시스템에는 최소한 하나 이상의 컴포넌트가 존재하고, 이 컴포넌트가 나머지 컴포넌트를 생성하고, 조정하고, 관리한다. 이 컴포넌트를 메인 (Main) 이라고 부른다.
> 멀리서 찾을것 없이 `main.js`, 그리고 각 모듈의 `index.js` 라고 할 수 있겠다.

게임을 생성할 때 `htw.game.HuntTheWumpusFacade` 라는 클래스 이름을 전달하는데, 이 클래스는 메인보다도 더 지저분하기 때문이다.
이는 이 클래스에 변경이 생겨도 메인을 재컴파일/재배포하지 않아도 되게 하기 위함이다.
> 컴포넌트 단위로 컴파일/배포하지 않아서 크게 와닿지 않았다. fe에서 동적으로 링킹하는게 효과적인 상황이 어떤게 있을까?

요지는 메인은 클린 아키텍처에서 가장 바깥에 위치하는 지저분한 저수준 모듈이라는 점이다.
메인은 고수준의 시스템을 위한 모든것을 로드한 뒤, 제어권을 고수준의 시스템에게 넘긴다.

# 결론
메인은 애플리케이션의 플러그인이라고 생각하자.
메인은 초기 조건 설정을 구성하고, 외부 자원을 모두 수집한 후, 제어권을 애플리케이션의 고수준 정책으로 넘기는 플러그인이다.
메인은 플러그인이므로 메인 컴포넌트를 애플리케이션의 설정별로 하나씩 두도록 하여 둘 이상의 메인 컴포넌트를 만들수도 있다.

예를 들어 개발용 메인 플러그인, 별도의 테스트용 메인 플러그인, 그리고 또 다른 상용 메인 플러그인을 만들 수 있다.
또한 배포하려는 국가별로, 관할 영역별로, 고객별로 메인 플러그인을 만들 수도 있다.

메인을 플러그인 컴포넌트로 여기고, 그래서 아키텍처 경계 바깥에 위치한다고 보면 설정 관련 문제를 훨씬 쉽게 해결할 수 있다.

# 소감
내가 `index.js`에 관계설정 책임을 주었던 것은 틀리지 않았다.

**Comment by genie-youn** [comment]
# 26장 메인 컴포넌트
246p

모든 시스템에는 최소한 하나 이상의 컴포넌트가 존재하고, 이 컴포넌트가 나머지 컴포넌트를 생성하고, 조정하고, 관리한다. 이 컴포넌트를 메인 (Main) 이라고 부른다.
> 멀리서 찾을것 없이 `main.js`, 그리고 각 모듈의 `index.js` 라고 할 수 있겠다.

248p
게임을 생성할 때 `htw.game.HuntTheWumpusFacade` 라는 클래스 이름을 전달하는데, 이 클래스는 메인보다도 더 지저분하기 때문이다.
이는 이 클래스에 변경이 생겨도 메인을 재컴파일/재배포하지 않아도 되게 하기 위함이다.
> 컴포넌트 단위로 컴파일/배포하지 않아서 크게 와닿지 않았다. fe에서 동적으로 링킹하는게 효과적인 상황이 어떤게 있을까?

# 27장 크고 작은 모든 서비스들
## 개발 및 배포 독립의 오류
254p
이러한 믿음에도 어느 정도 일리가 있지만, 극히 일부일 뿐이다.
첫째로, 대규모 엔터프라이즈 시스템은 서비스 기반 시스템 이외에도, 모노리틱 시스템이나 컴포넌트 기반 시스템으로도 구축할 수 있다는 사실은 역사적으로 증명되어 왔다.
따라서 서비스는 확장 가능한 시스템을 구축하는 유일한 선택지가 아니다.

둘째, "결합 분리의 오류"에 따르면 서비스라고 해서 항상 독립적으로 개발하고, 배포하며, 운영할 수 있는 것은 아니다.
데이터나 행위에서 어느정도 결합되어 있다면 결합된 정도에 맞게 개발, 배포, 운영을 조정해야만 한다.

> 이해가 잘 안되는데. 첫째는 어쨋든 각 서비스별로 스케일을 확장할 수 있으니 트래픽을 받아내는데 모놀리식보다 더 유연한 장점은 명확하게 가지고 있는것 아닌가? 여기서 말하는 확장은 개방폐쇄에서 확장을 의미하는것으로 보인다. 둘째도 결국 서비스의 경계를 잘못 부여한것이 문제 아닐까?

257p
이제 당연히 물어봐야 할 질문은 "서비스에서도 이렇게 할 수 있을까?" 다. 그 대답은 물론 "예"다.

> 읽으면서 서비스 내부적으로도 동일하게 경계를 만들어주면 되는거 아니야? 했는데 그렇다고 한다. 결국 서비스를 어떻게 구성해야 하는가? 에 대한 절이었다.

# 28장 테스트 경계
262p Cucumber Test?

https://techblog.woowahan.com/2658/


263p
이 문제를 해결하려면 테스트를 고려해서 설계해야 한다. (테스트를 고려하든 아니면 다른 이슈든) 소프트웨어 설계의 첫 번째 규칙은 언제나 같다.
변동성이 있는 것에 의존하지 말라.
GUI는 변동성이 크다. GUI로 시스템을 조작하는 테스트 스위트는 분명 깨지기 쉽다.
따라서 시스템과 테스트를 설계할 때, GUI를 사용하지 않고 업무 규칙을 테스트 할 수 있게 해야 한다.

> 좋은 말이기도 하고, 나중에 레퍼런스로 써먹을 일이 생길것 같아서.. 메모..

264p. 
결국 쉽게 깨지지 않는, 견고한 테스트를 만들기 위해서는 애플리케이션의 구조를 테스트로부터 숨기는 테스트 API를 만들어 딸 ㅗ진화할 수 있게 하라는것인데.. 사실 잘 안와닿는다.

# 29장 클린 임베디드 아키텍처
269p 안드로이드 앱 개발자 역시 업무 로직을 안드로이드 API로부터 분리하지 않는다면 펌웨어를 작성하는 셈이다.

> 마찬가지로 프론트엔드 개발자가 업무 로직을 Web API나 리액트같은 라이브러리로 부터 분리하지 않는다면 마찬가지로 소프트웨어가 아닌 펌웨어를 작성하는 것이다. 메모..

**Comment by GyujinCh0** [comment]
### 26장 메인 컴포넌트
p.250
"요지는 메인은 클린 아키텍처에서 가장 바깥 원에 위치하는, 지저분한 저수준 모듈이라는 점이다. 메인은 고수준의 시스템을 위한 모든 것을 로드한 후, 제어권을 고수준의 시스템에게 넘긴다."
> 어렴풋하게 느끼고 있던 것을 명확한 문장으로 잘 정리해줘서 좋았다.

### 28장 테스트 경계
p.264
테스트 API 부분 전체
> 잘 와닿지 않는다. 목적은 이해가 가는데 어떻게 하라는건지 잘 모르겠다.

**Comment by KangJiJi** [comment]
## 26장 메인 컴포넌트

p.248
"메인을 재컴파일/재배포하지 않아도 된다". 책 앞부분에서도 계속 메인을 재배포하지 않아도 된다는 것을 큰 장점처럼 말하고 우리 스터디에서도 여러번 이런것들에 대해서 이야기 했습니다. 근데 또 말하고, 정말 중요하게 생각하는 것 같습니다. 또다시 이게 그렇게 중요한가라는 생각이 들었습니다. "결국 변경된 다른 컴포넌트는 재배포 돼야하는거 아닌가? 메인만 재배포하지 않아도 되는것이 무슨 의미가 있지?"

**Comment by hyesun03** [comment]
# 27장 크고 작은 모든 서비스들
p. 254
야옹이 문제 위에 있는 `이러한 믿음에도 어느 정도 일리가 있지만, 극히 일부일 뿐이다. ~~~`이 문단이 잘 이해가 안됩니다. 마이크로 서비스가 만능이 아닌건 맞는데 모놀리틱 시스템 보다는 훨씬 유연한건 맞지 않나 싶기도하고.. 잘 모르겠네요. 

p. 254
맨 아래에 `따라서 마이크로서비스의 개수는 프로그래머의 수와 거의 같아진다` 이 각주가 왜 있는지 모르겠습니다. 통상 1인당 마이크로 서비스 1개씩 담당하는게 이상적이라는 뜻일까요..?

**Comment by joi0104** [comment]
### 27장 '크로 작은 모든' 서비스들

p.256

> 서비스 다이어그램을 살펴보자. 이 기능을 구현하려면 이들 서비스 중 어디를 변경해야 할까? 전부다. 의심의 여지 없이 야옹이 배달 기능을 추가하려면 개발과 배포 전략을 매우 신중하게 조정해야 한다. 이게 바로 횡단 관심사가 지닌 문제다. 

이런 상황을 왜 `횡단 관심사 cross-cutting concern` 라고 표현하는지 잘 이해가 가지 않았습니다. 관심사가 흩어져있어서 각 컴포넌트를 횡단하면서 수정해줘야 하는 상황이여서 저렇게 표현한건가? 생각드네요.

p.259

>  서비스 시스템의 확장성과 개발 가능성 측면에서 유용하지만, 그 자체로는 아키텍처적으로 그리 중요한 요소는 아니다. 시스템의 아키텍처는 시스템 내부에 그어진 경계와 넘나드는 의존성에 의해 정의된다.

너무 좋은 말 같아요. 실제로 이번에 새로운 서비스를 개발하면서 기존 서비스와 완전히 분리하고 퍼사드를 활용하도록 구조를 가져갔는데 결국에는 두 서비스과 공유해야하는 데이터/도메인들이 계속 생겼고 이를 위한 추가 작업들이 너무 많이 들어서 이를 후회한 적이 있어요.

### 28장 테스트 경계

> 테스트는 시스템 외부에 있지 않다. 오히려 시스템의 일부다. ... 테스트를 시스템의 일부로 설계하지 않으면 테스트는 꺠지기 쉽고 유지보수하기 어려워지는 경향이 있다.

이전부터 저희가 스터디 시간에 계속 말했던 내용이 나온 것 같아요. UI 테스트, controller 테스트와 같이 테스트 생명주기가 짦은 테스트를 지양해야겠다는 생각을 또 다시 하게되네요!

**Comment by hjsung809** [comment]
p 264 테스트 API은 통합 테스트중에서 값비싼 자원을 목킹한 것 정도로 보면 될까요?
사용자 인터페이스가 사용하는 인터렉터와 인터페이스 어댑터들의 상위집합이 될거라는게 무슨 의미일까요?

p 264 테스트가 애플리케이션 구조에 결합되는 케이스가 있다면 테스트를 좀더 단위 테스트처럼 만들어야되는게 맞다고 생각하는데 테스트 API를 만들어서 테스트 해야하는 경우가 있을까요?

**Comment by duckbok** [comment]
### 26장 메인 컴포넌트
> (p.250) 메인은 플러그인이므로 메인 컴포넌트를 애플리케이션의 설정별로 하나씩 두도록 하여 둘 이상의 메인 컴포넌트를 만들 수도 있다.

메인을 가장 바깥에서 의존성을 주입해주고 초기 진입에 필요한 지저분한 작업들을 해주는 것은 이해를 해서 그렇게 잘 쓰고있는데 이 부분은 헷갈려서 iOS에서 어떻게 해줄까 고민을 해봤습니다.. target 모듈이 나눠져있어서 빌드할 때 설정을 바꿔가며 할 수 있는데 이게 이 책에서 말하는 플러그인이라는 생각이 들어서 그 동안은 기본적으로 제공하는 test target만 사용했는데 존재 의미를 알게 된 거 같네요 ㅎㅎ

### 27장 '크고 작은 모든' 서비스들
서비스를 기준으로 아키텍처를 보면 안된다.. 라고 이해를 했습니다. 하지만 결론에는 클라이언트와 서비스가 강하게 결합되어 아키텍처적으로 의미가 많을때가 더 많다는 얘기를 하는데, 어떤 예시가 있는지 궁금하네요!

### 28장 테스트 경계
돌이켜보면 제가 막 개발하다가 테스트하려면 빨간 줄이 막 생기면서 하.. 그냥 테스트 포기하자. 라고 했던 적도 많고, 아니면 테스트 코드에 묶여서 변경을 돌아가거나 안한 적도 있는데 너무 뜨끔한 챕터였습니다. 앞으로는 분리를 잘해야겠다는 생각이 드네요.

### 29장 클린 임베디드 아키텍처
전체적으로 임베디드에 특화된 챕터라서 크게 와닿거나 이해되지는 않아서 최대한 iOS에 대입해서 읽어봤는데 펌웨어를 애플이 기본 제공하는 프레임워크라 생각하면, 이런 경우에 소프트웨어를 분리시키는 작업이 큰 의미가 있는가? 라는 생각이 들었습니다.
