### ISSUE TITLE
[7주차] 30장 데이터베이스는 세부사항이다 ~ 34장 빠져 있는 장 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#85]
.
9시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올린 사람들을 대상으로 호스트 정하기 사다리~
호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

--- 안건
- 스터디 이대로 괜찮은가.
- 도메인 영역에서도 어노테이션을 통해 bean에 등록하기만해도 스프링에 의존성이 생기는거 아닌가?
- 프레임워크와는 적당한 거리를 둔다면 프레임워크를 전혀 준비하지 않더라도 필요한 유스케이스 전부에 대해서 단위테스를 할 수 있어야 한다.
- 유스케이스란?

**Comment by GyujinCh0** [comment]
### 33장
p.314  결론부분
> 액터의 분리와 의존성 규칙이라는 핵심개념을 잘 정리해줘서 좋았다. 이전 장들의 내용을 복습하기에 좋은 장인 것 같다.

### 34장
p.322-327 컴포넌트 기반 패키지 부분 전체
> 서로 연관 되어있지만  흩어져 있는 기능들을 하나의 컴포넌트로 모은다. 이렇게 하면 어떤 기능을 추가하거나 변경할 때 그 컴포넌트 하나만 살피면 된다. 따라서 계층 기반 패키지에서 우회 등으로 인해 나타나는 의존성 문제들을 막을 수 있다. 이렇게 이해했는대 맞는지 잘 모르겠다.

**Comment by hyesun03** [comment]
## 30장, 31장
데이터베이스는 세부사항이고, 웹은 세부사항인건 알겠는데 '마케팅 귀재'라고 비꼴거까지 있나? 뭐 이런 생각이 들었습니다. 돈을 벌려고 파는 소프트웨어의 1순위는 고객만족이고, 좋은 설계나 공학적인 근거 등등은 전부 후순위라 생각하는데, RDBMS 관련 일화인 p.294, 295를 보면서 별 공감은 안갔습니다. 

## 32장
p. 306 아래쪽에 `@Autowired 어노테이션이 업무 객체 도처에 산재해서는 안된다.`는 말이 잘 이해 안갔는데요, 의존성 주입을 이상하게 막 남발하지 말고, @Autowired를 적절하게 쓰라는 말로 받아들였습니다.(다른 의도로 적어둔 말일까요?) 좀 찾아보니 아래 링크가 같이 걸려있어서 가져왔습니다 ㅎㅎ 9년전 질문글이긴한데, User 객체안에 Service 클래스를 두고 @Autowired 시도하는 분도 있었군요..
https://stackoverflow.com/questions/15455878/how-to-autowire-business-objects-in-spring

**Comment by joi0104** [comment]
### 32 장 프레임워크는 세부사항이다 

> p305. 사실상 프레임워크 제작자는 당신에게 프레임워크와 혼인하기를 요구하는 것이다. 이 혼인관계는 일반적이다.

너무나 재미있는 표현이었다 ㅋㅋㅋㅋㅋ 저런 측면으로 봤을때 내가 쓰고있는 코드는 일부다처제가 아닐까... 너무나 많은 결혼을 하고 있다...

> p.306 업무 객체를 만들 때 프레임워크가 자신의 기반 클래스로부터 파생하기를 요구한다면, 거절하라! 대신 프락시를 만들고, 업무 규칙에 플러그인 할 수 있는 컴포넌트에 이들 프락시를 위치시켜라.

우리가 스터디하면서 항상 이야기 나눴던 부분이었지만, 실제로 프레임워크를 추상화 시켜서 결혼을 피하기가 쉽지 않았던 경험이 있다. ([zod](https://www.npmjs.com/package/zod) 와 같은 라이브러리) 라이브러리의 인터페이스가 워낙 독특해서 추상화에 비용이 많이드는경우에 도입을 포기한적이 있는데, 추상화 비용을 적게 가져가면서 빠르게 도입할 수 있는 방법은 없을까..

### 34장 빠져 있는 장


> 본질적으로 이 접근법에서는 업무 로직과 영속성 관련 코드를 하나로 묶는데, 이 묶음을 나는 컴포넌트라고 부른다.

위 그림에서 OrdersComponent는 다른 아키텍쳐의 OrdersService와 다른게 뭘까? 영성성 관련된 코드는 결국 Repository가 담당하게 될텐데, 그럼 결국 업무규칙만 수행하게 되지 않나? Service와 똑같지 않나? 컴포넌트 기반 패키지에 대해서 잘 이해를 못한거 같다..

**Comment by hjsung809** [comment]
34장 빠져있는 장은 기고문이라 그런지 뭔가 납득이 잘 안되는 부분이 많았던것 같습니다.

p 321. 도표에서 Orders가 DDD의 Entity, VO를 말하는 것 같은데 타입이 인터페이스로 되어있는데 이게 맞을까요?
그말은 즉 Orders의 세부 구현을 아래 계층에서 하라는것 같은데 도메인 로직의 격리 측면에서 잘못된 도표같습니다.
도표가 엄밀하지 못한게 맞을까요?

p326. 업무 로직과 영속성 관련 코드를 하나로 묶어 컴포넌트라고 부른다고 설명하고 "컴포넌트는 ~ 연관된 기능의 묶음으로 ~" 라고 했는데, 도메인 로직과 영속화는 연관된 기능이 아닌것 같은데 다른 분들의 생각이 어떤지 궁금합니다.
오히려 앞에서 계층형 아키텍처의 단점을 말하는 것처럼, 도메인 계층의 불변식을 무시한채 레포지토리에 접근하는 케이스를 막기 위해 도메인 로직과 영속화를 같이 묶는다는게 좀더 납득되는것 같습니다.

**Comment by genie-youn** [comment]
# 30장 데이터베이스는 세부사항이다.

> 디스크가 없다면 어떻게 될까? 292p 

브라우저에서 페이지의 상태를 저장하기 위해 예전에는 세션 스토리지에 직렬화해서 넣고 뺏고했다. 이제는 BFCache가 Heap의 상태와 진행중이던 timer 까지 멈춘채로 스냅샷을 저장했다가 복구해준다. 이렇게 생각하니 이 장의 내용이 좀 더 와닿았다.

# 31장

> (한숨이 나온다) 298

ㅋㅋㅋ

> 마케팅의 귀재는 어디나 존재하며, 당신이 사소한 결합을 만드는 순간 물고 늘어지려 항상 대기하고 있기 때문이다. 300

요즘 세상은 긍정적인 이유로 UI 변경이 잦다. 더 나은 UI.UX를 제공하고 위해 많은 서비스들이 다양한 시도를 하기도 하고 웹이 앱보다 갖는 강점이 그러한 것이기 때문에..

**Comment by duckbok** [comment]
### 30장 데이터베이스는 세부사항이다
> 293p,디스크가 모두 사라진다면, 그래서 모든 데이터가 RAM에 저장된다면 데이터를 어떻게 체계화할 것인가?

생각을 해본 적이 없었는데 책에서 얘기한 듯이 정말 당연하게 하던 작업이어서 한 대 맞은 기분이었습니다.

> 296p, 첫 문단

엔터프라이즈는 뭔지 잘 모르겠는데, 서비스지향 아키텍처도 기술적인 이점보다 마케팅적인 부분이 더 큰 게 맞는걸까요??

### 31-32장 웹/프레임워크는 세부사항이다.
저번에도 궁금해했던 iOS가 종속된 Swift, Foundation 프레임워크까지도 추상화를 해야하는가에 대해서 책에서도 해답을 찾을 수 있던 장이었습니다. 애플이 UI를 그리는 프레임워크를 새로 공개한지도 3년이 지났는데 상용화가 되지 못하고 계속 두 개의 프레임워크를 모두 지원하는 중인것을 보면, 애초에 개발을 할 때 유스케이스를 UI와 분리해두면 확실히 이런 변화에 빠르게 적용할 수 있을 거란 생각이 들었습니다.

### 33장 사례 연구: 비디오 판매
> 312p, 각주 1

UML 표준을 고수하는 의미를 찾지 못하겠다는 내용이 있는데 큰틀은 유지하되 팀에서 정한 규칙대로 바꿔서 사용하는지 궁금하네요! 저는 그릴 때 막 찾아서 하다가 세부적인 내용은 너무 복잡해서 대충 제 맘대로 하게 되더라구요..ㅎㅎ

### 34장 빠져 있는 장
항상 계층형으로 그룹(디렉터리)를 한 프로젝트에 나눠서 코딩을 했는데, 이게 331p에서 말하는 모노리틱 애플리케이션인듯한 느낌이 드는디 맞는 지 궁금하네요 ㅎㅎ 책에서 패키지가 새로 나올때마다 오 괜찮은데? 라는 생각을 하며 읽었습니다. 특히 321p 포트와 어댑터에서 영속데이터의 추상화에 대한 이름을 Repository라고 안두고 도메인과 관련되게 붙여준게 인상깊었고, 324p의 그림같이 추상화한거를 뛰어 넘는 거는 생각도 안해봤는데, 이런 접근제어를 나누는 방식에 대해서 고민을 해봐야겠다고 반성하게 되네요.
