### ISSUE TITLE
[8주차] 부록 전부!

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#86]
.
9시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올린 사람들을 대상으로 호스트 정하기 사다리~
호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

--- 안건
- 클린 아키텍처 스터디 회고
- 2회차 함께할 사람 모집하기
- 동아리 세미나 어떻게 하지? 듣고싶은 사람은 있나?
- 진영이 숙제
- 도메인 영역에서도 어노테이션을 통해 bean에 등록하기만해도 스프링에 의존성이 생기는거 아닌가?
- 프레임워크와는 적당한 거리를 둔다면 프레임워크를 전혀 준비하지 않더라도 필요한 유스케이스 전부에 대해서 단위테스를 할 수 있어야 한다.
- 유스케이스란?

**Comment by duckbok** [comment]
책에서도 말하지만 저자의 연대기여서 대부분 내용을 한 눈으로 보고, 한 눈으로 흘리면서 봤네요.. ㅎㅎ 그래도 격한 감정이 생생하게 와닿아서 재밌게 읽었습니다. 

> 3주 동안 천장만 노려보다가 이틀 만에 몸에 있는 모든 구멍이란 구멍에서 코드를 쏟아내는 식이었다. 그러고는 퇴사했다. 
> ...
> 이 경험은 내게 훌륭한, 클린 코드의 가치를 깊이 새겨주었다. (356p ~ 357p)

> 몸에서 구멍이라고 볼 수 있는 모든 곳에서 우리는 C코드를 쏟아냈다. (377p)

과거의 경험에서 클린코드의 가치를 깨달은 저자도 스타트업의 일정에는 당해내지 못하고 쏟아내는 모습이 인상적이였습니다..

> "폴링(Polling)" (363p)

하나의 프로그램(장치)이 다른 프로그램(장치)을 주기적으로 검사해서 일정 조건을 만족하면 처리하는 방식이라고 하네요..!

> 소프트웨어 아키텍처가 완전히 다를지라도 효과는 동등할 수 있다. (368p)

친구와 프로젝트를 할 때 아키텍처를 어떻게 할지에 대해서 왈가왈부했던 적이 있었는데, 그 때 저자처럼 제가 생각하는 게 더 낫다는 전제하에 얘기를 했던 기억이 나서 적어봤습니다. 인용한 문장과 같은 상황은 아직 잘 모르겠는디.. 저런 걸 느낄 일이 있을까요??
