### ISSUE TITLE
[클린코드] 1주차 3장 함수 끝까지 ~ 65p

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#87]
코멘트로 간단한 자기소개를 작성해 주세요.
이번 스터디에서 이 부분은 꼭 얻어가고 싶다는게 있다면 함께 남겨주세요.

스터디에서 읽을 책.
- 클린코드
- 객체지향의 사실과 오해
- 리팩터링
- TDD
- 오브젝트
- GoF의 디자인 패턴
- DDD
- 클린아키텍처

개인적으로 곁들여 읽으면 좋은 책.
- 소프트웨어 장인
- 실용주의 프로그래머
- 맨먼스 미신
- 익스트림 프로그래밍
- 코딩 호러가 들려주는 진짜 소프트웨어 개발 이야기
- 코딩 호러의 이펙티브 프로그래밍
- 조엘 온 소프트웨어

.
8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 짧은 세미나 발표하기~

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by usageness** [comment]
안녕하세요, 이번 스터디부터 다시 함께할 17학번 김용래입니다. 웹 프론트엔드 개발자를 지망하고 있고, 리액트와 타입스크립트를 배우고 있습니다.

1회차 북스터디를 중간부터 참여해서 클린 코드는 이번이 1회독입니다. 처음 읽는 입장에서 궁금한 점이 많아 엉뚱한 질문을 믾이 남길 것 같은데, 가감없이 답변해주시면 감사하겠습니다. 잘 부탁드립니다.

**Comment by junnie082** [comment]
안녕하세요, 21학번 전효정입니다.
현재는 덕환 선배님과 iOS 스터디를 진행하고 있고, C 언어로 자료구조를 공부하고 있습니다. 

아직 실력도 없고 부족한 점이 많지만, 이번 스터디를 통해 저만의 지식 체계를 넓혀 나감으로써 시간이 흘렀을 때 더 나은 프로그래머가 되고 싶습니다. 

이것도 모르나 싶을 정도로 어이 없는 질문들이 많을 것 같지만 너그럽게 봐주셨으면 좋겠습니다.
잘 부탁드립니다!

**Comment by yossogood8611** [comment]
안녕하세요! 19학번 이유진입니다.
프론트엔드 개발자로 진로를 설정해두고 있고, 웹과 앱을 개발합니다.

이번 스터디에서 저만의 목표는 전공에 대한 몰입 유지, 책에 대한 다양한 견해를 맛보아 전공 식견을 기르는 것입니다.
2학기 캡스톤, 키스트 인턴과 병행할 예정인데, 스터디의 마지막 즈음엔 부쩍 성장해 있는 모습을 볼 수 있길 기대중입니다!
주말에 노느라 바빠 정신없는 글을 한 번 쓰고 다음 날에 조금 수정하는 과정을 거칠 것 같습니다. 미처 수정이 되지 못한 두서없는 글이 매우 많을 것 같아 걱정이지만 너그럽게 이해해주실 거라 믿겠습니다.. 감사합니다!

---

### **"르블랑의 법칙, 나중은 결코 오지 않는다."**
: 르블랑이라는 롤 챔피언이 생각나서 저 혼자 재미났던 기억이 있지만, 가장 공감되었던 부분입니다. 일단 돌아가는 프로그램을 완성시키고 추후 보수를 다짐했던 적이 많았습니다. 그러고는 약 90%의 확률로 다신 열어보지 않았는데, 혹 열어보더라도 수정하고 싶지 않은 코드라 고이 덮어놨습니다. 나쁜 코드로 시작한 프로젝트는 개선하는 과정에서도 나쁜 코드를 만들어 낸다는 말 또한 이해가 되었고, 나쁜 코드로 시작한 프로젝트의 생산성은 0이 되고, 재설계의 꿈도 무너져 내린다는 말에 깊은 공감이 되어 이 문구를 남깁니다.
(개발한 것 중에 작동은 되지만 코드의 가독성이 매우 떨어지고 변수명도 부끄러워 차마 포트폴리오에 올리기 망설여지는 것이 있습니다.. 후회가 되지만 절대 고칠 생각은 없어요)

### **"소프트웨어를 짜는 행위는 여느 글짓기와 비슷하다"**
: 컴퓨터 "언어"라는 말을 다시 한 번 떠올리게 하는 문구였습니다. 글짓기에서 의미가 분명한, 이해하기 쉬운, 불필요한 부분이 없는 글이 깔끔하고 정돈된 글임은 누구나 공감할 것입니다. 글짓기와 마찬가지로 우리는 프로그래밍 "언어"를 사용해 이야기를 풀어나가야 합니다. 이야기를 매끄럽게, 간단하게, 잘 읽히게 풀어나가야 하며 초안을 작성한 후 다듬는 작업 또한 필요합니다. 책을 읽을 수록 프로그래밍 "언어"라고 하는 이유를 깨닫게 되었습니다.
이야기를 매끄럽게 풀어나가기 위해, 언어를 이용해 최대한 작게 나누어 의미를 분명하게 표현하는 법, 의도가 분명한 이름을 짓는 것을 연습해야 하고, 고민해야 합니다.
이 책에서는 이야기를 짓기 위해 고민해야 함과 함께 고민해야 할 것, 연습해야 할 것들을 설명하고 있습니다. 코딩할 때 좋은 이야기를 위해 조금이라도 고민한다면 저는 이 책의 효과를 보는 것이라고 생각합니다. 너무나 작은 목표같지만, 작은 고민이 습관이 되길 바라면서 문구를 정했습니다!

---

### **궁금했던 점**
- 함수를 설계할 때 한 가지만 하게 해야한다는 말에 리액트로 만들었던 ajax 함수를 생각해보았습니다. json으로 데이터를 받아오고 원하는 데이터를 변수로 저장하고, 오류를 처리하는 등의 다양한 일을 합니다. 하지만 한가지 일을 한다면 이 함수를 데이터를 받아오기만 하고 데이터 자체를 저장하게 한 후, 데이터를 나누어 변수로 저장하게 하는 함수를 추가하고 오류를 처리하는 예외 함수는 따로 만들어야 하는 것인지. 한 가지 일이라는 범위를 어떻게 나누어야 하는지가 궁금했습니다. 그리고 중복되는 일이 아니어도 함수를 따로 만들어야 하는지 또한 궁금했습니다. 같은 예외가 생기더라도 다른 일을 해야할 수 있는데, 그럼 함수마다 예외처리하는 함수도 각각 만들어야 하는지입니다.

---

### **느낀 점**
- 생각할 것, 궁금했던 점을 쓰며 실제 코드들에 집중하지 않고 큰 맥락에 초점을 맞추는 것을 느꼈습니다. 이 책으로 동기와 5장까지 정리하고 생각을 나누는 스터디를 예전에 했었는데, 그 때에도 친구는 3장을 읽고 의존석 자석 오류 코드의 뜻, 중복 제거 전략인 구조적 프로그래밍, AOP, COP의 개념 정리, 추상팩토리가 의미하는 바를 찾아보았습니다. 경험에 의존하여 생각해보는 저와는 다르게 새로운 개념에 집중하며 기술적 의미와 개념들을 찾아보았는데, 이런 견해를 보아도 따로 정리하지는 않았습니다. 이번엔 기술적인 개념들에 집중한 견해를 보며 코드를 짜기 위해 고민할 때 참고할 여러가지 것들을 정리해두려고 다짐합니다.

**Comment by genie-youn** [comment]
안녕하세요. 12학번 윤지수라고 합니다.

TCP에서 북스터디를 4년째 운영하고 있고, 어떻게 하면 시장의 요구사항에 따라 기민하게 반응할 수 있는 소프트웨어를 만들수 있을지에 대해 관심이 많습니다.

카카오, 네이버를 거쳐 현재는 토스 페이먼츠에서 프론트엔드 개발자로 일하고 있습니다.

---

들어가며 읽었나요?

# 깨끗한 코드

4p.
회사가 망한 이유는 결국 나쁜코드 탓이었다.
우리 모두는 대충 짠 프로그램이 돌아간다는 사실에 안도감을 느끼며 그래도 안 돌아가는 프로그램보다 돌아가는 쓰레기가 좋다고 스스로를 위로한 경험이 있다.
다시 돌아와 나중에 정리하겠다고 다짐했었다. 물론 그때 그 시절 우리는 르블랑의 법칙을 몰랐다. 나중은 결코 오지 않는다.

```
나는 우하하고 효율적인 코드를 좋아한다. 논리가 간단해야 버그가 숨어들지 못한다. 의존성을 최대한 줄여야 유지보수가 쉬워진다. 오류는 명백한 전략에 의거해 철저히 처리한다. 성능을 최적으로 유지해야 사람들이 원칙 없는 최적화로 코드를 망치려는 유혹에 빠지지 않는다. 깨끗한 코드는 한 가지를 제대로 한다.
```

# 의미있는 이름

28p. 검색하기 쉬운 이름을 사용하라! 특히 자바스크립트 환경이라면 더더욱이..

31p. 인터페이스와 구현클래스. 저는 정 좋은 방법이 떠오르지 않는 경우 구현클래스에 Simple 접두어를 붙이는 편..

# 함수

45p. 단순히 다른 표현이 아니라 의미 있는 이름으로 다른 함수를 추출할 수 있다면 그 함수는 여러 작업을 하는 셈이다.

45p. 함수당 추상화 수준은 하나로 

49p. 일반적으로 나는 switch 문을 단 한번만 참아준다.

52p. 플래그 인수는 추하다.

62p. 일하기전 → 설계 → 테스트 → 개발 → 테스트 → 리팩터링  → 테스트 → 리팩터링 → 테스트 → 리팩터링 → 테스트 …

마치며..

코드를 따라서 타이핑 해보세요.
문제라고 얘기하는 코드가 나오면 먼저 타이핑해보고 이 코드가 왜 문제일지 생각해보고 저자가 왜 이 코드가 문제라고 얘기하는지와 비교해보세요.

**Comment by KangJiJi** [comment]
안녕하세요. 16학번 강지훈입니다.

학부생때는 프론트엔드 개발자를 꿈꿔왔고, 새로운 것을 경험하고 싶어 현재는 도메인을 바꿔서 데이터엔지니어로써 일하고 있습니다. 데이터 ETL 파이프라인을 구현 && 유지보수 하는 일을 합니다. 병렬처리, 빅데이터 등등 학부생때는 알기 힘든것들이 많아서 자신의 가치를 올리기 좋은 직종이 아닐까 생각합니다.

넷마블 빅데이터실 데이터엔지니어링팀에서 근무하고 있습니다.

# 깨끗한 코드

p17) 실제로도 이 책에서 주장하는 기업 다수는 논쟁의 여지가 있다, 여러분도 모든 기법에 동의하지 않으리라. 어떤 기법은 격렬히 반대하리라. 그래도 괜찮다. 우리 생각이 무조건 옳다고 주장할 의도는 없으니까. 하지만 권고한다. 우리의 시각을 이해하고 존중하려 애써주면 좋겠다.

처음에 책을 읽고, 여러가지 적용하다보면 코드 작성이 안될때가 많았습니다. 클린코드는 정답은 아니지만, 많은 장인들이 정답이라고 생각하는 것을 모아둔 책입니다. 그래서 항상 클린코드를 지향하지만, 거기에 너무 매몰되지 않는것도 중요하다고 생각했습니다.

# 의미있는 이름

p35) 우수한 프로그래머와 설계자라면 해법 영역과 문제 영역을 구분할 줄 알아야한다.

해결하고자 하는 문제가 무엇이고, 해결법이 뭔지 도출하는 것은 매우 중요한 것 같습니다.

# 함수

p52) 이항 함수, 삼항 함수

그냥 생각없이 코드를 작성하다보면, 여러 인자를 가진 함수를 작성할때가 많습니다. 다시한번 리팩터링을 통해 분리하고 추상화 시켜서 읽기 쉬운 함수를 만들도록 노력해야겠습니다.

**Comment by siathus** [comment]
안녕하세요. 12학번 임성국입니다. 현재 백수입니다. 잘 부탁드려요.
* * *
# 깨끗한 코드
"대다수 관리자는 진실을 원한다. 일정에 쫓기더라도 대다수 관리자는 좋은 코드를 원한다. 그들이 일정과 요구사항을 강력하게 밀어붙이는 이유는 그것이 그들의 책임이기 때문이다. 좋은 코드를 사수하는 일은 바로 우리 프로그래머들의 책임이다." (p. 7)
일천하지만 흔하디 흔한 금융솔루션 중소기업에서 1년간 일하면서 느낀 바로는 일감을 가져오는 영업이건 담당자건, 심지어 고객사 담당자건 간에 그닥 진실을 원하진 않더군요. 그냥 일정 내에 대충 돌아가기만 하면 상관하지 않음.
좋은 회사를 가면 좋은 코드를 사수할 수 있을까요? 궁금하네요.

**Comment by wlsh44** [comment]
안녕하세요! 19학번 김진호 입니다.
이번에 4학년 1학기를 다니게 되고, 백엔드 개발자를 목표로 하며 스프링을 공부하고 있습니다.
예전부터 북스터디에 참여하고 싶었는데 이번에 기회가 되어 함께 책을 읽게 되었습니다.

평소에 좀 더 나은 코드를 작성하려고 노력을 많이 하는데 잘 되지 않아 힘든 경험이 많았습니다.
이번에 클린코드를 읽으면서 조금이나마 성장하기 위해 열심히 노력하겠습니다 🙂

#깨끗한 코드

p17) 우리는 저자다

이 부분을 보면서 동시에 우리 또한 독자라는 생각을 했습니다. 내가 짠 코드는 아마 내가 제일 많이 보게 될 것이고 본인이 작성했음에도 며칠 뒤에 다시 봤을 때 이게 뭐지라는 생각을 참 많이 했어서 나를 위해서라도 이 책을 보며 조금 더 좋은 코드를 작성하고자 하는 의지를 가지게 된 것 같습니다.

#의미있는 이름

p28) 검색하기 쉬운 이름을 사용하라.

가끔 코드를 작성할 때 29p의 첫 번째 예시처럼 의미가 불분명한 매직 넘버를 사용한 적이 있습니다.
이런 경우에는 항상 며칠 뒤에 코드를 다시 보거나 남이 제 코드를 볼 때 다시 한 번 생각하게 만들게 되어 고치려고 노력하고 있어 인상깊게 보았습니다.

다만 **이름 길이는 범위에 비례해야 한다** 는 말이 약간 이해가 가지 않았습니다. 로컬로 딱 한 번 사용되는 상수라 할지라도 그 역할에 맞게 이름이 길어질 수 있다고 생각하는데 어떻게 생각하시는지 궁금합니다!

#함수

42p) 작게 만들어라

예전에 c언어로 하나의 파일에 5개 함수, 25줄 이내의 컨벤션을 갖고 코딩을 해야돼서 힘들었던 기억이 있는데 요즘들어 그때의 경험이 참 도움이 많이 되었던 것 같습니다😂

45p) 함수 당 추상화 수준은 하나로

함수를 분리하는데 있어 굉장히 중요하다고 생각이 되는데 종종 각 함수의 추상화 레벨을 쉽게 파악하지 못하는 경우가 있습니다.
혹시 추상화 레벨을 나누는 개인적인 기준? 또는 노하우가 있는지 궁금합니다!

52p) 변환 함수 형식을 따르는 편이 좋다.

`setter`의 역할을 하는 함수들을 제외하고 최대한 리턴 값이 `void`인 함수를 피하려고 노력하고 있습니다. 
함수 내부에서 인수의 값이 변경되게 되면 후에 코드를 볼 때나 디버깅할 때, 테스트 코드를 작성할 때 힘든 적이 많았습니다.
