### ISSUE TITLE
[클린코드] 2주차 4장~5장 ~116p

### ISSUE THREAD

**Issue by yossogood8611** [TeamCrazyPerformance/http#88]
2주차 호스트 이유진입니다!

이번주 스터디 범위는 4장~5장 전체입니다.

조금 일찍 올려주신다면 원활한 진행을 위해 정독해오도록 하겠습니다.
감사합니다~!!

---
- 주석으로 처리한 코드가 제일 찔렸다. 개발을 하며 함수 재사용을 고려하지 않아 나중에 여기서 또 이렇게 기능을 구현하면 되겠지~하고 적어놓고 주석처리해뒀는데, 모든걸 잘못하고 있었던 것..
- 호출하는 함수를 호출되는 함수보다 먼저 배치해야 한다. 신문 기사처럼 코드를 작성하라는 말이 와닿았다.
- 앞으로 먼저 개발해뒀던 코드를 읽어보게 될 텐데, 원래 있던 코드 분석은 어느 정도로 어떻게 하면 좋을지 궁금했다. 예를 들어, 알림 기능을 새로 추가해야 한다면? -> 전체 데이터와 기능들을 대충 살펴보고 알림 기능과 관련 데이터들을 자세히 읽는다.

---
8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 짧은 세미나 발표하기~

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by joi0104** [comment]
## 4장 주석

- 책에서 나왔던 좋은 주석에 대해서는 해당되지 않지만, 개인적으로 좋았던 주석이 있었는데 **복잡하고 어려운 도메인 용어를 표현하는 주석**이었다. 개인적으로는 너무 좋았던 부분. (나중에는 javadocs에서 정의한 description을 가져와서 자동으로 generate 해주면 개발자 수고가 더 줄 수 있을 것 같다.)

```typescript
interface Response {
  /** 카드결제조건그룹 **/
  terminalId: string;
}
```

vscode에서 해당 값에 hover하면 아래와 같이 나타난다.
![image](https://user-images.githubusercontent.com/28296417/187059490-f43bed7d-70b3-4b4d-b04b-5af9ecf2db74.png)


- 같은 이야기를 중복하는 주석 부분을 읽다보니 내 테스트 코드가 생각났다. 아래와 같이 테스트 코드에서 비슷한 개념들을 빈 행으로 분리하고 when, given, then 주석을 추가하였는데 불필요할까? 예시는 사실 간단한 테스트 코드지만, 조금 복잡한 코드(모킹을 해야하는 등등 테스트 코드 환경을 만들기 위한 작업이 필요한 경우)에서는 확실히 가독성이 좋다고 느꼈고 수정하기에도 편했다.

```typescript
describe('removeSpace', () => {
  test('공백이 존재하는 문자를 넘기면, 공백이 제거된 문자를 반환한다.', () => {
    //Given
    const given = 'foo bar ';

    //When
    const actual = removeSpace(given);

    //Then
    const expected = 'foobar';
    expect(actual).toBe(expected);
  });
}
```

## 5장 형식 맞추기
- 전체적으로 내용이 좋았다. 밀접한 것들은 가까이. 위에서 아래로 고차원에서 저차원으로. 코드는 컴퓨터가 아니라 사람이 읽는다는 것을 다시 한번 상기할 수 있었다.
- 평소 린트로 위임하던 들여쓰기나 공백에 대해서도 다시한번 생각해볼 수 있었다. 연산자 우선순위를 공백으로 표현한 것도 인상깊었는데, 이런 부분을 챙겼을때 세심하고 정교하다라는 느낌을 받는 것 같다.
- 어제도 개발하면서 위에서 아래로 고차원에서 저차원으로 라는 규칙을 가장 간과한 부분이 있는데, 상수를 정의할때 그랬던 것 같다. 상수를 선언할때 가장 위쪽에 정의하는 경우가 많은데 상수도 결국 세부구현에 속하는 저차원이 아닐까?

```typescript
const SESSION_STORAGE_KEY = '@service/test';

const TestStorage = {
  getItem() {},
  setItem() {},
}
```

**Comment by genie-youn** [comment]
4장.
개인적으로 꼭 필요하다고 생각되는 주석은 해당 코드와 관련된 문서를 나타내는 주석

예를들어 `Config API`의 `client` 라면

```typescript
/**
*  Config API client
*  @see {@link https://payment-config-api.com/#swagger}
*/

export function fetchConfig() {
  // ..
}
```

같은 느낌으로 달아둔다.

뭐.. 광고플랫폼 팀에서 제공하는 SDK의 Adapter 라면

```typescript
/**
* AdvertPlatformSDKAdapter
* @see {@link 해당 SDK의 레퍼런스}
*/
```

그리고 늘 고민되는건 도메인 맥락에 관련된 부분을 기술해야하는지 마는지.
코드만으로 충분히 표현해내기 어려운 경우가 많은것 같다.
뭐 코드가 술술 읽히게 작성할 수 있다면 문제 없겠지만 아직 복잡한 도메인 로직을 그렇게 풀어내기엔 역량이 부족한것 같다.

**Comment by KangJiJi** [comment]
## 4장 주석

주석을 지양하는 편이 좋다고 생각하지만, 내가 속해있는 조직의 규칙을 따라야 한다. 다른 사람(상급자)의 주석을 보고, 뭐라하기 힘들 것 같다. 눈치껏 하자!!!

## 5장 형식 맞추기

lint와 같은 형식을 맞춰주는 도구들이 많다. 팀 규칙에 잘 맞게 사용하자.

**Comment by hjsung809** [comment]
4장 p94
'제곱근까지만 루프를 돌면 정말로 시간을 절약할까?'
-> 가독성, 객체 지향을 하기 위해 성능적인 손실이 있던 경험이 있으신가요? 다른 분들의 생각이 궁금합니다.
저는 반복문 1번에 모든걸 할 수 있는 경우인데 객체로 분리하고 캡슐화된 메소드를 만들어 호출하다보니 반복문을 여러번 돌거나 했던 경험이 있는데요, 이게 그저 설계의 미흡함이라고 봐야할지 아니면 객체지향이 가지는 패널티라고 생각해야할 지 궁금하네요.
저는 설계가 미흡했던거라고 생각하긴 하는데 모두가 매번 완벽한 설계를 할 수 있는건 아니라서 현실적으로 많이 발생하는 문제같습니다.

5장
형식이 주는 시각적인 정보도 코드의 일부분이라는 생각이 들어 좋았습니다.

**Comment by siathus** [comment]
# 5장 형식 맞추기
## 가로 형식 맞추기
### 가로 공백과 밀집도
p.109
```java
public class Quadratic {
	public static double root1(double a, double b, double c) {
		double determinant = determinant(a, b, c);
		return (-b + Math.sqrt(determinant)) / (2*a);
	}

	public static double root2(int a, int b, int c) {
		double determinant = determinant(a, b, c);
		return (-b - Math.sqrt(determinant)) / (2*a);
	}

	private static double determinant(double a, double b, double c) {
		return b*b - 4*a*c;
	}
}
```
다른 부분은 (크게 의식하진 않았지만서도) 그래도 평소 제가 짜는 스타일과 비슷했지만, 이 부분의 `b*b`는 제가 선호하는 방식이랑 달라서 괜히 반발심이 드네요. 변수명이 `a`나 `c`처럼 한 글자가 아니라 여러 단어로 된 긴 이름이 세 개 이상 곱셈 연산자로 묶여있을때도 읽기가 편할지? 우선순위를 위한 공백이라면 차라리 소괄호를 통해 표현하는 게 어떤가 싶네요.
```java
return (b * b) - (4 * a * c);
```
## 팀 규칙
"개개인이 따로국밥처럼 맘대로 짜대는 코드는 피해야 한다." (p.113)
별 건 아니고 이 문장의 원문이 궁금하네요. 따로국밥이라는 비유가 적절한지는 둘째치고...

**Comment by usageness** [comment]
### 4. 주석
javadocs처럼 jsdocs를 이용한 주석을 적극적으로 기용해보는것도 괜찮겠네요.
어느정도는 ts가 역할을 해주고 있어서 괜찮을지도..?

### 5. 형식맞추기
- 변수는 사용하는 위치에 가까이 선언하자?
   - 예시로 리액트 컴포넌트의 경우 각종 선언들의 위치가 정해져있다.
```jsx
function MyComponent() {
  // 최상단에는 각종 훅에서 export된 state들을 선언한다.
 const [state, setState] = useState(0);
 const {customValue, setCustomValue, customFunction} = useCustomHook();

  // 다음에는 컴포넌트 훅스를 사용한다.
  useEffect(() => {
    ...
  }, []);

  // 여기부터 각종 함수들을 선언할 수 있다.
  const componentFunctionA = () => { ... }
  const componentFunctionB = () => { ... }

  return (
    <> ... </>
  );
}
```

- 컴포넌트에서 가장 많이 사용하는 변수인 state 들은 암묵적인 약속이 있는데, 이런 경우에도 변수를 사용처에 가깝게 선언하는 것이 맞을까?
- 애초에 사용처에 멀게 선언할 수 밖에 없을 정도로 긴 코드를 만드는 것이 잘못인듯...

**Comment by duckbok** [comment]
### 4장 주석
저는 주석을 보통 MARK 주석, TODO 주석을 통해 구역을 나누거나 나중에 찾기 쉬운 용도로 주로 사용을 하고, 가끔 가다가 사용법이 필요하다 판단이 들면 JavaDocs처럼 그에 대한 주석을 남기는 편입니다.
그런데 84p를 보면 위치를 표시하는 주석은 자주 쓰면 좋지 않다고 하는데, 아래 그림과 같이 구분하는 것에 대해 다들 어떻게 생각하시는 지 궁금합니다!
<img width="328" alt="스크린샷 2022-08-28 오후 8 00 55" src="https://user-images.githubusercontent.com/63839917/187070749-22ec9d0f-50b4-4591-8222-4270b774bf27.png">

### 5장 형식 맞추기
우선 *"신문기사처럼 작성하라"*라는 문구는 굉장히 와닿았고 마음에 들었습니다. 대체적으로 서술된 내용을 끄덕끄덕하며 읽었는데 의견을 들어보고 싶은 부분이..
#### 107p, 가로 형식 맞추기
항상 고민을 하는 부분입니다.. 120~130자 정도로 맞춰서 보통 작성을 했었는데, 이게 변수명이나 함수에 의미를 넣어주다보면 이름이 길어지게 되고, 인자가 많이 필요한 경우 이를 넘어가게 되서 결국 개행을 해버리는데.. 이런 경우에 다들 어떻게 처리 혹은 예방을 하시는 지 궁금합니다.
#### 112p, 들여쓰기 무시하기
```Swift
guard let name = name else { return nil }
```
이렇게 간단하게 반환을 하는 블록의 경우 한 줄로 처리를 하는 게 깔끔하다는 생각이 들어서 저는 이렇게 작성을 하고 있는데, 이런 유혹이 책에서 말하는 거 처럼 나쁜 것인지.. 아니면 단순한 호불호인지.. 궁금합니당.

**Comment by junnie082** [comment]
pg. 68
우리는 코드로 의도를 표현하지 못해, 그러니까 실패를 만회하기 위해 주석을 사용한다. 프로그래머들이 주석을 유지하고 보수하기란 현실적으로 불가능하다. 코드만이 정확한 정보를 제공하는 유일한 존재다. 우리는 주석을 가능한 줄이도록 꾸준히 노력해야 한다.

---> 주석을 많이 달수록 내가 코드를 짠 의도를 명확하게 전달하는 것이라고 생각했는데, 오히려 반대였다니. 어떻게 해야 주석을 사용하지 않아도 나의 의도를 코드로 나타낼 수 있을까? -> 아마도 많은 경험이 필요하지 않을까?? 프로그래밍은 글을 짓는 행위와 다르지 않다고 했는데, 마찬가지로 고민을 많이 해보고 코드를 많이 짜봐야겠다. 


많은 경우 주석으로 달려는 설명을 함수로 만들어 표현해도 충분하다. 


<좋은 주석>
법적인 주석, 정보를 제공하는 주석, 의도를 설명하는 주석, 의미를 명료하게 밝히는 주석, 결과를 경고하는 주석, TODO 주석, 중요성을 강조하는 주석.


간과하고 있던 형식의 중요성을 깨닫게 된다.

**Comment by wlsh44** [comment]
## 4장 주석

71p: 의도를 설명하는 주석

의도를 설명하는 주석과 함수나 변수로 제대로 표현하지 못하여 적는 주석의 경계가 모호하다고 느꼈습니다.
특히 저같은 경우는 어떠한 계산이 필요한 경우나 오프셋을 설정해주는 경우에 종종 주석을 사용합니다.

```java
//JPA 페이징 처리를 0부터 하기 때문에 -1 처리
Pageable pageable = PageRequest.of(page - 1, PAGE_SIZE);
```
예를 들어 JPA의 `Pageable`은 첫 번째 페이지를 0부터 시작하여 데이터를 가져오는데 실제 페이지는 1부터 시작하고 `page - 1`이 부분을 함수로 빼서 이름을 짓기도 잘 생각이 나지 않아 주석으로 처리했습니다.
혹시 이에 대해 좀 더 나은 의견이 있는지 궁금합니다.

또 '정말 이때가 아니면 주석을 사용하지 않는다' 하는 본인만의 기준이 있으신지도 궁금합니다!


## 5장 형식 맞추기

96p: 적절할 행 길이를 유지하라

예전에 c언어로 개발할 때 함수 세로 25줄, 가로 75줄, 한 파일 내에 함수 5개 이내, 가로 정렬 등의 컨벤션으로 개발을 한 적이 있는데 당시에 개발을 시작한지 얼마 되지 않아 상당히 힘들었던 기억이 납니다...

98p: 신문 기사처럼 작성하라

함수의 이름만 보더라도 코드를 이해할 때 이 함수를 봐야 하는지 아닌지를 알게되는 경우가 있었던 것 같습니다.
특히 보통 글쓰기를 할 때 제목의 중요성, 첫 문장의 중요성에 대해 배우는데 비슷한 맥락이지 않을까 하며 인상깊게 읽었습니다.

104p: 종속 함수

보통 개발을 하거나 리팩토링을 할 때 IDE에서 메서드 추출 단축키를 사용해 함수를 추출했는데 이러다보니 추출된 함수의 위치를 신경쓰지 않게 된 것 같아 이 부분에 대해 좀 더 신경써야 되겠다고 느꼈습니다.
