### ISSUE TITLE
[클린코드] 3주차 ~8장 경계 끝까지 (~152p)

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#89]
지난주에 리팩터링한 코드 집단지성으로 리팩터링하기

---
8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 짧은 세미나 발표하기~

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by yossogood8611** [comment]
- 객체는 자료를 숨기고 함수(동작)를 공개한다. 새 객체 타입을 추가하기 쉽고 기존 객체에 새 동작을 추가하기는 어렵다. 새로운 자료 타입을 추가하는 유연성이 필요하면 객체가 더 적합
- 자료구조는 동작없이 자료를 노출한다. 자료 구조에서 새 동작을 추가하기 쉽고 기존 함수에 새 자료구조를 추가하기는 어렵다. 새로운 동작을 추가하는 유연성이 필요하면 자료구조가 더 적합
- 클래스와 객체지향 / 절차적인 코드와 자료 구조를 적절한 상황에 따라 사용. 잡종 구조는 피하는 것이 좋다.
-> 그렇다면 각각 적절한 상황의 예시에는 무엇이 있을까

- try-catch-finally 문부터 사용
- 확인된 예외는 의존성의 문제가 있음
- 애초에 null 값이 넘어오지 못하게 하는 것이 좋음

- 경계를 숨긴다. 외부 코드가 변하더라도 나머지 프로그램에 영향을 미치지 않음.
- 학습테스트 : 패키지의 새 버전으로 이전하기 쉬워진다.
- 통제가 불가능한 외부 패키지에 의존하는 대신 통제가 가능한 우리 코드에 의존하자.
- 새로운 클래스로 경계를 감싸거나 ADAPTER 패턴을 사용해 우리가 원하는 인터페이스를 패키지가 제공하는 인터페이스로 변환하자.
-> 새로운 패키지를 사용할 때 학습테스트는 따로 파일을 만들어서 남겨두고 패키지 업데이트 시 확인하는 방식?
-> 맞다면 만약 패키지를 많이 사용할 경우 각각의 패키지마다 학습테스트 파일을 만들어두는지. 혹시 이것이 추가될 코드 파일들로 인한 복잡함 증가, 학습테스트의 이점. 둘 중 고민하게 될 여지가 있는지.

**Comment by KangJiJi** [comment]
# 6장 객체와 자료 구조

### 121

함수를 추가하는것은 어렵지 않게 할 수 있겠지만, 휴먼 폴트가 발생할 여지가 있는 것 같다. 이런 경우는 6-6 예제처럼 다형성으로 풀어내야 하는 문제라고 생각된다.

### 125

디미터의 법칙을 위배하지 않기 위해서 125쪽 맨 아래와 같이 리펙터링을 한다는데...잘 이해가 안간다. 결국은 scratchDir 객체에서 제공해주는 절대 경로가 필요한 것인데, 125쪽 맨 아래 메서드의 구현은 결국 scratchDir 의 절대 경로 메서드를 호출하는거 아닌가?

### 140

단순 궁금증) 서버개발에서 api 인자가 없는 경우는 어떻게 처리하나? api를 요청하는데 필수적인 인자가 5~6개 라면 이 경우는 결국 각각의 인자에 대해서 입력이 없을 시 어떤 값을 반환해야하는지 다 정의해야하나? 좀더 우아한 방법이 있나?

**Comment by joi0104** [comment]
## 6장 객체와 자료구조

전반적으로 내용이 너무 좋고 대부분 공감가는 많아 큰 질문은 없습니다.

122p
> 분별 있는 프로그래머는 모든 것이 객체라는 생각이 미신임을 잘 안다. 때로는 단순한 자료 구조와 절차적인 코드가 가장 적합한 상황도 있다

개인적으로 뼈맞은 부분이다. 절차적인 코드는 지양해야한다고 생각했는데 결국 이 부분도 trade off 지점이라는 것을 깨달았던거 같다.

123p

- 디미터 법칙을 지켰을때 가질 수 있는 이점을 명확하게 말하기가 어렵다. 제대로 이해를 못한거 같기도 한데, 낯선사람을 경계하고 친구랑만 놀게 됨으로써 어떤 이점을 가질 수 있는지?

123p
- `getOptions().getScratchDir().getAbsolutePath()` 이런 코드를 기차충돌이라고 표현하고 이를 지양해야 한다고 적혀있는데, `[].map().sum()` 이런 함수도 기차충돌 코드인가? 함수형 프로그래밍에서는 이를 지향하지 않나?

**Comment by siathus** [comment]
# 객체와 자료 구조
## 자료 전달 객체
> 좀 더 일반적인 형태는 빈(bean) 구조다. 빈은 비공개 변수를 조회/설정 함수로 조작한다. 빈은 일종의 사이비 캡슐화로, 일부 객체지향 순수주의자나 만족시킬 뿐, 별다른 이익을 제공하지 않는다.

여기서 말하는 빈은 스프링에서의 빈과는 다른 개념인가?
# 오류 처리
## null을 전달하지 마라
> 대다수 프로그래밍 언어는 호출자가 실수로 넘기는 null을 적절히 처리할 수 있는 방법이 없다. 따라서 애초에 null을 넘기지 못하도록 금지하는 정책이 합리적이다. 즉, 인수로 null이 넘어오면 코드에 문제가 있다는 의미이다.

개발자가 주의해서 코드를 짜는 것 이외에 인수로 null이 넘어오지 못하도록 강제할 수 있는 방법이 있을까요?
# 경계

학습 테스트를 통한 외부 라이브러리 학습 좋아보이네요.

---
이해하는데 크게 방해가 됐던 부분은 아니지만 특히 6, 7장의 코드 및 설명에서 오탈자가 너무 많아서 좀 그랬음... 적어도 코드만큼은 틀리지 않도록 검수를 더 꼼꼼하게 했어야 하지 않을까 싶네요.

**Comment by hjsung809** [comment]
6장 객체와 자료구조
1.
자바의 Map은 처음엔 자료구조라고 생각했는데 구체적인 구현이 감춰진채로 isEmpty, size 등 추상화된 메서드를 제공하기 때문에 객체로 구현되어 있다고 생각됩니다. Map을 자료구조로 활용할 수있어 헷갈렸던것 같은데 맞을까요?
2.
DDD의 VO도 추상화된 메소드로 구성할수록 바람직 하니 객체로 생각됩니다. 어떻게 생각하실까요?

**Comment by junnie082** [comment]
6장.  
(자료구조를 사용하는) 절차적인 코드는 기존 자료구조를 변경하지 않으면서 새 함수를 추가하기 쉽다. 반면, 객체 지향 코드는 기존 함수를 변경하지 않으면서 새 클래스를 추가하기 쉽다. 반면, 객체 지향 코드는 기존 함수를 변경하지 않으면서 새 클래스를 추가하기 쉽다.

[디미터 법칙]
디미터 법칙은 잘 알려진 휴리스틱으로, 모듈은 자신이 조작하는 객체의 추사점을 몰라야 한다는 법칙이다. 객체는 자료를 숨기고 함수를 공개한다. 
디미터 법칙은 "클래스 C의 메서드 f는 다음과 같은 객체의 메서드만 호출해야 한다"고 주장한다. 
1. C 클래스
2. f가 생성한 객체
3. f 인수로 넘어온 객체
4. C 인스턴스 변수에 저장된 객체
final String outputDir = ctxt.getOptions().getScratchDir().getAbsolutePath();

[기차 충돌]
흔히 위와 같은 코드를 기차 충돌이라 부른다. 일반적으로 조잡하다 여겨지는 방식이므로 피하는 편이 좋다. 
객체라면 내부 구조를 숨겨야 하므로 확실히 디미터 법칙을 위반한다. 반면, 자료 구조라면 당연히 내부 구조를 노출하므로 디미터 법칙이 적용되지 않는다. 

[잡종 구조]
잡종 구조는 중요한 기능을 수행하는 함수도 있고, 공개 변수나 공개 조회/설정 함수도 있다. 공개 조회/설정 함수는 비공개 변수를 그대로 노출한다.

[구조체 감추기]
코드 예제처럼 줄줄이 사탕으로 엮어서는 안된다. 객체라면 내부 구조를 감춰야 하니까. 
ctxt.getAbsolutePathOfScratchDirectoryOption();

**Comment by wlsh44** [comment]
## 객체와 자료 구조

### 디미터 법칙

디미터 법칙은 여러 개의 도트(.)를 사용하지 말라는 법칙으로도 알려져 있다고 합니다.
기차 코드를 보면서 자바의 Stream API는 기차 코드일까 라는 궁금증이 생겨 찾아봤습니다.
그 결과, 우선 디미터 법칙은 객체의 결합도와 관련된 법칙이고 `어떤 메세지를 전달하는가`가 중요하기 때문에 Stream은 객체를 Stream 객체로 변환할 뿐, 그 stream을 어떻게 사용하느냐에 따라 디미터 법칙을 준수할 수도 있고 아닐 수도 있다는 답을 얻었습니다.

## 오류 처리

### 예외에 의미를 제공하라

저는 개발을 하다보니 예외의 의미를 제공하는 방식이 크게 3가지로 나뉘어졌습니다.

인증에 관련해서 예를 들 경우
`원인` - `UserNotFoundException()` `PasswordNotCorrectException()`
`결과` - `LoginFailedException()` `SignUpFailedException()`
`도메인` - `AuthenticationFailedException()`

예를 들어 저같은 경우는 맨 처음에 예외의 이름에 `원인`을 붙여주었습니다.
그런데 개발을 하다 보니 종종 `결과` 가 이름이 되는 경우랑 섞이거나, 너무 많은 예외 클래스가 생겼습니다.
그래서 최근에는 `도메인` 을 예외의 이름으로 두고 내부에 원인과 결과를 추가하는 식으로 개발하고 있습니다.
다른 분들은 어떤 방식으로 예외의 의미를 제공하는지 궁금합니다.

### null을 반환, 전달하지 마라

제가 실력이 부족해서 그런지 제가 알지 못하는 부분에서 `null`이 반환되거나 전달되는 경우가 가끔 생기게 됩니다.
그래서 null 체크를 해줘야 한다고 생각은 하는데 아무리 생각해도 '여기서는 null이 넘어오지 않을 것 같다' 라고 생각이 드는 경우가 있어 null 처리를 할지 말지 고민이 되는 경우가 많습니다.
혹시 다들 개발 하시면서 그래도 '이 부분에서는 null 처리를 꼭 해준다' 하는 부분이 있으신가요?

## 경계

### 학습 테스트

학습 테스트가 단순히 외부 API의 사용법을 익히는 코드인 줄 알았는데 외부 API의 사용 방식에 따라 검증을 해줄 수 있는 코드가 되기도 한다는 사실에 학습 테스트라는 것의 중요성을 깨닫게 된 것 같습니다.
