### ISSUE TITLE
[GoF 디자인패턴] 2주차 ~ 4.2 Adapter

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#9]

**Comment by hyesun03** [comment]
# Prototype 패턴
게임에서 한 직업군(ex 마법사, 전사..) 내에서 쓰는 무기는 같은 동작(알고리즘)을 수행하고, 능력치의 차이만 있잖아요. 이런 무기들을 prototype 패턴으로 생성하면 적절할까요?

# Singleton 패턴
## p.183 4. 인스턴스의 개수를 변경하기가 자유롭습니다.
Singleton 인스턴스가 여러개인 상황이 어떤 경우가 있을까요? 실 예제가 안떠올라요.. 그리고 인스턴스가 여러개일 경우에는 **Double Checked Locking** 을 어떻게 구현하면 좋을까요?

## p.188 예제코드 바로 윗 줄
```
또한 어쩌다 일어날 수 있는 사용자에 의한 객체 생성을 막기 위해, 생성자는 반드시 protected로 선언해야 합니다.
```
Java는 `protected`가  "**c++에서 의미하는 protected의 접근범위 + 같은 패키지 내에서 접근 가능**" 이잖아요. 제가 봐왔던 Java의 Singleton 예제들은 서브클래스도 없고 `private` 키워드를 썼던걸로 기억하는데, 서브클래스가 있는 Java Singleton 에서의 생성자에는 `private`키워드 대신에 `protected`를 쓰면 적절할까요? 서브클래스가 있는 Java 예제 코드랑 상황이 궁금합니다.. 

## Util 클래스 만들때 
Util 용으로 클래스 만들 때 Singleton으로 구현하든지, static class로 구현하든지 둘 다 상관없을까요? static으로 만드는 게 더 낫다고 생각은 하는데 궁금합니다.

**Comment by hyesun03** [comment]
안드로이드에서 흔히 쓰는 Adapter가 Adapter 패턴의 한 예제인줄 알았는데, 찾아보니 아니라는 스택오버플로 글을 발견했어요.

다른 블로그들을 보면 안드에서 쓰는 Adapter들이 Adapter패턴의 예시라고 설명이 되어있어서 헷갈리는데 안드에서는 왜 Adapter라는 이름을 가져다 쓸까요..?

아래 링크는 안드에서 Adapter패턴이 아닌 이유는 그저 데이터 가져오고 뷰에 뿌려주는 역할(mvp에서의 p)일뿐 gof 디패에서 말하는 adapter와는 의미가 다르다는 내용이예요.

https://stackoverflow.com/questions/41626980/are-android-adapters-an-example-of-adapter-design-pattern
