### ISSUE TITLE
[클린코드] 4주차 ~ 10장 클래스 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#90]
지난주에 리팩터링한 코드 집단지성으로 리팩터링하기

---
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 짧은 세미나 발표하기~

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by usageness** [comment]
### TDD 법칙 세 가지 ~ 깨끗한 테스트 코드 유지하기
- TDD는 결국 테스트 커버리지를 높게 가져간다는 전제 하에 효율적인게 아닐까?

  ⇒ 정말 모든 코드에 테스트가 있어야 할까?
  ⇒ 사이드 이펙트가 없는게 확실한 코드라면, 단위 테스트 이상으로는 필요하지 않아보인다.

### 변경하기 쉬운 클래스 / 변경으로부터 격리
- 원칙 : 이상적인 시스템은 확장을 하되, 기존 코드를 변경하지는 않는다. (변경에는 닫혀있고 확장에는 열려있는)
- 하지만 요구사항은 자주 변했고, 코드를 변경해야 할 일은 많이 생겨왔다.
- 지금껏 잦은 리팩토링으로 커버했지만, 애초에 각 기능을 작은 단위로 관리하고, 이를 관련된 개념으로 묶어 최대한 격리시킨다면 손쉽게 관리할 수 있지 않았을까.

  ⇒ 프로젝트 전체가 하나의 상태를 공유하는 경우에도 잘게 쪼개는 것이 위와 같은 의미가 있을까? (상태를 공유하는 각 개체들에게 사이드 이펙트를 미침)

**Comment by siathus** [comment]
# 단위 테스트
## TDD 법칙 세 가지
부끄럽게도 아직 TDD에 대해 알지 못하기 때문에 다 중요해보이긴 하는데 '구체적으로 어떻게?' 짜야하는지는 감이 잘 안오네요. TDD 관련 책이나 참고할만한 링크 공유해주시면 감사하겠습니다.
# 클래스
## 클래스는 작아야 한다!
> 클래스 이름이 모호하다는 것은 필경 클래스 책임이 너무 많아서이다.

2장 '의미 있는 이름'에서보다 오히려 이 파트에서 네이밍의 중요성이 더 와닿는 느낌이네요. 동시에 네이밍을 위한 영어 공부의 중압감도 커지는게..
### 응집도를 유지하면 작은 클래스 여럿이 나온다
- 큰 함수를 작은 함수 여럿으로 분리.
- 작은 함수가 사용하는 변수는 되도록 인자가 아닌 인스턴스 변수로 분리.
- 인스턴스 변수가 너무 늘어난다면 독자적인 클래스로 분리.

**Comment by joi0104** [comment]
157p

> 테스트 케이스가 있다면 공포는 사실상 사라진다. 테스트 커버리지가 높을수록 공포는 줄어든다.

한정된 자원으로 개발하는 조직에선 테스트 커버리지 100%를 채우는 것은 어려워 보인다. 결국 테스트 커버리지를 다 채우지 못하면, 어디부터 채워야 하는가 라는 생각으로 이어질 수 있을것 같다.

테스트 코드는 어디부터 어떤 케이스부터 작성되어야 할까?
ddd때 이야기 했던 것처럼 비지니스 로직부터? 결합도가 높은 곳 부터? 개발자가 불완전하다고 판단한 곳 부터? 작은 기능을 가진 테스트가 쉬운 곳 부터?

**Comment by duckbok** [comment]
### 09 단위 테스트
> 문제는 실제 코드가 진화하면 테스트 코드도 변해야 한다는 데 있다. (156p)
> 테스트 코드는 실제 코드 못지 않게 중요하다.

한 때 테스트 커버리지 기능을 처음 발견해서 높이려고 이것 저것 해본 적이 있었는데 책에 적힌데로 공포가 줄어들기는 했지만, 막무가내로 하다보니  실제 코드가 수정되면 변경해야할 테스트 코드가 너무 많아졌고 결국 버려지게 되는 결말을 봤었다.. 다음에는 책에 적힌대로 최대한 하나의 개념만 포함하고 간단하게 만들어서 도전해봐야겠다.

### 10 클래스
- (172p) Swift에는 `protected`가 없어서 하지 못하는 선택지인데.. 오히려 더 안전하게 갈 수 있어서 좋은 걸 지도 모르겠다.
- (177p) 몇몇 메서드만 사용하는 인스턴스 변수가 많아지면 분리의 신호라는 것은 잘 써먹을 수 있을 거 같은 내용이였다. 혹시 추가적으로 클래스를 분리해야겠다고 느끼는 순간이 있으신가요??

**Comment by genie-youn** [comment]
# 9. 단위테스트

167p FIRST 원칙

# 10. 클래스

176p. 책임, 즉 변경할 이유를 파악하려 애쓰다 보면 코드를 추상화하기도 쉬워진다.

178p. 응집도를 유지하면 작은 클래스 여럿이 나온다?

188p. 새 기능을 수정하거나 기존 기능을 변경할 때 건드릴 코드가 최소인 시스템 구조가 바람직하다.

190p. 본질적으로 DIP는 클래스가 상세한 구현이 아니라 추상화에 의존해야 한다는 원칙이다.

**Comment by wlsh44** [comment]
# 9 단위 테스트

161p 이중 표준

테스트를 위한 표준 API를 만드는 점에 대한 장점을 어느 정도 알게 된 것 같습니다.
그런데 이중 표준을 새로 만드는 과정에서 이 표준이 제대로 만들어 진다는 가정이 있어야 하지 않나 궁금합니다.

167p) F.I.R.S.T
Repeatable 부분에서 발생 확률, 외부 API애 의존된 코드를 테스트 하는 경우 등 환경이나 확률에 따라 결과가 달라질 수 있지 않나요?

그 외 테스트에 대해 궁금한 점

1. 테스트를 하고싶은 로직이 private 로 되었을 경우

- 접근 제어자 패키지 수준 또는 protected 후 mock 클래스 생성
    - 문제점: 테스트를 위해 실제 코드 변경, 캡슐화 깨짐
- ReflectionUtils
    - 문제점: string을 사용해야 하므로 추후 코드 변경이 어려움, 테스트 코드 가독성 떨어짐

이런 경우에는 상황에 따라 다를 수 있겠지만 설계 상의 문제인지 궁금합니다!

2. 테스트 케이스가 많을 경우 어떻게 하나요?

- parameterizedTest
    - 각 테스트 케이스가 어떤 경우인지 알기 힘듬
- test fixture
    - 새로운 라이브러리를 익혀야 함 → 협업에 힘듬

# 클래스

OCP
책에서도 많이 보고 에제도 많이 봤는데 막상 코드에 적용을 하려고 하면 잘 안되는 규칙인 것 같습니다.
조금 더 설계에 대한 경험이 많아지면 해결되는 부분일까요..?
