### ISSUE TITLE
[클린코드] 5주차 ~ 13장 동시성 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#91]
지난주에 리팩터링한 코드 집단지성으로 리팩터링하기

유비쿼터스 랭귀지와 DSL..

지훈
- 유비쿼터스는 사람이랑 얘기할때 쓰는거?
- DSL은 컴퓨터랑 얘기할때 쓰는거?

지수
- 유비쿼터스 랭귀지는 딕셔너리
- DSL은 API.. DSL이 유비쿼터스 랭귀지로 쓰여지지 않을까?

호준
- 유비쿼터스는 프로젝트 단위로 편하게 쓰는거고
- DSL은 업계 표준아닐까? 더 엄밀(정확) 해야 함.

진영
- DSL 은 업계 표준화된 API 다. DDD에서 화학 얘기는 DSL 이야기였다.
- DSL 은 잘 모르겠다
- 타입스크립트는 DSL 인가?

성국
- HTML 도 DSL 이다. 띠용
- HTML 도 프로그래밍 언어다

송열
- 대충 그냥 코드에서 도메인을 더 잘보기 위한 API 이다.
- https://www.wwdcnotes.com/notes/wwdc21/10253/

용래
- HTML은 DSL이 아니다
- CSS는 DSL 이다

주변에 다른 개발자 만나면 한번 물어보고 오기~

AOP는 토비에 설명이 잘 되어 있다.

---
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
# 11장 시스템

> 복잡성은 죽음이다. 개발자들에게서 생기를 앗아가며, 제품을 계획하고 제작하고 테스트하기 어렵게 만든다.

## Main 분리

> 시스템 생성과 시스템 사용을 분리하는 한 가지 방법으로, 생성과 관련한 코드는 모두 main 이나 main이 호출하는 모듈로 옮기고, 나머지 시스템은 모든 객체가 생성되었고 모든 의존성이 연결되었다고 가정한다.

`Provider` 를 사용할 때 각 컴포넌트는 해당 Context 가 생성되어 있다고 가정하고 사용하는 부분이 왠지 모르게 찝찝하게 느껴졌는데, 이 단락이 마음의 짐을 덜어주었다.

### 의존성 주입

> 사용과 제작을 분리하는 강력한 메커니즘 하나가 의존성 주입이다. 의존성 주입은 제어 역전 기법을 의존성 관리에 적용한 매커니즘이다.

명확하게 정의를 정리해주어서 가져왔다.

> '처음부터 올바르게' 시스템을 만들 수 있다는 믿음은 미신이다. 대신에 우리는 오늘 주어진 사용자 스토리에 맞춰 시스템을 구현해야 한다. 내일은 새로운 스토리에 맞춰 시스템을 조정하고 확장하면 된다. 이것이 반본적이고 점진적인 애자일 방식의 핵심이다. 테스트 주도 개발, 리팩터링, 깨끗한 코드는 코드 수준에서 시스템을 조정하고 확장하기 쉽게 만든다.

내가 만드는 제품은..

리액트나 뷰와 같은 모던한 프론트엔드 프레임워크들의 반응성 시스템도 AOP 라고 할 수 있을까?

AOP는 매번 봐도 잘 모르겠다.

## 테스트 주도 시스템 아키텍처 구축

> 애플리케이션 도메인 논리를 POJO로 작성할 수 있다면, 즉 코드 수준에서 아키텍처 관심사를 분리할 수 있다면, 진정한 테스트 주도 아키텍처 구축이 가능해진다. (210p) 

이거다! 내가 했던 일, 내가 찾던 방법!

> 최선의 시스템 구조는 각기 POJO 객체로 구현되는 모듈화된 관심사 영역(도메인)으로 구성된다. 이렇게 서로 다른 영역은 해당 영역 코드에 최소한의 영향을 미치는 관점이나 유사한 도구를 사용해 통합한다. 이런 구조 역시 코드와 마찬가지로 테스트 주도 기법을 적용할 수 있다.

## 결론

처음 읽었을땐 전체가 뭔소리인가 했는데, 이번에 읽을 때는 절반정도는 이해와 공감이 가능했다.

내가 Vue 애플리케이션에서 도메인 계층을 순수 js 로 분리해내 작성했던 이유가 여기 다 적혀있는걸 보고 괜히 뿌듯해졌다.

DSL은 뭔지 알것같기도 하고 모르는것 같기도하고 여전히 알쏭달쏭한 영역이다. 유비쿼터스 랭귀지랑은 무엇이 다른거지. 유비쿼터스 랭귀지는 딕셔너리고 DSL은 API 수준인건가?

**Comment by siathus** [comment]
# 시스템
> "우리는 때때로 가능한 마지막 순간까지 결정을 미루는 방법이 최선이라는 사실을 까먹곤 한다. 게으르거나 무책임해서가 아닌, 최대한 정보를 모아 최선의 결정을 내리기 위해서다."

> "EJB2는 단지 표준이라는 이유만으로 많은 팀이 사용했다. 가볍고 간단한 설계로 충분했을 프로젝트에서도 EJB2를 채택했다. 아주 과장되게 포장된 표준에 집착하는 바람에 고객 가치를 뒷전으로 미루면 안 된다."

너무 당연하지만 여태껏 잊고 있었던 사실. 특히, 표준에 대한 부분에서 온리 스프링만 생각하는 나 자신에 대해 더욱 반성.

> "좋은 DSL은 도메인 개념과, 그 개념을 구현한 코드 사이에 존재하는 '의사소통 간극'을 줄여준다. 도메인 전문가가 사용하는 언어로 도메인 논리를 구현하면 도메인을 잘못 구현할 가능성이 줄어든다."

살짝 검색해보니 DSL이란 언어가 따로 있는 건 아닌 것 같은데 그렇다면 도메인 전문가가 사용하는 언어로 도메인 논리를 구현한다는 것은 현실적으로 해당 팀에서 사용하는 언어와 도메인 전문가가 사용하는 언어가 일치해야만 가능한 부분일지?
# 창발성
> 테스트 케이스가 많을수록 개발자는 테스트가 쉽게 코드를 작성한다. (p. 217)

몇 번을 봐도 대체 무슨 문장인지 모르겠음... 그냥 오타인가? "개발자는 테스트하기 쉽게 코드를 작성한다."인가? 아니면 "개발자가 쉽게 코드를 작성한다."일까? 뭐든 간에 말하고자 하는 바는 알겠지만...

> 테스트 케이스는 '예제로 보여주는 문서'다.

> 하지만 표현력을 높이는 가장 중요한 방법은 노력이다. 흔히 코드만 돌린 후 다음 문제로 직행하는 사례가 너무도 흔하다. 나중에 읽을 사람을 고려해 조금이라도 읽기 쉽게 만들려는 충분한 고민은 거의 찾기 어렵다. 하지만 나중에 코드를 읽을 사람은 바로 자신일 가능성이 높다는 사실을 명심하자.

"하지만 나중에 코드를 읽을 사람은 바로 자신일 가능성이 높다는 사실을 명심하자." 또한, '현재 코드를 짜는 나'와 '나중에 코드를 읽는 나'는 완전히 다른 사람이라는 사실도 명심해야 할 것이다.

**Comment by KangJiJi** [comment]
# 11장

195) 관심사의 분리는 우리 분야에서 가장 오래되고 가장 중요한 설계 기법 중 하나다.

199) 처음부터 올바르게 시스템을 만들 수 있다는 믿음은 미신이다.

# 12장

222) 클래스와 메서드 수를 최소로 줄여라

# 13장

231) 공유 자료를 줄이려면 처음부터 공유하지 않는 방법이 제일 좋다.

# 결론

좋아보이는 이야기를 모아봤습니다.

**Comment by duckbok** [comment]
> 시스템 제작과 시스템 사용을 분리하라 (195~196p)

예로 초기화 지연을 들고있는데, “테스트도 문제다.”로 시작하는 문단에서 설명하는 것들이 적어놓은 데로 단위테스트를 진행하면 되는 게 아닐까 싶은 생각이 들었고, 그럼 초기화 지연 기법은 자주 쓰기엔 나쁜 기법인지 궁금하다. 인스터스를 만들 때 아직 쓰이지 않은 프로퍼티에 대해서는 지연 변수로 두는 방식을 자주 사용했고, 이 방식의 단점은 초기화 시점을 파악하는 것이 어렵다.. 정도로 생각하고 있었는데 이는 자주 쓰면 나쁜 방식이였던 걸까?

> ‘처음부터 올바르게’ 시스템을 만들 수 있다는 믿음은 미신이다. 대신에 우리는 오늘 주어진 사용자 스토리에 맞춰 시스템을 구현하고, 내일은 새로운 스토리에 맞춰 시스템을 조정하고 확장하면 된다. (199p)

맞는 말이다.

> EJB2 아키텍처 (200~202p)

관심사를 적절히 분리하지 못하는 아키텍처의 예시로 나온다… 근데 한참을 봐도 이게 뭔지도 잘 이해가 안돼서 202p에서 얘기하는 비즈니스 로직이 컨테이너에 강하게 결합되는 이유도 모르겠고, 빈은 다른 빈을 상속 받지 못하는 이유도 잘 모르겠다.. 동일한 정보를 저장하는 자료 유형은 왜 또 두개인지..! 그냥 그렇구나하고 넘어가면 되는걸까ㅠ

그리고 208p에서 EJB3 코드를 보면 잘 읽혀지는데 이게 AOP인건가..

> 횡단 관심사 (202~203p)

![image](https://user-images.githubusercontent.com/63839917/192140113-767d1f68-9a61-4564-af3c-986adb9187c2.png)

요런 느낌인걸까? 관점이란 게 어느 특정 상황에 따라 동작하는 방식이 일정하게 바뀌는 것? 이 맞을 지 모르겠다. 210p에 관점으로 관심사를 분리하는 방식이 막강한 위력을 가진다는데.. 잘 모르겠다ㅠ

> 자바 프록시 (203~205p)

복잡하고, 설계 변경 시에 고칠 부분이 String 값으로 박혀있어서 굉장히 난잡할 거 같은데.. 이런 방식을 가끔 쓰는건가?

> 테스트 주도 시스템 아키텍처 구축 (210p)

애플리케이션 도메인 논리를 POJO(Plain Old Java Object, 코드 수준에서 아키텍처 관심사 분리)로 작성!

> “가장 적합한 친구에게 책임을 맡기면 가장 좋다. 가능한 마지막 순간까지 결정을 미루는 방법이 최선이다.” (211p)

역시 좋은 말이다.

**Comment by usageness** [comment]
### 시스템 제작과 시스템 사용을 분리하라 p.194

> 소프트웨어 시스템은 준비 과정과 런타임 로직을 분리해야 한다.

런타임 로직에 준비 과정의 흔적들이 곳곳에 남아있는 것을 보며 뒷정리(?)를 깨끗하게 해줘야겠다는 생각이 듭니다.

<br/> 
### 명백한 가치가 있을 때 표준을 현명하게 사용하라 p.211~212

> EJB2는 단지 표준이라는 이유만으로 많은 팀이 사용했다. 가볍고 간단한 설계로 충분했을 프로젝트에서도 EJB2를 많이 채택했다.

<br/> 

실제로 많은 프로젝트에서 규모에 어울리지 않는 기술스택을 사용하는 경우를 많이 보았습니다. 대부분은 “프로젝트의 규모가 커진다” 라고 하는 아직 오지 않은 상황에 대비하여 정말 큰 규모로 발전할 확률이 높은지 생각해보지 않고 채택한 경우라면, 낭비라고 생각합니다.

또한 이런 표준에 집착하여 정작 중요하게 고려되어야 할 고객 가치는 충분히 고려되지 않고 있다는 사실이 가슴에 와닿았는데, 현재 제 프로젝트가 그렇습니다. 이제서야 내부 QA를 진행하고 있는데 상상도 못했던 불편들과 온갖 버그들이 쏟아져 나와서 어지러운 상황이네요 ㅎㅎ…

오늘은 유독 여러가지로 책에게 팩트 폭행 당한 기분입니다….

### 단순한 설계 규칙 1 : 모든 테스트를 실행하라 p.216

버그들이 쏟아져 나오면서 테스트의 중요성을 실감하고 있는 요즘입니다. 다만 복잡성이 늘어나며 프론트 영역의 테스트만으로는 잡아낼 수 없는 버그들이 너무 많아져서… 라이브러리도 완전히 신뢰할 수가 없고… 아쉽습니다.

**Comment by wlsh44** [comment]
# 시스템

### 자바 프록시

206p 프레임워크는 사용자가 모르게 프록시나 바이트코드 라이브러리를 사용해 이를 구현한다.

예전에 스프링의 `@Transaction`이 어떤 방식으로 작동되는지 알고싶어서 공부를 하다가 프록시 패턴에 대해 알게 되었습니다.
처음에 프록시 패턴을 봤을 때 굉장히 신기해서 왜 스프링이 객체 지향적으로 잘 짜여진 프레임워크인지 조금이나마 느꼈던 것 같습니다.

### 의사 결정을 최적화하라

211p 도시든 소프트웨어 프로젝트든, 아주 큰 시스템에서는 한 사람이 모든 결정을 내리기 어렵다.

책에서는 '**관심사가 잘 분리된 프로젝트라면** 해당 관심사에 가장 적합한 사람이 책임을 맡아야 하고, 그러기 쉽다' 라는 의도로 적은 것 같습니다만, 저같은 경우는 프로젝트를 할 때마다 항상 혼자 진행하거나 하고자 하는 의지가 없는 사람들과만 해서 이 글을 읽고 조금 슬펐네요... 😂

### 명백한 가치가 있을 때 표준을 현명하게 사용하라

저같은 경우는 특히 DB를 정할 때 Mysql밖에 사용을 안해봐서 무조건 Mysql만 사용했는데, 이 부분을 읽고 다른 DB나 Nosql도 공부를 해서 DB를 정해야겠다고 반성하며 지나갑니다..

# 창발성

앞선 장들에서 나왔던 부분들의 총 정리 정도로 느껴집니다..!

# 동시성

아직까지 동시성 관련된 코드를 작성해본 적이 거의 없어 그렇구나 정도로 넘어가는 부분이 많았습니다..

### 자료 범위를 제한하라

이 부분을 보면서 Transaction 범위에 대한 고민을 했던 기억이 났습니다.

여러 개의 데이터를 삭제, 수정 등을 할 때 Transaction의 범위를 전체로 할 지, 개별로 할 지 궁금했습니다.

상황에 맞게 적용을 해야 한다고 생각하지만 아직 사용자가 있는 서비스를 만든 적도 없고, 대규모 트래픽은 더더욱 겪은 적이 없어 어떤 상황에 어떤 방법을 선택해야 되는지도 잘 모르겠고, 고민을 한다 해도 답이 안 나와서 머리만 아팠습니다..

혹시 이 부분에 대해 간단하게나마 공부할 키워드나 책이 있을까요?
아니면 아직 db에 대한 지식도 부족한데 공부하기에는 시기상조일까요...

# 느낀점

책이 점점 어려워지고 이런 내용까지 다뤄? 하는 부분도 있지만 재미있게 읽고 있습니다..!
공부를 열심히 해야겠네요..😭

**Comment by hjsung809** [comment]
11장
194p 복잡성은 죽음이다. 개발자에게서 생기를 앗아가며...~
- 생기를 이미 다 잃은것 같습니다. 레거시 코드가 C언어로 되는대로 짠 코드같아서 고치기도 어려워서 현타를 느끼고 있습니다. 이직만이 답일까요?

p194 -
스프링이 자연스럽게 해결해주는 것들이 주를 이루는 장이었습니다. 물론 개발자가 주의 해야겠지만요..

13장
p226. 자바 벡엔드에서는 직접 lock을 거는 경우도 별로 없고, 이미 thread에 안전한 자료구조도 많이 제공되고 굳이 톰캣쓰레드 외의 쓰레드를 돌릴 때에는 잘알려진 방식이나 라이브러리를 통해 돌리면 되기 때문에 여기 나온 내용을 실제로 적용할만한 일은 별로 없을것 같습니다

**Comment by joi0104** [comment]
## 11장
205p. 순수 자바 AOP 프레임워크

비지니스 로직을 담당하는 객체를 POJO로 관리하여 스프링의 의존성을 제거하고, 어노테이션을 이용해서 영속성, 보안과 같은 동작들은 선언적으로 작성하고 관심사가 분리되도록 작성하는 부분이 인상깊었다.

데코레이터 패턴을 러시아 인형이라고 표현한 것도 재밌었다 ㅋㅋ

## 12장
217p 중복을 없애라

제목에 오해의 소지가 있는게 아닌가 싶다. 이전에도 이야기가 나왔지만 변경의 원인이 다른, 책임이 다른 코드의 경우에 우발적으로 중복이 발생할 수 있는데 무조건 중복이 안좋아! 라고 전달하는거 조금 아쉬웠다

## 13장
평소 개발할 떄 크게 고려한 부분이 아니여서 그런지 조금 추상적으로 다가왔던 부분같다.
