### ISSUE TITLE
[클린코드] 6주차 ~ 14장 점진적인 개선

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#92]
연휴니까 한주 쉬고 10월 9일에 보는걸로.

지난주에 리팩터링한 코드 집단지성으로 리팩터링하기

유비쿼터스 랭귀지와 DSL..

지훈
- 유비쿼터스는 사람이랑 얘기할때 쓰는거?
- DSL은 컴퓨터랑 얘기할때 쓰는거?

지수
- 유비쿼터스 랭귀지는 딕셔너리
- DSL은 API.. DSL이 유비쿼터스 랭귀지로 쓰여지지 않을까?

호준
- 유비쿼터스는 프로젝트 단위로 편하게 쓰는거고
- DSL은 업계 표준아닐까? 더 엄밀(정확) 해야 함.

진영
- DSL 은 업계 표준화된 API 다. DDD에서 화학 얘기는 DSL 이야기였다.
- DSL 은 잘 모르겠다
- 타입스크립트는 DSL 인가?

성국
- HTML 도 DSL 이다. 띠용
- HTML 도 프로그래밍 언어다

송열
- 대충 그냥 코드에서 도메인을 더 잘보기 위한 API 이다.
- https://www.wwdcnotes.com/notes/wwdc21/10253/

용래
- HTML은 DSL이 아니다
- CSS는 DSL 이다

주변에 다른 개발자 만나면 한번 물어보고 오기~

AOP는 토비에 설명이 잘 되어 있다.

---
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by joi0104** [comment]
## 14장 점진적인 개선

전반적으로 리팩토링하는 과정을 잘 설명해주는 부분이 좋았지만 자바 문법이다보니 이해에 한계가 있었던 것 같습니당 🥲

>  286p 내가 인수 테스트 케이스를 FitNess에서 구현했기 때문이다. 그런데 FitNess 테스트는 boolean이 아닌 인수로 getBoolean을 호출하면 무조건 false를 반환했다. (단위 테스트는 그러지 않았다.)

무슨 소리인지 이해를 못했습니다..

> 310p ArgsException의 getErrorArgumentId

getErrorArgumentId 메서드의 경우 실제로 서비스 코드에서는 사용하지 않고 테스트 코드에서 사용된다. 테스트 코드 때문에 캡슐화가 깨진 케이스라고 생각하는데.. 좋은 방법이 없을지?

**Comment by KangJiJi** [comment]
# 14장

254) 깨끗한 코드를 짜려면 먼저 지저분한 코드를 짠 뒤에 정리해야한다.

> 맨날 정리는 안하는 제 모습을 다시한번 반성합니다.

**Comment by wlsh44** [comment]
## 14장 점진적인 개선

책에 있는 코드를 따라 해보면서 느낀 점은 '왜 내가 하는 리팩토링과 느낌이 다를까?' 였습니다.

제가 리팩토링을 할 때는 항상 테스트 코드가 깨져서 테스트 코드를 처음부터 다시 작성하는 경우가 많았습니다.
특히 설계가 잘못 된 경우가 많아 새로운 설계에 맞춰 코드를 수정하다보니, 테스트를 위해 `mocking` 해놓은 객체의 리턴 결과가 달라지는 등 툭 하면 테스트 케이스가 깨져서 힘들었던 것 같습니다.

그래서 어떻게 이 책에서는 테스트를 깨뜨리지 않고 리팩토링을 잘 진행하는지 생각을 해봤습니다.

우선, 책의 코드는 맨 처음에 하나의 클래스에서 모두 진행하기 때문에 `Args` 에 대한 통합 테스트밖에 존재하지 않았던 점이 컸던 것 같습니다.

그렇기에 의존성이 존재하지 않았고, 책에서 생략을 했는지는 모르겠지만 중간에 `Marshaler` 를 만들 때 그에 대한 단위 테스트를 진행하지 않아 `Marshaler` 를 수정할 때마다 그에 대한 테스트 케이스를 수정하지 않아도 되었습니다.

약간의 불평이 된 것 같긴 한데 결론을 내면 다른 분들은 리팩토링을 할 때 어떻게 진행을 하시는지, 혹은 테스트 코드가 걸림돌이 되지 않았는지 등의 경험이 궁금합니다!
