### ISSUE TITLE
[클린코드] 7주차 ~ 16장 SerialDate 리팩터링 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#93]
지난주에 리팩터링한 코드 집단지성으로 리팩터링하기

유비쿼터스 랭귀지와 DSL..

지훈
- 유비쿼터스는 사람이랑 얘기할때 쓰는거?
- DSL은 컴퓨터랑 얘기할때 쓰는거?

지수
- 유비쿼터스 랭귀지는 딕셔너리
- DSL은 API.. DSL이 유비쿼터스 랭귀지로 쓰여지지 않을까?

호준
- 유비쿼터스는 프로젝트 단위로 편하게 쓰는거고
- DSL은 업계 표준아닐까? 더 엄밀(정확) 해야 함.

진영
- DSL 은 업계 표준화된 API 다. DDD에서 화학 얘기는 DSL 이야기였다.
- DSL 은 잘 모르겠다
- 타입스크립트는 DSL 인가?

성국
- HTML 도 DSL 이다. 띠용
- HTML 도 프로그래밍 언어다

송열
- 대충 그냥 코드에서 도메인을 더 잘보기 위한 API 이다.
- https://www.wwdcnotes.com/notes/wwdc21/10253/

용래
- HTML은 DSL이 아니다
- CSS는 DSL 이다

주변에 다른 개발자 만나면 한번 물어보고 오기~

AOP는 토비에 설명이 잘 되어 있다.

---
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by duckbok** [comment]
### 15장 JUnit 들여다보기

장 이름부터가 JUnit 이여서 으엑 하면서 읽기 시작해서 처음에 코드가 딱 주어졌을 때 이해하려고 했지만 되지 않았다. 읽다보니까 그냥 정리가 되지 않아서 그런거구나 싶었고 어떤 언어로 작성한 코드던지 간에 클린 코드를 적용한다면 이해하기 쉬워진다는 생각이 들었다.
    
- 숨겨진 시간적인 결합 (334p)
 
  분명히 다른 기능을 하는 메서드이지만 내부적으로 순서대로 실행해야하는 경우이다. 나도 이런 적을 몇 번 경험한 적이 있어서 주의 깊게 읽어보았다. 처음으로 시도한 인수로 순서를 지정하는 방식은 책에서도 말하지만 정말 별로인거 같고.. 제안한 방식은 의존적인 메서드가 내부에서 앞의 메서드를 호출해서 사용하고 이름도 `findCommonPrefixAndSuffix()`와 같이 묶어주는 방식이다.

   의문이 드는 부분은 Swift API GuideLine도 그렇지만 하나의 메서드는 하나의 기능을 하는 것이 정상인데 이런 경우는 특례로 봐도 괜찮은걸까?
    
- 적절한 이름으로 변경: `index`와 `length` (336p)
    
    이해는 되지만 배열에서 `0 ~ (n-1)`로 진행될 때는 당연히 `index`라는 변수명을 사용하는데, `1 ~ n`같이 진행되는 경우에 `length`라는 변수명을 쓰면 어색한 건 내가 이상한 것일까?

> 코드를 리팩터링 하다 보면 원래 했던 변경을 되돌리는 경우가 흔하다. 리팩터링은 코드가 어느 수준에 이를 때까지 수많은 시행착오를 반복하는 작업이기 때문이다. (341p)

  👍

### 16장 SerialDate 리팩터링

> `java.util.Date`를 쓰지 않은 이유? (시간 기반 날짜 클래스 vs 순수 날짜 클래스) (449p)

너무 정밀하게 1/1000초로 시각을 표현해서 시간대에 따라 날짜가 달라지기 때문에 단순하게 특정 날짜만 표현하기 위해서 재정의함.

- 개인적인 의문점: 날짜를 기록할 때 시간대에 유동적으로 활용하기 위해서 Unix Timestamp로 저장하곤 했는데, mysql과 같은 데이터베이스는 이게 64bit로 구성되어 있지 않아서 문제가 발생하는 거로 알고 있다. 이런 경우에 이점을 포기하고 Datetime을 쓰는 지, Int형 필드로 대체해서 사용하는 지 궁금해졌다.

**(2) 고쳐보자.**

추상 메서드와 파생 메서드를 왔다갔다하면서 봐야해서 너무 지치는 부분이였다..

- `serialVersionUID`변수를 제거하여 컴파일러가 자동으로 생성하게 한다. (350p)
    
    깜빡하고 이를 변경하지 않아 생기는 괴상한 오류를 디버깅하기보단 `InvalidClassException`을 디버깅하는 편이 더 안전하고 낫다는 이유라는데.. 이 ID를 변경할 일이 언제 있는지, 이전 버전의 클래스를 복원하지 않아도 별 상관없는 건지 궁금하다.

- 메서드 인수로 플래그, 출력 형식을 선택하는 플래그 피하기 (358p)

   뭔지 대충은 알겠는데.. 플래그가 정확히 어떤 의미일까?

> 테스트하지 않는 코드는 너무 사소해 테스트할 필요도 없다. (366p)

테스트를 할 때, 커버리지에 눈이 돌아가서 막 사소한 거도 귀찮아하면서 테스트 코드를 만들고는 했었는데.. 그렇구나.

**Comment by wlsh44** [comment]
# Junit 들여다보기

> `findCommonSuffix`를 주의깊게 살펴보면 숨겨진 시간적인 결합이 존재한다.
...
`findCommonSuffix`라는 이름을 `findCommonPrefixAndSuffix`로 바꾸고, 가장 먼저 `findCommonPrefix`를 호출한다.(334~335p)

`findCommonPrefixAndSuffix` 함수를 살펴보면 `findCommonPrefix` 함수를 실행하고 아래에서 `suffix`를 구하는데 추상화 레벨이 깨진 코드라고 생각이 되었습니다.
차라리 맨 처음에 있었던 `findCommonPrefix`와 `findCommonSuffix`로 나누어져있는게 추상화 수준을 맞추는데 더 적합하지 않았나 라는 생각을 했습니다.
하지만 이렇게 하면 결국에는 맨 처음 문제처럼 시간적인 결합때문에 개발 과정에서 실수가 나오게 될텐데 혹시 조금 더 나은 방법이 있을지 궁금합니다!

# SerialDate 리팩터링

> 불행하게도 이미 자바 라이브러리에는 Date라는 클래스가 너무 많다.(348p)

저자는 대안으로 DayDate라는 이름을 사용하는데, 만약 처음으로 이 이름을 보는 사람이라면 역시나 한 번쯤 이름에 궁금증을 갖지 않을까 생각이 됩니다. 
혹시 이런 경우처럼 이미 사용되고 있는 이름이 있는 경우에(자바의 경우 User, Member 등) 그냥 이름을 사용하시는지, 아니면 책처럼 다른 대안을 찾으시는지 궁금합니다!

> 이전 버전에서 직렬화한 클래스를 복원하려 시도하면 `InvalidCalssException`이 발생한다. (350p)

이부분에 대한 개념이 부족해서 이해가 잘 되지 않았는데, 이전 버전에서 직렬화한 클래스를 복원해야 할 일이 언제 있나요..? 🤔

****

코드가 뒤에 있어서 읽기 너무 힘들었습니다..

**Comment by usageness** [comment]
## 15. JUnit 들여다보기

> 시작은 켄트백과 에릭 감마 ... 두 사람이 함께 아틀란타 행 비행기를 타고 가다 JUnit을 만들었다.

알고 있었지만 다시 들어도 놀라운 사람들...
