### ISSUE TITLE
[클린코드] 8주차 ~ 끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#94]
지난주에 리팩터링한 코드 집단지성으로 리팩터링하기

유비쿼터스 랭귀지와 DSL..

지훈
- 유비쿼터스는 사람이랑 얘기할때 쓰는거?
- DSL은 컴퓨터랑 얘기할때 쓰는거?

지수
- 유비쿼터스 랭귀지는 딕셔너리
- DSL은 API.. DSL이 유비쿼터스 랭귀지로 쓰여지지 않을까?

호준
- 유비쿼터스는 프로젝트 단위로 편하게 쓰는거고
- DSL은 업계 표준아닐까? 더 엄밀(정확) 해야 함.

진영
- DSL 은 업계 표준화된 API 다. DDD에서 화학 얘기는 DSL 이야기였다.
- DSL 은 잘 모르겠다
- 타입스크립트는 DSL 인가?

성국
- HTML 도 DSL 이다. 띠용
- HTML 도 프로그래밍 언어다

송열
- 대충 그냥 코드에서 도메인을 더 잘보기 위한 API 이다.
- https://www.wwdcnotes.com/notes/wwdc21/10253/

용래
- HTML은 DSL이 아니다
- CSS는 DSL 이다

주변에 다른 개발자 만나면 한번 물어보고 오기~

AOP는 토비에 설명이 잘 되어 있다.

---
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

---

# 앞으로 오프모임은?

- 책이 끝났을 때 모여서, 책걸이. 스터디 영업의 장
- 일단은 동아리에서 모집을 해서.. 추후 1 지인을 하든..
- 모여서 할일
- 할일
    - 회고 (1명이 이 책을 간단하게 요약하고 무엇을 배웠는지..)
    - 간단한 세미나. (발표자를 지원받아서)
    - **스터디때 다음에 봅시다 하고 넘어간 이슈 토론하기**
    - 음식, 술 **+ 회사생활, 커리어 고민 나누기**
- 책걸이에서 물어볼거
    - 현재 스터디의 속도는 적정한가?
    - 현재 스터디 방식의 보완할 점은 없을까?

**Comment by genie-youn** [comment]
### 일반
꿀챕터..

g2: 당연한 동작을 구현하지 않는다. (371p)
- 당연하지만 **당연한** 이란 단어가 너무 어려운 영역인것 같다. 당장 필요하지 않은 기능이지만 당연한 동작일 경우 어떻게 해야 할까?
- 애자일에서 이야기하는 실제로 문제가 됐을 때 해결한다. 추측에 의해 개발하지 않는다 등등 이에 정면으로 반하는 부분 아닌가?
- 그치만 예측 가능한 인터페이스와 동작 또한 중요하다.
- 추상화에 적절한 시점은? 실제로 중복이 생겼을때냐 중복이 예상될 때냐.. 여전히 너무 어렵다.

g3: 경계를 올바로 처리하지 않는다.
- 부지런함을 대신할 지름길은 없다. 모든 경계 조건, 모든 구석진 곳, 모든 기벽, 모든 예외는 우아하고 직관적인 알고리즘을 좌초시킬 암초다. 스스로의 직관에 의존하지 마라. 모든 경계 조건을 찾아내곡, 모든 경계 조건을 테스트하는 테스트 케이스를 작성하라.

g5: 중복
- 코드에서 중복을 발견할 때마다 추상화의 기회로 간주해라. 중복된 코드를 하위루틴이나 다른 클래스로 분리하라. 이렇든 추상화로 중복을 정리하면 설계 언어의 어휘가 늘어난다. 다른 프로그래머들이 그만큼 어휘를 사용하기 쉬워진다.

g21: 알고리즘을 이해해라 (383p)
- 대다수 괴상한 코드는 사람들이 알고리즘을 충분히 이해하지 않은 채 코드를 구현한 탓이다. 잠시 멈추고 실제 알고리즘을 고민하는 대신 여기저기 if 문과 플래그를 넣어보며 코드를 돌리는 탓이다.

g25: 매직 숫자는 명명된 상수로 교체하라. (387p)
- FEET_PER_MILE은 5280이 너무나도 잘 알려진 고유한 숫자라... 이기적이네 이친구들

g34: 함수는 추상화 수준을 한 단계만 내려가야 한다. (392p)
- 저자도 이야기 했지만, 너무 어려운 일이다.

**Comment by joi0104** [comment]
17장


앞장에서도 언급한 내용들을 쭉 다시 정리해주고, 좋은 이야기들이 많아서 읽기 너무 좋았습니당. 다른장 안읽고 이번장만 읽어도 괜찮다고 생각할만큼 알차네요 ㅋㅋ



>371p F3 플래그 인수
>boolean 인수는 함수가 여러 기능을 수행한다는 증거다. 플래그 인수는 혼란을 초래하느모 피해야 마땅하다.

그렇다고 플래그를 바깥에 받으면 이를 사용하는 함수쪽에서 전부 분기를 쳐줘야 할텐데...? 서비스 전반에서 모두 적용되어야 하는 규칙이라면 그냥 플래그 함수를 받는게 좋지 않을까?  오히려 플래그에 따른 동작을 함수 내부로 캡슐화 해놓으면 좋지 않을까?

좋은 예시는 아닌데 마땅히 딱 떠오르는 예시가 없다..

```typescript

function moveToRepresentativePage(isMobile: boolean) {

  return Router.push(isMobile ? ' /m/representative': '/representative')

}
```



> 371p G2 당연한 동작을 구현하지 않는다
> 최소 놀람의 원칙. 다른 프로그래머가 당연하게 여길 만한 동작과 기능을 제공해야 한다.

개발하면서 가장 어렵다고 생각하는 부분. 당연하게 여길 만한 동작, 일반적인 인터페이스 -> 주관적인 시각이 섞여있는 부분이라 예측하기가 너무 어렵다. 내가 개발할 때는 일반적이고 예측가능하다고 생각해도 막상 리뷰 받고보면 아차 싶을때가 많다. 요건 훈련의 영역인가?

> 372p G3 경게를 올바로 처리하지 않는다
> 모든 경계 조건을 찾아내고, 모든 경계 조건을 테스트하는 테스트 케이스를 작성하라

경계조건.. 뭔가 이번에 읽으면서 이 단어가 추상적이게 느껴졌다. 책에서 말한 경계조건이란 무엇일까? 해당 함수를 통해 전파되는 에러를 경계지을 수 있는 바운더리..? 


> 388p G27. 관례보다 구조를 사용하라
> 설계 결정을 강제할 때는 관례보다는 구조 자체로 강제하면 더 좋다. switch/case 문 보다 추상매서드가 있는 기초 클래스가 더 좋다.

switch/case가 비용이 적게 들다보니 굳이..? 라고 생각하면서  기초클래스/파생클래스로 만들기보다는 switch/case로 구현한 경우가 많았다. 내가 생각했던 굳이..? 가 굳이가 아니라는 걸 말해주는 부분이여서 좋았다.

**Comment by hjsung809** [comment]
최소 놀람 법칙 -> 헛짓거리 금지 법칙

p 374
잘못된 추상화 수준은 거짓말이나 꼼수로 해결하지 못한다

p378 기능 욕심.
어쩔수 없는경우.->(관심사에 따라야 하는경우)

p379 선택자 인수
메소드 동작을 제어하려는 인수를 두기보다는 메서드를 각각 만들자.

p382 
서술적인 변수 이름을 사용하라

p383 알고리즘을 이해하라
구현이 끝났다고 하기전에 알고리즘이 올바르다는 사실을 알아야한다.
기능이 뻔히 보일정도러 함수를 깔끔하고 명확하게 재구성하라


논리적 의존성은 물리적으로 드러내라

p385
if, swith전에 다형성을 고려하라
유형보다 함수가 더 쉽게 변하는 경우는 드물다?


p386
매직 숙자는 명명된 상수로 교체하라

p391
의도적으로 추가한 구문적인 복잡성이 원래있던 시간적인 복잡성을 드러낸 셈이다.


p392
경계 조건을 캡슐화 하라
변수를 할당하는것도 추상화로 볼수 있는가!


p395 디미터의 법칙
자신이 직접사용하는 모듈만 알아야한다

p 403
길다는 단점을 서술성이 충분히 메꾼다

**Comment by KangJiJi** [comment]
지금까지의 책 내용을 한번에 정리해주는 챕터같았다. 정말 좋은 내용이긴한데, 막상 하려고하면 안됨...

p376 죽은 코드

요즘 Go를 배우는데 이 언어는 선언해놓고 사용하지 않는 변수나 함수가 있으면, 빌드가 안됨

**Comment by usageness** [comment]
### 휴리스틱 : 대충 어림 짐작하기

- 정보나 시간이 많지 않을때 간편하게 추론하는 방법
- 코드 레벨의 휴리스틱을 찾자

### **C5: 주석 처리된 코드**

```tsx
export const parseDocument = (id: number, rawString: string) => {
  /** [parsing 예시]
    * <hr>
    * <p>title: 파일의 제목입니다
    * subTitle: 파일의 소제목입니다
    * date: 2022-09-14</p>
    * <hr>
    */

  const documentData = rawString.split('<hr>');
  const splitByTitle = documentData[1].split('title: ');
  const splitBySubTitle = splitByTitle[1].split('subTitle: ');
  const splitByDate = splitBySubTitle[1].split('date: ');
  const splitByPtag = splitByDate[1].split('</p>');

  return {
    id,
    title: splitBySubTitle[0],
    subTitle: splitByDate[0],
    date: splitByPtag[0],
    content: documentData[2],
  };
};
```

이런 주석은 어떨까? 지워야할까? 말아야할까? 고쳐야할까?

### **G1: 한 소스 파일에 여러 언어를 사용한다**

`Javadoc`처럼 정보를 전달해주는 목적인 코드도 언어로 보다니 흥미로운 관점이네요.

이렇게 보면 흔히 만드는 컴포넌트 하나에도 여러 언어가 짬뽕이 되어있는것 같습니다.

```tsx
function WholeGroups({ isFetching, data, refetch, groups }: WholeGroupsProps) {
  const target = useRef<HTMLDivElement>(null);

  useInfiniteScroll({ target, isFetching, data, refetch, groups });

  useEffect(() => {
    queryClient.invalidateQueries(QUERY_KEY.GROUP_DETAILS);
    queryClient.invalidateQueries(QUERY_KEY.GROUP_SUMMARIES);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLogin]);

  return (
    <S.Container>
      {groups.length > 0 ? (
        <S.GroupListBox>
          {groups.map(group => (
            <Card group={group} key={group.id} />
          ))}
        </S.GroupListBox>
      ) : (
        <NoResult>
          찾고 계신 모임이 없어요.
        </NoResult>
      )}
      {isFetching && (
        <S.LoadingWrapper>
          <Loading />
        </S.LoadingWrapper>
      )}
      <div ref={target} />
    </S.Container>
  );
}
```

그냥 봐도 typescript, 주석(eslint), jsx(html), css(in js) …

의식적으로 언어 종류를 줄이려고 하기보단 필요없는 코드만 걷어내도 언어 종류가 많아지진 않을 것 같다는 생각!

### G2: 당연한 동작을 구현하지 않는다

**최소 놀람의 원칙 (The Principle of Least Surprise)…**

개인적으로 마음에 들지 않는 번역이다. 명색이 **클린 코드**인데 번역도 **클린 코드스럽게** 했어야 하지 않을까? 코드 리뷰가 좀 필요해보인다.

### G11: 일관성 부족

lint나 prettier 같은 도구를 사용하는것도 좋은 방법인듯!

### G25: 매직 숫자는 명명된 상수로 교체하라

내용에는 엄청나게 동의하지만 ***‘매직 숫자’*** 라는 이름은 참을 수 없다.

**G11: 일관성 부족**!!!!! 영어든 한글이든 하나만 써주세요 제발!

### **G29: 부정 조건은 피하라**

부정 조건이 긍정 조건보다 이해하기 어렵다면 둘 중 어떤게 적절할까?

```tsx
if (!isSuccess) {
  return;
}

vs

if (isFailure) {
  return;
}
```

**Comment by wlsh44** [comment]
### G16: 모호한 의도

아무리 의도를 분명히 하려고 해도 표현이 잘 안 될때가 많은 것 같습니다...ㅜ
정말 욕심이 생기는 부분이면서 가장 어렵기도 한 부분인 것 같아요..

### G21: 알고리즘을 이해하라

백준 풀 때 이게 왜 되지? 의 경우 인 것 같네요..😂
항상 구현을 해도 내가 올바르게 했다는 자신감이 안 생기는데 다른 분들은 어떠신가요?

### G25: 매직 넘버는 명명된 상수로 교체하라

저는 제 기억력을 믿지 않기 때문에 동의합니다!

### G30: 함수는 한 가지만 해야 한다

이렇게 하다가 종종 함수가 너무 많아지고 깊이가 너무 깊어지는 느낌이 드는데 정상일까요..?

### G29: 부정 조건은 피하라

최근에 날짜 관련 코딩을 하는데 다음과 같은 코드가 나왔습니다.

```java
while (!date.isAfter(endDate)) {
        ...
        }
```
`date` 가 `endDate`를 넘지 않는 것이 조건인데, 자바에서 제공하는 `LocalDate` 객체라 함수의 표현을 바꾸지도 못하는데 이런 경우에 새롭게 긍정 조건으로 함수를 빼는게 나을까요?

**Comment by genie-youn** [comment]
추상화에 적절한 시점은? 실제로 중복이 생겼을때냐 중복이 예상될 때냐.. 여전히 너무 어렵다.
- 중복이 예상될 때다.
- 두 개의 시점이 그렇게 멀지 않을까?
  + A -> B -> C // A` (내가 아님)
  + 중복된 개발은 한다.. > 코드리뷰에서 잡거나 하면 다행,, 근데 리뷰어에 내가 안걸리면?
  + 그 사람이 꼼꼼하게 이전 피쳐들을 확인해서 **"어 이전에 이렇게 개발했네, 중복이 됐네, 리팩터링해야지"** > best case
  + 현실 > 기능 추가하래. 추가함. PR 올림 (나 리뷰어 안걸림) 머지
  + 커뮤니케이션의 문제다.
- 이걸 반대로하면
  + A (추상화 다함, 구조 빡세게 잡음) -> B, C, -> A` (안만듬...) / 필요 없는 추상화였음..
- 균형의 미가 어렵다..
  + 우선은 추상화를 고려한다.
- TDD 수준으로..
  + **이정도면 충분하다**. 라는 생각이 들때까지만 한다. 너무 탑다운으로 하면 과도한 추상화문제에 빠지기 쉽지만,
  + 바텀업으로하면 중간에 멈출 수 있다.
  + 날 것의 코드는 두지 않는다.
- 대답이 없는건..
  + 나는 설계하지 않고 개발한다?

**Comment by genie-youn** [comment]
사당: 6시
