### ISSUE TITLE
[객사오] 1주차 ~ 2장 이상한나라의 객체 끝까지 (~71p)

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#95]
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by joi0104** [comment]
> 31p 첫째, 객체는 충분히 협력적이어야 한다.

충분히 협력적이다라는 게 저에게는 어렵게 와닿았던거 같아요. 충분히 협력적이다라고 판단할 수 있는 요소들이 뭐가 있을까요?

**Comment by genie-youn** [comment]
책을 보다보니 대전제가 빠졌다. 이게 필요한 이유.

23p 실세계의 모방이라는 객체지향의 개념은 훌륭한 프로그램을 설계하고 구현하는 실무적인 관점에서는 부적합하지만 객체지향이라는 용어에 담긴 기본 사상을 이해하고 학습하는 데는 매우 효과적이다. 객체지향을 설명하는 많은 책들과 문서들이 오해의 여지가 있다는 사실을 잘 알고 있음에도 실세계의 모방이라는 개념을 쉽게 포기하지 못하는 이유가 바로 여기에 있다.

25p 마지막으로 좋은 소식을 전할 수 있어 기쁘다. 여러분은 객체지향에서 가장 중요한 개념 세 가지를 이미 이해했다는 점이다. 그것은 바로 역할, 책임, 협력이다.

27p 요청과 응답을 통해 다른 사람과 협력할 수 있는 능력은 인간으로 하여금 거대하고 복잡한 문제를 해결할 수 있는 공동체를 형성할 수 있게 만든다.

28p.
- 여러 사람이 동일한 역할을 수행할 수 있다.
- 역할은 대체 가능성을 의미한다.
- 책임을 수행하는 방법은 자율적으로 선택할 수 있다.
- 한 사람이 동시에 여러 역할을 수행할 수 있다.

37p..

**Comment by wise1ight** [comment]
(20p)애플리케이션을 개발하면서 객체에 직접적으로 대응되는 실세계의 사물을 발견할 확률은 그다지 높지 않다.
=> 실세계가 컴퓨터 세상과 많이 연동되면서 확장되었으니 다르게 생각해야할지도?

(21p)실세계의 방화벽이 건물과 연관돼 있다고 해서 네트워크 방화벽이 건물과 연관될 필요가 있는가?
=> 이름만 동일할 뿐이지 억지로 엮는거 같다

근데 무조건 실세계를 모방하는 것이 아니다라는것은 와닿는다
예시 설명에서 핵심적인 개념들을 볼드로 처리한게 보기 좋아

(27p)손님에게는 커피를 주문할 책임이 있다.
(38p) 지나치게 클래스를 강조하는 프로그래밍 언어적인 관점은 객체의 캡슐화를 저해하고 클래스를 서로 강하게 결합시킨다.
Class 기반의 객체지향 언어를 주로 사용하다보니 다른 방식들은 상상이 잘 되지 않는데 객체의 캡슐화를 저해하고 클래스를 서로 강하게 결합시킨다는게 잘 와닿지 않습니다.

55p 행동은 외부에 가시적이어야 한다.
어떻게 가시적이어야 하지?

56p 객체의 지능도 높아진다
??

Class 설계에만 매진하고 다른 객체들간의 협력을 되돌아 보는 계기가 되긴 하네요.

"행동이 상태를 결정한다."

66p부터는 은유와 객체
무슨 얘기를 하려는건진 알겠는데
이젠 현실 세계는 Real World로만 볼 것이 아니라 Real World + Cyber World로 봐야한다고 생각한다.



작성중

**Comment by siathus** [comment]
# 1장
> 중요한 것은 어떤 클래스가 필요한가가 아니라 어떤 객체들이 어떤 메시지를 주고받으며 협력하는가다. 클래스는 객체들의 협력 관계를 코드로 옮기는 도구에 불과하다. (p. 38)

# 2장
> 그러나 현실 세계와 소프트웨어 세계 사이의 유사성은 여기까지일 뿐이다. (중략) 소프트웨어 세계에서 살아가는 객체는 현실 세계에 존재하는 객체와는 전혀 다른 모습을 보이는 것이 일반적이다. (p. 42)

> 협력에 참여하는 훌륭한 객체 시민을 양성하기 위한 가장 중요한 덕목은 상태가 아니라 행동에 초점을 맞추는 것이다. (중략) 객체의 적합성을 결정하는 것은 상태가 아니라 객체의 행동이다. (p. 65)

> 소프트웨어 객체를 창조할 때 우리는 결코 현실 세계의 객체를 모방하지 않는다. 오히려 전혀 다른 특징을 부여하는 것이 일반적이다. (중략) 현실의 객체보다 더 많은 일을 할 수 있는 소프트웨어 객체의 특징을 의인화라고 부른다. (p. 67)

> 현실 세계와 객체지향 세계 사이의 관계를 좀 더 정확하게 설명할 수 있는 단어는 은유다. (p. 69)

확실히 의인화와 은유라는 두 단어가 확실히 현실에서의 객체와 소프트웨어 객체 사이의 간극을 가장 잘 메꿀 수 있는 단어들이라고 생각되네요.

**Comment by duckbok** [comment]
### 1장
하나의 기능을 위한 목표를 세우고 이를 여러 책임으로 나눈 후에 객체가 여러 책임을 지는 역할을 맡게되어 협력관계가 형성되는 내용을 풀어서 설명한 장이었다. 
> 클래스의 구조와 메서드가 아니라 객체의 역할, 책임, 협력에 집중하라. 객체지향은 객체를 지향하는 것이지 클래스를 지향하는 것이 아니다. (38p)

### 2장
> 행동이 상태를 결정한다 (64p)

애플리케이션에 필요한 협력이 무엇인가? 그렇다면 그에 필요한 행동은 무엇인가? 그럼 그를 수행할 객체는 누구인가? 라는 과정을 통해 객체를 형성하는 것은 간단하지만 간과하면 안되는 흐름이란 생각이 든다.

**Comment by usageness** [comment]
> "객체지향이란 실세계를 직접적이고 직관적으로 모델링할 수 있는 패러다임" (p.20)

이 문장에서 가장 중요한 단어를 뽑아야 한다면 실세계가 아니라 **모델링**을 뽑아야 한다고 생각합니다.
결국 객체지향이란 실세계의 '문제'를 다루기 위해 만들어진 일종의 체계이지,
그 자체가 실세계를 대체하거나 완벽히 모방하는 용어는 아닌 것 같아요.

객체가 가진 다양한 특성들보단 내가 직면한 문제에 필요한 속성들만을
부분적으로 취사선택하라는게 1장의 요점인 것 같습니다.


> 모든 과정 속에는 손님, 캐시어, 바리스타 사이의 암묵적인 **협력** 관계가 존재한다. (p.25)

따라서 이 세 객체 사이의 관계에서 우선적으로 집중해야할건 **'커피를 주문하는 문제'** 이고,
캐시어와 바리스타의 월급이 얼마인지, 커피의 맛이 어떠한지 등은 실세계의 객체가 가지고 있지만
문제를 해결하는데에는 필요하지 않은 속성들이라고 할 수 있을 것 같습니다.


> 객체지향이란 시스템을 상호작용하는 자율적인 객체들의 공동체로 바라보고 객체를 이용해 시스템을 분할하는 방법이다. (p.35)

시스템을 분할하여 **복잡도를 낮추는 것** 이 객체지향의 최종적인 목표가 되겠네요.


> 코드를 담는 클래스의 관점에서 메시지를 주고받는 객체의 관점으로 사고의 중심을 전환하는 것이다. (p.38)

=== `클래스가 아닌 인터페이스에 집중하자!`


> 문을 통과한다는 행동의 결과는 앨리스의 위치라는 상태를 이용해 쉽게 설명할 수 있다. (p.45)

문득 든 생각인데, '앨리스의 위치' 라는 상태는 앨리스라는 객체가 가지고 있는게 맞을까요?
앨리스와 같은 인물들이 굉장히 많고, '지역' 이라는 객체의 역할 중 각 인물들의 위치에 의존적인 동작들이 많다면
인물의 위치는 인물 객체 내부가 가지고 있어야 할까요? 아니면 지역이 가지고 있어야 할까요?


> 소프트웨어 안에 구현된 상품 객체는 실제 상품과는 전혀 다른 양상을 띤다. (p.66)

위에서 언급했던 관점이네요! 단순한 모방과 추상화가 아닌,
그 이후에 해당 객체의 특성을 변경시킨 무언가로 만드는 과정이라고 보고 있습니다.
결국 요지는 **객체지향과 현실의 관계는 슈퍼셋과 서브셋이 아니다!**

**Comment by wlsh44** [comment]
## 1장

> 실세계의 모방이라는 개념은 객체지향의 기반을 이루는 철학적인 개념을 설명하는 데는 적합하지만 유연하고 실용적인 관점에서 객체지향 분석, 설계를 설명하기에는 적합하지 않다.
> 

설계를 할 때 생각보다 둘의 구분이 힘들다는 것을 최근에 느꼈습니다...

> 그것은 객체가 충분히 ‘자율적’이어야 한다는 것이다. ‘자율적’이라는 뜻은 ‘자기 스스로의 원칙에 따라 어떤 일을 하거나 자기 스스로를 통제하여 절제하는 것’을 의미한다.
> ...
> 객체의 자율성은 객체의 내부와 외부를 명확하게 구분하는 것으로부터 나온다.

## 2장

> 세상에 존재하는 모든 것들이 객체인 것은 아니다.

문구를 읽고 클린 코드에서 자료구조와 객체의 차이에 대해 설명하는 부분이 생각이 났습니다!
****
property와 attribute의 차이를 모르고 혼용하며 썼던걸 반성하며 정리

Property: 객체의 상태를 구성하는 모든 특징 → 멤버 변수와 다른 객체간의 링크를 포함한 모든 것들

Attribute: 객체를 구성하는 단순한 값 → 단순 멤버 변수
****
> 객체는 스스로의 행동에 의해서만 상태가 변경되는 것을 보장함으로써 객체의 자율성을 유지한다.
> 

> 상태를 잘 정의된 행동 집합 뒤로 캡슐화하는 것은 자율성을 높이고 협력을 단순하고 유연하게 만든다.
이것이 상태를 캡슐화해야 하는 이유다.
>
좋은 말 정리...

****
올해 초에 객체지향에 대해 아무것도 모르고 읽었을 때는 뭔소리야! 했는데 이번에 다시 읽으니까 반가운 내용들이 많아서 좋았습니다...
그래도 깊게 생각을 하니까 여전히 어렵네요 😭

**Comment by lallaheeee** [comment]
- 역할은 대체 가능성을 의미한다 (중략) 역할은 유연하고 재사용 가능한 협력 관계를 구축하는 데 중요한 설계 요소다. 
회사에서 제 역할이 언제든 대체 가능하다는 의미처럼 읽혀서 슬프면서도 동시에 고개가 끄덕여졌어요
