### ISSUE TITLE
[객사오] 2주차 ~ 3장 타입과 추상화 (~105p)

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#96]
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by wlsh44** [comment]
## 타입과 추상화

> 객체란 특정한 개념을 적용할 수 있는 구체적인 사물을 의미한다.
개념이 객체에 적용됐을 때 객체를 개념의 인스턴스라고 한다. (84p)

정확히 이해를 한건지는 모르겠지만 여기서 개념이란 객체들을 분류하기 위한 대한 하나의 틀(또는 하나의 표현 방법)로 작용을 하고, 이 개념을 타입(표현 방법 중 하나로 class)이라고 한다 정도로 읽었습니다.

최근 들어 객체지향에서 class가 뭔지에 대해 궁금해졌는데 이번에 책을 읽으면서 평소보다 깊게 생각을 하는 시간을 가져서 좋았습니다!

> 다형성이란 동일한 요청에 대해 서로 다른 방식으로 응답할 수 있는 능력을 뜻한다.(93p)
...
훌륭한 객체지향 설계는 외부에 행동만을 제공하고 데이터는 행동 뒤로 감춰야 한다. 이 원칙을 흔히 캡슐화라고 한다.(94p)

캡슐화와 다형성은 서로 독립적인 개념인 줄 알았는데 연관되는 내용이였네요.

> 객체지향에서 중요한 것은 동적으로 변하는 객체의 '상태'와 상태를 변경하는 '행위'다.

이번 챕터 한 줄 요약을 하면 
```
객체의 행동으로 타입이 정해지고 추상화가 되며, 타입으로 객체가 분류된다.
```
정도일까요..?

**Comment by wise1ight** [comment]
묶어내고 솎아내기
복잡한걸 단순화해서 생각하기

클래스는 타입과 동일한 개념 아님
클래스는 타입뿐만 아니라 코드 재사용도

### 87p.
> 여러분의 인지능력을 발휘해 최대한 직관적으로 분류하라.

암호화폐 거래소에서 거래되는건 다 코인이 아닌가?

```
코인 vs 토큰
코인은 비트코인과 같이 단독적이고 독립적인 블록체인(네트워크)을 갖는 암호화폐
ex) 비트코인, 이더리움, 리플, 트론, 솔라나

토큰은 자체적인 블록체인을 갖진 않으나 또 다른 블록체인에 의존해 존재하는 암호화폐
ex) 체인링크(이더리움), 스테픈(솔라나), USDT(이더리움, 솔라나, 트론 등)
```

언제는 코인만 거래되던 것이
여러가지 블록체인에 존재하는 토큰들이 거래되기 시작하고
더 나아가 A블록체인에 있는 a토큰이 B블록체인도 지원하게 되면서 아주 복잡해지는 사례를 겪어봤습니다.

어떤 분야에 대해서 알지 못하면 정확하게 분류하기 어렵고
심지어 분류를 잘 했다고 생각했더니 복잡해집

### 94p.
[책임 주도 설계 vs 데이터 주도 설계](https://eunjin3786.tistory.com/324)

### 97p
Java 상속과 관련된 얘기?

**Comment by KangJiJi** [comment]
## p.75

![image](https://user-images.githubusercontent.com/22635168/204126097-ef8a7393-6501-42ac-a4a9-5c3843d4b5f7.png)

파블로 피카소의 그림도 똑같다.

**Comment by genie-youn** [comment]
76p. 따라서 진정한 의미에서 추상화란 현실에서 출발하되 불필요한 부분을 도려내가면서 사물의 놀라운 본질을 드러나게 하는 과정이라고 할 수 있다.

84p. 객체란 특정한 개념을 적용할 수 있는 구체적인 사물을 의미한다. 개념이 객체에 적용됐을 때 객체를 개념의 인스턴스라고 한다.

87p. 객체는 소중하다. 따라서 소중한 객체를 안전하고 **적절한 장소에 보관할 수 있도록** 여러분의 인지능력을 발휘해 최대한 직관적으로 분류하라.

89p. 타입은 개념이다. 따라서 타입이란 우리가 인식하고 있는 다양한 사물이나 객체에 적용할 수 있는 아이디어나 관념을 의미한다. 어떤 객체에 타입을 적용할 수 있을 때 그 객체를 타입의 인스턴스라고 한다. 타입의 인스턴스는 타입을 구성하는 외연인 객체 집합의 일원이 된다.

98p. 여기서 중요한 것은 객체지향에서 일반화/특수화 관계를 결정하는 것은 객체의 상태를 표현하는 데이터가 아니라 행동이라는 것이다. 어떤 객체가 다른 객쳅다 더 일반적인 상태를 표현하거나 더 특수한 상태를 표현한다고 해서 두 객체가 속하는 타입 간에 일반화/특수화 관계가 성립하는 것은 아니다. 두 타입 간에 일반화/특수화 관계가 성립하려면 한 타입이 다른 타입보다 더 특수하게 행동해야 하고 반대로 한 타입은 다른 타입보다 더 일반적으로 행동해야 한다.

100p. 따라서 어떤 타입을 다른 타입의 서브타입이라고 말할 수 있으려면 다른 타입을 대체할 수 있어야 한다. - Liskov 1988

예제로 같이보기

추상화, 분류
[https://github.com/getsentry/sentry-javascript/blob/master/packages/core/src/baseclient.ts#L85](https://github.com/getsentry/sentry-javascript/blob/master/packages/core/src/baseclient.ts#L85)

[https://github.com/getsentry/sentry-javascript/blob/master/packages/types/src/transport.ts#L31](https://github.com/getsentry/sentry-javascript/blob/master/packages/types/src/transport.ts#L31)

[https://github.com/axios/axios/tree/v1.x/lib/adapters](https://github.com/axios/axios/tree/v1.x/lib/adapters)

**Comment by lallaheeee** [comment]
## 타입과 추상화


```
사람에 인지에는 한계가 있어 문제가 어려울 수록 인지 능력이 떨어지고,  일반화와 단순화를 이용해 문제를 추상화하여 복잡함을 극복한다. (72~77p)
```

복잡한 금융을 쉽게 풀어내려하는 토스처럼  복잡한 문제를 사용자의 니즈에 맞게 서비스를 제공하는  IT 서비스 업계 특성이 추상화와 맞닿아 있다고 생각했어요. 

IT는 사용자가 조금 더 편리한 삶을 누릴 수 있도록  사용할 수 있도록 어떤 서비스를 제공하잖아요. 그래서 사람들이 잘 사용하는 IT 서비스를 만드려면 복잡하고 불필요한 부분을 최대한 감추고 일반화랑 단순화를 잘해야한다는 생각이 들어요.

객체지향에서 추상화를 뛰어넘어 우리가 밥벌이를 할 수 있고 해야하는 영역 전반에 걸쳐 추상화의 필요성, 목적, 방법들이 존재하는 듯.. 

```
 개념을 이용해 공통점을 가진 객체들을 분류할 수 있다는 아이디어는 객체지향 패러다임이 복잡성을 극복하는 데 사용하는 가장 기본적인 인지 수단이기 때문이다 (86p)
```

그래서 정말 딮-다이브로 설명하는듯.


```
그룹으로 나누어 단순화하기  정원사, 병사, 신하, 왕자와 공주, 하객으로 참석한 왕과 왕비들, 하트 잭, 하트 왕과 하트 여왕 (80~85p) 

분류란 특정한 객체를 특정한 개념의 객체 집합에 포함시키거나 포함시키지 않는 작업을 의미한다 (87p)
```

한자한자씩 다 쓴 것도 아니고 ctrl+c, v 했을거면서 자꾸 긴 글 읽게해서 킹받는데, 트럼프를 왜 트럼프라 줄여부르자고 하고 왜 줄여말할 수 있는지 이런 인지 과정을 세세하게 설명해주고
개념의 사전적 의미까지 수록해서 친절하면서도 단어의 의미에 한번 더 곱씹어보게 되니까 청중을 정말 잘 고려해서 쓴 책이라 생각해요


```
개념이란 단어는 간지가 나지 않아서 수학용어인 타입을 차용했다. (89p) 
```

잘한듯.. 타입 선언할때 개념 선언! 하면 간지 진짜 안나는듯.. 반대로 하나의 개념을 만든다는 느낌은 잘 와닿았을 것 같긴 함 



```
그렇다면 객체는 데이터인가? 
(···) 객체가 협력을 위해 어떤 책임을 지녀야 하는지를 결정하는 것이 객체지향의 설계의 핵심이다.  
(···) 행동에 따라 객체를 분류하기 위해서는 객체가 내부적으로 관리해야 하는 데이터가 아니라 객체가 외부에 제공해야 하는 행동을 먼저 생각해야 한다 (92-94p)
```
메모 메모 모니터 옆에 붙여두려구요 


```
개념은 객체를 분류하기 위한 틀을 제공한다(84) 
타입은 개념이다 (89p)
그래서 결국 타입은 추상화다 (103p)  
클래스와 타입은 동일한 것이 아니다 (104p)
→ 타입 = 개념 =  추상화 ≠ 클래스 
```

책 읽을 때 타입, 개념, 추상화 단어를 각 대치해서 읽어보면 필자가 반복 설명하는 개념들이 더 와닿는 것 같아요

**Comment by usageness** [comment]
## 지하철 노선도 문제 (p.73)

### 해결해야 할 문제 파악하기

- 실제와 유사하게 만들어야 함 (X)
- **어떤 역을 이용해야 쉽고 빠르게 목적지에 도착할 수 있는지 파악하게 하기 위함 (O)**
    > “역과 역 사이의 연결성을 직관적으로 표현해야 한다.”

- 필요하지 않은 정보 (지형지물) 를 제거하는 것이 복잡성의 극복으로 이어짐

  - **추상화의 개념**

> 분류는 객체지향의 가장 중요한 개념 중 하나다. (P.87)

⇒ **객체에 대한 분류가 잘 되면 좋은 품질의 객체지향으로 이어진다.**

## 타입 (p.89)

- 데이터를 어떻게 사용할지에 관한 분류
- 내부 방식은 외부에 노출되지 않음

### "행동 우선"의 특징

- 객체가 어떤 행동을 하는지에 따라 객체의 타입이 결정
- **그럼 자바스크립트의 덕 타이핑 (Duck Typing) 도 객체 지향의 특징이라고 할 수 있을까요?**

**Comment by joi0104** [comment]
> 문제는 복잡성의 총체인 현실이라는 괴물을 그대로 수용하기에는 인간이 지니고 있는 인지 능력과 저장 공간이 너무나도 보잘 것 없다는 점이다. 따라서 사람들은 본능적으로 이해기 쉽고 예측 가능한 수준으로 현실을 분해하고 단순화 하는 전략을 따른다.

추상화가 필요한 이유를 설명할 수 있는 하나의 문장. 복잡한 현실에 비해 인간의 인지 능력과 기억 능력은 너무나 보잘 것 없다.
코드는 기계는 읽는게 아니라 사람이 읽는 것이라는 걸 다시 한번 상기하게 되었다.


>  결국 객체의 일반화/특수화 관계에 있어서도 중요한 것은 객체가 내부에 보관한 데이터가 아니라 객체가 외부에 제공하는 행동이다.

객체지향 설계하면 많이 실수하게 되는 부분이라고 생각. 일반적인 개념으로 객체를 나누고 난 이후에는 실제로 요구사항에 맞는 데이터를 처리할 객체를 찾다보니 특수화를 할때 데이터 중심으로 객체를 나누곤 하는 거 같다.

**Comment by siathus** [comment]
## 행동이 우선이다
> 같은 타입에 속한 객체는 행동만 동일하다면 서로 다른 데이터를 가질 수 있다. 여기서 
동일한 행동이란 동일한 책임을 의미하며, 동일한 책임이란 동일한 메시지 수신을 의
미한다. (p. 93)

'동일한 책임이란 동일한 메시지 수신을 의미한다.'에 덧붙여서 '동일한 책임이란 동일한 메시지 수신 **및 응답**을 의미한다.'로 해야 하지 않을까 하는 생각이 듭니다.

위 글처럼 '동일한 행동이 동일한 메시지 수신'만을 의미하게 된다면, `B`라는 객체가 `A`라는 객체의 행동을 똑같이 수행하면서 반환값 타입만 다르게 응답한다 해도 `A`와 `B`는 같은 타입에 속한다고 생각해야 하지 않을까요?

아니면, 여기서의 '행동'이란 이 반환값까지 함께 포함하는 개념인걸까요? 써놓고 보니 이게 맞는 것 같기도 하고...

* * *
> 여자 친구가 화난 이유를 이해하는 것은 거의 불가능에 가깝다.

더 많고 폭넓은 독자들이 공감할 수 있는 비유를 사용해주셨으면 좋겠습니다~

**Comment by KimDa99** [comment]
> 데이터의 내부 표현 방식과 무관하게 행동만이 고려 대상이라는 사실은 외부에 데이터를 감춰야 한다는 것을 의미한다
그동안 캡슐화의 의미를 단순하게 '쓰기 편하게 하기 위함'으로만  생각했었다.
근데, **행동** = **책임** = **메시지** 라는 걸 읽고나서 왜 감춰야 하는지, 그 이유를 좀 더 알 수 있게 됐다.

1~2장을 읽으면서 반성과 성찰보다는 그렇구나~ 이렇게 짜면 좋겠지? 하고 넘어 갔는데
이번 장 후반부를 읽으면서 내가 상태 위주로 생각하고 그렇게 코드를 짜고 있음을 알 수 있었다.

**Comment by eagleda** [comment]
> 리처드 파인만:  "현상은 복잡하다. 법칙은 단순하다. 버릴게 무엇인지 알아내라"
공통점을 취합하고, 불필요한 세부 사항이나 차이점을 의도적으로 배제하는 추상화의 개념을 짧게 담고 있는 듯합니다.
앞에 나오는 지하철 노선도 등의 예시에서 추상화를 통해 현실의 복잡성을 극복해내는 것의 중요성을 찾을 수 있었습니다.

책의 초입부터 현재까지 "동적"인 프로그래밍에 중점적인 서술이 자주 보이는데, 객체가 행하는 행동과 그로 인해 동적으로 변하는 상태를 위주로 봐야 한다는 말에서, 지금까지 너무 데이터에만 집중한 코딩을 하지 않았는지 생각하였습니다. 동적인 프로그래밍을 위해선 무엇을 중점으로 생각을 해야하는지 알아보아야 겠네요..
