### ISSUE TITLE
[객사오] 3주차 ~ 4장 역할, 책임, 협력 (~137p)

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#97]
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by lallaheeee** [comment]
```
130p 
 일단 협력이라는 견고한 문맥이 갖춰지면 우리의 초점은 협력을 위해 필요한 책임의 흐름으로 옮겨진다. (···) 
객체의 행위에 초점을 맞추기 위해서는 협력이라는 실행 문맥 안에서 책임을 분배해야한다. 각 객체가 가져야 하는 상태와 행위에 대해 고민하기 전에 
그 객체가 참여할 문맥인 협력을 정의해라. (···) 객체를 충분히 협력적으로 만든 후에 협력이라는 문맥 안에서 객체를 충분히 자율적으로 만드는 것이다. 
```

**Comment by joi0104** [comment]
> 협력은 한 사람이 다른 사람에게 도움을 요청할 때 시작된다. 자신에게 할당된 일이 스스로 해결하기 어려운 문제에 부딪히게 되면  

트레이드 오프 지점 같기도 하지만 가볍게 여쭤봅니다. 할당된 일이 그 객체 스스로 해결하기 어려운 문제라고 판단할 수 있는 요인은 무엇일까요? 할당된 일이 스스로 해결해야하는 문제여서 객체의 역할을 확장해야하는 지점인지 다른 객체에 작업을 위임하기 위해 해당 책임을 담당하는 새로운 객체가 나와야하는 시점인지 판단하기가 어려워서 물어봅니다

**Comment by wise1ight** [comment]
118p
> 한 가지 주의할 점은 책임과 메시지의 수준이 같지는 않다는 점이다. 책임은 객체가 협 력에 참여하기 위해 수행해야 하는 행위를 상위 수준에서 개략적으로 서술한 것이다. 책임을 결정한 후 실제로 협력을 정제하면서 이를 메시지로 변환할 때는 하나의 책임이 여러 메시지로 분할되는 것이 일반적이다.

상위 수준에서 개략적으로 서술한 것이란게 잘 와닿지 않아요.
협력을 정제하면서 ~ 하나의 책임이 여러 메시지로 분할되는 것은 하나의 책임을 수행하더라도 메서드는 여러개가 될 수 있다고 이해하면 될까요?

**Comment by KimDa99** [comment]
이번 장은 그 전의 장보다 눈에 바로 안 들어오는 문장이 많았다.

> 책임이 협력이라는 문맥속에서, 요청을 수신하는 한 쪽의 객체 관점에서 무엇을 할 수 있는지를 나열하는 것이라면 메시지는 협력에 참여하는 두 객체 사이의 관계를 강조한 것이다. 117p
> 

*(협력이라는 문맥속에서) 책임이 “요청을 받은 객체가 할 수 있는 것들의 집합”이라면, 메시지는 협력에 참여하는 두 객체 사이의 관계를 강조한 것이다.* 으로 바꿔서 이해해도 될까?

> 역할을 대체하기 위해서는 각 역할이 수신할 수 있는 메시지를 동일한 방식으로 이해해야 한다.
> 

(*저번에 시간에 토론한 것? = 동일한 메시지를 수신할 수 있기 때문에 = 호환되어야 한다. )*

저번 주차에 대답을 했을 때 적절한 단어가 생각이 안 났는데 ‘호환’을 말하고 싶었던 것 같다.

**Comment by usageness** [comment]
p. 128
> 처음에는 전형적인 왕의 모습을 빌려 소프트웨어 객체를 창조하는 것이 합리적이고 적절해 보일지 모르지만 실제로 동작하는 애플리케이션을 구축하기 위해서는 왕이 참여하는 협력을 우선적으로 고려해야 한다.

p. 131
> ... 테스트-주도 개발(Test-Driven Development) 방법이다. 테스트-주도 개발은 테스트를 먼저 작성하고 테스트를 통과하는 구체적인 코드를 추가하면서 애플리케이션을 완성해가는 방식을 따른다.

제가 이해하기로는 128페이지의 논지는 흔히 떠오르는 왕의 모습(인터페이스)을 통해 객체를 창조하지 말라는 것인데, 이건 131페이지의 테스트 주도 개발의 과정 그 자체라는 생각이 드네요. 우선 객체의 모양을 맞춰나가는 방식으로 개발하고, 그 안에서 프로그램을 고도화시키며 리팩토링을 병행해서 가는 방식이라면 문제될게 없다고 생각됩니다.

애초에 프로그램을 만드는데 **왕** 클래스를 만든다고 해서 수염나고 근엄한 얼굴로 왕좌에 앉아있는 모습부터 구현하는 사람이 있을까 싶긴 한데... 하하

**Comment by wlsh44** [comment]
> 왕은 재판 집행이라는 책임을 수행하기 위해...(116p)
> 책임은 객체의 공용 인터페이스(public interface)를 구성한다. (117p)

개인적으로는 첫 번째 문장을 보고 약간 오해를 했습니다.
올바른 재판 집행의 책임은 왕과 하얀 토끼와 모자 장수가 바른 순서대로 협력할 수 있게 하는 객체에게 있다고 생각을 합니다.
다만 처음에 저 부분을 읽을 때는 왕이 재판 집행, 목격자 불러오기, 증언시키기 3가지의 인터페이스가 존재해야 하나 생각을 했었네요..

> 책임을 결정한 후 실제로 협력을 정제하면서 이를 메시지로 변환할 때는 하나의 책임이 여러 메시지로 분할되는 것이 일반적이다. (118p)
> 동일한 역할을 수행하는 객체들은 동일한 메시지를 수신할 수 있기 때문에 동일한 책임을 수행할 수 있다는 것은 매우 중요한 개념이다. (126p)

두 문장을 같이 두고 보니까 이해가 잘 안가네요...😭

예를 들어 전에 개인 프로젝트를 하면서 두 사이트를 크롤링해서 파싱을 하는 작업을 했었는데, 처음에는 파싱을 담당하는 인터페이스를 두고 코드를 작성하려고 했습니다.
그런데 A사이트에서는 파싱에 필요한 데이터가 json으로 넘어오고,  B사이트에서는 html로 넘어와 인자가 다른 메서드가 만들어졌습니다.
그래서 Object로 캐스팅해서 하나의 인터페이스로 처리할까 하다가 결국엔 A사이트도 html을 파싱하는 방식으로 변경하고 추상화를 했던 것 같습니다.

둘 다 파싱을 한다는 책임을 갖고있지만 메시지가 달라 동일한 역할을 수행하지 못했는데 하나의 책임이 여러 메시지로 분할된다는게 어떤 의미인지 잘 모르겠네요..

**Comment by eagleda** [comment]
이번뿐만 아니라 지난 챕터에서도 지속적으로 나오는 문구였던 "역할, 책임, 협력에 집중하라."에 대한 구체적인 이유를 알아 볼 수 있는 챕터였습니다.

> 한 가지 주의할 점은 책임과 메시지의 수준이 같지는 않다는 점이다. ... 메시지로 변환할 때는 하나의 책임이 여러 메시지로 분할되는 것이 일반적이다.  
수준이 같지 않다고 서술되어 있는데, 형식이 다르다는 걸까요? 아니면 집합과 원소의 개념으로 이해하면 쉬울 까요..

> 왕이 중요한 이유는 재판이라는 협력에 '판사'의 역할로 참여해서 죄인의 죄를 판결하는 책임을 수행할 수 있기 때문이다. p.129  
객체지향 프로그래밍을 문자 그대로  각각의 객체를 중심으로 설계하는 것으로 받아들이지 말고 그 객체들이 수행할 책임, 역할을 중점으로 설계하여 객체지향 패러다임의 특장점을 부각시키라는 것을 뜻하는 걸까요?

**Comment by duckbok** [comment]
> 129p, 협력을 설계한다는 것은 설계에 참여하는 객체들이 주고받을 요청과 응답의 흐름을 결정한다는 것을 의미한다.
이 흐름은 객체가 협력에 참여하기 위해 수행될 책임이 된다.
일단 객체에게 책임을 할당하고 나면 책임은 객체가 외부에 제공하게 될 행동이 된다.
이를 결정한 후에 그 행동을 수행하는 데 필요한 데이터를 고민해야 된다.
데이터와 행동이 어느 정도 결정된 후에 클래스의 구현 방법을 결정해야 한다.

이번 장에서 핵심적인 내용이라 생각이 듭니다.

객체들이 주고받을 요청과 응답의 흐름인 협력은 객체들이 수행할 책임으로 나뉘고, 이 책임은 여러 행동(메시지)로 나뉠 수 있으며, 하나의 행동을  수행하는 데 필요한 데이터를 결정한 후에 클래스의 구현 방법을 생각하라!

> 130p, 객체지향 시스템에서 가장 중요한 것은 충분히 자율적인 동시에 충분히 협력적인 객체를 창조하는 것이다. 이 목표를 달성할 수 있는 가장 쉬운 방법은 객체를 충분히 협력적으로 만든 후에 협력이라는 문맥 안에서 객체를 충분히 자율적으로 만드는 것이다.

객체를 협력적으로 만든다는 것이 단순히 필요한 요청과 응답을 잘 주고받을 수 있게 만든다는 의미가 맞을까요?

 > 131p, 테스트-주도 개발의 실제 목적은 구체적인 코드를 작성해나가면서 역할, 책임, 협력을 식별하고 식별된 역할, 책임, 협력이 적합한지를 피드백받는 것이다.
136p, 책임을 수행할 객체 또는 클라이언트가 기대하는 객체의 역할이 메시지를 수신할 때 어떤 결과를 반환하고 그 과정에서 어떤 객체와 협력할 것인지에 대한 기대를 코드의 형태로 작성하는 것이다.

TDD 굳..
