### ISSUE TITLE
[객사오] 4주차 ~5장 책임과 메세지 끝까지 (~137p)

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#98]
**스터디는 마이크를 끄지 않아요.**

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by KangJiJi** [comment]
# 캡슐화

캡슐화의 두가지 관점

- 상태와 행위의 캡슐화
- 사적인 비밀의 캡슐화

두 관점의 차이를 잘 모르겠습니다.

# 느낀점

이번장은 하나를 제외하고, 크게 어려움은 없이 읽을 수 있었습니다 :)

**Comment by genie-youn** [comment]
145p 성급한 일반화의 오류를 피하고 현재의 문맥에 가장 적합한 책임을 선택할 수 있는 날카로운 안목을 기르기 바란다.

149p 객체가 수신할 수 있는 '메시지'와 메시지를 처리하기 위해 선택할 수 있는 '방법(메서드)'

**Comment by lallaheeee** [comment]
```
묻지 말고 시켜라 
```
실무하다 보면 요청할 때 엄청 물어보고 요청하는 로직이 있는데 만악의 근원... 요청할 때 묻는 거에 대한 적절한 처리가 안되어 있으면 의도한 동작을 안함 -> 요청하는 쪽에서는 왜 안되는지 코드 일일히 까보면서 디버깅해야함 -> 진입점이 늘어날 때마다 고통이 배로 증가함.. 


```
어떤 메시지가 필요한지 결정한다. 메세지를 결정한 후에는 메시지를 수신하기에 적합한 객체를 선택한다. 
```
대상 먼저 선택하고 메시지를 고민하는 것보다 메시지 먼저 정하고 객체를 선택하는 전략이 유연한 설계를 만든다.

**Comment by siathus** [comment]
> 서로 다른 객체들이 다형성을 만족시킨다는 것은 객체들이 동일한 책임을 공유한다는 것을 의미한다.

> 객체지향의 강력함은 클래스가 아니라 객체들이 주고받는 메시지로부터 나온다.

이번 장은 특히나 스무스해서 두세번 다시 읽어보면서 짜내려 해도 딱히 의문이 가거나 궁금한 점은 없었네요.

꼭 이번 장에만 해당하는 건 아닌데, 한 가지 바라는 점은 앨리스를 통한 비유로 설명하는 것 이외에도 아주 간소하게나마 코드로 된 예시가 하나 있었으면 더 직관적이었을 것 같네요.

**Comment by usageness** [comment]
### 책임과 메시지

**메시지 전송** : `수신자`, `메시지 이름`, `인자`의 조합

메시지는 객체들이 협력을 위해 사용할 수 있는 유일한 소통 수단

메서드는 메시지를 처리하기 위해 내부적으로 선택하는 방법

```jsx
// witness.js
const talk = (content) => { // 메서드 : talk
  console.log(`저는 ${content}는 잘 모릅니다.`);
}

export { talk };

// main.js
import { talk as testify } from 'witness';

testify('범인'); // 메시지 이름 : testify, 인자 : '범인'
```

여기까지 내용 정리~
---


> p.153 모든 것이 다형성의 축복처럼 느껴지지만 이 모든 것은 다형성을 지탱하는 메시지가 존재하기 때문에 가능한 것이다.
> 

**다형성이 왜 좋은가요?** 라고 물었을때

“유연하고 확장 가능성이 높고, 재사용성이 높은 객체를 만들 수 있게 한다” 고는 답할 수 있었겠지만 다형성을 지탱하는 메시지를 생각해본적은 없었는데 책에서 잘 짚어준 것 같네요.

결국 객체지향의 핵심은 다형성도, 추상화도, 캡슐화도, 클래스도 아닌 **메시지**인 것 같습니다~

> p. 161 메시지를 믿어라. 그러면 자율적인 책임은 저절로 따라올 것이다.
> 

네

**Comment by joi0104** [comment]
저도 이번장은 스무스하게 읽어서 궁금한 부분은 딱히 없습니다!

> 145p 성급한 일반화의 오류를 피하고 현재 문맥에 가장 적합한 책임을 선택할 수 있는 날카로운 안목을 기르기 바란다.

객체지향 프로그래밍에서 가장 어려운 부분이자 가장 핵심적인 부분인 것 같아서 인용해봤습니당. `현재 문맥에 가장 적합한` 이라는 부분이 개발하면서 가장 어려운 것 같아요.

**Comment by duckbok** [comment]
> [149p] 메시지를 처리하기 위해 내부적으로 선택하는 방법을 **메서드**라고 한다.
...
메시지를 수신한 객체가 실행 시간에 메서드를 선택할 수 있다.

메시지와 메서드를 같다고 생각했었는데 이제 명확히 나눌 수 있겠네요.

> [153p] 셋째, 협력이 수행되는 방식을 재사용할 수 있다.

제가 제대로 못 읽은건가 싶긴한데 **협력의 구조를 재사용할 수 있다.** 를 말하고 있는 게 맞을까요?
그대로 읽으면 아래 예시에서 협력이 수행되는 다양한 방식 속에서 협력이 수행되는 방식을 재사용할 수 있다. 라서 뭔가 말이 오묘해서 적어봤습니다.

> [154p] 수신자와 송신자는 메시지라는 얇은 끈으로만 이어져 있다.

뒤에서 풀어주는 내용을 추상적으로 잘 표현한 문장이라는 생각이 들었습니다.

**Comment by eagleda** [comment]
> 144p 객체가 자율적이기 위해서는 객체에게 할당되는 책임의 수준 역시 자율적이어야 한다.    

한동안 알고리즘 위주로 공부하다보니 문제해결을 위한 구체적인 조건을 설정하는 경우가 많았는데,  오히려 실제 개발에선  객체간 협력을 위해서라도 높은 자율성을 주는 것이 좋다는 것을 알게 되었습니다.
  
전체적으로 "어떻게"보다 "무엇을"에 방점을 찍으라는 말이 중요한 부분인 것 같았습니다.  이를 통해서 객체지향의 주요 개념인 객체의 자율성/다형성 등을 확보할 수 있는 것이니까요.
(제대로 이해한 것이겠죠..?)

**Comment by wise1ight** [comment]
어떻게 수행할지가 아닌 메시지 결정 후 메시지를 수행할 객체를 정하자가 핵심인 것 같네요.
How X, What/Who

**Comment by KimDa99** [comment]
- 책임 공유 = 대체 가능 = 어떻게 처리하든 ‘무엇’을 해내기만 하면 됨
- 어떤 메시지를 주고 받는가에 초점을 두어야 한다, 데이터를 먼저 짜면 객체의 자율성을 저해한다

그동안 계속 데이터를 먼저 짠 다음 메시지를 생각했던 것 같다.

내가 이걸 구현할 수 있을까?에 매몰되다보니 계속 이렇게 코드를 짰었던 것 같다.

**Comment by wlsh44** [comment]
## 메시지를 믿어라

개별 객체가 아니라 메시지에 초점을 맞춰야 한다는게 저번 주 스터디때 질문했던 프로젝트 설계 오류를 생각하니까 좀 더 와닿았네요.
항상 구현을 생각할 때는 개별 객체의 세부 구현 내용만 생각했었는데 좀 더 숲을 보는 연습을 해야겠습니다..😭
