### ISSUE TITLE
[객사오] 5주차 ~끝까지

### ISSUE THREAD

**Issue by genie-youn** [TeamCrazyPerformance/http#99]
스터디는 마이크를 끄지 않아요.

8시까지 해당 이슈에 책을 읽으면서 궁금했던 부분, 함께 이야기해보면 좋을것 같은 부분을 코멘트로 달아주세요.
아무것도 안올리면 그 다음회차 호스트하기

호스트는 우선적으로 스터디원들이 올린 코멘트에 대해 자신의 생각을 이야기하고, 다른 사람들은 어떻게 생각하는지 토론을 이끌어 나가는 역할을 수행합니다.

.
우리 스터디에 멍청한 질문은 없습니다.
내가 이해 안 간 부분이 있다면 그건 높은 확률로 다른 사람도 이해를 못했을 것입니다.

우리 스터디는 이걸 위해서 진행합니다. 혼자서 읽었다면 무심코 넘어갔을 부분을 다양한 사람들이 모여 다양한 시각에서 바라보고 자신의 단어로 토론하고 이해하는걸 목표로 합니다.

그렇기 때문에 스터디때 질문하지 않고 의견을 내지 않는건 나 뿐만 아니라 스터디원 전체의 목표에 어긋나는 일이란걸 인지하고 "이런걸 물어봐도 되나?" 걱정하지 말고 마구마구 얘기하면 좋습니다.

그래서 우리 스터디에선 멍청한 질문은 없습니다. 모든 질문이 문제를 바라보는 새로운 관점일 뿐~

**Comment by genie-youn** [comment]
6장 객체 지도

182p
> 설계가 어려운 이유는 어제 약속했던 기능을 제공하는 동시에 내일 변경될지도 모르는 요구사항도 수용할 수 있는 코드를 창조해야 하기 때문이다. 요구사항을 만족시킬 수 있는 다양한 설계안들을 저울질하면서 그 결과로 단순하면서도 유연하 설계를 창조하는 것은 공학이라기보다는 예술에 가깝다.

그렇다고 하면 가설을 검증하기 위해 만드는 흔히 MVP라 부르는 것들은 어떨까? 이 제품들은 가설을 세우고 이를 검증하기 위해 최소한의 기능만을 갖춘 제품을 더티하고 빠르게 만드는게 핵심이다. 가설이 맞아떨어졌다면 제대로 된 제품을 만들기 시작할테고 그렇지 않다면 이 제품은 폐기될 것이다. 그럼 설계는 필요 없을까?


> 미래에 대비하는 가장 좋은 방법은 변경을 예측하는 것이 아니라 변경을 수용할 수 있는 선택의 여지를 설계에 마련해 놓는 것이다. 훌륭한 설계자는 미래에 구체적으로 어떤 변경이 발생할 것인지를 예측하지 않는다. 단지 언젠가는 변경이 발생할 것이며 아직까지는 그것이 무엇인지 모른다는 사실을 겸허하게 받아들인다. 좋은 설계는 나중에라도 변경할 수 있는 여지를 남겨 놓는 설계다. 설계를 하는 목적은 나중에 설계하는 것을 허용하는 것이며, 설계의 일차적인 목표는 변경에 소요되는 비용을 낮추는 것이다.

그냥. 너무 좋아서

195p

> 유스케이스는 사용자와 시스템 간의 상호작용을 보여주는 ‘텍스트’다. 유스케이스는 다이어그램이 아니다. 중요한 것은 유스케이스 안에 포함돼 있는 상호작용의 흐름이다. 유스케이스의 핵심은 사용자와 시스템 간의 상호작용을 일련의 이야기 흐름으로 표현하는 것이다. 다이어그램에 노력을 쏟지 말라. 중요한 것은 유스케이스에 담겨 있는 이야기다. 유스케이스는 사용자 인터페이스와 관련된 세부 정보를 포함하지 말아야 한다.

이 책을 처음 읽을 때도, 두번째 읽을 때도 이 챕터가 크게 안와닿았는데 이제야 좀 크게 와닿는것 같다. 읽는 내내 계단을 한 개 올라간 기분이었다.

7장 함께 모으기
현재 하고 있는 작업을 7장의 사고 흐름대로 한번 경험해보는것도 좋을것 같아요~

**Comment by wise1ight** [comment]
### 182p
> 미래에 대비하는 가장 좋은 방법은 변경을 예측하는 것이 아니라 변경을 수용할 수 있는 선택의 여지를 설계에 마련해 놓는 것이다.

**예측**과 **선택의 여지**는 어떤 차이가 있을까요?
물론 183p부터 좀 더 자세한 설명인 '안정적인 구조를 중심으로 설계하라'고 되어있는데
이는 뒤에 나오는 도메인 모델을 잘 생각하라는 걸 얘기하는것인지 아니면 또 다른 경우가 있을까요?

작성중

**Comment by siathus** [comment]
> 사람들에게 길을 묻지 마라. 객체를 이용해 지도를 만들어라. 기능은 지도에 표시된 길을 따라 자연스럽게 흘러갈 것이다. (p. 183)

저자는 현실 세계를 객체지향의 세계로 옮기는 것을 은유라고 설명합니다. 이 책의 구성 또한 대부분 챕터의 도입부에서 현실 세계의 사례를 소개한 뒤 그 사례를 바탕으로 비유를 통해 객체지향에 대해 설명합니다. 이 문구가 그 비유 중 가장 잘 사용된 것 같네요.

> 객체지향의 가장 큰 장점은 도메인을 모델링하기 위한 기법과 도메인을 프로그래밍하기 위해 사용하는 기법이 동일하다는 점이다. (p. 205)

> 개념 관점, 명세 관점, 구현 관점은 동일한 클래스를 세 가지 다른 방향에서 바라보는 것을 의미한다. (중략) 클래스는 세 가지 관점을 모두 수용할 수 있도록 개념, 인터페이스, 구현을 함께 드러내야 한다. (p. 208)

> 소프트웨어 클래스가 도메인 개념의 특성을 최대한 수용하면 변경을 관리하기 쉽고 유지보수성을 향상시킬 수 있다. (p. 226)

7장은 전체적으로 가볍게 읽을 수 있었습니다.

**Comment by lallaheeee** [comment]
### 06. 객체 지도
```
사람들에게 직접 길을 묻는 접근법은 기능에 구조를 종속시키는 방법이며 지도는 구조에 기능을 종속시키는 방법이다  -180p
```
문득 기능에 구조를 종속시킨 코드는 어떤 코드일지, 궁금하네요


```
기능 측면의 설계는 제품이 사용자를 위해 무엇을 할 수 있는지 초점을 맞춘다. 구조 측면의 설계는 제품의 형태가 어떠해야 하는지에 초점을 맞춘다. 설계의 가장 큰 도전은 기능과 구조라는 두가지 측면을 함께 녹여 조화를 이루도록 만드는 것이다.   - 181p
```
목적 조직의 경우에는 목표에 따라 사용자가 원하는 작은 기능을 조금씩 덧 붙이는 형태로 흘러가는데 이런 경우엔 기능 측면의 설계가 대다수인 것 같아요. 한번 쓰고 버릴 기능들이 아니라면 `제품의 형태가 어떠해야 하는지` 를 많이 고민하며 일하고 싶다는 생각이 들었어요 


```
불확실한 미래의 변경을 예측하고 이를 성급하게 설계에 반영하는 것은 불필요하게 복잡한 설계를 낳을 뿐이다.
```

```
미래에 대비하는 가장 좋은 방법은 변경을 예측하는 것이 아니라 변경을 수용할 수 있는 선택의 여지를 설계에 마련해 놓는 것이다. 
훌륭한 설계자는 미래에 구체적으로 어떤 변경이 발생할 것인지를 예측하지 않는다. 
단지 언젠가는 변경이 발생할 것이며 아직까지는 그것이 무엇인지 모른다는 사실을 겸허하게 받아들인다.  
좋은 설계는  나중에라도 변경할 수 있는 여지를 남겨 놓는 설계다.
설계를 하는 목적은 나중에 설계하는 것을 허용하는 것이며, 설계의 일차적인 목표는 변경에 소요되는 비용을 낮추는 것이다. -182p
```
어디까지가 예측이고.. 어디까지가 변경할 수 있는 여지를 남겨놓는 걸까요?
이번 장에서 좋았는데, 아직은 그 둘을 구별하기 어렵네요 


```
도메인이 무엇이건 상관없이 그곳에는 항상 도메인과 관련된 사람들이 도메인을 바라보는 모델이 존재한다.
도메인 모델은 단순히 다이어그램이 아니다
도메인 모델은 이해관계자들이 바라보는 멘탈 모델이다. (...)
사람들은 세상에 존재하는 현상을 이해하고 현상에 반응하기 위해 자신의 마음 속에 멘탈 모델을 구축한다. -185p
```
지난 스터디에 이 장은 결석했나봐요 ㅋㅋ 멘탈모델 처음 알게 된 개념이라 유익


```
훌륭한 디자인이란 사용자가 예상하는 방식에 따라 정확하게 반응하는 제품을 만드는 것이다. -186p
```
이런 제품을 만들고 싶어서 .. 

```
도메인 모델의 핵심은 사용자가 도메인을 바라보는 관점을 반영해 소프트웨어를 설계하고 구현하는 것이다.
도메인에 대한 사용자의 관점을 반영해야하는 이유는 사용자들이 누구보다도 도메인의 '본질적인' 측면을 가장 잘 이해하고 있기 때문이다. 
- 189p
```
계속 사용자 관점을 이야기 하니까 구조적 설계에 대한 설명을 이어가지 않고 서비스 잘 만드는 법에 대한 이야기를 하네? 의아했는데 
구조적 설계를 잘하려면 결국 만드는 사람 관점 말고.. 엔지니어 관점보다 사용자가 바라보는 관점으로 도메인을 바라보는 시각이 필요하구나 
깨달았어요

더불어 내가 만드는 제품을 서비스 측면에서도 설계 측면에서도 더 잘 만들려면 더 자주 써서 메이커 시각을 좀 버리고 유저의 입장이 되어야겠다는 생각도 들고 다른 서비스를 사용하면서도 나라면 어떻게 구성할까 고민해보는것도 좋겠다 .. 그런 생각을 ~ 했어요~

**Comment by eagleda** [comment]
> 안정적인 객체 구조는 변경을 수용할 수 있는 유연한 소프트웨어를 만들 수 있는 기반을 제공한다. (p.183) 
 
책에서 언급한 것처럼 요구 사항이 변경될 것을 고려하여 이를 수용할 수 있는 안정적인 구조를 제공해야 함을 명심해야겠군요.

> ... 사용자와 설계자는 직접적으로 상호작용할 수 없으며 단지 최종 제품인 시스템 그 자체를 통해서만 의사소통할 수 있다. 따라서 설계자는 디자인 모델을 기반으로 만든 시스템 이미지가 사용자 모델을 정확하게 반영하도록 노력해야 한다.(p. 186)

  

> ... 클래스를 명세 관점과 구현 관점으로 나눠볼 수 있어야 한다는 것이다. 캡슐화를 위반해서 구현을 인터페이스 밖으로 노출해서도 안 되고, 인터페이스와 구현을 명확하게 분리하지 않고 흐릿하게 섞어놓아서도 안 된다. (p.228)

public private 등을 구분해야 하는 것도 이러한 것의 일종이라 할 수 있을까요? 종종 실수를 할 때가 있어서..

**Comment by KimDa99** [comment]
> 자율적인 객체
이 '자율적'인 객체라는 말이 처음엔 와닿지 않았었는데, 그 이유는 '자율'과 '독립'의 뜻을 비슷하게 생각해서 그랬던 것 같다. 


  요새 프로젝트를 진행하면서 이 책에서 말하고 있는 내용들이 잘 지켜지고 있지 않다는 걸 느꼈다. 
  그 이유가 처음 설계를 메시지, 협력 위주로 짜지 않고 책임을 모호하게 다뤘기 때문도 있지만, 사용하는 툴의 미숙함 + 적은 경험 + 팀원들과 소통하지 않음 의 탓도 컸던 것 같다.
  위의 세 이유의 이유 때문에 설계 자체를, 프로젝트 구조를 이해하지 못했고 자연스럽게 부적절한? 비효율적인 방법으로 짠 것 같다.


책을 읽으면서 '음 이렇게 짜야겠다, 지금처럼 짜지 말아야지.'라고도 느꼈지만, 배운 것을 진짜로 수행하기 위해서는 경험의 양, 공부의 양 자체를 늘리는 것이 필요하다고 느꼈다.

**Comment by usageness** [comment]
> 자주 변하는 기능보다는 안정적인 구조를 따라 역할, 책임, 협력을 구성하라 (p.180)

객체지향이라는 개념을 기반으로 프로젝트를 구현할 때 가져야 할 생각을 잘 요약해 준 말이라고 생각합니다. 책 전체를 통틀어서 객체지향적 구현은 어떻게 해야하는 건가요? 라고 물었을때 답변의 핵심이 될 한 문장이라고 할 수 있을 것 같아요.


> 사람들에게 길을 묻지 마라. 객체를 이용해 지도를 만들어라. 기능은 지도에 표시된 길을 따라 자연스럽게 흘러갈 것이다. (p.183)

'기능' 의 관점이 아닌 '구조' 를 보고 만들라는 의미인데, 이 문장 뒤에 나올 내용들까지 함축적으로 잘 담고 있어서 자연스럽게 읽을 수 있었어요. "왜 우리가 지도를 만들어야 하는지?" 라는 의문을 품게하고, 그에 대한 해답을 순차적으로 제시해줘서 굉장히 설득력 있는 구성이었다고 생각합니다.


> 안정적인 도메인 모델을 기반으로 시스템의 기능을 구현하라. 도메인 모델과 코드를 밀접하게 연관시키기 위해 노력하라. 그것이 유지보수하기 쉽고 유연한 객체지향 시스템을 만드는 첫걸음이 될 것이다. (p. 206)

사용자가 매력적으로 느끼고 필요하다고 생각하는 기능을 구현하는 것도 중요하지만, 성공적인 프로그램은 계속해서 그러한 기능들을 빠르게 추가할 수 있어야한다는 점에서 왜 구조를 잘 짜야 하는지 설명하는 문장이었다고 생각해요.

**Comment by KangJiJi** [comment]
#함께 모으기

P. 217

```
현실 속의 메뉴판은 자기 스스로 메뉴 항목을 찾지 않을 것이다. 현실 속에서 메뉴판은 손님에 의해 펼
쳐지거나 닫혀지는 수동적인 존재다. 그러나 객체지향의 세계로 들어오면 수동적인 메뉴판이라는 개념
은 더 이상 유효하지 않다. 객체지향 세계에서는 모든 객체가 능동적이고 자율적인 존재다. 메뉴판은
마치 생명을 가진 존재처럼 자기 스스로 메뉴 항목을 찾는다. 따라서 설계자는 무생물을 생물처럼 ‘의인
화’해야 한다.
```

책을 읽으면서 메뉴판에는 메서드가 없어야한다고 생각했는데, 이 문단을 읽어보니 다시 생각하게 됐습니다.

**Comment by duckbok** [comment]
### 6장 객체 지도
*자주 변경되는 기능이 아니라 안정적인 구조를 따라 역할, 책임, 협력을 구성하라. 이것이 이번 장의 주제다. (180p)*

> 불확실한 미래의 변경을 예측하고 이를 성급하게 설계에 반영하는 것은 불필요하게 복잡한 설계를 낳을 뿐이다. 우리는 미래를 예측할 수 없다. 단지 대비할 수 있을 뿐이다.
...
좋은 설계는 나중에라도 변경할 수 있는 여지를 남겨놓는 설계다. (182p)

클린아키텍처에서  처음 읽고 명심한 부분인데 다시 한 번 생각하게 해줘서 좋았습니다.

> 훌륭한 디자인이란 사용자가 예상하는 방식에 따라 정확하게 반응하는 제품을 만드는 것이다. (186p)
...
사용자들이 누구보다도 도메인의 '본질적인' 측면을 가장 잘 이해하고 있기 때문이다.
...
본질적이라는 것은 변경이 적고 비교적 그 특성이 오랜 시간 유지된다는 것을 의미한다. (189p)

도메인 모델을 기반으로 코드를 작성해야하는 이유..

> 상호작용의 흐름을 텍스트로 정리한 것을 유스케이스라고 한다. (192p)
...
공통의 사용자 목표를 통해 강하게 연관된 시나리오의 집합이다. (193p)
...
다이어그램에 노력을 쏟지 말라. (194p)

이전에도 얘기한 적이 있었던 것같은데, 항상 그 Actor 그림과 함께 다이어그램에 목맸었던 과거가 부끄럽네요..
그 외에도 유스케이스에 대해 간략하게 알고있었는데 특징을 더 잘 알고 넘어갈 수 있어서 좋았습니다.


### 7장 함께 모으기

편하게 읽었지만, 참고에 적힌 내용인 UML을 용도에 맞게 얼마든지 뒤틀어도 좋다는 것과 설계에 목매지말고 최대한 빨리 코드를 구현해서 설계를 확인하라는 내용은 명심해야겠네요.
